### ISSUE TITLE
Remove the Unsafe.monitorEnter usage in code to support JDK11

### ISSUE THREAD

**Issue by wuchong** [ververica/flink-cdc-connectors#10]
Currently, it will throw the following exception if using JDK11

```
Caused by: java.lang.NoSuchMethodError: sun.misc.Unsafe.monitorEnter(Ljava/lang/Object;)V
    at com.alibaba.ververica.cdc.debezium.internal.DebeziumChangeConsumer.handleBatch(DebeziumChangeConsumer.java:101)
    at io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$2(ConvertingEngineBuilder.java:81)
    at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:810)
    at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:170)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

The JDK version
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

The reason is that we are using `Unsafe.monitorEnter` to manually hold the checkpoint lock during database snapshot phase. If we want to remove the `Unsafe.monitorEnter`, an approach is that, we have to using `synchronize` keyword to hold the checkpoint lock in `SourceFunction.run` method.

**Comment by balint133** [comment]
Hey @wuchong I really like the library, removing lots of moving parts. 
I took the initiative and opened a PR removing the UNSAFE calls to make the library compatible with Java 11. It'd be nice if you could give some feedback and hopefully get it merged.

**Comment by wuchong** [comment]
Hi @balint133 ! Glad to hear that you are inteseted on this issue. The introducing of `Unsafe.monitorEnte` is that we want to dynamically hold and release the checkpoint lock for database snapshot phase. The reason is that we can't perform checkpoint when scanning database table as we don't have an offset.

**Comment by wuchong** [comment]
One approach that comes to my mind is having a queue between the `DebeziumChangeConsumer` and `DebeziumSourceFunction`, and collect message in `DebeziumSourceFunction`, and use `synchronize` keyword to hold the checkpoint lock in `DebeziumSourceFunction.run` when it is scanning the database table.

**Comment by Tripti17jha** [comment]
Hi Wuchong,
I am using MySQL CDC connector and I am getting below error when doing the select on table in Flink CLI -
[ERROR] Could not execute SQL statement. Reason:
java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.monitorEnter(java.lang.Object)'

Please suggest how to resolve this issue.
I am using JDK 11 
I tried with both mysql cdc connector vesrion 1.1.0 and 1.2.0.In both version I am getting the same error.

**Comment by wuchong** [comment]
Please downgrade your JDK version to Java 8 before this issue is fixed.

**Comment by SwapnilKhante** [comment]
Any workaround to make it work with JDK 11? I can not downgrade to JDK 8.

**Comment by baobeidaodao** [comment]
Expecting!

**Comment by wuchong** [comment]
This has been supported in master branch with PR #194.
