### ISSUE TITLE
.NoSuchMethodError: org.apache.flink.formats.json.JsonRowDataSerializationSchema.<init> 这个咋整??

### ISSUE THREAD

**Issue by ithjz** [ververica/flink-cdc-connectors#101]
.NoSuchMethodError: org.apache.flink.formats.json.JsonRowDataSerializationSchema.<init> 这个咋整??

我预备要执行这个,执行不下去了???
INSERT INTO kafka_gmv
> SELECT DATE_FORMAT(order_date, 'yyyy-MM-dd') as day_str, SUM(price) as gmv
> FROM orders
> WHERE order_status = true
> GROUP BY DATE_FORMAT(order_date, 'yyyy-MM-dd');
[INFO] Submitting SQL update statement to the cluster...
[ERROR] Could not execute SQL statement. Reason:
java.lang.NoSuchMethodError: org.apache.flink.formats.json.JsonRowDataSerializationSchema.<init>(Lorg/apache/flink/table/types/logical/RowType;Lorg/apache/flink/formats/json/TimestampFormat;)V

**Comment by 22221cjp** [comment]
请教下怎么解决的，碰到同样的问题
