### ISSUE TITLE
Compatibility problem with Flink 1.14.*

### ISSUE THREAD

**Issue by anavrotski** [ververica/flink-cdc-connectors#1010]
`java.lang.NoClassDefFoundError: org/apache/flink/shaded/guava18/com/google/common/util/concurrent/ThreadFactoryBuilder`

**Environment :**
 - Flink version :  1.14.3
 - Flink CDC version: 2.2.0
 - Database and version: MySQL 8.0.*

**To Reproduce**
Class `com.ververica.cdc.debezium.DebeziumSourceFunction` in `com.ververica:flink-connector-debezium:2.2.0` has dependency (import) from `org.apache.flink.shaded.guava18.com.google.common.util.concurrent.ThreadFactoryBuilder` which is not available in Flink 1.14.* (it was used in Flink 1.13.*).

**Comment by swetakala** [comment]
Is there a temporary fix for this issue?

**Comment by springMoon** [comment]
+1

**Comment by aircraftbjtu** [comment]
+1

**Comment by jackiehff** [comment]
@swetakala you can consider building fink-cdc-connectors 2.2.0 source code using flink-shaded-guava-30-*.jar, for more details see https://blog.csdn.net/weixin_40455124/article/details/122247436

**Comment by rinkako** [comment]
use stream api with using pom dependency I encoutered same problem with flink 1.14.3 which using 30 shaded guava. job run on cluster will fail since it cannot find shaded 18 guava.

**Comment by AwesomeArthurLi** [comment]
shaded guava is the dependency for both flink-cdc-connectors 2.2.0  and flink streaming 1.14.4 , while these two use different version.  

When using guava 18 

`
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/flink/shaded/guava30/com/google/common/collect/Lists
	at org.apache.flink.streaming.api.transformations.LegacySinkTransformation.getTransitivePredecessors(LegacySinkTransformation.java:116)
`

**Comment by pedroyzkrak** [comment]
I have this same problem with the mongo connector! Can we have a fix?!

**Comment by swetakala** [comment]
how do we build job and package jar, so that it can be deploy it in a cluster after making changes on source in CI process?

**Comment by pmtmm** [comment]
+1 ，mark

**Comment by jorgeOliveiraTD** [comment]
We are facing the same problem on my team. Anyone knows if will there be a fix? Or any kind of plan?

**Comment by nyingping** [comment]
+1
mark

**Comment by cyongk** [comment]
+1

**Comment by jacentsao** [comment]
is this problem solved

**Comment by swetakala** [comment]
is there a ticket opened for this issue? Or shall I open one?

**Comment by hb0** [comment]
Any updates on this?

Found [this](https://github.com/ververica/flink-cdc-connectors/issues/946) issue which suggests to use the SQL-jar instead (my guess is that this means `com.ververica:flink-sql-connector-mongodb-cdc`), which fixes the exception, but I'm completely new to CDC and still have to find out if this intruduces any consequences ;)

**Comment by GdHuni** [comment]
mark
org.apache.flink.shaded.guava30.com.google.common.collect.Lists
