### ISSUE TITLE
flink-connector-oracle-cdc不支持number(19,0)

### ISSUE THREAD

**Issue by liuyonghn** [ververica/flink-cdc-connectors#1028]
flink-connector-oracle-cdc不支持number(19,0),不能正常显示数字（输出为DFDD，/w==这样的字符串），10位数字倒是没问题。

**Comment by liuyonghn** [comment]
flink-connector-oracle-cdc v2.2.0

**Comment by liuyonghn** [comment]
flink-connector-oracle-cdc v2.2.0

**Comment by liuyonghn** [comment]
[flink-connector-oracle-cdc v2.2.0](https://github.com/ververica/flink-cdc-connectors/issues/675

找到答案了,number(19,0)设置为字符串方式就能正常显示
properties.setProperty("decimal.handling.mode","STRING");)

**Comment by liuyonghn** [comment]
已解决。

**Comment by Jetol** [comment]
> [flink-connector-oracle-cdc v2.2.0](#675
> 
> 找到答案了,number(19,0)设置为字符串方式就能正常显示 properties.setProperty("decimal.handling.mode","STRING");)

还有其它解决办法吗？转换成String，这样同步过来的类型 不对；
