### ISSUE TITLE
Support CDC start from timestamp

### ISSUE THREAD

**Issue by Tan-JiaLiang** [ververica/flink-cdc-connectors#103]
Oracle Logminer CDC和Mysql binglog日志其实都会带有一个时间的概念，建议支持基于指定timestamp开始同步

**Comment by wuchong** [comment]
Related to #21

**Comment by Tan-JiaLiang** [comment]
that's great!

**Comment by wuchong** [comment]
Supported in 5264e80a7b7619b497c14a65f81a7cb5db32a567
