### ISSUE TITLE
postgresql cdc 报错TimeoutException: Heartbeat of TaskManager with id timed out.

### ISSUE THREAD

**Issue by William-Kaiser** [ververica/flink-cdc-connectors#104]
ERROR akka.remote.EndpointWriter   [] - dropping message [class org.apache.flink.runtime.rpc.messages.RemoteRpcInvocation] for non-local recipient [Actor[akka.tcp://flink@192.xx:45578/user/rpc/taskmanager_0#1283715547]] arriving at [akka.tcp://flink@192.xx::45578] inbound addresses are [akka.tcp://flink@localhost:6123]

Caused by: java.util.concurrent.TimeoutException: Heartbeat of TaskManager with id eaffacbed6a9d6025a362df2738d5299 timed out.

**Comment by ithjz** [comment]
解决了吗?截图看看?

**Comment by William-Kaiser** [comment]
![image](https://user-images.githubusercontent.com/17757880/108340084-28d62500-7213-11eb-9f23-f8c510a4111d.png)
没有解决，不知道怎么解决

**Comment by William-Kaiser** [comment]
> 解决了吗?截图看看?
还没有解决，截图如下：
![image](https://user-images.githubusercontent.com/17757880/108340361-7488ce80-7213-11eb-9c38-43ee8ba5b89f.png)
![image](https://user-images.githubusercontent.com/17757880/108340396-823e5400-7213-11eb-889c-6547a56445ad.png)
这是我的配置：
![image](https://user-images.githubusercontent.com/17757880/108340462-91bd9d00-7213-11eb-8316-b9e5dbba3dab.png)

**Comment by leonardBang** [comment]
This should not be related to cdc source

**Comment by zhilinli123** [comment]
> 错误 akka.remote.EndpointWriter [] - 为非本地收件人 [Actor[akka.tcp://flink@192.xx:45578/user] 丢弃消息 [class org.apache.flink.runtime.rpc.messages.RemoteRpcInvocation] /rpc/taskmanager_0#1283715547]] 到达 [akka.tcp://flink@192.xx::45578] 入站地址是 [akka.tcp://flink@localhost:6123]
> 
> 引起：java.util.concurrent.TimeoutException：ID 为 eaffacbed6a9d6025a362df2738d5299 的 TaskManager 的心跳超时。
 



May I ask if this problem had better be solved?

**Comment by zhilinli123** [comment]
Has this problem been solved at last？

**Comment by William-Kaiser** [comment]
solved&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月7日(星期五) 下午2:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ververica/flink-cdc-connectors] postgresql cdc 报错TimeoutException: Heartbeat of TaskManager with id timed out. (#104)





 
Has this problem been solved at last？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhilinli123** [comment]
> 解决了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年1月7日(星期五) 下午2:28 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [ververica/flink-cdc-connectors] postgresql cdc 报错TimeoutException: Heartbeat of TaskManager with id timed out. (#104) Has this problem been solved at last？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Excuse me you this problem is how to solve can you see say briefly?
