### ISSUE TITLE
flink-connector-sqlserver-cdc:compatible sqlserver2012

### ISSUE THREAD

**Issue by 15750571198** [ververica/flink-cdc-connectors#1040]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version: 
 - Database and version: sqlserver 2012

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**
Currently Flink SqlServer CDC connector only supports SqlServer whose version is either 14 or 15, but actual is 11.
Can sqlserver2012 work normally

**Comment by xiemingjin** [comment]
你可以修改源码 把里面的版本验证注释掉,我用2008试过，是可以的

**Comment by 15750571198** [comment]
> 你可以修改源码 把里面的版本验证注释掉,我用2008试过，是可以的

**Comment by 15750571198** [comment]
> 你可以修改源码 把里面的版本验证注释掉,我用2008试过，是可以的

版本验证注释掉了重编译后，使用的时候数据全为null

**Comment by GOODBOY008** [comment]
> 你可以修改源码 把里面的版本验证注释掉,我用2008试过，是可以的

你试过增量吗？
