### ISSUE TITLE
ORACLE 与SQLSERVER 开启CDC 最低需要什么权限

### ISSUE THREAD

**Issue by kolnick** [ververica/flink-cdc-connectors#1044]

**Comment by molsionmo** [comment]
@kolnick please see doucuments below
https://ververica.github.io/flink-cdc-connectors/master/content/connectors/oracle-cdc.html
https://ververica.github.io/flink-cdc-connectors/master/content/connectors/sqlserver-cdc.html

Can you close this issue if slove this question?

**Comment by gong** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! 
cc @GOODBOY008

**Comment by kolnick** [comment]
你好你发的邮件我已收到谢谢！Your message has received，thank you for your mail.
