### ISSUE TITLE
通过mysql-cdc-sql的方式读取数据出现noclassfound错误

### ISSUE THREAD

**Issue by misunnon** [ververica/flink-cdc-connectors#1048]
**Describe the bug(Please use English)**
Unable to read data of character type（varchar），
There is no problem with int type and date type

**Environment :**
 - Flink version :  1.14.0
 - Flink CDC version: 2.2.0
 - Database and version: 8.0.25

**To Reproduce**
1.Execute SQL query data through cli
2.Lib directory with Kafka connect API Kafka clients
3.The character type cannot be queried
4.There is no problem querying character types through JDBC connection

**Additional Description**
<img width="716" alt="43abf3ff580fceb7cdfa20b27bf4954" src="https://user-images.githubusercontent.com/34015716/161895915-97e1c517-af16-42fb-9ac2-2dfe1196b3c3.png">
<img width="611" alt="e1a4ed496f8059196f7a66553d5d0f2" src="https://user-images.githubusercontent.com/34015716/161895926-6134a0e1-d679-4410-9d26-4666520f7b0d.png">
<img width="750" alt="df2be41dd20b06caab9312d33ac162b" src="https://user-images.githubusercontent.com/34015716/161895934-9d539be8-9eb1-4a61-8459-464c6f3c5c21.png">
<img width="1067" alt="005c87b894ec4c47b76a0b3b8cbe3ac" src="https://user-images.githubusercontent.com/34015716/161895939-9d96a29b-a606-4ec6-9b93-db767f48d7af.png">

**Comment by rookiegao** [comment]
It looks like a jar package conflict.

**Comment by PatrickRen** [comment]
@misunnon Could you try to remove kafka related JARs from `lib` directory? I think it will conflict with Kafka related dependencies used by CDC connectors.

**Comment by cqlyiyeshu** [comment]
Have you resolved?
