### ISSUE TITLE
postgresql replication slot error

### ISSUE THREAD

**Issue by ydx2099** [ververica/flink-cdc-connectors#1058]
**Environment :**
 - Flink version :  1.14.4\1.13.2
 - Flink CDC version: 2.2.0\2.3-SNAPSHOT
 - Database and version: postgresql-12

I have set slot.name to "test_cc",but still error occurs:

[ERROR] Could not execute SQL statement. Reason:
org.postgresql.util.PSQLException: ERROR: replication slot "test_cc" is active for PID 79319

**Comment by PatrickRen** [comment]
@fsk119 Could you take a look at this issue? I'm not sure this could be fixed by upgrading Debezium to 1.6.4. Thanks
