### ISSUE TITLE
MySQL CDC incremental snapshot reading will duplicate when  a failure happend

### ISSUE THREAD

**Issue by onlywangyh** [ververica/flink-cdc-connectors#1061]
**Describe the bug(Please use English)**
The source of snapshot phase can support checkpoint in chunk level. If a failure happens, the source can be restored and continue to read chunks from last finished chunks.

 But the checkpoint will done multiple times in single split.  When the source restored the data will reapeat

**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version:  2.2
 - Database and version:  5.6

**Comment by ruanhang1993** [comment]
I am interested in this issue. Please assign this to me, thanks.

**Comment by hezhenghongmail** [comment]
I also encountered this problem.  when restore from the checkpoint ，the job do all the split。

**Comment by leonardBang** [comment]
> I also encountered this problem. when restore from the checkpoint ，the job do all the split。

I upgrade the severity to blocker and'll fix this issue soon

**Comment by leonardBang** [comment]
Fixed in #1505
