### ISSUE TITLE
There is no need to stop log collection during add new table

### ISSUE THREAD

**Issue by fuyun2024** [ververica/flink-cdc-connectors#1062]
Flink MySQL CDC 2.2 supports add new tables, but the binlog task needs to be stopped in the process of add new tables. If the new table takes a long time in the snapshot , it will affect the data capture of binlog task.

dblog paper : [DBLog: A Watermark Based Change-Data-Capture Framework](https://arxiv.org/pdf/2010.12597v1.pdf)
> capture transaction log events and the full state side by side without stalling one or the other. There are use cases that require high availability of transaction log events so that the replication lag to the source is kept to a minimum.

**Comment by ruanhang1993** [comment]
This should already be fixed in 2.4.0 .
