### ISSUE TITLE
fail to sink to sqlserver using jdbc

### ISSUE THREAD

**Issue by ydx2099** [ververica/flink-cdc-connectors#1065]
fail to sink to sqlserver using jdbc.

**Environment :**
 - Flink version :  1.14.4
 - Flink CDC version: 2.3.0-snapshot
 - Database and version: sqlserver-2019
 - flink-connector-jdbc_2.11-1.14.4
 - mssql-jdbc-8.4.1.jre8

1. Thes test data :no data
2. The test code :
 CREATE TABLE shipments_2 (
    shipment_id INT,
   order_id INT,
   origin STRING,
   destination STRING,
   PRIMARY KEY (shipment_id) NOT ENFORCED
  ) WITH (
    'connector' = 'jdbc',
    'url' = 'jdbc:sqlserver://172.23.16.236:55555;DatabaseName=inventory',
	'driver' = 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
    'username' = 'sa',
    'password' = '123456',
    'table-name' = 'shipments_2'
  );
 
select * from shipments_2 ;

4. The error :
[ERROR] Could not execute SQL statement. Reason:
java.lang.IllegalStateException: Cannot handle such jdbc url: jdbc:sqlserver://172.23.16.236:55555;DatabaseName=inventory

**Comment by choucmei** [comment]
Because current not supports sqlserver jdbc  in flink-connector-jdbc module, just supports mysql,pg,derby.
You can develop by yourself

**Comment by PatrickRen** [comment]
@ydx2099 Please report to Flink community about JDBC sink issues.
