### ISSUE TITLE
mysql表无法获取值，库中多个表，只有这个表无法获取数据，建表语句及flink sql语句如下

### ISSUE THREAD

**Issue by zz-big** [ververica/flink-cdc-connectors#1077]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.13
 - Flink CDC version: 2.2
 - Database and version: 

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

CREATE TABLE `shop` (
  `id` int(10) unsigned zerofill NOT NULL,
  `code` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '店铺编号',
  `operator_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '店铺平台创建者的帐号',
  `region_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '区域ID',
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `name_for_search` varchar(128) NOT NULL DEFAULT '' COMMENT '门店名字（全角半角大小写搜索用）',
  `primary_industry_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '行业大分类代号',
  `secondary_industry_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '行业中分类代号',
  `sn` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '自定义序号',
  `operation_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '店铺运营状态',
  `latitude` double NOT NULL COMMENT '纬度',
  `longitude` double NOT NULL COMMENT '经度',
  `position_type` tinyint NOT NULL DEFAULT '0' COMMENT '定位类型：1-gps（默认） 2-ip',
  `country_code` int DEFAULT NULL COMMENT '国家代码',
  `province_code` int DEFAULT NULL COMMENT '所在省份代码',
  `city_code` mediumint DEFAULT NULL COMMENT '市/城市代码',
  `area_code` mediumint DEFAULT NULL COMMENT '县/区代码',
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '具体地址',
  `grade` tinyint DEFAULT NULL COMMENT '评分',
  `shop_table` smallint DEFAULT NULL COMMENT '运送终点数',
  `site_start_time` datetime DEFAULT NULL COMMENT '场地创建时间',
  `site_installer` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '实施工程师',
  `broker_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '门店对接人',
  `broker_position` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '对接人职位',
  `broker_phone` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '对接人手机',
  `lora` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'LoRa通道',
  `belong_to` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '所属类型',
  `customer_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '客户ID',
  `traffic_type_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '业务类型code',
  `source_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '一级来源code',
  `second_source_code` varchar(64) DEFAULT NULL COMMENT '二级来源code',
  `marketing_campaigns_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '市场活动code',
  `business_practice_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '经营方式code',
  `brand_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '品牌code  旧字段',
  `brand_code_list` text COMMENT '品牌code list 新字段',
  `is_brand` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否品牌(1，是 2，否， 0，未填写)',
  `business_area` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '商圈',
  `mt_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '美团门店id',
  `status_code` tinyint DEFAULT NULL COMMENT '门店状态，0:未知值，1: 待认领，2: 已认领未合作，7: 合作运营中，8: 流失，9: 关闭',
  `status_unix_time` int DEFAULT NULL COMMENT '门店状态流转时间戳',
  `is_private_area` tinyint DEFAULT NULL COMMENT '是否是私海',
  `back_area_time` int NOT NULL DEFAULT '0' COMMENT '预计退回公海的时间戳',
  `actual_back_area_time` bigint NOT NULL DEFAULT '0' COMMENT '实际退回公海时间戳',
  `back_area_sort` bigint DEFAULT NULL COMMENT '退回公海时间戳排序字段',
  `is_check` tinyint(1) DEFAULT NULL COMMENT '是否核实',
  `verify_status` tinyint NOT NULL DEFAULT '0' COMMENT '核实信息0、未处理 1、已处理 2、已驳回 3、再次提交',
  `verify_submit_time` int NOT NULL DEFAULT '0' COMMENT '提交时间',
  `in_time` int DEFAULT NULL COMMENT '入驻时间',
  `out_time` int DEFAULT NULL COMMENT '流失时间',
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '修改时间',
  `delete_time` datetime(6) DEFAULT NULL COMMENT '删除时间',
  `source_type` int DEFAULT NULL COMMENT '来源平台',
  `create_type` int NOT NULL DEFAULT '0' COMMENT '创建类型',
  `sales_e_store_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '销售易门店ID',
  `use_applet` tinyint NOT NULL DEFAULT '2' COMMENT '是否启用配送小程序',
  `whether_sales_area` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否符合销售区域',
  `claimed_unix_time` int DEFAULT NULL COMMENT '认领时间戳',
  `oa_approval_number` varchar(255) NOT NULL DEFAULT '' COMMENT 'OA审批号',
  `stage_process_code` varchar(64) NOT NULL DEFAULT '' COMMENT '阶段进程',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `IDX_ad47b7c6121fe31cb4b05438e4` (`id`) USING BTREE,
  KEY `FK_713799e5448efdc71c77350d2c6` (`region_id`) USING BTREE,
  KEY `FK_711fd102a7bea7aafe2776272ed` (`primary_industry_code`) USING BTREE,
  KEY `FK_74063f5ee9a388b4978b2563531` (`operation_status`) USING BTREE,
  KEY `FK_635067cd047cdd97a2c94c0009b` (`country_code`) USING BTREE,
  KEY `FK_b7613781ce4fe98be9b84ec087c` (`province_code`) USING BTREE,
  KEY `FK_1dfc0529989fccb2ab232529835` (`customer_id`) USING BTREE,
  KEY `idx_back_area_time` (`back_area_time`) USING BTREE,
  KEY `idx_back_area_sort` (`back_area_sort`) USING BTREE,
  KEY `idx_city_code` (`city_code`) USING BTREE,
  KEY `idx_area_code` (`area_code`) USING BTREE,
  FULLTEXT KEY `idx_name_for_search` (`name_for_search`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC

CREATE TABLE IF NOT EXISTS `shop_src2` (
  `id` INT NOT NULL,
  `code` STRING NOT NULL,
  `operator_id` STRING NOT NULL,
  `region_id` STRING NULL,
  `name` STRING NOT NULL,
  `name_for_search` STRING NOT NULL,
  `primary_industry_code` STRING NOT NULL,
  `secondary_industry_code` STRING NULL,
  `sn` STRING NULL,
  `operation_status` STRING NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `position_type` INT NOT NULL,
  `country_code` INT NULL,
  `province_code` INT NULL,
  `city_code` INT NULL,
  `area_code` INT NULL,
  `address` STRING NULL,
  `grade` INT NULL,
  `shop_table` INT NULL,
  `site_start_time` TIMESTAMP NULL,
  `site_installer` STRING NULL,
  `broker_name` STRING NULL,
  `broker_position` STRING NULL,
  `broker_phone` STRING NULL,
  `lora` STRING NULL,
  `belong_to` STRING NULL,
  `customer_id` STRING NULL,
  `traffic_type_code` STRING NULL,
  `source_code` STRING NULL,
  `second_source_code` STRING NULL,
  `marketing_campaigns_code` STRING NULL,
  `business_practice_code` STRING NULL,
  `brand_code` STRING NULL,
  `brand_code_list` STRING NULL,
  `is_brand` INT NOT NULL,
  `business_area` STRING NULL,
  `mt_id` STRING NULL,
  `status_code` INT NULL,
  `status_unix_time` INT NULL,
  `is_private_area` INT NULL,
  `back_area_time` INT NOT NULL,
  `actual_back_area_time` BIGINT NOT NULL,
  `back_area_sort` BIGINT NULL,
  `is_check` INT NULL,
  `verify_status` INT NOT NULL,
  `verify_submit_time` INT NOT NULL,
  `in_time` INT NULL,
  `out_time` INT NULL,
  `create_time` TIMESTAMP NOT NULL,
  `update_time` TIMESTAMP NOT NULL,
  `delete_time` TIMESTAMP NULL,
  `source_type` INT NULL,
  `create_type` INT NOT NULL,
  `sales_e_store_id` STRING NULL,
  `use_applet` INT NOT NULL,
  `whether_sales_area` INT NOT NULL,
  `claimed_unix_time` INT NULL,
  `oa_approval_number` STRING NOT NULL,
  `stage_process_code` STRING NOT NULL,
  PRIMARY KEY(`id`)
 NOT ENFORCED
) with (
  'table-name' = 'shop',
  'connector' = 'mysql-cdc',
  'hostname' = 'xxx',
  'port' = 'xxx',
  'username' = 'xxx',
  'password' = 'xxx',
  'database-name' = 'xxx'
);

**Additional Description**

**Comment by zz-big** [comment]
经测试是由于zerofill 导致， flink cdc是否支持int(10) unsigned zerofill ？

**Comment by Jiabao-Sun** [comment]
Resolved by #1197.
