### ISSUE TITLE
监视千万级别的MYSQL表，全量阶段没有反应。

### ISSUE THREAD

**Issue by wpx1997-stack** [ververica/flink-cdc-connectors#1081]
**Describe the bug(Please use English)**
Use the Initia mode to monitor millions of tables, do not read data, no response;

**Environment :**
 - Flink version :  1.14.3
 - Flink CDC version: 2.2.0
 - Database and version:  MYSQL 8.0.15

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**
同步ersdata.book_datatype_rel这个1000多万的表，启动后没有任何反应；其他的数据量没有呢么大的表非常正常；

![image](https://user-images.githubusercontent.com/80240320/163754096-c8784fc3-2cf6-4aae-8308-cb1a13d6b3d5.png)

**Comment by wpx1997-stack** [comment]
找到原因了，原因是这个表没有设置主键。降到2.1.1版本后，启动后报错Incremental snapshot for tables requires primary key, but table ersdata.book_datatype_rel doesn't have primary key。但是在2.2.0无错误信息，建议抛出异常。

**Comment by rookiegao** [comment]
这是一个 bug，我们将修复它。
