### ISSUE TITLE
Can MongoDB CDC Connector support change stream filter config

### ISSUE THREAD

**Issue by xwzpp** [ververica/flink-cdc-connectors#1086]
**Is your feature request related to a problem? Please describe.**
MongoDB CDC connector has support "copy.existing.pipeline" to filter some document, can change stream also support this feature?

**Describe the solution you'd like**
just like add a config such as "stream.pipeline"

**Describe alternatives you've considered**
we need to filter some change stream event.

**Comment by Jiabao-Sun** [comment]
Thanks @xwzpp to report this enhancement.

If you wanna filter some database and collections, we can use regular expressions directly after release 2.2.0.
If you wanna filter a specific range of documents, it's recommended to use filter operation in stream api or where condition in flink sql.

The `pipeline` is currently used internally as a filter for the database and collection. 
My concern is that improperly used `pipeline` may affect the structure of the document and the correctness of the results. 
I think it would be better to provide `copy.existing.filter` and `stream.filter` as the `$match` stage of the `pipeline`.
