### ISSUE TITLE
[MySQL] Improve the chunks splitting of table with composite primary key

### ISSUE THREAD

**Issue by zhilinli123** [ververica/flink-cdc-connectors#1108]
The CDC uses the first joint primary key of a table by default. If the later version supports the joint primary key of a table, the CDC uses the first joint primary key of a table to determine whether a trusted field exists Is it possible to manually specify this field, so as to facilitate subsequent synchronization monitoring? Please kindly review it with the help of community leaders

**Comment by ruanhang1993** [comment]
The same problem occurs  when I use the mysql cdc connector. 
My problem lies in that the first joint primary key of my table is always the same. This will cause that the whole table only have one chunk in the snapshot phase. And the task manager will be out of memory when reading the whole table.

I have solved the problem. Could you assign this issue to me, @leonardBang? We also need a meaningful issue name in English.

**Comment by leonardBang** [comment]
Thanks @ruanhang1993 for picking this, assigned to you
