### ISSUE TITLE
Currently MySqlSource cannot support the StartupOptions with the SPECIFIC_OFFSETS startup mode. Will this be solved in a short time?

### ISSUE THREAD

**Issue by feifei0930** [ververica/flink-cdc-connectors#1114]
The old MySqlSource support four kinds of StartupMode, which contains INITIAL, EARLIEST, LATEST, SPECIFIC_OFFSETS. However, the new MySqlSouce only support INITIAL and LATEST mode. Will SPECIFIC_OFFSETS mode be supported soon?

**Comment by voyagertanyao** [comment]
+1

**Comment by yuandajn578** [comment]
+1

**Comment by ruanhang1993** [comment]
Hi, all,
This feature has been released in 2.3.0.
