### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.flink.formats.json.JsonRowDataSerializationSchema

### ISSUE THREAD

**Issue by fanghj** [ververica/flink-cdc-connectors#112]
flink 1.12

lib下已加入jar包
flink-format-changelog-json-1.1.0.jar

再将数据写入kafka时报错
[ERROR] Could not execute SQL statement. Reason:
java.lang.NoSuchMethodError: org.apache.flink.formats.json.JsonRowDataSerializationSchema.<init>(Lorg/apache/flink/table/types/logical/RowType;Lorg/apache/flink/formats/json/TimestampFormat;)V

kafka建标语句如下：

CREATE TABLE order_info_2_kafka (
  user_id       bigint         COMMENT '用户id',
  province_id   bigint         COMMENT '地区',
  order_id      bigint         COMMENT '订单编号',
  product_id    bigint         COMMENT '产品ID',
  product_name  STRING         COMMENT '产品名称',
  order_price   decimal(10,2)  COMMENT '购买价格'
) COMMENT '订单明细2kafka'
WITH (
    'connector' = 'kafka',
    'topic' = 'test04',
    'scan.startup.mode' = 'latest-offset',
    'properties.bootstrap.servers' = 'xxxx',
    'format' = 'changelog-json'
);

**Comment by AlienFromStar** [comment]
遇到同样的问题，flink 1.12
