### ISSUE TITLE
mysqlsource cdc 数据不完整

### ISSUE THREAD

**Issue by staenlyxu512** [ververica/flink-cdc-connectors#1125]
Synchronize mysql data through flink cdc datastream , but not all cdc data was caught, and the lost data is not regular
 

    val mySqlSource:MySqlSource[String] = MySqlSource.builder[String]()
      .hostname(Config.HOST)
      .port(Config.PORT)
      .databaseList(Config.DATABASE)
      .tableList(Config.TABLE_LIST)
      .username(Config.USER)
      .password(Config.PASSWORD)
      .deserializer(new CustomerDeserializationSchema())
      .startupOptions(StartupOptions.latest())
      .build()
      env.fromSource(mySqlSource, WatermarkStrategy.noWatermarks(), "MySQL Source")

**Environment :**
 - Flink version :  1.13.1
 - Flink CDC version: 2.2.0
 - Database and version: mysql 5.7.23

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**

**Comment by zhongqishang** [comment]
@staenlyxu512 Whether gtid mode is enabled? Via `show global variables like 'gtid_mode';`

**Comment by staenlyxu512** [comment]
> 
not errors in my execution , but change data was not always send into datastream

**Comment by zhang18668** [comment]
I also encountered the same problem. No error was reported, but some data was lost

**Comment by zhang18668** [comment]
![企业微信截图_16655378294398](https://user-images.githubusercontent.com/38175753/195237957-5316c640-17ff-4c14-8dd7-b45ee6d05830.png)

**Comment by zhang18668** [comment]
![image](https://user-images.githubusercontent.com/38175753/195238079-b242fce5-96d3-40c9-b244-c1f765dd4f09.png)

**Comment by zhang18668** [comment]
> 

I also encountered the same problem. No error was reported, but some data was lost

**Comment by chengyangfeng** [comment]
> 
me too,no error ,no exception.Have you solved the problem?

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
