### ISSUE TITLE
oracle cdc why  consist flush redo log

### ISSUE THREAD

**Issue by wayne-data** [ververica/flink-cdc-connectors#1126]
Enviroment:
Flink 1.13  
Oracle11g  
FlinkCDC-Oracle-Connector 2.2 or Debezium  Kafka Connector 1.7  
Desc:
Why does oracle cdc dba say that it will continue to refresh redolog, and it is useless to adjust the online catalog of logminer

**Comment by molsionmo** [comment]
@waynefor I guess you say that it will lead to more and more archive log in redo_log_catalog(log.mining.strategy)
see [log.mining.strategy](https://debezium.io/documentation/reference/1.6/connectors/oracle.html#oracle-property-log-mining-strategy)

You can config oracle database redo log size bigger and config rman to clean archive log that is expired.

**Comment by GOODBOY008** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
