### ISSUE TITLE
Can we expose op type in the metadata through flink sql?

### ISSUE THREAD

**Issue by yuhao-xu** [ververica/flink-cdc-connectors#1128]
**Is your feature request related to a problem? Please describe.**
I found it's painful that we can't get the op type of each message through flink sql natively.

**Describe the solution you'd like**
I hope we can expose the op type in the metadata

**Describe alternatives you've considered**
N/A

**Comment by EMsnap** [comment]
I've noticed it, thx, I'll create a pr for this

**Comment by EMsnap** [comment]
PLAL https://github.com/ververica/flink-cdc-connectors/pull/1137

**Comment by EMsnap** [comment]
my pleasure @yuhao-xu
