### ISSUE TITLE
postgres-cdc支持使用pg的pgoutput方式吗

### ISSUE THREAD

**Issue by LeeSinZz** [ververica/flink-cdc-connectors#114]

**Comment by Tan-JiaLiang** [comment]
支持，亲测，并且踩了一个大坑（线上PG数据库WAL膨胀导致磁盘满了）
---------------------
其实你开启了pgoutput模式，只需要指定postgres-cdc的pluginName为pgoutput即可
你是比较幸运的，上周作者和Contributor修复了pg cdc的一个大bug（未提交offset导致wal膨胀），还有，切记切记监控你的slot，如果发现有非active的slot，要么赶紧把对应的replica任务启起来，要么把这个slot删除掉，否则同样会导致WAL日志膨胀

**Comment by Tan-JiaLiang** [comment]
支持，亲测，并且踩了一个大坑（线上PG数据库WAL膨胀导致磁盘满了）
---------------------
其实你开启了pgoutput模式，只需要指定postgres-cdc的pluginName为pgoutput即可
你是比较幸运的，上周作者和Contributor修复了pg cdc的一个大bug（未提交offset导致wal膨胀），还有，切记切记监控你的slot，如果发现有非active的slot，要么赶紧把对应的replica任务启起来，要么把这个slot删除掉，否则同样会导致WAL日志膨胀

**Comment by Tan-JiaLiang** [comment]
支持，亲测，并且踩了一个大坑（线上PG数据库WAL膨胀导致磁盘满了）

其实你开启了pgoutput模式，只需要指定postgres-cdc的pluginName为pgoutput即可
你是比较幸运的，上周作者和Contributor修复了pg cdc的一个大bug（未提交offset导致wal膨胀），还有，切记切记监控你的slot，如果发现有非active的slot，要么赶紧把对应的replica任务启起来，要么把这个slot删除掉，否则同样会导致WAL日志膨胀

**Comment by LeeSinZz** [comment]
ok，我验证一下，感谢分享。

**Comment by LeeSinZz** [comment]
感谢分享
