### ISSUE TITLE
[mysql] expose op_ts field in the metadata through flink sql 

### ISSUE THREAD

**Issue by EMsnap** [ververica/flink-cdc-connectors#1140]
**Is your feature request related to a problem? Please describe.**
[mysql] expose op_ts field in the metadata through flink sql 
right now there are only binlog timestamp in meta data

**Describe the solution you'd like**
[mysql] expose op_ts field in the metadata through flink sql 

**Describe alternatives you've considered**
[mysql] expose op_ts field in the metadata through flink sql

**Comment by leonardBang** [comment]
This has been supported in #496, close this issue now.
