### ISSUE TITLE
run OracleE2eITCase occurs error 

### ISSUE THREAD

**Issue by EMsnap** [ververica/flink-cdc-connectors#1144]
**Describe the bug(Please use English)**

see https://github.com/ververica/flink-cdc-connectors/pull/1139/checks?check_run_id=6223168193

Apr 29 05:33:42 05:33:42.735 [ERROR]   OracleE2eITCase.testOracleCDC:170 expected:
<[101,scooter,Small 2-wheel scooter,3.14, 102,car battery,12V car battery,8.1, 103,12-pack drill bits,12-pack of drill bits with sizes ranging from #40 to #3,0.8, 104,hammer,12oz carpenters hammer,0.75, 105,hammer,14oz carpenters hammer,0.875, 106,hammer,18oz carpenter hammer,1.0, 107,rocks,box of assorted rocks,5.1, 108,jacket,water resistent black wind breaker,0.1, 109,spare tire,24 inch spare tire,22.2, 111,jacket,new water resistent white wind breaker,0.5]> 
<[101,scooter,Small 2-wheel scooter,3.14, 102,car battery,12V car battery,8.1, 103,12-pack drill bits,12-pack of drill bits with sizes ranging from #40 to #3,0.8, 104,hammer,12oz carpenters hammer,0.75, 105,hammer,14oz carpenters hammer,0.875, 106,hammer,16oz carpenters hammer,1.0, 107,rocks,box of assorted rocks,5.1, 108,jacket,water resistent black wind breaker,0.1, 109,spare tire,24 inch spare tire,22.2, 111,jacket,new water resistent white wind breaker,0.5]>

they seem to be the same string

**Comment by GOODBOY008** [comment]
> https://dev.azure.com/ververica/flink-cdc-connectors/_build/results?buildId=1656&view=logs&j=e2e8c2ba-e5b6-5b79-a88d-9472a63f4b18&t=13455d78-7f59-5190-8dc4-08c938daaa21
> 
> Hi @GOODBOY008, can you please help with this issue?

Ok, I'm willing to fix this unstable test.
