### ISSUE TITLE
flink1.12中的jdbc-connector与mysql-cdc的区别在哪里？

### ISSUE THREAD

**Issue by yaoboxu** [ververica/flink-cdc-connectors#115]
最近刚准备了flink1.12的集群，flink sql-client也调试好了，但是发现flink1.12中有jdbc connector可以连接数据库进行数据同步并计算，然后前期一直打算用吴邪的mysql-cdc去搭建实时数仓，两者功能基本一致吗，因为flink-cdc的项目是依赖Debezium 实现数据拉取全增量的，但是flink1.12好像没有依赖，是否原生的jdbc-connector无法拉取全量数据？

**Comment by jinhshi** [comment]
同问

**Comment by Tan-JiaLiang** [comment]
本人也不是精通，说的只能作为参考
jdbc-connector一般都是作为Lookup维表或者全量scan查询（导入导出功能），这种只能查询，不能实时捕捉到数据变化
而cdc-connector用mysql举例底层是采集mysql binlog，需要mysql开启主从复制的功能，这种connector可以实时捕捉到数据的变化

原生的jdbc-connector可以拉取全量数据，但是这种全量是flink主动通过拉取的，时效性很差，适合做离线
cdc-connecotr是增量拉取数据，是Flink监听数据库表变化，时效性非常好，适合做实时

另外Flink-CDC-connector在Flink1.12确实是没有依赖的，因为这是flink单独出来的一个项目（其实这种项目发展会比较快，如果通过社区去维护可能会经过多重审批才能合并代码），这种项目其实只需要将依赖下载下来，然后把jar放到flink的lib目录即可使用

**Comment by yaoboxu** [comment]
@Tan-JiaLiang 看了flink-jdbc-connector源码，确实如此，那原生的jdbc-connector确实是用于维表关联用的，不适合直连业务库，可用于中间维表库关联查询。 非常感谢!

**Comment by hezongjin** [comment]
好像是唉

**Comment by hezongjin** [comment]
> 本人也不是精通，说的只能作为参考
> jdbc-connector一般都是作为Lookup维表或者全量scan查询（导入导出功能），这种只能查询，不能实时捕捉到数据变化
> 而cdc-connector用mysql举例底层是采集mysql binlog，需要mysql开启主从复制的功能，这种connector可以实时捕捉到数据的变化
> 
> 原生的jdbc-connector可以拉取全量数据，但是这种全量是flink主动通过拉取的，时效性很差，适合做离线
> cdc-connecotr是增量拉取数据，是Flink监听数据库表变化，时效性非常好，适合做实时
> 
> 另外Flink-CDC-connector在Flink1.12确实是没有依赖的，因为这是flink单独出来的一个项目（其实这种项目发展会比较快，如果通过社区去维护可能会经过多重审批才能合并代码），这种项目其实只需要将依赖下载下来，然后把jar放到flink的lib目录即可使用

感谢
