### ISSUE TITLE
[Postgres] Use Incremental Snapshot Framework for Postgres CDC Connector

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#1163]
Is your feature request related to a problem? Please describe.
Adapt Postgres CDC Connector to the abstraction framework of https://github.com/ververica/flink-cdc-connectors/issues/724

**Comment by qiao-x** [comment]
Hi @leonardBang I am interested in this feature, could you assign this adaption work to me?  
BTW I think it's kinda big task, if anyone is intersted to work on this work as well, feel free to comment here and let's split it into subtasks and cooperate on this feature.

**Comment by leonardBang** [comment]
@qiao-x Thanks for taking this ticket, assigned to you.

**Comment by sap1ens** [comment]
@qiao-x hey, is there a WIP branch available for this by any chance?

**Comment by sap1ens** [comment]
@leonardBang could you assign this to @xiaom? We're actively working on this.

**Comment by leonardBang** [comment]
@sap1ens Sure, I'm pretty excited to hear that.

**Comment by leonardBang** [comment]
@qiao-x As the task has been stuck for a while and there're new volunteer to take over this issue, I prepare to assign this ticket to the new volunteer, you can still also help review or take some subtask if possible. 
@xiaom Could you comment under this ticket so that I can assign this issue to you?

**Comment by xiaom** [comment]
👋 @leonardBang sure, excited to work on this issue!

**Comment by leonardBang** [comment]
@xiaom I've assigned this ticket to you 😊

**Comment by leonxu8** [comment]
Hi Is there any progress on the PR? We are also very interested in trying this out.

**Comment by sap1ens** [comment]
https://github.com/ververica/flink-cdc-connectors/pull/1823 is ready for review.

**Comment by ruanhang1993** [comment]
Thanks for the contribution. I will review this PR when I am available.

**Comment by ruanhang1993** [comment]
There are some failed tests need to be resolved. Merge this in order not to block debezium update PR.
We will resolve these tests later
