### ISSUE TITLE
MySQL decimal type in JsonDebeziumDeserializationSchema return data error

### ISSUE THREAD

**Issue by winskin** [ververica/flink-cdc-connectors#1177]
**Describe the bug(Please use English)**
MySQL decimal type in JsonDebeziumDeserializationSchema return data error

**Environment :**
 - Flink version :  1.13.6
 - Flink CDC version: 2.2.1
 - Database and version: MySQL 8

**To Reproduce**
1. Thes test data :  db decimal data 7.9
2. The test code :
3. The error :  return data "AxY="

**Additional Description**
![image](https://user-images.githubusercontent.com/11605556/167992081-9ea65c3d-e867-463a-a76b-20749131f21a.png)

**Comment by yansheng105** [comment]
This seems to be your misunderstanding. Debezium uses bytes to transmit decimal data by default. You can display numbers by modifying the decimal.handling.mode configuration item to string.
![image](https://user-images.githubusercontent.com/65000135/168077930-d6e54a45-c7db-42da-af94-4d483171e82a.png)
