### ISSUE TITLE
ORACLE-CDC什么时候可以支持并行读取快照 并记录检查点

### ISSUE THREAD

**Issue by szhengshuai** [ververica/flink-cdc-connectors#1180]
目前在钉钉群看到不少人有这方面的需求 ， 目前看2.2主要是在支持更多DB上下功夫的，想了解下社区对于什么时候可以支持并行读取快照 ？

**Comment by GOODBOY008** [comment]
This feature will suppeort by this pr https://github.com/ververica/flink-cdc-connectors/pull/1079.

**Comment by szhengshuai** [comment]
thanks ~
