### ISSUE TITLE
When using mysql cdc connector, some task hanged in the snapshot phase

### ISSUE THREAD

**Issue by ruanhang1993** [ververica/flink-cdc-connectors#1190]
**Describe the bug(Please use English)**
When using mysql cdc connector, some task hanged in the snapshot phase. The job master continues to send chunks to this task. But the task stops to read these chunks. After other tasks finished, they will wait the problem task to finish. And the total job hanged there.

This problem is that the reader doesn't release the thread resource, which causes that the number of threads becomes larger and larger. And each thread will get less time to execute.

**Comment by ruanhang1993** [comment]
I will raise a PR to fix this bug.

**Comment by dailai** [comment]
This bug is fatal and occurs frequently

**Comment by dailai** [comment]
Would you explain how to reproduce the bug more detailed ? I have tried serval times , but could not reproduce.

**Comment by ruanhang1993** [comment]
duplicated to #1350
