### ISSUE TITLE
tidb cdc 2.2 读取全量的tidb的表数据时，出现丢数据的问题

### ISSUE THREAD

**Issue by zengqinchris** [ververica/flink-cdc-connectors#1195]
tidb的表数据大概有 80万多条记录，通过flink CDC全量读取到kafka后才20万条记录，丢时比较多

`public class TicdcUtils {

    /**
     * 获取tidb flink cdc connection source
     * @return
     */
    public static SourceFunction<String> getTidbSource(TiConfiguration tiConfiguration,String dbName, String tableName){

        TiSession session = TiSession.create(tiConfiguration);
        TiTableInfo table = session.getCatalog().getTable(dbName, tableName);

        try {
            session.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        return
        TiDBSource.<String>builder()
                .database(dbName) // set captured database
                .tableName(tableName) // set captured table
                .tiConf(
                        tiConfiguration)
                .snapshotEventDeserializer(
                        new TiKVSnapshotEventDeserializationJSONStrSchema(table) )
                .changeEventDeserializer(
                        new TiKVChangeEventDeserializationJSONStrSchema(table))
//                .startupOptions(StartupOptions.latest())

                .build();
    }
}`

```
public class TiKVSnapshotEventDeserializationJSONStrSchema extends TiKVEventDeserialization implements TiKVSnapshotEventDeserializationSchema<String> {
    public TiKVSnapshotEventDeserializationJSONStrSchema(TiTableInfo table) {
        super(table);
    }

    @Override
    public void deserialize(Kvrpcpb.KvPair record, Collector out) throws Exception {
        JSONObject jsonObject = new JSONObject();
//        TiTableInfo tiTableInfo = fetchTableInfo();
        List<TiColumnInfo> columns = table.getColumns();
        JSONObject dataJSON = getDataJSON(record, columns,table);
        jsonObject.put("data",dataJSON);
        jsonObject.put("operateType","BOOTSTRAP");
        out.collect(jsonObject.toJSONString());
    }

    private JSONObject getDataJSON(Kvrpcpb.KvPair record, List<TiColumnInfo> columns,TiTableInfo tiTableInfo) {
        JSONObject jsonObject = new JSONObject();
        Object[] tikvValues =
                decodeObjects(
                        record.getValue().toByteArray(),
                        RowKey.decode(record.getKey().toByteArray()).getHandle(),
                        tiTableInfo);
        List<Object> objects = Arrays.asList(tikvValues);
        for (int i = 0; i < tikvValues.length; i++) {
            String type = columns.get(i).getType().getName();
            jsonObject.put(columns.get(i).getName(),getDataObject(objects.get(i),type));
        }
        return jsonObject;
    }

    @Override
    public TypeInformation getProducedType() {
        return BasicTypeInfo.STRING_TYPE_INFO;
    }

```
`public class TiKVChangeEventDeserializationJSONStrSchema extends TiKVEventDeserialization implements TiKVChangeEventDeserializationSchema<String>  {
    public TiKVChangeEventDeserializationJSONStrSchema(TiTableInfo table) {
        super(table);
    }

    @Override
    public void deserialize(Cdcpb.Event.Row row, Collector collector) throws Exception {
//        TiTableInfo tiTableInfo = fetchTableInfo();
        List<TiColumnInfo> columns = table.getColumns();

        JSONObject jsonObject = new JSONObject();
        jsonObject.put("data",getDataJSON(row,columns,table));
        jsonObject.put("old",getOldJSON(row,columns,table));
        jsonObject.put("operateType",row.getOpType().getValueDescriptor().getName());
        jsonObject.put("ts",row.getStartTs());
        collector.collect(jsonObject.toJSONString());
    }

    private JSONObject getDataJSON(Cdcpb.Event.Row row, List<TiColumnInfo> columns,TiTableInfo tiTableInfo) {
        JSONObject dataJOSN = new JSONObject();
        if (row.getValue().toByteArray().length!=0) {
            Object[] objects =
                    decodeObjects(
                            row.getValue().toByteArray(),
                            RowKey.decode(row.getKey().toByteArray()).getHandle(),
                            tiTableInfo);
            List<Object> objectList = Arrays.asList(objects);
            for (int i = 0; i < objectList.size(); i++) {
                String type = columns.get(i).getType().getName();
                dataJOSN.put(columns.get(i).getName(),getDataObject(objectList.get(i),type));
            }
        }
        return dataJOSN;
    }

    @Override
    public TypeInformation getProducedType() {
        return BasicTypeInfo.STRING_TYPE_INFO;
    }

    @Override
    protected void finalize() throws Throwable {
        super.finalize();
    }
}
`
主流调用 全量拉取数据

`TiConfiguration tiConfiguration = TDBSourceOptions.getTiConfiguration("production".equals(parameterTool.get("env")) ? Constant.TIDB_PD_ADDR : Constant.TIDB_PD_ADDR_TEST, new HashMap<>());
        SourceFunction<String> tidbSource = TicdcUtils.getTidbSource(tiConfiguration, "xxx", "xxxx");
        DataStreamSource<String> stringDataStreamSource = env.addSource(tidbSource);`

**Comment by GOODBOY008** [comment]
@zengqinchris You can cherry pick https://github.com/ververica/flink-cdc-connectors/pull/1196 and install locally.

**Comment by zengqinchris** [comment]
https://github.com/ververica/flink-cdc-connectors/issues/1159，解决方法
