### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by lknan** [ververica/flink-cdc-connectors#1199]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.13.1
 - Flink CDC version: 2.2.1
 - Database and version: 8.0.21

**To Reproduce**
![image](https://user-images.githubusercontent.com/40596486/169254919-54a09a1d-9e80-4ce9-86c7-267dfdf0c805.png)
![image](https://user-images.githubusercontent.com/40596486/169255033-3e1fc731-e1cf-412b-909c-03bc0490dd9e.png)

**Additional Description**
数据库有1T大小数据，8000张表，非均匀分布主键，LATEST_OFFSET 模式下，cp没成功过，直到OOM

**Comment by Jiabao-Sun** [comment]
#941

**Comment by ysyl23588** [comment]
++1
