### ISSUE TITLE
Unsupported startup mode: SPECIFIC_OFFSETS

### ISSUE THREAD

**Issue by winskin** [ververica/flink-cdc-connectors#1200]
**Describe the bug(Please use English)**
Specifies the binlog exception，Is there any way to solve it?

**Environment :**
 - Flink version :  1.13.6
 - Flink CDC version: 2.2.1
 - Database and version: mysql 8

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**
![image](https://user-images.githubusercontent.com/11605556/169258421-f2d8f542-8acb-4bd3-95e5-aebd7e6f0caa.png)

**Comment by ruanhang1993** [comment]
Fixed by #1661.
