### ISSUE TITLE
memory consumption

### ISSUE THREAD

**Issue by lknan** [ververica/flink-cdc-connectors#1201]
大库大表非均匀分布主键情况下，使用快照全量读的时候为什么job manage特别消耗内存，使用binlog增量读取的时候为什么task特别耗内存（设置的4G），以致cp都无法成功；这两种方式为啥会有这样的情况？

**Comment by vanliu-tx** [comment]
adjust splitSize and fetchSize of MySqlSource, also change the checkpoint interval to < 60s during snapshot period.
