### ISSUE TITLE
when start up  flink job with checkpoint or savepoint. please accept below Suggest.

### ISSUE THREAD

**Issue by juyonychen** [ververica/flink-cdc-connectors#1205]
stage:
when i used mysql-flink-cdc monitor tableA and tableB  and sync data  to other database(eg:clickhouse or Doris )
when tableA added fileds clickhouse or Doris table don't synchronous add。so tableA add column corresponding will be abandon .
if i needed total data of tableA ，i have no choice but relistening 。i just want to relistening tableA but not all tables;

**Suggest**
when start up  flink job with checkpoint or savepoint. Can you compare the difference between listening table list and backup table list? if listening table is not exits backup table list,  please delete the not exits tables from the back up list.

**Comment by ruanhang1993** [comment]
CDC source could send the schema change records. But CDC can not decide how to deal with it in the sink.
This feature can not be completed in cdc. It should be implemented in the Flink engine and sink connectors.
