### ISSUE TITLE
Make offsetState of DebeziumSourceFunction queryable 

### ISSUE THREAD

**Issue by baisui1981** [ververica/flink-cdc-connectors#1208]
**Is your feature request related to a problem? Please describe.**
When running of Flink CDC job , I want to monitor the job  change log state from user client by Flink Queryable State ,but by now it is not support .

I am developing a DataOps product integrated with Flink CDC , If the user can directly see the binlog consumption offset in the CDC source on the tis platform, it will be very intuitive

**Describe the solution you'd like**

add a config propery to switch off/on the `offsetState` of DebeziumSourceFunction queryable to outside

https://github.com/ververica/flink-cdc-connectors/blob/b21466a84889e7c1e99350305d2034f7b65eb24b/flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumSourceFunction.java#L232-L236

Modify to :
``` java
        OperatorStateStore stateStore = context.getOperatorStateStore();

    ListStateDescriptor offsetDesc = new ListStateDescriptor<>(
                                OFFSETS_STATE_NAME,
                                PrimitiveArrayTypeInfo.BYTE_PRIMITIVE_ARRAY_TYPE_INFO);
    // add code block of below 
    if(someCase){
        offsetDesc.setQueryable("queryable_" +OFFSETS_STATE_NAME); 
     } 
        this.offsetState =
                stateStore.getUnionListState(  offsetDesc);
```
Then  I can get the `offsetState` from client, like below

``` scala
 object QueryableState {
  def main(args: Array[String]): Unit = {
    
    val client = new QueryableStateClient("train",9069)
    val jobID = JobID.fromHexString("ccfd376e18bb81be5c6e1b40ddb66837")
    var queryName = "queryable-offset-states" 
    var queryKey = "offset-states" 

    val vsd = new ValueStateDescriptor[Int]("mysql-cdc", createTypeInformation[XXXXX])

    val resultFuture = client.getKvState(jobID,queryName,queryKey,createTypeInformation[String],vsd)

    val state:ValueState[Int] = resultFuture.get()
    
    client.shutdownAndWait()

  }
}
```

If possible ,I can provide a PR of the Issue

**Comment by leonardBang** [comment]
Thanks @baisui1981 for reporting this ticket, I think it makes sense that expose offset information to users, but maybe we need better design for example, cover all Source APIS and expose the offset information by metric way
