### ISSUE TITLE
[sqlserer-cdc] Use Incremental Snapshot Framework to impl sqlserver cdc connector.

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#1212]
Use Incremental Snapshot Framework to impl sqlserver cdc connector.

**Comment by murongpingtian** [comment]
需要

**Comment by chenfanz** [comment]
Much needed, thanks for the contribution

**Comment by wd6608286** [comment]
need more

**Comment by GOODBOY008** [comment]
https://github.com/ververica/flink-cdc-connectors/pull/1732 merged
