### ISSUE TITLE
schema isn't known to connector

### ISSUE THREAD

**Issue by z070204z** [ververica/flink-cdc-connectors#1223]
when scan newly added tables
if i set  startupOptions=StartupOptions.latest() throw Error

 ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource  [] - Encountered change event 'Event{header=EventHeaderV4{timestamp=1653474984000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=33, nextPosition=999048757, flags=0}, data=TableMapEventData{tableId=302, database='test', table='src', columnTypes=15, 15, 3, columnMetadata=765, 765, 0, columnNullability={0, 1}, eventMetadata=null}}' at offset {transaction_id=null, ts_sec=1653474975, file=mysql-bin.000021, pos=999048633, server_id=1, event=1} for table test.src whose schema isn't known to this connector. One possible cause is an incomplete database history topic. Take a new snapshot in this case.

**Comment by ysyl23588** [comment]
我也遇到了 ++1

**Comment by Peng-89** [comment]
the table not in savepoint state

**Comment by OrangeLinforCode** [comment]
I set startupOptions=StartupOptions.inital() , still encounter this problem，So, besides not starting from the state, is there a better way?

**Comment by z070204z** [comment]
> I set startupOptions=StartupOptions.inital() , still encounter this problem，So, besides not starting from the state, is there a better way?

I tested the latest version 2.4.0, everything is working fine.
