### ISSUE TITLE
[postgres-cdc] Add upsert changelog mode to avoid replica identity FULL

### ISSUE THREAD

**Issue by fbad** [ververica/flink-cdc-connectors#1241]
**Is your feature request related to a problem? Please describe.**
I am trying to use `postgres-cdc` connector without setting replica identity FULL.
The reason is we would like to prevent the growth of our replication slots. Moreover, replica identity is a table property so we cannot configure it on a replication slot level and we have other consumers that would not support replica identity FULL as of now.

**Describe the solution you'd like**
I think we can add support for [upsert changelog mode](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/concepts/dynamic_tables/#table-to-stream-conversion) by adding `changelogMode` option with mandatory primary key configuration. Basically, with `changelogMode=upsert` we will not push `BEFORE_UPDATE` rows and we will require a primary key for the table.

Do you think this feature makes sense and it can be useful for the community? If yes, I am happy to open a PR. 

**Describe alternatives you've considered**
The alternative is to set replica identity FULL which is not feasible for us.

**Comment by leonardBang** [comment]
Thanks @fbad for report this issue, the idea makes sense to me, CC: @fsk119 could you take a look the issue as well as the PR ?

**Comment by sap1ens** [comment]
Hey everyone, just wanted to check on the status of this issue. It seems like the PR has been approved. Is there anything else to be done here? 

I'm thinking if I should wait until it's merged to master or just try it as is in my internal fork.

**Comment by leonardBang** [comment]
@sap1ens I've merged this PR and we plan to release 2.3 at the end of this month, hope to see you to have a try.

**Comment by sap1ens** [comment]
Thanks for the heads up! I did try this and it worked perfectly. Unfortunately, I've realized I can't use this feature - it's ok for me to skip UPDATE_BEFOREs, but I need a full row in case of DELETEs...
