### ISSUE TITLE
is there some flag that help me get the primary key in output

### ISSUE THREAD

**Issue by foobarrer** [ververica/flink-cdc-connectors#1243]
I use flink cdc in copy the mysql data from one to another, what I want is tell me which column is the primary key in the output. So I can use the primary key to update and delete the data。

**Comment by huzk8** [comment]
I want to get  the primary key from playload too....

**Comment by fjyulu** [comment]
I really appreciate it if someone can tell me wether there is a **primary key flag**in the future or there will **not have** a primary key flag. I'm waiting for a certain answer, no matter whether it's true or false. 
thanks a lot

**Comment by ruanhang1993** [comment]
This information should be known before the job starts. And we do not need to pass it when reading data.
If it is  DataStream job, you may be able to pass it after the deserialization.
But we can not do it in flink sql.
