### ISSUE TITLE
flink sql，mysql cdc update会拆成delete+create，是否有办法可以合并成一个update

### ISSUE THREAD

**Issue by JanCong** [ververica/flink-cdc-connectors#1256]
flink sql，mysql cdc update会拆成delete+create，是否有办法可以合并成一个update？
目标需求是将mysql中不同的表cdc同步到es的同一个index
现在其中一个表update的时候，因为先delete再insert，把es原有数据的其他字段都替换掉了

**Comment by moonService** [comment]
@fuyun2024 同样的问题，想问下为什么一开始要把update拆成delete和create，另外源码哪个测试用例是用来测试这块的，能不能指个路
