### ISSUE TITLE
release-1.2无法在Flink 1.11集群上运行

### ISSUE THREAD

**Issue by tiyh** [ververica/flink-cdc-connectors#126]
release-1.2无法在Flink 1.11集群上运行
java.lang.NoClassDefFoundError: org/apache/flink/api/common/state/CheckpointListener
请问flink-cdc-connectors的版本支持的Flink版本有规划吗

**Comment by dua01** [comment]
flink1.12 版本将CheckpointListener接口从org.apache.flink.runtime.state包迁移到了org.apache.flink.api.common.state包下，
flink-cdc1.2中DebeziumSourceFunction 实现CheckpointListener接口引用了新包

```
import org.apache.flink.api.common.state.CheckpointListener;
@PublicEvolving
public class DebeziumSourceFunction<T> extends RichSourceFunction<T> implements
		CheckpointedFunction,
		CheckpointListener,
		ResultTypeQueryable<T>
```
如果必须要用flink-cdc1.2 + flink1.11的话建议修改cdc1.2源码，重新导入找不到的类/接口后重新编译打包。
