### ISSUE TITLE
CDC  Mysq 到 ClickHouse  其中有几张表单表数据30G 无同步

### ISSUE THREAD

**Issue by zjialin** [ververica/flink-cdc-connectors#1269]
一直卡在这一句

        TableResult tableResult = tableEnv.executeSql("insert into sink_flink_point_status_history select * from source_flink_point_status_history");

        System.out.println("+++++++++++++++++++++++++++++");
        // 等待flink-cdc完成快照
        tableResult.print();
        System.out.println("-----------------------------");

        env.execute("flink-cdc");

**Comment by ruanhang1993** [comment]
Please provide more information and reopen it . Thanks~
