### ISSUE TITLE
请问clickhouse支持cdc么

### ISSUE THREAD

**Issue by yl-yue** [ververica/flink-cdc-connectors#1273]
1. 请问clickhouse支持cdc么
2. clickhouse能实现cdc么
3. 如何扩展clickhouse cdc实现（贡献指南）

谢谢！

**Comment by ruanhang1993** [comment]
Does clickhouse have a CDC feature? Now cdc connector relies on the debezium connectors. But there is not support for the clickhouse. :(

**Comment by xleoken** [comment]
+1，we also need flinkcdc to clickhouse(single cluster mode)
