### ISSUE TITLE
[mongodb-cdc] add debezium mongo connector property cursor.max.await.time.ms

### ISSUE THREAD

**Issue by suhli** [ververica/flink-cdc-connectors#1274]
**Is your feature request related to a problem? Please describe.**
cursor not found exception in some scene with large table or complex tasks

**Describe the solution you'd like**
add debezium mongo connector property cursor.max.await.time.ms

**Describe alternatives you've considered**
 debezium add cursor.max.await.time.ms property since v1.8 to avoid this
![image](https://user-images.githubusercontent.com/23626907/173169135-1bd5936f-f495-46a1-8689-5fa7579a33da.png)

**Comment by Jiabao-Sun** [comment]
Hi @suhli.
Currently MongoDB CDC Connector does not use the Debezium MongoDB connector implementation and there is no good way to set this config option.

So I temporarily closed this issue and consider adding this configuration option to the implementation of parallel mongodb cdc sources.
