### ISSUE TITLE
TiDB CDC can not get change data

### ISSUE THREAD

**Issue by yujunyong** [ververica/flink-cdc-connectors#1282]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.14
 - Flink CDC version: 2.2.1
 - Database and version: 5.4.0

**Taskmanager Log**
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/2252569/173794797-4baf8d74-d0b3-4421-8278-009b637b0601.png">

TiDB CDC started normal in a day, but can not get change data after a day. no error log in taskmanager. no error log in TiDB CDC Server.
when `2022-06-14 16:32:32,858 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 433899583002640387, regionId: 67814` log don't receive, change data not receive too.

**Comment by RaiToKU** [comment]
https://github.com/ververica/flink-cdc-connectors/issues/1252

**Comment by GOODBOY008** [comment]
@yujunyong @RaiToKU  https://github.com/ververica/flink-cdc-connectors/pull/1196  you can checkout pr and compile local.

**Comment by Hugoincug** [comment]
I had the same situation. The synchronization will stop when the incremental synchronization reaches a certain value

**Comment by xieyi888** [comment]
I had the same question.
maybe the problem is similar to this issue：https://github.com/tikv/client-java/issues/628
tidb-cdc  don't receive ChangeDataEvent from tikv store after several hours,because tikv region transfer leader.
you can verify  log of tikv store,if there are logs about  **"transfer leader"**
```java
......
 ["try to transfer leader"] [to_peer="id: **** store_id: ***"] [from_peer="id: **** store_id: ****"] [region_id=****]
["transfer leader"] [peer="id: **** store_id: ****"] [peer_id=****] [region_id=***]
.....
```

**Comment by GOODBOY008** [comment]
> I had the same question. maybe the problem is similar to this issue：[tikv/client-java#628](https://github.com/tikv/client-java/issues/628) tidb-cdc don't receive ChangeDataEvent from tikv store after several hours,because tikv region transfer leader. you can verify log of tikv store,if there are logs about **"transfer leader"** of your region_id
> 
> ```java
> ......
>  ["try to transfer leader"] [to_peer="id: **** store_id: ***"] [from_peer="id: **** store_id: ****"] [region_id=****]
> ["transfer leader"] [peer="id: **** store_id: ****"] [peer_id=****] [region_id=***]
> .....
> ```

When a region was created after start cdclient, this case also cann't capture data change.

**Comment by Hugoincug** [comment]
> > I had the same question. maybe the problem is similar to this issue：[tikv/client-java#628](https://github.com/tikv/client-java/issues/628) tidb-cdc don't receive ChangeDataEvent from tikv store after several hours,because tikv region transfer leader. you can verify log of tikv store,if there are logs about **"transfer leader"** of your region_id
> > ```java
> > ......
> >  ["try to transfer leader"] [to_peer="id: **** store_id: ***"] [from_peer="id: **** store_id: ****"] [region_id=****]
> > ["transfer leader"] [peer="id: **** store_id: ****"] [peer_id=****] [region_id=***]
> > .....
> > ```
> 
> When a region was created after start cdclient, this case also cann't capture data change.

it means cdcClient needs to be fix ?

**Comment by mxd-321** [comment]
Is there a follow-up to this question?

**Comment by mxd-321** [comment]
> > I had the same question. maybe the problem is similar to this issue：[tikv/client-java#628](https://github.com/tikv/client-java/issues/628) tidb-cdc don't receive ChangeDataEvent from tikv store after several hours,because tikv region transfer leader. you can verify log of tikv store,if there are logs about **"transfer leader"** of your region_id
> > ```java
> > ......
> >  ["try to transfer leader"] [to_peer="id: **** store_id: ***"] [from_peer="id: **** store_id: ****"] [region_id=****]
> > ["transfer leader"] [peer="id: **** store_id: ****"] [peer_id=****] [region_id=***]
> > .....
> > ```
> 
> When a region was created after start cdclient, this case also cann't capture data change.

Will this issue be fixed in the future?

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
