### ISSUE TITLE
flink_yarn使用oceanbase_cdc场景下。多表sql出现logproxy表通道重复创建的现像

### ISSUE THREAD

**Issue by staryzhou** [ververica/flink-cdc-connectors#1287]
### **环境如下：**
**1、flink_yarn(hadoop集群)**
**2、oceanbase与oblogproxy暂使用docker的方式** docker方式参考的https://ververica.github.io/flink-cdc-connectors/release-2.2/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/oceanbase-tutorial-zh.html。
//本有自己的OB集群，但因故障较多，所以使用了外面已成功的方案来进行测试。

### **故障描述**
flink使用oceanbase_cdc读取两张表：orders,products,再Jdbc写入oceanbase。
a、在flink单机集群下正常。oblogproxy在run/目录下可看到两张表的通道目录。
b、其它保持不变，flink单机集群切到hadoop_yarn后，如sql只涉及单表就正常，但像上面操作多张表时会出现异常。会反复创建其中一张表的oblogproyx通道。导致oblogproxy端报通道已存在，进程异常退出。整个flink任务也失败。

### **重要信息**
**1、oblogproxy异常日志：logproxy.INFO**
![1655429365753_lQLPJxZont7dc2zNArzNBc-wjlmMa6EpNG0CrHoHMEAZAA_1487_700](https://user-images.githubusercontent.com/56627592/174204317-f8adb163-08c4-4e3c-a77a-e63ab3a2ae86.png)

**2、sql如下**
[sql.txt](https://github.com/ververica/flink-cdc-connectors/files/8923870/sql.txt)

**3、taskmanager日志**
[taskmanager.log](https://github.com/ververica/flink-cdc-connectors/files/8923868/taskmanager.log)

**4、oblogproxy通道目录，只有一张表的**
![1655364636175_CC8FB9B8-0BA1-4b81-97A1-CC5FC76E7369](https://user-images.githubusercontent.com/56627592/174203946-42415e38-9bc0-4bb4-898d-7c839fd0a73a.png)

**5、关于此通道的日志，我是整个目录打包的。**
[10.20.210.138_14402_1655364371sys.ob.products.zip](https://github.com/ververica/flink-cdc-connectors/files/8923787/10.20.210.138_14402_1655364371sys.ob.products.zip)

### 个人的一些理解
因为涉及到两张表，所以正常是会创建两张表通道的。如下是我正常的flink单机集群下的Logproxy日志
![image](https://user-images.githubusercontent.com/56627592/174205845-0ca47dd9-7159-4b95-bf74-5efda2abf69c.png)

而在异常的flink_yarn场景下。会是重复某一张表的通道创建。如下
![image](https://user-images.githubusercontent.com/56627592/174205994-fb6b028f-7c2a-4975-8736-898e0732f83b.png)

阿里同学也帮我们分析了：logproxy没有异常信息，可能是在flink / logproxy-client这边。烦请协助分析下。

**Comment by whhe** [comment]
经过排查，初步判定问题出在 oblogclient 的配置类上，目前已发布的版本里，配置类的成员变量都是 static 的，对象之间没有隔离，在并发环境下存在问题。

ref: oceanbase/oblogclient#47
