### ISSUE TITLE
'debezium.snapshot.locking.mode' = 'none' 报错

### ISSUE THREAD

**Issue by xechaos** [ververica/flink-cdc-connectors#129]
Could not execute SQL statement. Reason:
org.apache.flink.table.api.ValidationException: Unsupported options found for connector 'mysql-cdc'.

Unsupported options:

debezium.snapshot.mode

Supported options:

connector
database-name
hostname
password
port
property-version
server-id
table-name
username

**Comment by dua01** [comment]
#120 This may help you . Above options only support Table/SQL API.
