### ISSUE TITLE
SQLServer 为过程或函数 cdc.fn_cdc_get_all_changes_ ...  提供的参数数目不足

### ISSUE THREAD

**Issue by ynzzxc** [ververica/flink-cdc-connectors#1291]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.14.4
 - Flink CDC version: 2.2.1
 - Database and version: Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)

**To Reproduce**
1. Thes test data :
2. The test code :

t_env.execute_sql(
"""
create table carflow (
    id bigint,
    car_number varchar(20),
    camera_time timestamp(3),
    c_time AS TIMESTAMPADD(hour,-8,camera_time),
    primary key (id) NOT ENFORCED,
    WATERMARK FOR c_time AS c_time
) WITH (
    'connector' = 'sqlserver-cdc',
    'hostname' = '...',
    'port' = '...',
    'username' = 'cdcreader',
    'password' = '...',
    'database-name' = '...',
    'debezium.snapshot.mode' = 'schema_only',
    'debezium.snapshot.isolation.mode' = 'read_committed',
    'schema-name' = 'dbo',
    'table-name' = '...'
"""
)

t_env.execute_sql(
"""
create table car (
    car_number varchar(20),
    first_time timestamp(3),
    WATERMARK FOR first_time AS first_time, 
    primary key (car_number) NOT ENFORCED
) WITH (
    'connector' = 'jdbc',
    'url' = 'jdbc:mysql:',
    'username' = '...',
    'password' = '...',
    'lookup.cache.max-rows' = '100000',
    'lookup.cache.ttl' = '60 s',
    'lookup.max-retries' = '3',
    'table-name' = '...'

"""
)

t_env.sql_query(
"""
SELECT
    CAST(a.camera_time AS date) camera_date,
    HOUR(a.camera_time) AS camera_hour,
    COUNT( CASE WHEN a.c_time=b.first_time THEN a.plate_license ELSE NULL END ) f_cnt
FROM carflow AS a
    JOIN car FOR SYSTEM_TIME AS OF a.c_time AS b ON b.car_number=a.car_number
GROUP BY CAST(a.camera_time AS date), HOUR(a.camera_time)
""").insert_into('f_cnt')

4. The error :
2022-06-18 04:33:00,733 ERROR io.debezium.pipeline.ErrorHandler                            [] - Producer failure
com.microsoft.sqlserver.jdbc.SQLServerException: 为过程或函数 cdc.fn_cdc_get_all_changes_ ...  提供的参数数目不足。

**Additional Description**

**Comment by Xiaojun-Pan** [comment]
Has this problem been solved, and if so, can you share it? Thanks!

**Comment by ynzzxc** [comment]
> Has this problem been solved, and if so, can you share it? Thanks!

not
