### ISSUE TITLE
Flink CDC for oracle无锁全量同步

### ISSUE THREAD

**Issue by luckes-yang** [ververica/flink-cdc-connectors#1292]
Flink CDC for oracle 目前版本在同步的时候需要锁表权限，这个权限在使用过程中是非常危险的，易造成锁表，希望能够实现和mysql cdc一样的无锁全量同步。

**Comment by fuyun2024** [comment]
You can track this pr : [url](https://github.com/ververica/flink-cdc-connectors/pull/1079)
