### ISSUE TITLE
flink-cdc-connectors-sql  ,有没有好心人 支持oracle数据库或者华为高斯gaussdb数据库了??

### ISSUE THREAD

**Issue by ithjz** [ververica/flink-cdc-connectors#130]
flink-cdc-connectors-sql   ,有没有好心 支持oracle数据库或者华为高斯gaussdb数据库了??

**Comment by Tan-JiaLiang** [comment]
debezuim的oracle cdc还在测试/开发阶段 flink-cdc应该需要等到debezium社区的oracle cdc出稳定版后才会支持

**Comment by KyleZhang0536** [comment]
https://debezium.io/blog/2021/04/08/debezium-1-5-final-released/
debezuim 1.5里oracle connector已经是稳定版了，不知道有没有试用过的

**Comment by leonardBang** [comment]
duplicate with #76
