### ISSUE TITLE
flink cdc tidb throw exception while the project start

### ISSUE THREAD

**Issue by phoeph** [ververica/flink-cdc-connectors#1319]
**Describe the bug(Please use English)**
Demo from flink cdc tidb github , I test on my laptop, run the project, and then error occurs, like below:
![image](https://user-images.githubusercontent.com/34429096/175868739-2ab147a3-f4b2-4612-9191-62dd3b17c54f.png)

**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version: 2.2.1
 - Database and version: 5.4.0

**Comment by phoeph** [comment]
Is anyone who can help me? 
Many Thanks:)

**Comment by TheBiiigBlue** [comment]
I also encountered this problem and asked for help

**Comment by TheBiiigBlue** [comment]
> 

How did you solve it? Can you give me some ideas？
