### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by roy-long** [ververica/flink-cdc-connectors#1322]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.15.0
 - Flink CDC version: 2.2.1
 - Database and version: mongodb4.4.6

**To Reproduce**
1. Thes test data :
2. The test code :String sourceDDL = "CREATE TABLE Data_Input (" +
                " _id STRING," +
                " t1 STRING," +
                " t2 STRING," +
                " t3 STRING," +
                "  PRIMARY KEY (`_id`) NOT ENFORCED"+
                ") WITH (" +
                "  'connector' = 'mongodb-cdc'," + 
                "  'hosts' = '10.219.227.233:27017'," +
                "  'username' = 'xzj'," +
                "  'password' = '421102xzj'," +
                "  'database' = 'sjzt'," +
                "  'collection' = 'sjzt.test'," +
                "  'connection.options' = 'authSource=sjzt',"+
                "  'copy.existing' = 'false'"+     //默认为 全量+增量 读取；使用copy.existing=false参数设置为只读增量。
                ")";
        String sinkDDL ="CREATE TABLE Data_Output (" +
                " id STRING," +                                                      //字段类型
                " t1 STRING," +                                                   //字段类型
                " t2 STRING," +                                                   //字段类型
                " t3 STRING," +
                " PRIMARY KEY (`id`) NOT ENFORCED " +
                ") WITH (" +
                " 'connector' = 'jdbc'," +                                                   //输出表使用jdbc connector输出到mysql
                "'driver' = 'com.mysql.cj.jdbc.Driver',"+
                " 'url' = 'jdbc:mysql://10.219.227.233:3307/flink_web?serverTimezone=UTC&useSSL=false'," +
                " 'username' = 'root'," +
                " 'password' = '11230506'," +
                " 'table-name' = 'test_copy1'" +
                ")";
        String transformDmlSQL ="INSERT INTO Data_Output (SELECT * FROM Data_Input)";
3. The error :
![image](https://user-images.githubusercontent.com/28853880/176070142-45d3b857-7833-45d8-9fb8-b55819491173.png)

**Additional Description**

**Comment by gong** [comment]
@roy-long  Maybe, you need change flink version. [supported-flink-versions](https://ververica.github.io/flink-cdc-connectors/release-2.2/content/about.html#supported-flink-versions)

**Comment by roy-long** [comment]
1.14.4 version has same problems.

**Comment by Jiabao-Sun** [comment]
Hi @roy-long ,
Do you include both flink-connector-mongodb-cdc and flink-sql-connector-mongodb-cdc in your pom file?
It looks like a dependency problem.

**Comment by Jiabao-Sun** [comment]
Hi @roy-long ,
Do you include both flink-connector-mongodb-cdc and flink-sql-connector-mongodb-cdc in your pom file?
It looks like a dependency problem.
