### ISSUE TITLE
[Mysql]coding problem lead to chinese garbled

### ISSUE THREAD

**Issue by yangyin666** [ververica/flink-cdc-connectors#1325]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.13.6
 - Flink CDC version: 2.1.1
 - Database and version: 5.7.30

**To Reproduce**

Thes test data : 
```
CREATE TABLE `test` (
  `id` varchar(255) NOT NULL,
  `name` varchar(255) CHARACTER SET gbk NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `test` VALUES ('1', '中国');
INSERT INTO `test` VALUES ('2', '美国');
```

encoding of the table is utf-8, the field 'name' encoding is gbk. 
The test code :
```
    tEnv.executeSql(
      """
        | CREATE TABLE source (
        |  `id` STRING,
        |  `name` STRING,
        |  PRIMARY KEY (`dev_id`) NOT ENFORCED
        |   ) WITH (
        |    'connector' = 'mysql-cdc',
        |    'hostname' = 'localhost',
        |    'port' = '3306',
        |    'username' = 'test',
        |    'password' = 'test',
        |    'database-name' = 'test',
        |    'table-name' = 'test'
        |   )
      """.stripMargin)

    tEnv.executeSql(
      """
        | select * from source
        |""".stripMargin).print()
```

print data directly

The error :
![image](https://user-images.githubusercontent.com/40516136/176132741-bf801f14-0d63-45af-99a9-d00ef9f67e79.png)

Add new data
```
INSERT INTO `test` VALUES ('3', '中国');
INSERT INTO `test` VALUES ('4', '美国');
```

![image](https://user-images.githubusercontent.com/40516136/176132939-8a6d6e7d-ed28-4d39-a80a-a415ee4e28f6.png)

Existing data will generate garbled characters. After the program starts, The new data will not be garbled.

How to ensure that it will not be garbled together?
**Additional Description**

**Comment by ruanhang1993** [comment]
This issue is duplicate to #1166.
