### ISSUE TITLE
Flink1.14.4 冲突

### ISSUE THREAD

**Issue by zzj-always** [ververica/flink-cdc-connectors#1335]
### Discussed in https://github.com/ververica/flink-cdc-connectors/discussions/1035

<div type='discussions-op-text'>

<sup>Originally posted by **syb853553110** April  1, 2022</sup>
Error:(75, 62) java: 不兼容的类型: org.apache.kafka.connect.source.SourceRecord无法转换为com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.source.SourceRecord
</div>

**Comment by ruanhang1993** [comment]
Please provide more information and reopen this.
