### ISSUE TITLE
是否可以支持mysql-cdc 建表 放入sql-client.yaml配置文件里？

### ISSUE THREAD

**Issue by yaoboxu** [ververica/flink-cdc-connectors#135]
like this:
.......
tables:
  - name: order_info
    type: source
    connector: mysql-cdc
        hostname: 127.0.0.1
        port: 3306
        username: canal
        password: canal
        database-name: test
        schema:
          - name: id
            type: BIGINT
          - name: user_id
            type: BIGINT
          - name: create_time
            type: TIMESTAMP
          - name: operate_time
            type: TIMESTAMP
          - name: province_id
            type: INT
          - name: order_status
            type: STRING
          - name: total_amount
            type: DECIMAL
.......

**Comment by fsk119** [comment]
The sql-client.yaml file is not recommended to init the sql-client right now. In the master branch, it has already totally remove the usage of the YAML. Please use the init file as the replacement. Please take a look at the doc for more details[1].

[1] https://ci.apache.org/projects/flink/flink-docs-master/docs/dev/table/sqlclient/#initialize-session-using-sql-files
