### ISSUE TITLE
[mysql] The debezium reader resources exists thread leak risk

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#1350]
The debezium reader resources exists thread leak risk, we should release the thread timely

**Comment by qq443672581** [comment]
Could you please briefly describe how you discovered it and the corresponding impact? @leonardBang

**Comment by Matrix42** [comment]
As far as I know, `SnapshotSplitReader` and `BinlogSplitReader` when close method was invoked, the executor maybe failed to shutdown properly .

**Comment by qq443672581** [comment]
> As far as I know, `SnapshotSplitReader` and `BinlogSplitReader` when close method was invoked, the executor maybe failed to shutdown properly . @qq443672581

thanks

**Comment by leonardBang** [comment]
Thanks @Matrix42 for the additional comment, would you like to take this issue?

**Comment by Matrix42** [comment]
I'd like to take this issue. @leonardBang
