### ISSUE TITLE
[mysql] Add validation for connect.timeout option

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#1352]
The value of `connect.timeout` master bigger than 250ms due to the Connection pool limitation, we can add a validation for it.

**Comment by LXin96** [comment]
hello, @leonardBang. Does this enhancement mean to check the `connect.timeout` is a positive integer value expect zero as the description of connect.timeout.ms in debezium doc? 
<img width="1688" alt="截屏2022-09-03 下午10 05 16" src="https://user-images.githubusercontent.com/23535593/188277174-aa643e30-dd20-4837-a9a2-4d43adc33e7f.png">
