### ISSUE TITLE
往目标表写数据时候报“UpsertStreamTableSink requires that Table has a full primary keys if it is updated”

### ISSUE THREAD

**Issue by chenzhiyuan0402** [ververica/flink-cdc-connectors#136]
我链接的是Mysql,创建了一个cdc源，并往目标表写数据，但是一直报以下错误，找不到原因。
Exception in thread "main" org.apache.flink.table.api.TableException: UpsertStreamTableSink requires that Table has a full primary keys if it is updated

    private static final String benefitSalarySql = "CREATE TABLE cdcsourcetable (\n" + "\t\tBENEFIT_SALARY_ID\tbigint,\n"
        + "\t\tPERSON_ID\tbigint,\n" + "\t\tSOURCE_TYPE\tvarchar,\n" + "\t\tBENEFIT_SALARY_YEAR\tint,\n"
        + "\t\tBENEFIT_SALARY_MONTH\tint,\n" + "\t\tGRADE_VALUE\tvarchar,\n"
        + "\t\tBENEFIT_SALARY_AMOUNT\tdecimal,\n" + "\t\tSECTION_OU_ID\tbigint,\n" + "\t\tORG_ID\tbigint,\n"
        + "\t\tSOURCE_ID\tvarchar,\n" + "\t\tENABLE_FLAG\tvarchar,\n" + "\t\tREMARK\tvarchar,\n"
        + "\t\tCREATED_BY\tbigint,\n" + "\t\tCREATION_DATE\tTIMESTAMP(3),\n" + "\t\tLAST_UPDATED_BY\tbigint,\n"
        + "\t\tLAST_UPDATE_DATE\tTIMESTAMP(3),\n" + "\t\tATTRIBUTE_1\tvarchar,\n" + "\t\tATTRIBUTE_2\tvarchar,\n"
        + "\t\tATTRIBUTE_3\tvarchar,\n" + "\t\tATTRIBUTE_4\tvarchar,\n" + "\t\tATTRIBUTE_5\tvarchar,\n"
        + "\t\tATTRIBUTE_6\tvarchar,\n" + "\t\tATTRIBUTE_7\tvarchar,\n" + "\t\tATTRIBUTE_8\tvarchar,\n"
        + "\t\tATTRIBUTE_9\tvarchar,\n" + "\t\tATTRIBUTE_10\tvarchar,\n" + "\t\tSECTION_REAL_L1\tvarchar,\n"
        + "\t\tSECTION_REAL_L2\tvarchar,\n" + "\t\tSECTION_REAL_L3\tvarchar,\n" + "\t\tSECTION_REAL_L4\tvarchar,\n"
        + "\t\tSECTION_REAL_L5\tvarchar,\n" + "\t\tSECTION_REAL_L6\tvarchar,\n" + "\t\tDELEGATE_FLAG\tvarchar,\n"
        + "\t\tOFFSET_LEDGER_FLAG\tvarchar,\n" + "\t\tCURRENCY_CODE\tvarchar,\n" + "\t\tPAYROLL_ID\tbigint,\n"
        + "\t\tTENANT_CODE\tvarchar\n" + ") WITH (\n" 
		+ "    'connector' = 'mysql-cdc',\n"
        + "    'hostname' = 'url',\n"
        + "    'port' = '1233',\n"
        + "    'database-name' = 'db',\n"
        + "    'table-name' = 'cdcsourcetable ',\n"
        + "    'username' = 'name',\n"
        + "    'password' = '12334'\n"
        + ")";

    private static final String sinkddl = "create table sinktable \n" + "(\tBENEFIT_SALARY_ID\tbigint,\n"
        + "\tPERSON_ID\tbigint,\n" + "\tSOURCE_TYPE\tvarchar,\n" + "\tBENEFIT_SALARY_YEAR\tint,\n"
        + "\tBENEFIT_SALARY_MONTH\tint,\n" + "\tGRADE_VALUE\tvarchar,\n" + "\tBENEFIT_SALARY_AMOUNT\tdecimal,\n"
        + "\tSECTION_OU_ID\tbigint,\n" + "\tORG_ID\tbigint,\n" + "\tSOURCE_ID\tvarchar,\n"
        + "\tEMPLOYEE_NUMBER\tvarchar,\n" + "\tLAST_NAME\tvarchar,\n"
        + "\tPRIMARY KEY(BENEFIT_SALARY_ID) NOT ENFORCED\n"
        + ") WITH (\n"
            + "    'connector.type' = 'jdbc',\n"
            + "    'connector.url' = 'url',\n"
            + "    'connector.table' = 'sinktable',\n"
            + "    'connector.driver' = 'com.mysql.jdbc.Driver',\n"
            + "    'connector.username' = 'name',\n"
            + "    'connector.password' = '12334'\n"
        +  ")";

        StreamTableEnvironment tEnv = StreamTableEnvironment.create(env, bsSettings);
        tEnv.executeSql(benefitSalarySql);
        tEnv.executeSql(benefitSalaryDest);

        TableResult tableResult = tEnv.executeSql("INSERT INTO sinktable (BENEFIT_SALARY_ID, PERSON_ID,SOURCE_TYPE,BENEFIT_SALARY_YEAR,BENEFIT_SALARY_MONTH,"
            + "GRADE_VALUE,BENEFIT_SALARY_AMOUNT,SECTION_OU_ID,ORG_ID,SOURCE_ID,EMPLOYEE_NUMBER,LAST_NAME)"
            + "SELECT\n" + "\tt.BENEFIT_SALARY_ID,\n" + "\tt.PERSON_ID,\n"
            + "\tt.SOURCE_TYPE,\n" + "\tt.BENEFIT_SALARY_YEAR,\n" + "\tt.BENEFIT_SALARY_MONTH,\n" + "\tt.GRADE_VALUE,\n"
            + "\tt.BENEFIT_SALARY_AMOUNT,\n" + "\tt.SECTION_OU_ID,\n" + "\tt.ORG_ID,\n" + "\tt.SOURCE_ID,\n"
            + "\t'test',\n"
            + "\t'test' \n" + "FROM\n" + "\cdcsourcetable t\n"
            + "WHERE\n"
            + "\t BENEFIT_SALARY_ID = 505\n");

       tEnv.execute("insert start");

**Comment by wuchong** [comment]
用新版的 jdbc connector 就可以了（`connector = jdbc`）。 https://ci.apache.org/projects/flink/flink-docs-master/docs/connectors/table/jdbc/
