### ISSUE TITLE
Support for Flink 1.15

### ISSUE THREAD

**Issue by tigrulya-exe** [ververica/flink-cdc-connectors#1363]
Hello! Are there any plans in the near future to support version 1.15 of Flink?

**Comment by leonardBang** [comment]
Yes, we will support 1.15 @tigrulya-exe, let me think how to support multiple versions(1.13&1.14&1.15)

**Comment by tigrulya-exe** [comment]
Hello, @leonardBang! Thanks for reply, but is it even possible to support all of this Flink versions in one CDC-connectors version without backporting Flink 1.15 features to older versions of Flink? At first, I thought about using different maven profiles in CDC for different Flink versions, but, as far as I understand, Flink 1.15 also brings some code, that breaks backward compatibility (e.g. removing old planner, LogicalTypeChecks.hasFamily removal, etc.). So, maybe it will be more simpler to introduce separate version for 1.15+?

**Comment by tigrulya-exe** [comment]
Hello, @leonardBang! I've added PR with Maven profiles approach - #1504. Could you take a look, please?

**Comment by leonardBang** [comment]
Thanks @tigrulya-exe for opening this PR， @PatrickRen Could you help review this PR？
