### ISSUE TITLE
Mongo CDC setting checkpoint does not take effect.

### ISSUE THREAD

**Issue by 421119407** [ververica/flink-cdc-connectors#1377]
**Describe the bug(Please use English)**
Mongo setting checkpoint does not take effect.

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version:  2.3-SNAPSHOT(mongo)
 - Database and version: 4.0.9

**To Reproduce**
`StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.enableCheckpointing(1457865148, CheckpointingMode.AT_LEAST_ONCE);`

**Additional Description**
Excuse me, does flink-connector-mongodb-cdc currently support setting checkpoint for resuming the transfer from a breakpoint?

**Comment by Jiabao-Sun** [comment]
Hi @421119407,
MongoDB CDC connector supports checkpoint when snapshot phase is finished.

**Comment by 421119407** [comment]
What should I do if I want to set the point from which to read the log?

**Comment by 421119407** [comment]
> 


What should I do if I want to set the point from which to read the log?

**Comment by 421119407** [comment]
> Hi @421119407, MongoDB CDC connector supports checkpoint when snapshot phase is finished.


What should I do if I want to set the point from which to read the log?
