### ISSUE TITLE
Is it so hard to support Flink1.14.*

### ISSUE THREAD

**Issue by future94** [ververica/flink-cdc-connectors#1395]
**Describe the bug(Please use English)**
Caused by: java.lang.ClassNotFoundException: org.apache.flink.shaded.guava18.com.google.common.util.concurrent.ThreadFactoryBuilder

**Environment :**
 - Flink version :  1.14.5
 - Flink CDC version:  2.2.1

unsupported documents can be deleted？

![image](https://user-images.githubusercontent.com/78329752/180391590-f6379d78-7b30-48e2-bf4a-30e1fb85b839.png)

**Comment by liyichencc** [comment]
Maybe it's your use problem. I have successfully used version 2.2.1 CDC in flink1.14

**Comment by future94** [comment]
> Maybe it's your use problem. I have successfully used version 2.2.1 CDC in flink1.14

class `com.ververica.cdc.debezium.DebeziumSourceFunction` import `org.apache.flink.shaded.guava18.com.google.common.util.concurrent.ThreadFactoryBuilder` ,  flink 1.14 do not have guava18，it is guava30，you do not have problem? How to solve this error problem? Thank you，Looking forward to your reply.

**Comment by gezhiwei8899** [comment]
![image](https://user-images.githubusercontent.com/16362526/184759544-578f9be8-414d-47c6-93fe-ffc0ce591271.png)
I solved the problem like this.

**Comment by Level1Accelerator** [comment]
> ![image](https://user-images.githubusercontent.com/16362526/184759544-578f9be8-414d-47c6-93fe-ffc0ce591271.png) I solved the problem like this.

 Could not resolve substitution to a value: ${akka.stream.materializer}
cdc:2.3.0

**Comment by Level1Accelerator** [comment]
> > ![image](https://user-images.githubusercontent.com/16362526/184759544-578f9be8-414d-47c6-93fe-ffc0ce591271.png) I solved the problem like this.
> 
> Could not resolve substitution to a value: ${akka.stream.materializer} cdc:2.3.0
flink :1.15.3
