### ISSUE TITLE
No entry to modify the DBZ properties

### ISSUE THREAD

**Issue by NextMark** [ververica/flink-cdc-connectors#14]
Mysql cdc connector need add the entry to modify the DBZ properties.

**Comment by wuchong** [comment]
Yes, I think this is a reasonable feature. Passing through debezium's properties will be very helpful. For example, we can support 'debezium.*' to pass throught the properties.

**Comment by wuchong** [comment]
Fixed in c89b46f14a26ed9f00c0c357c3c12420e9ae68f0
