### ISSUE TITLE
CDC 首次启动的时候 LOCK TABLES 权限

### ISSUE THREAD

**Issue by xuhaiL** [ververica/flink-cdc-connectors#141]
有点疑惑，mysql cdc 首次启动获取binlog offset 为什么需要锁表权限？这种缩表权限会不会对业务影响较大，有没有其他更好的方法去处理？

**Comment by oooguai** [comment]
看Wiki:[The global read lock (FLUSH TABLES WITH READ LOCK)](https://github.com/ververica/flink-cdc-connectors/wiki/MySQL-CDC-Connector#the-global-read-lock-flush-tables-with-read-lock)里面有介绍。

**Comment by xuhaiL** [comment]
ok，明白了
