### ISSUE TITLE
flink-cdc-connectors 编译 maven  install 报错了

### ISSUE THREAD

**Issue by ithjz** [ververica/flink-cdc-connectors#142]
flink-cdc-connectors 编译 maven  install 报错了

[INFO] 
[INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ flink-cdc-connectors ---
[WARNING] JAR will be empty - no content was marked for inclusion!
JAR will be empty - no content was marked for inclusion!

Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project flink-cdc-connectors: Too many files with unapproved license: 1 See RAT report in: E:\360down\flink-cdc-connectors-master\target\rat.txt

**Comment by ithjz** [comment]
Some problems were encountered while building the effective model for com.alibaba.ververica:flink-connector-debezium:jar:1.2-SNAPSHOT
'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-enforcer-plugin @ com.alibaba.ververica:flink-cdc-connectors:1.2-SNAPSHOT, E:\360down\flink-cdc-connectors-master\pom.xml, line 329, column 21
Some problems were encountered while building the effective model for com.alibaba.ververica:flink-cdc-connectors:pom:1.2-SNAPSHOT
'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-enforcer-plugin @ line 329, column 21
It is highly recommended to fix these problems because they threaten the stability of your build.
For this reason, future Maven versions might no longer support building such malformed projects.

**Comment by ithjz** [comment]
Printing headers for text files without a valid license header...
 
=====================================================
== File: Test Results - MySQLSourceTest_testConsumingAllEvents.html

**Comment by leonardBang** [comment]
This should be related to your environment

**Comment by codejianhongxie** [comment]
@leonardBang It seems that the developer forgot to add a license to the file header during development. 
We can skip the check by adding "- Drat. skip=true" during compilation.
However, I personally suggest that we can check that all relevant files are added with licenses during the code merge request, and formulate them into code submission specifications.

**Comment by leonardBang** [comment]
We do it all the time @codejianhongxie 
[1] https://github.com/ververica/flink-cdc-connectors/blob/master/tools/ci/compile.sh#L55
