### ISSUE TITLE
could flink cdc  insert mysql just snapshot  not Incremental data by binlog ？ 

### ISSUE THREAD

**Issue by linmingze** [ververica/flink-cdc-connectors#1428]
I want insert mysql snapshot data on sometime by day，the data do not change  frequent。

**Comment by ruanhang1993** [comment]
I think it is not suitable to do this job by using the cdc connectors.

**Comment by linmingze** [comment]
you are right，it is suitable for batch processing

**Comment by linmingze** [comment]
> I don't think it is suitable to do this job by using the cdc connectors.

you are right，it is suitable to use batch processing

**Comment by linmingze** [comment]
> I don't think it is suitable to do this job by using the cdc connectors.
you are right，it is suitable to use batch processing
