### ISSUE TITLE
[Feature] debezium version can upgrade to 1.9, the version 1.6.4Final has some Bug

### ISSUE THREAD

**Issue by youyangkou** [ververica/flink-cdc-connectors#1434]
**Is your feature request related to a problem? Please describe.**
i make sure the issue https://github.com/ververica/flink-cdc-connectors/issues/1279 is relation to debezium 1.6.4Final version's Bug

**Describe the solution you'd like**
I think the debezium depency's version of flink-cdc-connectors can upgrade to 1.9 version.

**Describe alternatives you've considered**
this is debezium's Mantanier's response
![image](https://user-images.githubusercontent.com/33364356/181734467-bb103cee-a1ec-4d25-9873-5c960c71fb9f.png)

**Comment by youyangkou** [comment]
@leonardBang

**Comment by leonardBang** [comment]
Thanks @youyangkou for report this issue, assigned this issue to me.

**Comment by hezhenghongmail** [comment]
@leonardBang   hi， Are there any plans to upgrade to DeBezium 1.9?   I meet the same problem.

**Comment by leonardBang** [comment]
> @leonardBang hi， Are there any plans to upgrade to DeBezium 1.9? I meet the same problem.

Could you share your issue detail? the upgrade is a big task and will take some time to deal.

**Comment by GOODBOY008** [comment]
https://github.com/ververica/flink-cdc-connectors/pull/2156#pullrequestreview-1485319925  was merged.
