### ISSUE TITLE
TiDB CDC dealUnsignedColumnValue throw NullPointerException

### ISSUE THREAD

**Issue by gbzy** [ververica/flink-cdc-connectors#1442]
dealUnsignedColumnValue will throw NullPointerException when column value is null.
![image](https://user-images.githubusercontent.com/18411217/182544295-28791253-48bc-409e-912f-c5a73c8bc430.png)

**Comment by GOODBOY008** [comment]
@gbzy Thanks for your issue , I will take it, if it is a bug.
