### ISSUE TITLE
10:08:16.249 [Canceler/Interrupts for Source: Custom Source -> Sink: Unnamed (1/1)#0 (fa21d4177bd34fe5e18fd99a4b09f437).] WARN  org.apache.flink.runtime.taskmanager.Task  - Task 'Source: Custom Source -> Sink: Unnamed (1/1)#0' did not react to cancelling signal - interrupting; it is stuck for 30 seconds in method:

### ISSUE THREAD

**Issue by Angelasp** [ververica/flink-cdc-connectors#1458]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version: 2.1.0
 - Database and version: postgresql 12

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :
10:08:16.249 [Canceler/Interrupts for Source: Custom Source -> Sink: Unnamed (1/1)#0 (fa21d4177bd34fe5e18fd99a4b09f437).] WARN  org.apache.flink.runtime.taskmanager.Task  - Task 'Source: Custom Source -> Sink: Unnamed (1/1)#0' did not react to cancelling signal - interrupting; it is stuck for 30 seconds in method:
**Additional Description**

**Comment by Angelasp** [comment]
[Canceler/Interrupts for Source: Custom Source -> Sink: Unnamed (1/1)#1 (6d1e861b136a5123475f9555967ab3dc).] WARN  org.apache.flink.runtime.taskmanager.Task  - Task 'Source: Custom Source -> Sink: Unnamed (1/1)#1' did not react to cancelling signal - interrupting; it is stuck for 30 seconds in method:  这个问题有人知道吗？

**Comment by yaoyi** [comment]
@Angelasp 我这边也遇到一样的问题，你解决了吗？

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
