### ISSUE TITLE
DataStream下MySQL读取到的字段Date类型的更改输出异常

### ISSUE THREAD

**Issue by HaoRanCang** [ververica/flink-cdc-connectors#150]
按照文档的DataStream api例子读取mysql的binlog并进行打印，打印出的生日字段异常，mysql的生日字段为日期格式

**Comment by xiaoshijiang523** [comment]
date类型的应该变为距离1970-01-01的天数了吧，我这边是这样，然后需要自己再转换。

**Comment by leonardBang** [comment]
DataStream作业需要你自己做类型转换
