### ISSUE TITLE
Flink cdc 同步 TiDB， 每个任务只能拉一个表吗？

### ISSUE THREAD

**Issue by mxd-321** [ververica/flink-cdc-connectors#1509]
Flink cdc 同步 TiDB， 每个任务只能拉一个表吗？

**Comment by mooncake020** [comment]
支持  现在数据库名和表名都不如mysqlcdc好用 mysqlcdc库名表名都可以正则匹配  tidb的太鸡肋了

**Comment by mooncake020** [comment]
你提了我就不单独提issue了哈兄嘚

**Comment by mxd-321** [comment]
嗯嗯，我看了 tidb-cdc 的源码，flink-cdc 用的 tikv-client， tikv-client 的每个 cdcClient 只能拉一个表，所以 flink-cdc 没做单任务多表拉取。
