### ISSUE TITLE
Flink-sql-cdc如何将一对多的数据转换成一个嵌套对象结构的文档写入elasticsearch

### ISSUE THREAD

**Issue by Myuan93** [ververica/flink-cdc-connectors#151]
场景是现在需要将订单数据同步至elasticsearch,订单数据在mysql中的结构是订单主体数据加订单商品明细数据的集合,我们ES中的数据也是使用这种嵌套对象的模型,目前自己自定义实现了org.apache.flink.table.functions.AggregateFunction#getValue方法来处理明细数据,将明细数据转换成json放在主表的一个字段上,但是发现还是写入不了,想问下对于这种场景有没有什么好的办法呢?

**Comment by wuchong** [comment]
mysql 中的字段类型是什么？

**Comment by Myuan93** [comment]
mysql中是一张表的数据,现在是想把这张表的数据组装成对象的集合放在Es中,类似这样的数据结构
`{
        "_index" : "trade_flink",
        "_type" : "_doc",
        "_id" : "T210329133820491",
        "_score" : 1.0,
        "_source" : {
          "virtual" : 0,
          "shop" : 110,
          "id" : "T210329133820491",
          "tradeItems" : [
            {
              "productSale" : "10353454",
              "purchaseQuantity" : 20,
              "id" : 128679552,
            },
            {
              "productSale" : "10352384",
              "purchaseQuantity" : 30,
              "id" : 128679553,
            }
          ],
          "status" : "DELIVERING",
          "customer" : 1702627547
        }
      }`

**Comment by yinjiangit** [comment]
1.将es表中tradeItems 类型为ARRAY<ROW< productSale STRING, purchaseQuantity INT, id INT>>
2.定义一个udf es  传入groupby后的拼接group_concat es(COLLECT( DISTINCT CONCAT(productSale,':',purchaseQuantity,':'id)))
3.udf 中构建出org.apache.flink.types.Row 的数组 每个row是嵌套中的每个元素 ArrayList<Row> rows = new ArrayList<>();rows.toArray(new Row[0])
4. udf输出的格式指定       @Override
        public TypeInformation<?> getResultType(Class<?>[] signature) {
            return Types.OBJECT_ARRAY(Types.ROW_NAMED("productSale,purchaseQuantity,id".split(","), Types.STRING, Types.INT,Types.INT));
        }

**Comment by Myuan93** [comment]
> 1.将es表中tradeItems 类型为ARRAY<ROW< productSale STRING, purchaseQuantity INT, id INT>>
> 2.定义一个udf es 传入groupby后的拼接group_concat es(COLLECT( DISTINCT CONCAT(productSale,':',purchaseQuantity,':'id)))
> 3.udf 中构建出org.apache.flink.types.Row 的数组 每个row是嵌套中的每个元素 ArrayList rows = new ArrayList<>();rows.toArray(new Row[0])
> 4. udf输出的格式指定 @override
> public TypeInformation getResultType(Class[] signature) {
> return Types.OBJECT_ARRAY(Types.ROW_NAMED("productSale,purchaseQuantity,id".split(","), Types.STRING, Types.INT,Types.INT));
> }

thanks 这个问题已经解决了

**Comment by 812406210** [comment]
> > 1.将es表中tradeItems 类型为ARRAY<ROW< productSale STRING, purchaseQuantity INT, id INT>>
> > 2.定义一个udf es 传入groupby后的拼接group_concat es(COLLECT( DISTINCT CONCAT(productSale,':',purchaseQuantity,':'id)))
> > 3.udf 中构建出org.apache.flink.types.Row 的数组 每个row是嵌套中的每个元素 ArrayList rows = new ArrayList<>();rows.toArray(new Row[0])
> > 4. udf输出的格式指定 @override
> > public TypeInformation getResultType(Class[] signature) {
> > return Types.OBJECT_ARRAY(Types.ROW_NAMED("productSale,purchaseQuantity,id".split(","), Types.STRING, Types.INT,Types.INT));
> > }
> 
> thanks 这个问题已经解决了

老哥，请问你那边是怎么解决的，上面的老哥写的没有看懂

**Comment by 812406210** [comment]
> 1.将es表中tradeItems 类型为ARRAY<ROW< productSale STRING, purchaseQuantity INT, id INT>>
> 2.定义一个udf es 传入groupby后的拼接group_concat es(COLLECT( DISTINCT CONCAT(productSale,':',purchaseQuantity,':'id)))
> 3.udf 中构建出org.apache.flink.types.Row 的数组 每个row是嵌套中的每个元素 ArrayList rows = new ArrayList<>();rows.toArray(new Row[0])
> 4. udf输出的格式指定 @override
> public TypeInformation getResultType(Class[] signature) {
> return Types.OBJECT_ARRAY(Types.ROW_NAMED("productSale,purchaseQuantity,id".split(","), Types.STRING, Types.INT,Types.INT));
> }

老哥，代码块可以发给我看下不？你这个步骤没看懂

**Comment by oulexue** [comment]
如何通过sql实现呢？

**Comment by gwqlovelinux** [comment]
求详细的解决方案

**Comment by yilongchuan** [comment]
nested 字段具体如何处理的？

**Comment by xiaofei159** [comment]
> 

请问你解决没，怎么实现的啊

**Comment by mojirml** [comment]
同问怎么解决的一对多的这种情况呀 @Myuan93 Myuan93

**Comment by BlackChen277** [comment]
同问
