### ISSUE TITLE
cdc读取mysql DateTime类型 数据快了8个小时,设置了时区为Asia/Shanghai没有作用

### ISSUE THREAD

**Issue by hezongjin** [ververica/flink-cdc-connectors#152]

**Comment by zhisheng17** [comment]
不知道这个是不是你想要的 https://github.com/ververica/flink-cdc-connectors/issues/44

**Comment by hezongjin** [comment]
感谢大佬



***@***.***
 
发件人： zhisheng
发送时间： 2021-04-19 11:41
收件人： ververica/flink-cdc-connectors
抄送： hezongjin-dd01; Author
主题： Re: [ververica/flink-cdc-connectors] cdc读取mysql DateTime类型 数据快了8个小时,设置了时区为Asia/Shanghai没有作用 (#152)
不知道这个是不是你想要的 #44
