### ISSUE TITLE
when will flink cdc mysql 2.X  support specific-offset

### ISSUE THREAD

**Issue by lijunkai** [ververica/flink-cdc-connectors#1543]
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.table.api.ValidationException: Unsupported option value 'specific-offset', 
the options [earliest-offset, specific-offset, timestamp] are not supported correctly, 
please do not use them until they're correctly supported

**Comment by GOODBOY008** [comment]
Hi @lijunkai ,Pr has opened , pay attention to this pr https://github.com/ververica/flink-cdc-connectors/pull/1157.

**Comment by ruanhang1993** [comment]
PR #1661 fixed this issue.
