### ISSUE TITLE
When postgres cdc get exception 'FATAL: no pg_hba.conf'  but work normally in jdbc connector.

### ISSUE THREAD

**Issue by lpn666** [ververica/flink-cdc-connectors#1545]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :   1.14.4
 - Flink CDC version:  postgres cdc 2.2.1
 - Database and version:  postgres 9.6

**To Reproduce**
1. The test data : 
2. The test code : 

CREATE TABLE eee (
	a string ,
	b string 
) WITH (
  'connector' = 'postgres-cdc',
  'hostname' = 'localhost',
  'port' = '5432',
  'username' = 'postgres',
  'password' = 'postgres',
  'database-name' = 'test',
  'schema-name' = 'public',
  'table-name' = 'flink01'
);

select * from eee;
4. The error :
![image](https://user-images.githubusercontent.com/26716574/188773626-94a23af9-36f8-4973-88e9-18b4131e3cc2.png)

**Additional Description**
When I use jdbc connector  or  spring jdbc   to  connect  the  database,  it's running normally. 

I have try to alter the pg_hba.conf file.  but it's not work.
![image](https://user-images.githubusercontent.com/26716574/188775915-ef0f415e-b549-436b-b34a-20fa9287f34e.png)

**Comment by jcunhafonte** [comment]
@lpn666 Were you able to fix this issue?
