### ISSUE TITLE
cdc connectors 2.0以上版本，debezium配置不起效

### ISSUE THREAD

**Issue by yangmingjie** [ververica/flink-cdc-connectors#1546]
**Describe the bug(Please use English)**
cdc connectors 2.0以上版本，debezium配置不起效
之前的版本是可以的

![image](https://user-images.githubusercontent.com/5827183/188776525-0010837b-14d0-4616-8b91-e73e7bc12ad7.png)

@leonardBang @wuchong @GOODBOY008

**Comment by burningg** [comment]
我也遇到了，没解决

**Comment by GOODBOY008** [comment]
Hi. @yangmingjie  @burningg . Thanks for reporting this issue. I will reproduce this scenio and find out what happens.

**Comment by lykpass** [comment]
![image](https://user-images.githubusercontent.com/48595535/189060613-60958d96-4a68-4497-8d86-0af990f13f85.png)
![lQLPDhteKU_wZeXMqc0BkbACp5P1Uhy-zgJq8nvpgAIA_401_169](https://user-images.githubusercontent.com/48595535/189060670-d5bc0bd8-c091-4bfc-9e32-232680e29701.png)
还请后续支持该功能，我们的业务很需要这个功能，我们目前用的还是1.4的版本

**Comment by Yanbigfeng** [comment]
是的，我们再项目中也遇到了！怎么设置都不起作用。
Yes, we also met in the project! No matter how you set it, it won't work.

**Comment by yangmingjie** [comment]
> Hi. @yangmingjie @burningg . Thanks for reporting this issue. I will reproduce this scenio and find out what happens.

Thanks，Big Hero.

**Comment by GOODBOY008** [comment]
@yangmingjie  config 'debezium.startup.model' was wrong, it should be `scan.startup.mode`.

**Comment by GOODBOY008** [comment]
BTW, brand new parallel mysql implement perform oneself `snapshots ` , so some `debezium` config won‘t work.

**Comment by yangmingjie** [comment]
> BTW, brand new parallel mysql implement perform oneself `snapshots ` , so some `debezium` config won‘t work.

那 debezium的配置，在我们自己的实现有对应的配置吗？

**Comment by lykpass** [comment]
@GOODBOY008 有相关的支持计划吗

**Comment by GOODBOY008** [comment]
> @GOODBOY008 有相关的支持计划吗

Yes, Added to next release roadmap https://github.com/ververica/flink-cdc-connectors/issues/1728 .

**Comment by lykpass** [comment]
> > @GOODBOY008 有相关的支持计划吗
> 
> Yes, Added to next release roadmap #1728 .

Thanks
