### ISSUE TITLE
flinkcdc oracle 中oracle生成的表LOG_MINING_FLUSH是干嘛用的

### ISSUE THREAD

**Issue by glaryaugus** [ververica/flink-cdc-connectors#1553]
使用flinkcdc Oracle 会在Oracle库中生成LOG_MINING_FLUSH表，里面只有一个字段一个值LAST_SCN并且在一直变化中，这个表有什么作用呢。能不能解释一下。

**Comment by GOODBOY008** [comment]
HI @glaryaugus ,This table is created and maintained by debezium, which is used to flush logwriter processs.

**Comment by GOODBOY008** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
