### ISSUE TITLE
OracleE2eITCase occurs error 

### ISSUE THREAD

**Issue by EMsnap** [ververica/flink-cdc-connectors#1555]
**Environment :**
 - Flink version : 1.13  
 - Flink CDC version: 2.3-SNAPSHOT
 - Database and version: oracle-xe-11g-r2-cdc:0.1

**To Reproduce**
1. The test data :
2. <[101,scooter,Small 2-wheel scooter,3.14, 102,car battery,12V car battery,8.1, 103,12-pack drill bits,12-pack of drill bits with sizes ranging from #40 to #3,0.8, 104,hammer,12oz carpenters hammer,0.75, 105,hammer,14oz carpenters hammer,0.875, 106,hammer,18oz carpenter hammer,1.0, 107,rocks,box of assorted rocks,5.1, 108,jacket,water resistent black wind breaker,0.1, 109,spare tire,24 inch spare tire,22.2, 111,jacket,new water resistent white wind breaker,0.5]> 
3. The test code : com.ververica.cdc.connectors.tests.OracleE2eITCase
4. The error :
expected:
<[101,scooter,Small 2-wheel scooter,3.14, 102,car battery,12V car battery,8.1, 103,12-pack drill bits,12-pack of drill bits with sizes ranging from #40 to #3,0.8, 104,hammer,12oz carpenters hammer,0.75, 105,hammer,14oz carpenters hammer,0.875, 106,hammer,18oz carpenter hammer,1.0, 107,rocks,box of assorted rocks,5.1, 108,jacket,water resistent black wind breaker,0.1, 109,spare tire,24 inch spare tire,22.2, 111,jacket,new water resistent white wind breaker,0.5]> 
but was:
<[101,scooter,Small 2-wheel scooter,3.14, 102,car battery,12V car battery,8.1, 103,12-pack drill bits,12-pack of drill bits with sizes ranging from #40 to #3,0.8, 104,hammer,12oz carpenters hammer,0.75, 105,hammer,14oz carpenters hammer,0.875, 106,hammer,16oz carpenters hammer,1.0, 107,rocks,box of assorted rocks,5.1, 108,jacket,water resistent black wind breaker,0.1, 109,spare tire,24 inch spare tire,22.2, 111,jacket,new water resistent white wind breaker,0.5]>

see also in 
https://github.com/ververica/flink-cdc-connectors/pull/1139/checks?check_run_id=6224642546
**Additional Description**

**Comment by ruanhang1993** [comment]
It seems that the update sql about the id 106 is not captured by the connector. This same error appeared many times in CI.
<img width="1369" alt="截屏2022-10-31 上午10 53 39" src="https://user-images.githubusercontent.com/17610579/198921253-45308049-333b-48b2-b0d6-398970a31454.png">
