### ISSUE TITLE
flink sql cdc 同步数据到kafka时发送数据为null

### ISSUE THREAD

**Issue by Myuan93** [ververica/flink-cdc-connectors#157]
![image](https://user-images.githubusercontent.com/26614448/114358355-6917ab00-9ba5-11eb-9882-9a605a8d5077.png)
如图 并且我对数据库中某条记录某一个字段的修改 发送了多条kafka记录 并且还有为null的记录

**Comment by RyanLee1996** [comment]
有定位到是哪里的问题吗？遇到了同样的情况，往kafka写入会这样
