### ISSUE TITLE
Use Incremental Snapshot Framework for Sqlserver CDC Connector 

### ISSUE THREAD

**Issue by murongpingtian** [ververica/flink-cdc-connectors#1570]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by zjialin** [comment]
加1

**Comment by yuangjiang** [comment]
加1

**Comment by GOODBOY008** [comment]
https://github.com/ververica/flink-cdc-connectors/pull/1732 merged
