### ISSUE TITLE
flink cdc sqlserver全量+增量不锁表

### ISSUE THREAD

**Issue by zjialin** [ververica/flink-cdc-connectors#1571]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by murongpingtian** [comment]
加1

**Comment by rookiegao** [comment]
Follow this pr https://github.com/ververica/flink-cdc-connectors/pull/1222

**Comment by zjialin** [comment]
我需要全量这部分数据，只增量不会锁表的

**Comment by rookiegao** [comment]
> 

增量快照目的就是为了全量阶段无锁，并且可以并行读取
具体原理可浏览文档以及相关博客
https://ververica.github.io/flink-cdc-connectors/master/content/connectors/mysql-cdc%28ZH%29.html#a-name-id-001-a

**Comment by zjialin** [comment]
source = sqlserver  不是mysql

**Comment by rookiegao** [comment]
cc @GOODBOY008

**Comment by guandatawangjialin** [comment]
只是增量也会锁表的吧 @zjialin 
![image](https://user-images.githubusercontent.com/102361568/205582663-237ca3c9-869f-4d9a-b913-0d7913905e18.png)
这个逻辑在全量跟增量的时候都会走这段逻辑

**Comment by ruanhang1993** [comment]
This is duplicated to #1570 and #1212 . Let's discuss in these issues. 
Close this issue.
