### ISSUE TITLE
flink cdc使用新的MySqlSource中必须包含主键吗？可以不使用无锁算法吗？我想同时抓取到无主键的表和DDL

### ISSUE THREAD

**Issue by KK900716** [ververica/flink-cdc-connectors#1579]
我在使用flink cdc做同步的项目中，无法同时同步无主键的表和DDL语句！

**Comment by dsimile** [comment]
1.需要注意的是，由于表是无主键的，Flink CDC无法使用Initial模式获取全量数据。
2.com.ververica.cdc.connectors.mysql.source.MySqlSource不可以使用Initial模式获取全量数据，参数为 startupOptions.latest()，表示从最新的数据开始读取。
3.com.ververica.cdc.connectors.mysql.MySqlSource 可以使用Initial模式获取全量数据 + 增量数据。

**Comment by KK900716** [comment]
所以必须要使用弃用的类和方法才能获取吗？这貌似有些不合理，不过非常感谢您的解答

**Comment by ruanhang1993** [comment]
2.4.0 support the no PK table.
