### ISSUE TITLE
my flink cdc cannot link to mysql

### ISSUE THREAD

**Issue by 805094591** [ververica/flink-cdc-connectors#1585]
![截图 2022-09-27 18-10-01](https://user-images.githubusercontent.com/39234160/192499497-b19456da-ad10-418a-8278-5aecfe0bf82b.png)

ask for help. thank you.

**Comment by 805094591** [comment]
Flink SQL> select id from products_cdc;
[ERROR] Could not execute SQL statement. Reason:
java.net.ConnectException: 拒绝连接 (Connection refused)

**Comment by pbnoyz** [comment]
How can you connect to 0.0.0.0?

**Comment by echobigdata** [comment]
hostname这里改下呢

**Comment by ruanhang1993** [comment]
First of all, could you connect to mysql by `mysql -h 0.0.0.0 -P 3306 -uroot -p`?
