### ISSUE TITLE
[MySQL-cdc]set scan.startup.mode=initial and  the Parallelism >1  ,mysql-cdc can't work correctly

### ISSUE THREAD

**Issue by dutao1** [ververica/flink-cdc-connectors#1591]
**Describe the bug(Please use English)**
 When I use datastream  api  and set scan.startup.mode=initial  and  parallelism >1 ,for example: I set parallelism=4, 

please to see :https://ververica.github.io/flink-cdc-connectors/master/content/connectors/mysql-cdc.html#startup-reading-position

program can pull snapshot datas ,but can't pull any changed data .

But  when I set parallelism=1 the program can pull snapshot datas  and changed data correctly .

**Environment :**
 - Flink version :  1.14
 - Flink CDC version: 2.2.1
 - Database and version: MySQL, 

 code:

              MySqlSource<String> mySqlSource = MySqlSource.<String>builder()
              .hostname("127.0.0.1")
              .port(3306)
              .scanNewlyAddedTableEnabled(false) // enable scan the newly added tables feature
              .databaseList("test123") // set captured database
              .tableList("test123.citys2") // set captured tables [product, user, address]
              .username("root")
              .password("123456")
              .startupOptions( StartupOptions.initial())
              .deserializer(new JsonDebeziumDeserializationSchema()) // converts SourceRecord to JSON String
              .build();
      StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
      env.setParallelism(1);
      // enable checkpoint
      env
              .fromSource(mySqlSource, WatermarkStrategy.noWatermarks(), "MySQL Source")
              // set 4 parallel source tasks
              .setParallelism(4)
             .print().setParallelism(1); // use parallelism 1 for sink to keep message ordering

      env.execute("Print MySQL Snapshot + Binlog");

**Comment by ruanhang1993** [comment]
Hi, @dutao1 , I add the following test in the `MySqlConnectorITCase.java` at the branch release-2.2. But there is not any error.

```java
    @Test
    public void testParallelism() throws Exception {
        if (!incrementalSnapshot) {
            return;
        }
        customerDatabase.createAndInitialize();
        String dbName = customerDatabase.getDatabaseName();
        MySqlSource<String> mySqlSource = MySqlSource.<String>builder()
                .serverTimeZone("UTC")
                .hostname(MYSQL_CONTAINER.getHost())
                .port(MYSQL_CONTAINER.getDatabasePort())
                .scanNewlyAddedTableEnabled(false)
                .databaseList(dbName)
                .tableList(dbName + ".customers")
                .username(customerDatabase.getUsername())
                .password(customerDatabase.getPassword())
                .startupOptions(StartupOptions.initial())
                .deserializer(new JsonDebeziumDeserializationSchema())
                .build();
        env.setParallelism(1);
        env.fromSource(mySqlSource, WatermarkStrategy.noWatermarks(), "MySQL Source")
                .setParallelism(4)
                .print().setParallelism(1);
        JobClient res = env.executeAsync("Print MySQL Snapshot + Binlog");
        Thread.sleep(10000);
        // test binlog phase
        try (Connection connection = customerDatabase.getJdbcConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("UPDATE customers SET `name` = 'test';");
        }
        while (true) {
        }
    }
```

**Comment by young2633** [comment]
I met the same problem before, but it solved when i enbale checkpoint
