### ISSUE TITLE
flink cdc 支持同步表结构的变更吗，比如新增列，删除列

### ISSUE THREAD

**Issue by echobigdata** [ververica/flink-cdc-connectors#1594]
使用flinkcdc 从mysql同步数据到doris，如果数据源端表结构发生变化新增了一列，下游doris表如何同步更新呢

**Comment by JesseAtSZ** [comment]
支持，MySQL Source有个选项includeSchemaChanges，填写true可以同步DDL

**Comment by echobigdata** [comment]
> 支持，MySQL源码选项includeSchemaChanges，重新可以同步刷新DDL
非常感谢您的解答，我去按您说的这个方式搞搞

**Comment by hqbhoho** [comment]
> 支持，MySQL Source有个选项includeSchemaChanges，填写true可以同步DDL

support create/drop database/table?
