### ISSUE TITLE
Made a Flink demo tutorial

### ISSUE THREAD

**Issue by Amber1990Zhang** [ververica/flink-cdc-connectors#1601]
As title. I made a video Flink demo tutorial by using the Flink OceanBase CDC connector as an example. 
Reference doc: https://github.com/ververica/flink-cdc-connectors/blob/master/docs/content/connectors/oceanbase-cdc.md
https://github.com/ververica/flink-cdc-connectors/blob/master/docs/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/oceanbase-tutorial-zh.md
Video:
[Bilibili](https://www.bilibili.com/video/BV1Zg411a7ZB/?spm_id_from=333.999.0.0&vd_source=bae71264252ba53dea03d1d4d145cfcf)
[YouTube](https://www.youtube.com/watch?v=ODGE-73Dntg)

**Comment by leonardBang** [comment]
@Amber1990Zhang So cool！！ Would you like to open a PR to add the video links to the document?
