### ISSUE TITLE
运行一段时间读取binlog错误，binlog文件没有失效，是什么原因引起的呢？

### ISSUE THREAD

**Issue by zjwwf** [ververica/flink-cdc-connectors#1602]
运行一段时间后出现DebeziumException错误，具体报错日志如下
the connector is trying to read binlog starting at SourceInfo [currentGtid=null, currentBinlogFilename=mysql-bin-changelog.254939, currentBinlogPosition=8204468, currentRowNumer=0, serverId=0, sourceTime=null, threadId=-1, currentQuery=null, tableIds=[], databaseName=null], but this no longer avallable on the server. Reconfigure the connector to use a snapshot when needed

此 mysql-bin-changelog.254939 binlog文件存在，这个是什么原因引起的呢？设置 properties.setProperty("snapshot.mode", "when_needed"); 是否可以避免此错误？

**Comment by guixin** [comment]
hi, what's you cdc version using? Use latest version may fixed it. By the way, cdc don't support `when_needed` mode. this comment hope to help you.
