### ISSUE TITLE
flink cdc Oracle 在监听oracle日志期间,监听表添加了字段,下标越界

### ISSUE THREAD

**Issue by tanjcf** [ververica/flink-cdc-connectors#1607]
Environment :

Flink version : 1.14.5
Flink CDC version: 2.3-SNAPSHOT
Database and version: 12c

To Reproduce
flink cdc Oracle 在监听oracle日志期间,监听表添加了字段,下标越界
场景:表新增了字段,监听出来的日志,DML报异常下标越界
<img width="905" alt="454A5AFD-091D-4576-B60D-21BF6DC75404" src="https://user-images.githubusercontent.com/70000350/194759714-6cfcac51-d63b-4f14-b0dd-a16860eff0df.png">

**Comment by tanjcf** [comment]
新增加一个字段
<img width="501" alt="1665324299315_C4D67DD0-DE4C-4f7a-A151-2559BB968B47" src="https://user-images.githubusercontent.com/70000350/194813697-7ce4b890-ff87-47e2-9f49-5f1644b36722.png">
<img width="188" alt="1665324381358_3A77CFFA-E4F4-4fb5-860C-60CC7EF47680" src="https://user-images.githubusercontent.com/70000350/194813716-9c61c076-2c5d-4c49-8c01-a17fcace4c82.png">
然后在插入一条数据 id 为40的这条
<img width="459" alt="1665324405334_F1949A7F-5BD7-4418-AF77-17FBFB0DFFE4" src="https://user-images.githubusercontent.com/70000350/194813821-651b6cea-eb72-4684-a943-1e038d39761e.png">

然后就会出现DML下标越界
<img width="884" alt="1665324679516_E81A640F-4F22-4ebc-9C38-AF1CE3B35AAC" src="https://user-images.githubusercontent.com/70000350/194813874-7b8f5ff9-69b5-4bfb-81b0-22d63e2ffa16.png">

**Comment by ruanhang1993** [comment]
Thanks for your report, @tanjcf. I am interested in this bug. And I will take a look at this later.

**Comment by ruanhang1993** [comment]
@tanjcf Adding `'debezium.internal.log.mining.dml.parser'='legacy'` table option to your table may be helpful. This seems to be a bug in 1.6.4.Final debezium oracle connector.
