### ISSUE TITLE
Support datetime type format

### ISSUE THREAD

**Issue by lanse-li** [ververica/flink-cdc-connectors#1613]
cdc for mysql JsonDebeziumDeserializationSchema datetime type format result "2022-10-13T09:35:40Z", Expected to support custom formatting；

Expected：
MySqlSource.builder().date_format("yyyy-MM-dd HH:mm:ss.SSS")

**Comment by ruanhang1993** [comment]
This option is not from the cdc connector. It is the format option from the json format.

Maybe [json.timestamp-format.standard](https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/connectors/table/formats/json/) is what you need.
