### ISSUE TITLE
flink cdc是否可以以配置的方式来实现在全量读取时，不阻塞chk来实现at least once，结合hudi的upsert语义，最终实现exactly once.

### ISSUE THREAD

**Issue by mincwang** [ververica/flink-cdc-connectors#163]
问题：
在使用flink cdc写入hudi时，由于hudi的flush to storage需要在chk触发，因此在大表全量同步期间，没有chk的所有的数据积攒在内存中导致Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded.

期望：
flink cdc是否可以以配置的方式来实现在全量读取时，不阻塞chk来实现at least once，结合hudi的upsert语义，最终实现exactly once.

**Comment by leonardBang** [comment]
supported in flink cdc 2.0
