### ISSUE TITLE
你好，请问 flinkcdc 最新版本 是否支持 postgresql 14?

### ISSUE THREAD

**Issue by wolihaito** [ververica/flink-cdc-connectors#1642]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by GOODBOY008** [comment]
@wolihaito Currently, don't support pg 14.

**Comment by wolihaito** [comment]
好的，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 中午1:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ververica/flink-cdc-connectors] 你好，请问 flinkcdc 最新版本 是否支持 postgresql 14? (Issue #1642)





 
@wolihaito Currently, don't support pg 14.

**Comment by pipinet** [comment]
Looking forward to supporting pg 14

**Comment by ruanhang1993** [comment]
2.4.0 update the debezium to 1.9.7.Final.
