### ISSUE TITLE
[feature] flink-cdc-connector support elasticsearch 8.x

### ISSUE THREAD

**Issue by CaoYunzhou** [ververica/flink-cdc-connectors#1689]
**Is your feature request related to a problem? Please describe.**
when elasticsearch 8.x support for flink-cdc-connector

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by Jiabao-Sun** [comment]
Hi @CaoYunzhou.
Does elasticsearch 8.x provides some way of change capture?
If not, we can hardly get the change operations of elasticsearch.
