### ISSUE TITLE
FlinkCDC-kafka-Es 同步警告

### ISSUE THREAD

**Issue by 812406210** [ververica/flink-cdc-connectors#170]
![image](https://user-images.githubusercontent.com/22192011/115979186-1a134200-a5b7-11eb-8661-59a1e4ea9ad5.png)
你好，请问下为啥会有这个警告，会影响整个job吗？
版本信息：
               flink版本为：1.11.3
               flinkcdc格式是：changelog-json
               读取kakfa数据格式为: changelog-json
               写入es格式为：json
具体如下图:
![image](https://user-images.githubusercontent.com/22192011/115979294-a291e280-a5b7-11eb-9ed3-c7472ae20d2d.png)

![image](https://user-images.githubusercontent.com/22192011/115979298-ae7da480-a5b7-11eb-948b-44bb423609b2.png)

![image](https://user-images.githubusercontent.com/22192011/115979304-bb9a9380-a5b7-11eb-9144-30971328a68e.png)

**Comment by wuchong** [comment]
没关系，不用关心。
