### ISSUE TITLE
Bump Debezium version to 1.7.0 or above to support Oracle schema changes.

### ISSUE THREAD

**Issue by EngonVHKxZ** [ververica/flink-cdc-connectors#1730]

**Comment by sap1ens** [comment]
I'd highly recommend bumping to 1.9.4+ if you can, it contains quite a few important bug fixes.

**Comment by EngonVHKxZ** [comment]
> I'd highly recommend bumping to 1.9.4+ if you can, it contains quite a few important bug fixes.

There are many differences between 1.6.4 and 1.9.4. Updating too fast will increase a lot of development time
