### ISSUE TITLE
Replace the 2.3 JAR flinkcdc mysql table, restart the FlinkCDC task and report an error

### ISSUE THREAD

**Issue by wangyayuan18** [ververica/flink-cdc-connectors#1733]
1.描述问题：
之前的flink-sql-connector-mysql-cdc是自己编译的为了兼容Flink1.15.2版本，源码包只修改了Flink版本号，打包然后启动Flinkcdc-mysql任务，今天换了官方新发布的flink-sql-connector-mysql-cdc-2.3.0包，重启flinkcdc任务(savepoint)报错

![1668154494223_1668154306935_276044D6-8DA4-47ad-86E7-BA3F19BB764C](https://user-images.githubusercontent.com/64136230/201318235-bf5458ed-547a-4fa4-9c7d-d021f8b1ae9d.png)

2.flinkcdc任务代码(flinkcdc-kafka)

set  jobmanager.memory.process.size= 2048m;
set  taskmanager.memory.process.size= 6144m;

-- set taskmanager.memory.task.offheap=2048m;
-- set taskmanager.memory.framework.offheap=2048m;
SET taskmanager.memory.managed.size = 256m;
set execution.checkpointing.interval = 120s;
set execution.checkpointing.timeout= 120000;
-- set execution.savepoint.ignore-unclaimed-state = true;

set taskmanager.numberOfTaskSlots=2;
set table.exec.resource.default-parallelism = 2;
set table.exec.iceberg.infer-source-parallelism=true;
set table.exec.iceberg.infer-source-parallelism.max=1;
set table.exec.sink.not-null-enforcer=DROP;
set table.dynamic-table-options.enabled= true;

USE CATALOG default_catalog;

use default_database;

/*活动奖品MYSQLCDC*/
CREATE TABLE ods_tb_activity_award_mysql_cdc(
AWARD_ID varchar NOT NULL COMMENT '主键',
ACTIVITY_ID varchar NOT NULL COMMENT '活动主键',
PRIZE_ID varchar NOT NULL COMMENT '奖品ID',
PRIZE_DESC varchar COMMENT '',
PRIZE_ALIAS varchar COMMENT '',
PRIZE_BANNER_URL varchar COMMENT '',
PRIZE_DESC_URL varchar COMMENT '',
STOCK_NUM int COMMENT '库存',
PRICE decimal(16,4) COMMENT '奖品价格',
AWARD_NAME varchar COMMENT '奖项名称',
IMG_URL varchar COMMENT '奖项图标',
CATEGORY_TYPE int COMMENT '奖品类型',
GOODS_SCENE int COMMENT '优惠券使用场景',
GOODS_URL varchar COMMENT '优惠券兑换URL',
RECHARGE_TYPE varchar COMMENT '奖品对应的类目',
ORDER_NUM int COMMENT '奖品下单数量',
PAY_FLAG varchar COMMENT '奖品网关支付标识，0:不需要；1:需要网关支付',
THIRD_INFO varchar COMMENT '第三方充值信息',
AWARD_TYPE int COMMENT '奖品类型 0:子包 1:主包',
PARENT_AWARD_ID varchar COMMENT '',
status int COMMENT '商品状态',
AWARD_ORDER int COMMENT '奖品顺序编号',
TOTAL_STOCK_NUM int COMMENT '奖品总库存',
PRIMARY KEY (AWARD_ID) NOT ENFORCED
) WITH (
    'connector' = 'mysql-cdc',/*连接类型*/
    'hostname' = '172.xx.xx.xx',/*地址*/
    'port' = '3307',/*端口*/
    'username' = 'cdcuser',/*用户*/
    'password' = '123456',/*密码*/
    'database-name' = 'market_db',/*库名*/
    'table-name' = 'tb_activity_award',/*表名*/
    'connect.timeout' = '60s', /*连接超时时间*/
    'debezium.skipped.operations'='d', /*跳过binglog删除操作*/
    'server-id'='5301-5310',/*服务器 id*/
	'server-time-zone' = 'Asia/Shanghai', /*时区调整*/
    'scan.startup.mode'='initial',/*initial全量，latest-offset最新binglog读取及更新*/
    'scan.incremental.snapshot.enabled'='true',/*增量快照*/
    'scan.incremental.snapshot.chunk.size'='8096',
    'scan.snapshot.fetch.size'='1024',
    'jdbc.properties.useSSL' = 'false'
);

/*活动奖品KAFKA_SOURCE*/
CREATE TABLE ods_tb_activity_award_kafka_source(
award_id varchar not null comment '主键',
activity_id varchar not null comment '活动主键',
prize_id varchar not null comment '奖品id',
prize_desc varchar comment '',
prize_alias varchar comment '',
prize_banner_url varchar comment '',
prize_desc_url varchar comment '',
stock_num int comment '库存',
price decimal(16,4) comment '奖品价格',
award_name varchar comment '奖项名称',
img_url varchar comment '奖项图标',
category_type int comment '奖品类型',
goods_scene int comment '优惠券使用场景',
goods_url varchar comment '优惠券兑换url',
recharge_type varchar comment '奖品对应的类目',
order_num int comment '奖品下单数量',
pay_flag varchar comment '奖品网关支付标识，0:不需要；1:需要网关支付',
third_info varchar comment '第三方充值信息',
award_type int comment '奖品类型 0:子包 1:主包',
parent_award_id varchar comment '',
status int comment '商品状态',
award_order int comment '奖品顺序编号',
total_stock_num int comment '奖品总库存',
PRIMARY KEY (award_id) NOT ENFORCED
) WITH (
      'connector' = 'kafka' /*kafka连接类型*/
    , 'topic' = 'ofpmdb.ods.tb_activity_award_cdc_iceberg'/*topic名称*/
    , 'scan.startup.mode' = 'earliest-offset'/*消费策略*/
    , 'properties.bootstrap.servers' = '172.xx.xx.xx:9092,172.xx.xx.xx:9092,172.xx.xx.xx:9092'/*连接地址*/
    , 'value.format' = 'debezium-json'/*数据json格式解析*/
    , 'sink.parallelism'='1'/*并行度设置*/
);

insert into default_catalog.default_database.ods_tb_activity_award_kafka_source 
select
AWARD_ID, 
ACTIVITY_ID,
PRIZE_ID,
PRIZE_DESC,
PRIZE_ALIAS,
PRIZE_BANNER_URL,
PRIZE_DESC_URL,
STOCK_NUM,
PRICE,
AWARD_NAME,
IMG_URL,
CATEGORY_TYPE,
GOODS_SCENE,
GOODS_URL,
RECHARGE_TYPE,
ORDER_NUM,
PAY_FLAG,
THIRD_INFO,
AWARD_TYPE,
PARENT_AWARD_ID,
status,
AWARD_ORDER,
TOTAL_STOCK_NUM
from default_catalog.default_database.ods_tb_activity_award_mysql_cdc;

**Comment by leonardBang** [comment]
@PatrickRen Could you take a look this ticket?

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! 

为了方便各个国家的贡献者交流，请在 [Apache Jira](https://issues.apache.org/jira)  的 `Flink` 项目下重新用英文创建问题，同时在问题上将 Component 标注为 `Flink CDC`。谢谢！
