### ISSUE TITLE
[core] Format print connector config to log.

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#1742]
**Is your feature request related to a problem? Please describe.**
We need to print connector config to log just like debezium does (formatted and sensetive info hidden).

**Comment by TyrantLucifer** [comment]
I want to try it. Could you please assign it to me?

**Comment by GOODBOY008** [comment]
@TyrantLucifer OK, assigned. :)

**Comment by ruanhang1993** [comment]
Hi, @TyrantLucifer. Is there any progress about this issue ?

**Comment by TyrantLucifer** [comment]
I will submit code in these two days，I'm sorry for delay delivery.

**Comment by ruanhang1993** [comment]
@TyrantLucifer Thanks for your reply. If you need helps, please be free to @ me.
