### ISSUE TITLE
FlinkCDC_2.3.0 TableAPI didn't check "scan.startup.mode" when the mode is "timestamp"

### ISSUE THREAD

**Issue by Ocean22** [ververica/flink-cdc-connectors#1743]
**Describe the bug(Please use English)**
使用cdc的tableAPI创建表，并指定从指定时间戳读取，只指定参数‘scan.startup.timestamp-millis’而不指定参数‘scan.startup.mode’，运行可以通过，并且使用的是默认的‘initial’模式。
（Use the cdc table API to create a table and specify to read from the specified timestamp. Only specify the parameter 'scan. startup. timestamp millis' and not the parameter 'scan. startup. mode'. It can be run and the default 'initial' mode is used.）

**Environment :**
 - Flink version :  1.16.0
 - Flink CDC version: 2.3.0
 - Database and version: mysql 8

**To Reproduce**
1、使用mysql-cdc创建一个表（create a table use mysql-cdc）
![image](https://user-images.githubusercontent.com/45907917/201863686-1f22946f-43eb-49ce-9f57-3fc1e46d683f.png)

2、查询表（select the table）
一般来说，上述两个参数应该配合使用，如果缺乏其中一个，运行时都应该报错误，但是运行通过了。
（Generally speaking, the above two parameters should be used together. If one of them is missing, the runtime should get an error, but the operation passes.）
![image](https://user-images.githubusercontent.com/45907917/201870449-d65a95a3-e170-4e5f-9528-39ec5d333cdf.png)

**Additional Description**

**Comment by rookiegao** [comment]
@leonardBang Please assign it to me

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! 

为了方便各个国家的贡献者交流，请在 [Apache Jira](https://issues.apache.org/jira)  的 `Flink` 项目下重新用英文创建问题，同时在问题上将 Component 标注为 `Flink CDC`。谢谢！
