### ISSUE TITLE
flinkcdc 能否只采集全量数据

### ISSUE THREAD

**Issue by 245831311** [ververica/flink-cdc-connectors#1745]
flinkcdc 目前能否像sqoop框架一样支持只全量采集，不增量同步的功能

**Comment by JasonFang1993** [comment]
目前好像没有这个功能

**Comment by lufzhangzitao** [comment]
你可以试下设置debezium的参数 snapshot.mode = initial_only
[https://debezium.io/documentation/reference/2.0/connectors/mysql.html#mysql-property-snapshot-mode](url)

**Comment by ruanhang1993** [comment]
There is already an issue #1687 about this feature. So we could trace and discuss in that issue. Thanks for reporting ~

**Comment by Roger0917** [comment]
> 你可以试下设置debezium的参数 snapshot.mode = initial_only [https://debezium.io/documentation/reference/2.0/connectors/mysql.html#mysql-property-snapshot-mode](url)

不起作用
