### ISSUE TITLE
Document In Mysql cdc and mongodb

### ISSUE THREAD

**Issue by xixingya** [ververica/flink-cdc-connectors#1750]
**Describe the bug(Please use English)**
mysql cdc description:
![image](https://user-images.githubusercontent.com/37765666/202147688-b37665ff-8aef-4561-a33d-eefb9fe52e4c.png)
and code:
![image](https://user-images.githubusercontent.com/37765666/202148128-26bc0a40-131d-47d2-af1d-d73e3929cefe.png)
mongodb doc:
![image](https://user-images.githubusercontent.com/37765666/202148242-07a1276d-9b24-4ce6-9980-51e95fee279c.png)

**Comment by Jiabao-Sun** [comment]
Closed by #1751.
