### ISSUE TITLE
Connection is not closed when used with oracle.

### ISSUE THREAD

**Issue by phalix** [ververica/flink-cdc-connectors#1752]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.16.0
 - Flink CDC version: 2.3
 - Database and version: Oracle 19g 

**To Reproduce**
1. The test data : I connect flink over flink-cdc with oracle. The number of connections is more or less 180 for 760.000 records of data.
2. The test code : select count(1) from gv$session where machine =
3. The error : regardless if the job is idle or cancelled those connections are not closed at any point of time, nor can i find any config option to reduce the number

**Comment by Soulmate76** [comment]
How did you solve it？

**Comment by phalix** [comment]
I deactivated scan.incremental.snapshot.enabled , at least for my version of oracle this caused open connections from the initial load.

**Comment by rolan018** [comment]
Did you have a problem with the fact that after completing the task, the session to the database did not end ?

**Comment by phalix** [comment]
Yes, and based on the chunk size, a huge amount of connections were left open.

**Comment by rolan018** [comment]
When deactivating this parameter 'scan.incremental.snapshot.enabled'='false', the session does not close when the job is completed ? (AFAIK, Flink does not control the closing of the session to the database)
