### ISSUE TITLE
[oracle-cdc]flink1.13.6withflinkcdc2.3.0 Version compatibility issues

### ISSUE THREAD

**Issue by wdzhanghao** [ververica/flink-cdc-connectors#1754]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version : flink1.13.6 
 - Flink CDC version: 2.3.0
 - Database and version: oracle 11g

**To Reproduce**
1. The test data 👍 
2. The test code :
my maven Configuration
 <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <flink.version>1.13.6</flink.version>
        <scala.version>2.11</scala.version>
    </properties>
    <dependencies>
        
        <dependency>
            <groupId>com.ververica</groupId>
            <artifactId>flink-connector-oracle-cdc</artifactId>
            <version>2.3.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.flink</groupId>
                    <artifactId>flink-shaded-guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-jdbc_2.11</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.73</version>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-streaming-java_2.11</artifactId>
            <version>${flink.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-api-java-bridge_2.11</artifactId>
            <version>${flink.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-clients_2.11</artifactId>
            <version>${flink.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-jdbc_2.11</artifactId>
            <version>${flink.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-shaded-guava</artifactId>
            <version>18.0-13.0</version>
        </dependency>
    </dependencies>
code:
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
//        env.enableCheckpointing(10*60*1000L);
//        env.getCheckpointConfig().setCheckpointingMode(CheckpointingMode.EXACTLY_ONCE);   env.getCheckpointConfig().enableExternalizedCheckpoints(CheckpointConfig.ExternalizedCheckpointCleanup.RETAIN_ON_CANCELLATION);
//        env.setRestartStrategy(RestartStrategies.fixedDelayRestart(10,20000L));
//        env.getCheckpointConfig().setCheckpointTimeout(60*1000L);
//        env.getCheckpointConfig().setTolerableCheckpointFailureNumber(200);
//        env.getCheckpointConfig().setMaxConcurrentCheckpoints(1);

        Properties cdcProps = new Properties();
        cdcProps.setProperty("database.tablename.case.insensitive","false");
        cdcProps.setProperty("log.mining.strategy","online_catalog");
        cdcProps.setProperty("log.mining.continuous.mine","true");
        cdcProps.setProperty("scan.startup.mode","latest-offset");
        DebeziumSourceFunction<String> sourceFunction = OracleSource.<String>builder()
                .url("jdbc:oracle:thin:@****:1521:****")
                .port(1521)
                .database("****") 
                .schemaList("****") 
                .tableList("****")
                .username("****")
                .password("****")
                .debeziumProperties(cdcProps)
                .startupOptions(StartupOptions.latest())
                .deserializer(new CustomerDeserializationSchema())
                .build();

        DataStreamSource<String> Result = env.addSource(sourceFunction);
        Result.print().setParallelism(1);
        env.execute();
5. The error :
Caused by: java.lang.ClassNotFoundException: org.apache.flink.shaded.guava30.com.google.common.util.concurrent.ThreadFactoryBuilder
**Additional Description**
I saw from the official website can support 1.13.6 version of flink and 2.3 version of cdc for testing, found that there is no data, when I changed the version to 1.14 found that it can run and data also appeared, if support 1.13.6 please tell me the answer, if not to consider upgrading the generation environment flink version, this is not a for me good choice

**Comment by rookiegao** [comment]
Please refer to any of the following poms

https://github.com/ververica/flink-cdc-connectors/blob/master/flink-cdc-e2e-tests/pom.xml

https://github.com/DataLinkDC/dlink/blob/dev/dlink-flink/dlink-flink-1.13/pom.xml

In fact, the community tests have been running in the environment of Flink 1.13 - Flink 1.16

![image](https://user-images.githubusercontent.com/34996528/202596098-a63243c0-29bc-4000-a7e4-c6685cf291f8.png)

**Comment by rookiegao** [comment]
You can replace mysql with oracle

**Comment by wdzhanghao** [comment]
> You can replace mysql with oracle

ok,I'll try it.If it works, I will get back to you
