### ISSUE TITLE
[mysql-cdc、DataStreamApi] FlinkCDC_2.3.0 Use 'scan.startup.mode' = 'timestamp' will get errors when restart job from checkpoint/savepoint

### ISSUE THREAD

**Issue by Ocean22** [ververica/flink-cdc-connectors#1756]
**Describe the bug(Please use English)**
我在测试使用“从指定时间戳启动模式 + 动态加表功能“时，发现了问题。
1、首先同步a表，指定从1001这个时间戳启动
2、运行一段时间后，a表同步了5条数据，将任务停止到保存点
3、加入b表，将任务从保存点重新启动
4、任务没能启动成功
5、一开始是以为这个模式不支持动态添加表，于是去掉b表，将任务从保存点启动，依然报同样的错误
6、以下为启动命令与报错信息
【
I found a problem when testing the use of "starting mode from specified timestamp+dynamic adding table function".
1. First, synchronize table 'A', and specify to start from the timestamp 1001
2. After running for a period of time, table 'A' synchronizes 5 pieces of data , stops the job to the savepoint
3. Add table 'B' and restart the job from the save point
4. Job failed to start
5. At first, I thought that this mode did not support add tables dynamically, so I removed table 'B', started the job from the savepoint, but still get the same error
6. The following are job startup commands and error messages
】
![lQLPJxbcyGYFFrhHzQZvsDFFF-rGw-RFA2rL_zUAmwA_1647_71](https://user-images.githubusercontent.com/45907917/202378310-6d85265b-85f0-4245-8a58-5267eaba442d.png)
![image](https://user-images.githubusercontent.com/45907917/202378212-711412d3-f266-4af6-8857-0495b6133d05.png)

7、期望的结果：
     a表从保存点记录的位移点继续往后同步，动态新增的b表从时间戳1001开始同步
【
7. Expected results:
    Table ‘A’ continues to synchronize backward from the displacement point recorded at the savepoint, and dynamically added table 'B' starts to synchronize from the timestamp 1001
】

**Environment :**
 - Flink version :  1.16.0
 - Flink CDC version: 2.3.0
 - Database and version:

**Comment by dusukang** [comment]
@Ocean22 Hi, could you provide more detailed code and steps? cc @leonardBang for a look.

**Comment by Ocean22** [comment]
> @Ocean22 Hi, could you provide more detailed code and steps? cc @leonardBang for a look.

Yes,of cource.
![image](https://user-images.githubusercontent.com/45907917/202643491-e240b548-617a-4178-bcaa-558f3ef61b44.png)
![image](https://user-images.githubusercontent.com/45907917/202643526-8da578c1-7f7f-4d4e-95aa-562d9ee703ae.png)

Steps are the following
1、Read mysql binlog data
2、Print data

**Comment by feiyuyitiao** [comment]
补充：异常起始位置：
![image](https://user-images.githubusercontent.com/5387559/203683061-ae5fe42b-5eb5-4cb6-8caa-9ac56e490653.png)

**Comment by feiyuyitiao** [comment]
问题很容易复现，起始不用追加或变更表
1. 启动服务，trigger savepoint
2. 关闭服务，配置从trigger savepoint恢复服务，并且更改函数中的参数timestamp： .startupOptions(StartupOptions.timestamp(timestamp))
3. 再次启动服务，剖出上边异常。

**Comment by ruanhang1993** [comment]
2.4.0 fixed this .

**Comment by Yoona-wzw** [comment]
2.4.2还是有同样的问题
