### ISSUE TITLE
Checkpoint error when load mysql increase data

### ISSUE THREAD

**Issue by MadBeeDo** [ververica/flink-cdc-connectors#1760]
Checkpoint error when load aliyun rds mysql 5.7 inrease data.Use streaming code not sql,like this:

`      val source = MySqlSource.builder()
        .hostname(mysql_config.url)
        .port(mysql_config.port)
        .databaseList(databases.toList: _*)
        .tableList(tablenames: _*)
        .username(mysql_config.username)
        .password(mysql_config.password)
        .debeziumProperties(prop)
        .deserializer(new JsonDebeziumDeserializationSchema())
        .startupOptions(StartupOptions.latest())
        .build()
stream = env.fromSource(source, WatermarkStrategy.noWatermarks(), mysql_config.name)
`
Error info on webUI like this:
![lQLPJxbiPnGvf7fNA2_NBdewlFwEWwo-lqkDc76NUgBAAA_1495_879 png_620x10000q90](https://user-images.githubusercontent.com/43366155/202613206-324c5ce7-f85b-4650-b33d-c2b1a4761f17.jpg)
single parallelism report this,too.
How to fix this?
thanks
 

 - Flink version :  1.16.0
 - Flink CDC version: 2.3.0
 - Database and version:  aliyun rds mysql 5.7

**Comment by ruanhang1993** [comment]
Please provide more error logs about it.

If the problem still exists, please re-create your issue in English on Apache Jira under project Flink with component tag Flink CDC. Thank you!
