### ISSUE TITLE
mysql无法开启gtid的情况下，如何实现flink CDC mysql-ha

### ISSUE THREAD

**Issue by yeezychao** [ververica/flink-cdc-connectors#1764]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by yeezychao** [comment]
@ruanhang1993

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
