### ISSUE TITLE
由flinkcdc 2.2.1 升级到2.3.0版本，无法读取到任何数据

### ISSUE THREAD

**Issue by zhu-sy** [ververica/flink-cdc-connectors#1766]
flink version: 1.13.5
mysql : 8.x
flinkcdc version: 2.3.0

<img width="768" alt="image" src="https://user-images.githubusercontent.com/56377085/203213906-392cf1b5-4e94-4fe4-b860-8dc3df40810a.png">

**Comment by zhu-sy** [comment]
> flink 版本：1.13.5 mysql：8.x flinkcdc 版本：2.3.0
> 
> <img alt="图片" width="768" src="https://user-images.githubusercontent.com/56377085/203213906-392cf1b5-4e94-4fe4-b860-8dc3df40810a.png">


问题定位到了， jar包冲突导致的。我在maven中引入了一个mysql的jar包，导致任务异常，去掉就可以了

**Comment by bravelll** [comment]
能把你的pom.xml给我一下吗，我的程序就是跟你
反应一样
