### ISSUE TITLE
flink cdc docker运行有问题

### ISSUE THREAD

**Issue by hust419** [ververica/flink-cdc-connectors#1767]
https://ververica.github.io/flink-cdc-connectors/master/content/quickstart/mysql-postgres-tutorial.html 
按照这个quck start 安装完docker，虽然能起来，但是kibana连不上elasticsearch，一直报找不到

环境是mac pro的M1的笔记本

**Comment by LuyuZhang00** [comment]
同kibana连不上elasticsearch，一直报找不到

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
