### ISSUE TITLE
编写FlinkCDC怎么才能支持MySQL的  sha256_password呢

### ISSUE THREAD

**Issue by liushuaihang** [ververica/flink-cdc-connectors#1772]
FlinkCDC监听binlog无法通过sha256_password身份认证

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
