### ISSUE TITLE
[oracle-cdc]com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.DataException: file is not a valid field name

### ISSUE THREAD

**Issue by sin2015** [ververica/flink-cdc-connectors#1776]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.15.1
 - Flink CDC version: 2.3.0
 - Database and version: Oracle 19c 19,3,0,0

**To Reproduce**
1. Start sql-client.sh
2. CREATE TABLE source_users (
> USERID decimal(38,0) NOT NULL,
> NAME string,
> PRIMARY KEY (USERID) NOT ENFORCED
> ) WITH (
> 'connector' = 'oracle-cdc',
> 'hostname' = 'x.x.x.x',
> 'port' = '1521',
> 'database-name' = '****',
> 'schema-name' = '****',
> 'table-name' = 'users',
> 'username' = 'flinkuser',
> 'password' = '****',
> 'scan.startup.mode' = 'initial'
> );
3. > select * from srouce_users; #Everything is OK.
4. Login SOURCE DATABASE, try to UPDATE one row or INSERT new one, moment later, SQL-CLIENT displays: 
![image](https://user-images.githubusercontent.com/10595652/203998007-b6baebc7-7456-4a58-b9a4-f8fb5e71685f.png)
[ERROR] Could not execute SQL statement. Reason:
com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.DataException: file is not a valid field name
By the way, TABLE users contains only 2 columns too, USERID and NAME.

**Additional Description**

**Comment by sin2015** [comment]
在相同环境下，目前该问题已解决。方法：将database-name, schema-name, table-name值全部大写。供大家参考。

**Comment by sin2015** [comment]
在相同环境下，目前该问题已解决。方法：将database-name, schema-name, table-name值全部大写。供大家参考。

**Comment by ighack** [comment]
@sin2015 

Flink version : 1.17.1
ojdbc8-19.3.0.0.jar
flink-sql-connector-oracle-cdc-2.4.0.jar

我参照你说的方法把database-name, schema-name, table-name全部改在大写
`java.lang.NoSuchMethodError: io.debezium.connector.oracle.logminer.LogMinerChangeRecordEmitter.addStaticHeader(Ljava/lang/String;Lcom/ververica/cdc/connectors/shaded/org/apache/kafka/connect/data/SchemaAndValue;)V`
报这个错

**Comment by byd-android-2017** [comment]
Flink version : 1.17.1
flink-sql-connector-oracle-cdc-2.4.1.jar

把database-name, schema-name, table-name全部改在大写,异常消失，新增或修改记录，不会出现异常了。

CREATE TABLE IF NOT EXISTS 客户_SRC (
  客户_ID INT,
  客户_NAME STRING,
  EMAIL STRING,
  PHONE STRING,
  PRIMARY KEY (客户_ID) NOT ENFORCED
) with (
  'connector' = 'oracle-cdc',
  'hostname' = 'XXXX',
  'port' = '1521',
  'username' = 'XXX',
  'password' = 'XXXX',
  -- 'database-name' = 'nhddb6',
  **'database-name' = 'NHDDB6',
  'schema-name' = 'NEWMIS',**
  'table-name' = '客户',
  'url' = 'jdbc:oracle:thin:@10.1.8.145:1521/nhddb6?oracle.jdbc.timezoneAsRegion=false&oracle.jdbc.timezoneUpdate=true&oracle.jdbc.timezone=Asia/Shanghai',
  'scan.startup.mode' = 'initial',
  'debezium.decimal.handling.mode' = 'STRING',
  -- 'debezium.database.tablename.case.insensitive' = 'false',
  'debezium.log.mining.strategy'='online_catalog',
  'debezium.log.mining.continuous.mine'='true'
);

**Comment by LenMotion** [comment]
> Flink version : 1.17.1 flink-sql-connector-oracle-cdc-2.4.1.jar
> 
> 把database-name, schema-name, table-name全部改在大写,异常消失，新增或修改记录，不会出现异常了。
> 
> CREATE TABLE IF NOT EXISTS 客户_SRC ( 客户_ID INT, 客户_NAME STRING, EMAIL STRING, PHONE STRING, PRIMARY KEY (客户_ID) NOT ENFORCED ) with ( 'connector' = 'oracle-cdc', 'hostname' = 'XXXX', 'port' = '1521', 'username' = 'XXX', 'password' = 'XXXX', -- 'database-name' = 'nhddb6', **'database-name' = 'NHDDB6', 'schema-name' = 'NEWMIS',** 'table-name' = '客户', 'url' = 'jdbc:oracle:thin:@10.1.8.145:1521/nhddb6?oracle.jdbc.timezoneAsRegion=false&oracle.jdbc.timezoneUpdate=true&oracle.jdbc.timezone=Asia/Shanghai', 'scan.startup.mode' = 'initial', 'debezium.decimal.handling.mode' = 'STRING', -- 'debezium.database.tablename.case.insensitive' = 'false', 'debezium.log.mining.strategy'='online_catalog', 'debezium.log.mining.continuous.mine'='true' );

我的都是大写的，也遇到了这个问题

**Comment by HK-hub** [comment]
我的database name, schema name, table name 都是大写了但是还是存在这个问题
