### ISSUE TITLE
不同过数据库类型转为flink datatype，没有复用

### ISSUE THREAD

**Issue by melin** [ververica/flink-cdc-connectors#1778]
是否可以参考spark jdbc，有一个统一封装，数据库特殊类型特殊处理，：
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/1145830/204090615-7b5912da-0e20-4fd1-8d21-07871a216412.png">
 
oracle 只需要处理下面几个数据类型，对比flink cdc oracle 处理NUMERIC 是有问题的， @leonardBang 
<img width="953" alt="image" src="https://user-images.githubusercontent.com/1145830/204090648-7fa2469a-6bd3-4de2-8119-38ca94c33be1.png">

<img width="994" alt="image" src="https://user-images.githubusercontent.com/1145830/204090876-cef6cdd6-7209-48ba-923d-f417e96028cb.png">

**Comment by GOODBOY008** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
