### ISSUE TITLE
[Oracle] Failed to set setXIncludeAware(true) for parser oracle.xml.jaxp.JXDocumentBuilderFactory

### ISSUE THREAD

**Issue by KyleZhang0536** [ververica/flink-cdc-connectors#1779]
**Describe the bug(Please use English)**
I update cdc version from 2.2.1 to 2.3.0, an error occur after starting job.
Maybe, it is an conflict bewteen com.oracle.database.xml and flink-shaded-hadoop-2-uber-1.15.2-stream3 dependency.

**Environment :**
 - Flink version :  1.15.2
 - Flink CDC version: 2.3.0
 - Database and version: Oracle 12c
 - Use ververica platform to deployment 
 - hdfs as statebackend

**To Reproduce**
1. The test data :
2. The test code :
3. The error :

**Additional Description**
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/6970622/204194789-9b144886-e3ae-48b1-9515-55dffa8c1b87.png">

**Comment by li57598** [comment]
I have the same problem

**Comment by GOODBOY008** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!

**Comment by GOODBOY008** [comment]
@KyleZhang0536 @li57598 https://ververica.github.io/flink-cdc-connectors/master/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/datastream-api-package-guidance-zh.html Maybe help you to solve this issue.
