### ISSUE TITLE
[MysqlCDC] 关联查询如何设置 Server id SQL Hints

### ISSUE THREAD

**Issue by zhuangwk** [ververica/flink-cdc-connectors#1786]
场景：mysqlCDC同步数据到TiDB，有A、B、C多张mysql表，关联查询后同步数据到TiDB数据表X,
sql形式:  insert into x select * from A left join B left join C
请问这种情况下如何设置Server id SQL Hints？

**Comment by ruanhang1993** [comment]
Maybe like this:
```sql
insert into x 
select * from A  /*+ OPTIONS(...)*/
left join B /*+ OPTIONS(...)*/
left join C  /*+ OPTIONS(...)*/
```

**Comment by zhuangwk** [comment]
> Maybe like this:
> 
> ```sql
> insert into x 
> select * from A  /*+ OPTIONS(...)*/
> left join B /*+ OPTIONS(...)*/
> left join C  /*+ OPTIONS(...)*/
> ```

这样是ABC每个表都作为单独的slave吗

**Comment by ruanhang1993** [comment]
Yes, we should use the different server id for these tables.
