### ISSUE TITLE
CDC scan.startup.mode设置为timestamp读不到数据

### ISSUE THREAD

**Issue by lykpass** [ververica/flink-cdc-connectors#179]
![image](https://user-images.githubusercontent.com/48595535/117809101-4fdf4880-b290-11eb-9f86-c9d67fb74bff.png)

![image](https://user-images.githubusercontent.com/48595535/117808981-2a523f00-b290-11eb-9ede-a71fc2a20c9a.png)

**Comment by lykpass** [comment]
使用本地的mysql  scan.startup.mode  三个参数都行 本地的mysql版本为8.0.15，用服务器上的mysql      版本 为 5.6 or5.7，设置 scan.startup.mode  为timestamp不行，但是latest-offset可以

**Comment by lykpass** [comment]
服务器上的为aliyun rds mysql 5.6，5.7 。我在钉钉交流群里看到有人在开发环境用8.x也会出现这个问题，换了一个拥有所有权限的账号也不行，是不是配置的问题

**Comment by Narutor** [comment]
同遇到这个问题

**Comment by lykpass** [comment]
![image](https://user-images.githubusercontent.com/48595535/118094384-3e697e00-b401-11eb-9557-116bba49e4ff.png)
感觉问题的关键点 是   我 他没使用我传入的时间戳   ，使用了一个早的时间戳，那个时间戳对应的binlog文件不是最新的，导致读不到数据

**Comment by lykpass** [comment]
Encountered change event for table db_oms.tbl_sell_order whose schema isn't known to this connector

**Comment by lykpass** [comment]
20:05:31,506 ERROR io.debezium.connector.mysql.BinlogReader                      - Error during binlog processing. Last offset stored = null, binlog reader near position = mysql-bin.001439/2231
20:05:31,516 ERROR io.debezium.connector.mysql.BinlogReader                      - Failed due to error: Error processing binlog event
org.apache.kafka.connect.errors.ConnectException: Encountered change event for table bigdata.oms_sell_order whose schema isn't known to this connector

**Comment by wuchong** [comment]
目前 scan.startup.mode 指定为timestamp 和 sepcific-offset 在实现机制上都有问题，要求 binlog 存储历史上全部数据（但是生产上都不可能）。所以请先不要使用这两个选项。

**Comment by Narutor** [comment]
好的 ，感谢大佬

**Comment by baiJoker** [comment]
有变化吗 ，能支持了吗
