### ISSUE TITLE
oracle cdc  DataException: file is not a valid field name

### ISSUE THREAD

**Issue by midoll3** [ververica/flink-cdc-connectors#1792]
![image](https://user-images.githubusercontent.com/31194732/205428920-9f82d130-61b2-4797-9c22-9c2c5d670538.png)
 这个属性是做什么的，oraclecdc 的job获取变更数据时就报这个错; 

我的配置:
![image](https://user-images.githubusercontent.com/31194732/205428967-cbbc292c-110b-477a-9294-5e0c7265e7ac.png)

**Comment by midoll3** [comment]
![image](https://user-images.githubusercontent.com/31194732/205429733-1a23fda8-2839-4460-bf94-929bfa6058c6.png)
补上一张debug的图

**Comment by xguibao** [comment]
me too,请问目前有解决了吗

**Comment by tfbi** [comment]
#1804  我找到原因了，估计都是抓schema change 日志时报错了，我目前是自己本地编译修改了，把那几行直接try catch了， 其实后面还有一个错误，#1803

**Comment by weAreFriendYo** [comment]
> me too,请问目前有解决了吗

请问你解决了么

**Comment by weAreFriendYo** [comment]
如果实在做实时同步，由于debezium在获取oracle的database时，将database转换为大写，所以你需要将database转换未大写

**Comment by e-mhui** [comment]
This is a bug. "file" is a parameter for MySQL CDC, but Oracle does not have it. you can review this pr https://github.com/ververica/flink-cdc-connectors/pull/2078 .

**Comment by zhbdesign** [comment]
> This is a bug. "file" is a parameter for MySQL CDC, but Oracle CDC does not have it. you can review this pr #2078 .

怎么临时解决，看代码还没有合并

**Comment by gong** [comment]
It is duplication https://github.com/ververica/flink-cdc-connectors/issues/2311. And this PR https://github.com/ververica/flink-cdc-connectors/pull/2315 will fix it. We can close it. cc @GOODBOY008.
