### ISSUE TITLE
Connection refused when flink on yarn mode

### ISSUE THREAD

**Issue by jingrongchen** [ververica/flink-cdc-connectors#1796]
**Describe the bug(Please use English)**
when querying mysql using flink, it shows Connection refused on yarn mode.
it succeeded using standalone mode.

**Environment :**
 - Flink version :  1.4.6
 - Flink CDC version: 2.3.0
 - Database and version: mysql 8

**To Reproduce**
1. The test data : 
2. CREATE TABLE mysql_binlog (
 id INT NOT NULL,
 name STRING,
 description STRING,
 weight DECIMAL(10,3)
) WITH (
 'connector' = 'mysql-cdc',
 'hostname' = 'localhost',
 'port' = '3306',
 'username' = 'flinkuser',
 'password' = 'flinkpw',
 'database-name' = 'inventory',
 'table-name' = 'products'
);

3. The test code : SELECT * FROM mysql_binlog
4. The error :

[ERROR] Could not execute SQL statement. Reason:
java.net.ConnectException: Connection refused (Connection refused)

**Additional Description**
When using standalone mode, it also fails sometimes. but it can connect.
but on yarn session mode, it always shows connection refused

**Comment by ruanhang1993** [comment]
If the problem still exists, please re-create your issue in English on Apache Jira under project Flink with component tag Flink CDC. Thank you!
