### ISSUE TITLE
The schema change record of oracle cdc is directly discarded

### ISSUE THREAD

**Issue by tfbi** [ververica/flink-cdc-connectors#1803]
The schema change record of oracle cdc is directly discarded,

I found that  the KEY defined  in `SourceRecordUtils  `
`SCHEMA_ CHANGE_ EVENT_ KEY_ NAME = "io.debezium.connector.mysql.SchemaChangeKey"`

so, if the sourceRecord is the schema change record of Oracle，`isSchemaChangeEvent` always returns False
```java
public static boolean isSchemaChangeEvent(SourceRecord sourceRecord) {
        Schema keySchema = sourceRecord.keySchema();
        return keySchema != null && SCHEMA_CHANGE_EVENT_KEY_NAME.equalsIgnoreCase(keySchema.name());
    }
```

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version: 2.3.0
 - Database and version: oracle 11g

**Additional Description**

<img width="598" alt="企业微信截图_16703906611727" src="https://user-images.githubusercontent.com/104058276/206099210-aeb41f54-a2ca-4ac3-b30d-e93046b55756.png">

**Comment by GOODBOY008** [comment]
Duplicated with https://github.com/ververica/flink-cdc-connectors/issues/2311 , and Someone had open a pr to fix this.
