### ISSUE TITLE
There may be some bugs in the JdbcSourceEventDispatcher class

### ISSUE THREAD

**Issue by tfbi** [ververica/flink-cdc-connectors#1804]
I used OracleSourceBuilder.OracleIncrementalSource to read the records of the oracle, and when listening for schema change, I found that the following error was reported
<img width="803" alt="企业微信截图_20221207141759" src="https://user-images.githubusercontent.com/104058276/206128338-ea9cf744-338d-4e6d-9bd1-faad2268fbf8.png">

I think these errors because Oracle Record does not have `file, server_id, pos`  field，but in the `JdbcSourceEventDispatcher` class `schemaChangeRecordValue` method according to mysql record resolution, and mysql-cdc does not use this class,
 ```java
private Struct schemaChangeRecordValue(SchemaChangeEvent event) throws IOException {
            Struct sourceInfo = event.getSource();
            Map<String, Object> source = new HashMap<>();
            String fileName = sourceInfo.getString(BINLOG_FILENAME_OFFSET_KEY);
            Long pos = sourceInfo.getInt64(BINLOG_POSITION_OFFSET_KEY);
            Long serverId = sourceInfo.getInt64(SERVER_ID_KEY);
            source.put(SERVER_ID_KEY, serverId);
            source.put(BINLOG_FILENAME_OFFSET_KEY, fileName);
            source.put(BINLOG_POSITION_OFFSET_KEY, pos);
```

oracle
`
Struct{version=1.6.4.Final,connector=oracle,name=oracle_logminer,ts_ms=0,db=ORCL,schema=FLINKUSER,table=STU,scn=0,commit_scn=0}
`
mysql
`
Struct{version=1.6.4.Final,connector=mysql,name=mysql_binlog_source,ts_ms=0,db=test,table=stu,server_id=0,file=,pos=0,row=0}
`

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version: 2.3.0
 - Database and version: oracle 11g

**Comment by GOODBOY008** [comment]
Duplicate with https://github.com/ververica/flink-cdc-connectors/issues/1792.
