### ISSUE TITLE
oracle  sink to oracle,throw file is not a valid field name

### ISSUE THREAD

**Issue by xguibao** [ververica/flink-cdc-connectors#1805]
**Describe the bug(Please use English)**
I want to use flink，oracle  to oracle ,  oracle-cdc sink to oracle(jdbc),when I insert or update data,job throws exception,
caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errprs.DataException:file is not a valid name

**Environment :**
 - Flink version :  1.16
 - Flink CDC version: oracle-cdc-2.3, jdbc-1.6
 - Database and version: oracle 12

**To Reproduce**
1. The test data :
2. The test code :
Flink SQL> CREATE TABLE test01_cdc (
A int,
B string,
C string,
D string,
E string,
F string,
PRIMARY KEY(A) NOT ENFORCED
) WITH (
'connector' = 'oracle-cdc',
'hostname' = 'localhost',
'port' = '1521',
'username' = 'flinkuser',
'password' = 'flinkuser',
'database-name' = 'XE',
'schema-name' = 'inventory',
'table-name' = 'test01_cdc'，
'debezium.log.mining.strategy'='online_catalog',
'debezium.log.mining.continuous.mine'='true',
'debezium.database.tablename.case.insensitive'='false'
);

Flink SQL> CREATE TABLE test01_oracle_sink(
A int,
B string,
C string,
D string,
E string,
F string,
PRIMARY KEY(A) NOT ENFORCED
) WITH (
'connector' = 'jdbc',
'url' = 'jdbc:oracle:thin:@localhost:1521:d1rptdb1',
'username' = 'flinkuser',
'password' = 'flinkuser',
'table-name' = 'test01_sink'
)

Flink SQL> insert into test01_oracle_sink select * from test01_cdc;

4. The error :
caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errprs.DataException:file is not a valid name

**Additional Description**

通过flink sql，测试oracle到oracle,源表用cdc，目标表用jdbc,oracle  sink to oracle

**Comment by zhbdesign** [comment]
这个解决了吗，遇到了同样的问题

**Comment by LenMotion** [comment]
> 这个解决了吗，遇到了同样的问题

您解决这个问题了吗？我也遇到了

**Comment by zhbdesign** [comment]
> > 这个解决了吗，遇到了同样的问题
> 
> 您解决这个问题了吗？我也遇到了

库名 表名 字段名 改成大写试试，我们换成大写就好了

**Comment by dinglingithub** [comment]
这就是bug 不知道为啥一直没有 在master里合并， BINLOG_FILENAME_OFFSET_KEY 的属性只有 mysql的 ddl事件会有这个属性， oracle的 SchemaChangeEvent 根本没有个属性  ，不知道楼上的仁兄怎么改大写就搞定了。我是改了 base cdc的源码

**Comment by GOODBOY008** [comment]
> 这就是bug 不知道为啥一直没有 在master里合并， BINLOG_FILENAME_OFFSET_KEY 的属性只有 mysql的 ddl事件会有这个属性， oracle的 SchemaChangeEvent 根本没有个属性 ，不知道楼上的仁兄怎么改大写就搞定了。我是改了 base cdc的源码

@dinglingithub Can you give me more information to reproduce the scence.

**Comment by GOODBOY008** [comment]
Duplicated with https://github.com/ververica/flink-cdc-connectors/issues/1792
