### ISSUE TITLE
Oracle CDC-2.3.0 DML statement couldn't be parsed

### ISSUE THREAD

**Issue by wmtbnbo** [ververica/flink-cdc-connectors#1814]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.14.6
 - Flink CDC version: 2.3.0
 - Database and version: Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production

**To Reproduce**
1. The test data :
Insert a piece of data
2. The test code :
```
CREATE TABLE purchasegoods_source (
    BIZNO	string,
    GOODS_NAME	string,
    SOURCE	string,
    CORPNAME	string,
    IDCARD	string,
    TAXNUM	string,
    CREATE_TIME	string,
    DEAL_TIME	timestamp,
    PROJNAME	string,
    TOTAL_AMOUNT	decimal(22,2),
    TOTAL_COUNT	decimal(22),
    TOTAL_AMOUNT_RATIO	decimal(22,4),
    TOTAL_COUNT_RATIO	decimal(22,4),
    GOODS_PRICE	decimal(22,2),
    GOODS_MODEL	string,
    GOODS_UNIT	string,
    PRIMARY KEY(BIZNO,GOODS_NAME,SOURCE) NOT ENFORCED
) WITH (
     'connector' = 'oracle-cdc',
     'hostname' = '10.0.0.1',
     'port' = '1521',
     'username' = 'xxxxx',
     'password' = 'xxxxxxx',
     'database-name' = 'db',
     'schema-name' = 'tpd',
     'table-name' = 'PURCHASEGOODS',
     'debezium.log.mining.continuous.mine'='true',
     'debezium.log.mining.strategy'='online_catalog',
     'debezium.database.tablename.case.insensitive'='false',
     'scan.startup.mode' = 'latest-offset'
)
```
5. The error :
![image](https://user-images.githubusercontent.com/44955013/206606102-6199cdd9-efbe-4693-921f-1c8c1af5ff7a.png)
![企业微信截图_16704821223976](https://user-images.githubusercontent.com/44955013/206606132-18805a11-ead3-437c-a711-336ec83f1e34.png)

**Additional Description**

The task initialization is normal, and this exception only occurs when the data changes.
Error is still reported after adding parameters according to the prompts in the figure.use cdc-2.2.1 is normal.

**Comment by wmtbnbo** [comment]
Error is still reported after adding parameters according to the prompts in the figure

**Comment by GOODBOY008** [comment]
Duplicated with https://github.com/ververica/flink-cdc-connectors/issues/1965.
