### ISSUE TITLE
tidb cdc在列数比较多时部分列数据无法同步到目标表

### ISSUE THREAD

**Issue by Wintle** [ververica/flink-cdc-connectors#1815]
使用flink sql 增加cdc souce table后，即便使用select * from table where row_n is not null也无法返回数据，而row_n是不为null的。经过测试在124列之后的数据在cdc都是null。
tidb version 5.3 
cdc version 2.3.0

**Comment by mxd-321** [comment]
Hi, 怎么关闭了该 issues呢？解决了吗，怎么解决的呀？

有个同学也报告了该 bug，https://github.com/ververica/flink-cdc-connectors/issues/1883
