### ISSUE TITLE
flink-connector-postgres-cdc Could not initialize class io.debezium.embedded.EmbeddedEngine

### ISSUE THREAD

**Issue by MurderWind** [ververica/flink-cdc-connectors#1819]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.16.0
 - Flink CDC version:  2.3.0
 - Database and version:  PostgreSQL 14.3 (Debian 14.3-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

**To Reproduce**
1. The test data :
    **of course . i fixed postgresql wal config**
      the config example
      logicalwal_level = logical
      max_wal_senders = 20
      wal_sender_timeout = 180s
   
     **the postgresql table struct**
               CREATE TABLE "public"."t_student" (
            "id" varchar(233) COLLATE "pg_catalog"."default" NOT NULL,
            "user_name" varchar(255) COLLATE "pg_catalog"."default",
            "sex" varchar(255) COLLATE "pg_catalog"."default",
            CONSTRAINT "t_student_pkey" PRIMARY KEY ("id")
          )
          ;

          ALTER TABLE "public"."t_student" 
            OWNER TO "postgres";

          COMMENT ON COLUMN "public"."t_student"."id" IS '主键';

          INSERT INTO "public"."t_student" ("id", "user_name", "sex") VALUES ('1', 'f', '男');

2. The test code :
                          StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
                        env.enableCheckpointing(3000, CheckpointingMode.EXACTLY_ONCE);
                        env.getCheckpointConfig().setCheckpointStorage("file:///Users/summer/flink/pg-checkpoint1");
                        EnvironmentSettings environmentSettings = EnvironmentSettings.inStreamingMode();
                        StreamTableEnvironment tableEnv=StreamTableEnvironment.create(env,environmentSettings);

                        TableResult sql = tableEnv.executeSql("CREATE TABLE pg_t_student(\n" +
                                " id STRING NOT NULL,\n" +
                                " user_name STRING,\n" +
                                " sex STRING,\n" +
                                " PRIMARY KEY(id) NOT ENFORCED\n" +
                                ") WITH (\n" +
                                " 'connector' = 'postgres-cdc',\n" +
                                " 'hostname' = 'localhost',\n" +
                                " 'port' = '5432',\n" +
                                " 'username' = 'postgres',\n" +
                                " 'password' = '123456',\n" +
                                " 'database-name' = 'postgres',"+
                                "'schema-name' = 'public'," +
                                " 'table-name' = 't_student'\n" +
                                ")");
                        sql.print();
                        System.out.println("======查询开始===============");

                        DataStream<Row> dataStream = tableEnv.toChangelogStream(tableEnv.sqlQuery(" select * from pg_t_student"));

                        dataStream.map(new MapFunction<Row, Object>() {
                            @Override
                            public Object map(Row value) throws Exception {
                                System.out.println(value.getKind().name());
                                System.out.println(value.getField("id"));
                                System.out.println(value.getField("name"));
                                System.out.println(value.getField("sex"));
                                return value;
                            }
                        });
                        env.execute();

3. The error :  
       Could not initialize class io.debezium.embedded.EmbeddedEngine$EmbeddedConfig

**Additional Description**

**Comment by MurderWind** [comment]
i  had solve this  question. close the issues

**Comment by kaiwangleo** [comment]
你好，请问这个怎么解决的呢，我也遇到这个问题了

**Comment by tttzzzwww** [comment]
cdc内置connect-api 版本冲突了，可查看cdc内部依赖的connect-api版本
依赖：
[INFO] +- com.ververica:flink-connector-mysql-cdc:jar:2.2.0:compile
[INFO] |  +- com.ververica:flink-connector-debezium:jar:2.2.0:compile
[INFO] |  |  +- io.debezium:debezium-api:jar:1.5.4.Final:compile
[INFO] |  |  \- io.debezium:debezium-embedded:jar:1.5.4.Final:compile
[INFO] |  |     +- org.apache.kafka:connect-runtime:jar:2.7.0:compile
[INFO] |  |     |  +- org.apache.kafka:kafka-tools:jar:2.7.0:compile
[INFO] |  |     |  |  \- net.sourceforge.argparse4j:argparse4j:jar:0.7.0:compile

**Comment by tttzzzwww** [comment]
cdc内置connect-api 版本冲突了，可查看cdc内部依赖的connect-api版本
依赖：
[INFO] +- com.ververica:flink-connector-mysql-cdc:jar:2.2.0:compile
[INFO] |  +- com.ververica:flink-connector-debezium:jar:2.2.0:compile
[INFO] |  |  +- io.debezium:debezium-api:jar:1.5.4.Final:compile
[INFO] |  |  \- io.debezium:debezium-embedded:jar:1.5.4.Final:compile
[INFO] |  |     +- org.apache.kafka:connect-runtime:jar:2.7.0:compile
[INFO] |  |     |  +- org.apache.kafka:kafka-tools:jar:2.7.0:compile
[INFO] |  |     |  |  \- net.sourceforge.argparse4j:argparse4j:jar:0.7.0:compile

**Comment by tttzzzwww** [comment]
> 你好，请问这个怎么解决的呢，我也遇到这个问题了
我也遇到这个问题了，我是基于：flink 1.16.2   oracle cdc2.2
原因是jar包冲突

cdc内置connect-api 版本冲突了，可查看cdc内部依赖的connect-api版本
依赖：
[INFO] +- com.ververica:flink-connector-mysql-cdc:jar:2.2.0:compile
[INFO] |  +- com.ververica:flink-connector-debezium:jar:2.2.0:compile
[INFO] |  |  +- io.debezium:debezium-api:jar:1.5.4.Final:compile
[INFO] |  |  \- io.debezium:debezium-embedded:jar:1.5.4.Final:compile
[INFO] |  |     +- org.apache.kafka:connect-runtime:jar:2.7.0:compile
[INFO] |  |     |  +- org.apache.kafka:kafka-tools:jar:2.7.0:compile
[INFO] |  |     |  |  \- net.sourceforge.argparse4j:argparse4j:jar:0.7.0:compile
