### ISSUE TITLE
PostgreSQL CDC如何启动只从最新的binlog读取数据，目前每次都要扫描全表的数据才开始正常工作，等待时间过长

### ISSUE THREAD

**Issue by Xuzhengz** [ververica/flink-cdc-connectors#1825]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by zZxiaowang** [comment]
把你的配置贴出来

**Comment by wallkop** [comment]
Using the following code:
```
debeziumProperties.setProperty("snapshot.mode", "never");
```
