### ISSUE TITLE
Mysql connector support parallel snapshot when there are no primary key for tables

### ISSUE THREAD

**Issue by EMsnap** [ververica/flink-cdc-connectors#1827]
**Is your feature request related to a problem? Please describe.**

Mysql connector now only support parallel snapshot for tables with primary key which means that 
we can only use cdc-version1  to support multiple tables read when there are some tables are without primary key 
Read multiple tables using just one subtask is pretty slow and unbearable for the users

**Describe the solution you'd like**

1、remove the constraint in mysql-cdc 2.0 for primary key
2、for those tables which don't contain primary key, split the whole table as a chunk during split stage
3、since there's no need for the SnapshotSplitReader to upsert binlog with the snapshot data for a whole table
split , just let the highwatermark equals to the lowwatermark to escape the upsert stage.

**Comment by zstraw** [comment]
@EMsnap Hi,  EMsnap, what's the status of the issue? I find the PR only modify the codes in test.

**Comment by zstraw** [comment]
Hi, @leonardBang , could you spare some time to review the PR?

**Comment by ruanhang1993** [comment]
Closed by #2150.
