### ISSUE TITLE
NoClassDefFoundError: com/ververica/cdc/debezium/utils/ResolvedSchemaUtils

### ISSUE THREAD

**Issue by Zelexshow** [ververica/flink-cdc-connectors#1832]
**Describe the bug(Please use English)**
Following the quickstart doc:
https://ververica.github.io/flink-cdc-connectors/master/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/mysql-postgres-tutorial-zh.html#

I got  a ERROR like this below:
![image](https://user-images.githubusercontent.com/52685431/208236003-89eb7d54-2337-41eb-b0c8-1d75a96bb42a.png)
![image](https://user-images.githubusercontent.com/52685431/208236019-efdfea65-7274-452e-ba25-59c4e785034a.png)

`
Caused by: java.lang.NoClassDefFoundError: com/ververica/cdc/debezium/utils/ResolvedSchemaUtils
	at com.ververica.cdc.connectors.mysql.table.MySqlTableSourceFactory.createDynamicTableSource(MySqlTableSourceFactory.java:102) ~[flink-connector-mysql-cdc-2.3.0.jar:2.3.0]
`
**Details**:
I create the **source** table:
`
CREATE TABLE t_db1_post_1 (
   id BIGINT,
   topic VARCHAR(50),
   content VARCHAR(1000),
   poster_id BIGINT,
   poster_nickname VARCHAR(30),
   poster_verif BOOLEAN,
   post_type TINYINT,
   `views` BIGINT,
   agrees BIGINT,
   disagrees BIGINT,
   confidence INT,
   major_type VARCHAR(20),
   mentioned_tutor VARCHAR(10),
   mentioned_tutor_uni VARCHAR(10),
   ext_info VARCHAR(500),
   gmt_create_time TIMESTAMP,
   gmt_gmt_mod_time TIMESTAMP,
   PRIMARY KEY (id) NOT ENFORCED
 ) WITH (
   'connector' = 'mysql-cdc',
   'hostname' = '192.168.0.107',
   'port' = '3306',
   'username' = 'root',
   'password' = 'root',
   'database-name' = 'db_tutor_hunter_1',
   'table-name' = 't_post_1'
 );
`

and the sink table:
`
CREATE TABLE es_idx_post (
   id BIGINT,
   topic VARCHAR(50),
   content VARCHAR(1000),
   poster_id BIGINT,
   poster_nickname VARCHAR(30),
   poster_verif BOOLEAN,
   post_type TINYINT,
   `views` BIGINT,
   agrees BIGINT,
   disagrees BIGINT,
   confidence INT,
   major_type VARCHAR(20),
   mentioned_tutor VARCHAR(10),
   mentioned_tutor_uni VARCHAR(10),
   ext_info VARCHAR(500),
   gmt_create_time TIMESTAMP,
   gmt_gmt_mod_time TIMESTAMP,
   PRIMARY KEY (id) NOT ENFORCED
) WITH (
  'connector' = 'elasticsearch-7',
  'hosts' = 'http://localhost:9200',
  'index' = 'idx_post'
);
`
By the way, I had adding the related jar file:
[flink-sql-connector-mysql-cdc-2.3.0.jar](https://mvnrepository.com/artifact/com.ververica/flink-connector-mysql-cdc)
[flink-sql-connector-elasticsearch7-1.16.jar](https://nightlies.apache.org/flink/flink-docs-release-1.16/zh/docs/connectors/table/elasticsearch/)

**Environment :**
 - Flink version :  flink-1.16.0
 - Flink CDC version: 2.3
 - Database and version: mysql:8.0.26;  elasticsearch 7.17.5
 - jdk-11.0.16.1

Substitutions:
After downloading the source code, I found that the target Class exists:"ResolvedSchemaUtils"
![image](https://user-images.githubusercontent.com/52685431/208236060-d8376c19-b8d3-407a-90e0-c150de2f1928.png)
So, I wonder that how to solve this ERROR problem

**Comment by zhangbool** [comment]
Some problem

**Comment by lpong** [comment]
解决了吗

**Comment by jbarrieault** [comment]
@Zelexshow I saw this error when using `flink-connector-mysql-cdc-[VERSION].jar`. Using `flink-sql-connector-mysql-cdc-[VERSION].jar` instead resolved it (I'm using [`v.2.3.0`](https://repo1.maven.org/maven2/com/ververica/flink-sql-connector-mysql-cdc/2.3.0/flink-sql-connector-mysql-cdc-2.3.0.jar)).

**Comment by liwei9902** [comment]
> @Zelexshow I saw this error when using `flink-connector-mysql-cdc-[VERSION].jar`. Using `flink-sql-connector-mysql-cdc-[VERSION].jar` instead resolved it (I'm using [`v.2.3.0`](https://repo1.maven.org/maven2/com/ververica/flink-sql-connector-mysql-cdc/2.3.0/flink-sql-connector-mysql-cdc-2.3.0.jar)).

yes, use flink-sql-connector-mysql-cdc-2.3.0.jar works ok.
