### ISSUE TITLE
Oracle cdc 2.3.0 concurrently inserted oracle 11g lost insert message

### ISSUE THREAD

**Issue by Roger0917** [ververica/flink-cdc-connectors#1835]
The benchmark 5.0 tool first initializes the first warehouse data, and then starts the synchronization test program. The full amount of data synchronization is no problem, and then 10 terminals run the transaction for 5 minutes. The own program monitors the changes in real time, and finally the synchronization count is inconsistent，The attachment is the benchmark test program compression package。
[benchmarksql-5.0.tar.gz](https://github.com/ververica/flink-cdc-connectors/files/10265941/benchmarksql-5.0.tar.gz)

The link below is the address of my synchronization program. When reproducing the bug, you need the Xugu database and driver, please contact me

https://github.com/Roger0917/flink-oracle-cdc-xugu-test

contact details ：phone or Wechat 17381797208  E-mail 1421128167@qq.com

**Environment :**
-  OS Windows10 
-  Developer Tools : IntelliJ IDEA 2022.3 Ultimate Edition
 - Flink version :  1.16.0
 - Flink CDC version:  oracle 2.3.0
 - Database and version: Source Database : Oracle 11g Oracle jdbc 19.3.0.0  Target Database: Xugu V12  Xugu jdbc 12.1.0

1. First use the benckmark 5.0 tool to initialize warehouse 1 data to Oracle 11g
![faeb2375d275997dba58937d62b6918](https://user-images.githubusercontent.com/21167121/208594138-8a8608ef-a491-46a8-857a-fb8440a05f76.png)

2. Start the test to synchronize to the Xugu database program, the full synchronization is no problem
![73cf5e5bd8d27e85969dd33b7ab450f](https://user-images.githubusercontent.com/21167121/208594897-db91a3f6-fac3-46f4-9599-4998d5b73bd6.png)
![0c8cfb64e05af8d5a6448018e436e84](https://user-images.githubusercontent.com/21167121/208594937-97f7e5dc-98b8-415a-8b67-b0fdd529945e.png)
![104fd67b95b070cb9fbdb29c016a466](https://user-images.githubusercontent.com/21167121/208594970-aeba5a01-5f22-4ef4-9bea-eab52700b23e.png)

3. Execute the script and start running the benchamrk transaction to insert incremental data concurrently into Oracle for 5 minutes. The incremental synchronization is correct only when the terminals are equal to 1 single thread. If it is greater than 1, for example, 10 concurrent inserts, the amount of data after incremental synchronization is less than that of Oracle
![e2dddf5d8f205a31e19a8b7418bd750](https://user-images.githubusercontent.com/21167121/208594166-b2a26964-49d7-4b21-8379-877eb5ef66eb.png)

4. Console keeps warning about Missing SCN
![c56d9fa455b20a0abd60c31db612f87](https://user-images.githubusercontent.com/21167121/208595479-f088fd01-34b1-4034-a894-86d380649e22.png)

5. After synchronization, the data size of the tables at both ends is inconsistent，The amount of data in the target database is less than that of the source, so there are either fewer inserts or more deletes, but the tables of the benchmark all have primary keys, and delete will only delete one piece of data based on the primary key, so there will not be too many deletes. , so I guess it may be that the insert message monitored by flink oracle cdc is missing
![5330f5d64daea092fec36eba68d327b](https://user-images.githubusercontent.com/21167121/208596228-37aeee0c-543d-4f0b-9248-8245f21ba0b5.png)

6. The following sql is used to compare the consistency of the databases at both ends. If the result sets are the same, the consistency is correct, but the consistency is not the same after flink cdc synchronization

Oracle: 
(Select w_id, w_ytd from bmsql_warehouse) minus (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id) ;
(Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district) minus (select o_w_id, o_d_id, max(o_id) from bmsql_oorder group by o_w_id, o_d_id) ;
(Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district) minus (select no_w_id, no_d_id, max(no_o_id) from bmsql_new_order group by no_w_id, no_d_id) ;
select * from (select (count(no_o_id)-(max(no_o_id)-min(no_o_id)+1)) as diff from bmsql_new_order group by no_w_id, no_d_id) where diff != 0 ;
(select o_w_id, o_d_id, sum(o_ol_cnt) from bmsql_oorder group by o_w_id, o_d_id) minus (select ol_w_id, ol_d_id, count(ol_o_id) from bmsql_order_line group by ol_w_id, ol_d_id) ;
(select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id) minus (Select w_id, w_ytd from bmsql_warehouse) ;

Xugu:

 (Select w_id, w_ytd from bmsql_warehouse) except (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id);
(Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district) except (select o_w_id, o_d_id, max(o_id) from bmsql_oorder group by o_w_id, o_d_id);
(Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district) except (select no_w_id, no_d_id, max(no_o_id) from bmsql_new_order group by no_w_id, no_d_id);
select * from (select (count(no_o_id)-(max(no_o_id)-min(no_o_id)+1)) as diff from bmsql_new_order group by no_w_id, no_d_id) where diff != 0;
(select o_w_id, o_d_id, sum(o_ol_cnt) from bmsql_oorder group by o_w_id, o_d_id) except (select ol_w_id, ol_d_id, count(ol_o_id) from bmsql_order_line group by ol_w_id, ol_d_id);
(select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id) except (Select w_id, w_ytd from bmsql_warehouse);

![31073089567173de703cde413851107](https://user-images.githubusercontent.com/21167121/208597294-68c02557-f53e-45b0-9e54-ada8b3846cdd.png)
![4bb8301ce46b3b201f8f9f7afc71c77](https://user-images.githubusercontent.com/21167121/208597323-51d30823-7998-4838-a7e1-16a0e3be2daa.png)

@leonardBang God help me to look at this problem?

**Comment by tigrulya-exe** [comment]
@Roger0917 Hi, how did you fix your issue?
