### ISSUE TITLE
为什么数据很慢以及索引卡死

### ISSUE THREAD

**Issue by lsfff** [ververica/flink-cdc-connectors#1844]
CREATE TABLE org (
`id` string,
`source_id` string,
`org_kind` string,
`name` string,
`parent_id` string,
PRIMARY KEY (`id`) NOT ENFORCED
) WITH (
'connector' = 'mysql-cdc',
'hostname' = '192.168.17.126',
'port' = '83',
'username' = 'root',
'password' = '',
'database-name' = 'collection-main',
'table-name' = 'org'
);

CREATE TABLE address (
`id` string,
`police_org_id` string,
`grid_org_id` string,
PRIMARY KEY (`id`) NOT ENFORCED
) WITH (
'connector' = 'mysql-cdc',
'hostname' = '192.168.17.126',
'port' = '83',
'username' = 'root',
'password' = '',
'database-name' = 'collection-main',
'table-name' = 'address'
);

CREATE TABLE org_statistics (
  `id` string,
`org_kind` string,
`name` string,
`parent_id` string,
`count_address` bigint,
  PRIMARY KEY (`id`) NOT ENFORCED
) WITH (
    'connector' = 'elasticsearch-7',
    'hosts' = 'http://192.168.17.124:9200',
    'index' = 'org_statistics'
);

INSERT INTO org_statistics
SELECT
	o.id,o.org_kind,o.name,o.parent_id,
	count(a.id) AS count_address 
FROM
	org o 
LEFT JOIN address a ON o.id = a.grid_org_id
group by o.id,o.org_kind,o.name,o.parent_id

我只想尝试做些简单的聚合实时统计(两张mysql表)，一张2万组织表一张200万地址表，为什么写入到es直接索引卡死掉了，是不是我的用法不对

是不是因为flink是读取到一条数据就更新一次es导致的，不是开始先统计出来一次性插入es。

还有进入es的数据出现查不到的情况或者查单条文档(有count的数据并且很大)直接卡住，返回timeout，没有count的数据正常，我已经等了两个小时了还是这样。

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
