### ISSUE TITLE
flink cdc采集oracle数据库的时候会由logminer自动生成高并行度的统计分析sql，这个对主库影响还是挺大的，有没有办法设置一些参数，将并行度降下来。

### ISSUE THREAD

**Issue by wangdabin1216** [ververica/flink-cdc-connectors#1849]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by GOODBOY008** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
