### ISSUE TITLE
scanNewlyAddedTableEnabled

### ISSUE THREAD

**Issue by HoboLegion** [ververica/flink-cdc-connectors#1865]
使用scanNewlyAddedTableEnabled=true该配置，发现新添加的tableList，在使用过程中，Flinkcdc程序首次启动模式位initial时，进行savepoint，新增tableList，从检测点重启FlinkCDC程序，新添加表的binlog是正常打印的。但是 当Flinkcdc程序首次启动模式位latest时，进行savepoint，新增tableList，从检测点重启FlinkCDC程序，新添加表会提示元数据未知的问题。 有些时候我不需要全量的数据，只需要增量的数据但目前测试是不支持的。

` ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource  [] - Encountered change event 'Event{header=EventHeaderV4{timestamp=1672999597000, eventType=TABLE_MAP, serverId=921673408, headerLength=19, dataLength=94, nextPosition=190804502, flags=0}, data=TableMapEventData{tableId=10131, database='打码', table='打码', columnTypes=3, 15, 15, 15, 15, 15, 15, -4, 3, 17, 17, 3, columnMetadata=0, 400, 400, 400, 400, 400, 400, 2, 0, 0, 0, 0, columnNullability={4, 5, 6, 7}, eventMetadata=TableMapEventMetadata{signedness={}, defaultCharset=224, charsetCollations=null, columnCharsets=null, columnNames=null, setStrValues=null, enumStrValues=null, geometryTypes=null, simplePrimaryKeys=null, primaryKeysWithPrefix=null, enumAndSetDefaultCharset=null, enumAndSetColumnCharsets=null,visibility=null}}}' at offset {transaction_id=null, file=mysql-bin.000093, pos=190804289, gtids=554cce38-1238-11ed-acb8-a0369ffb5d60:1-1,65426913-1238-11ed-b921-a0369ffc6a4c:1-63916873, server_id=921673408, event=1} for table ppdai_ods_tele_alarm.flink_instance_config whose schema isn't known to this connector. One possible cause is an incomplete database history topic. Take a new snapshot in this case.`

**Comment by HoboLegion** [comment]
遇到这种情况，该如何解决呢？

**Comment by Capri0110** [comment]
不支持的，scanNewlyAddedTableEnabled 只能使用 initial startup mode 去启动

**Comment by minchowang** [comment]
> 我本地能稳定复现这个bug

我修了这个bug，可以来review下

**Comment by minchowang** [comment]
问题是在于，首次扫描表时会填充schema信息，而在后续新加的表这个`split.getTableSchemas().isEmpty()` 将不会进入，意味着不会对新加表进行schema填充
https://github.com/ververica/flink-cdc-connectors/blob/22f68d321d1a44f8074787e65e1d5d5ea5ee5d74/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/reader/MySqlSourceReader.java#L212
