### ISSUE TITLE
从Oracle同步数据至kafka，Oracle库内存占用持续上升

### ISSUE THREAD

**Issue by zjx210000** [ververica/flink-cdc-connectors#1868]
**Describe the bug(Please use English)**
从Oracle中抽取20张表，提交任务后Oracle所在服务器内存占用持续上升。

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version: 2.2.1
 - Database and version: Oracle 19c
 - Yarn version：3.0.0

Flink SQL：
CREATE TABLE test_source (
    ID INT,
    NAME STRING,
    PRIMARY KEY (ID) NOT ENFORCED
  ) WITH (
    'connector' = 'oracle-cdc',
    'hostname' = 'localhost',
    'port' = '1521',
    'username' = 'user',
    'password' = '***',
    'database-name' = 'test',
    'schema-name' = 'flinkuser',  
    'table-name' = 'test_source',
    'debezium.database.tablename.case.insensitive' = 'false',
    'debezium.log.mining.strategy' = 'online_catalog'
  );

CREATE TABLE test_sink (
    ID INT,
    NAME STRING,
    PRIMARY KEY (ID) NOT ENFORCED
 ) WITH (
   'connector' = 'kafka',
   'topic' = 'test_topic',
   'properties.bootstrap.servers' = 'xxx:9092',
   'scan.startup.mode' = 'latest-offset',
   'format' = 'debezium-json'
 );

 INSERT INTO test_sink SELECT * FROM test_source;

Oracle单表数据量在几千到数百万不等，Oracle开了6组500MB~2G的redo log，任务提交时单个连接占用Oracle服务器内存180MB左右，24h后增长至单个连接1.7G。
yarn-session参数：
parallelism.default:1
state.savepoint.dir: hdfs://xxx/flink-savepoints
slots: 30

**Comment by LiaoMinYu** [comment]
问题解决了吗

**Comment by KK900716** [comment]
同问，感觉有内存泄漏，OOM的位置在OracleDdlParser这个类

**Comment by GOODBOY008** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
