### ISSUE TITLE
Flink CDC 同步数据时 statement  为什么不把where 后面的条件传进去

### ISSUE THREAD

**Issue by lykpass** [ververica/flink-cdc-connectors#187]
这样的话，如果我要同步年初至今的数据的话，binlog太久远，也没了，难道只能把所有的数据加载到内存筛选吗，有什么好办法吗

**Comment by wuchong** [comment]
目前还不支持 filter 条件的下推。

这是个挺好的 feature。 Debezium 也暴露了 `snapshot.select.statement.overrides` 相关的参数让上层指定 snapshot select query。 所以理论上也能支持。 欢迎贡献。 

https://debezium.io/documentation/reference/1.4/connectors/mysql.html#mysql-property-snapshot-select-statement-overrides

**Comment by lykpass** [comment]
> 目前还不支持 filter 条件的下推。
> 
> 这是个挺好的 feature。 Debezium 也暴露了 `snapshot.select.statement.overrides` 相关的参数让上层指定 snapshot select query。 所以理论上也能支持。 欢迎贡献。
> 
> https://debezium.io/documentation/reference/1.4/connectors/mysql.html#mysql-property-snapshot-select-statement-overrides
1.4.0确实支持这个功能了，我还有一个疑问，cdc同步数据时目前是单个Parallelism，是为了保证数据的一致性吗，那可以在做快照时多开几个并行度吗，然后快照完成后  从最新binlog消费时再恢复成单个并行度   可以吗

**Comment by wuchong** [comment]
@lykpass , 目前还不支持。 主要是 Debezium 底层设计是单并发的。 

目前社区正在开发 mysql-cdc 2.0 版本，解决多并发以及 checkpoint 问题，预计7月份发布。可以多关注下。

**Comment by lykpass** [comment]
> @lykpass , 目前还不支持。 主要是 Debezium 底层设计是单并发的。
> 
> 目前社区正在开发 mysql-cdc 2.0 版本，解决多并发以及 checkpoint 问题，预计7月份发布。可以多关注下。

翀哥 我用的flink1.13   使用 row_mumber函数出现 java.lang.RuntimeException: Can not retract a non-existent record. This should never happen.  这个问题    我看你有在其它地方回复过别人  显示是1.12就修复了  我的sql逻辑是
    SELECT 
    	* 
    FROM (
		SELECT 
		     wvtd.vh_train_no AS car_train_no    
		    ,wvtd.bulk_num AS order_disperse_num 
		    ,wvtd.flag                           
		    ,wvtd.qty_whole AS order_whole_num   
		    ,wvtd.bill_no AS order_no            
		    ,wvtd.qty_box AS order_box_num       
		    ,ROW_NUMBER()over(partition by wvtd.bill_no  order by wvth.update_date desc,wvtd.add_time desc 
		) ranks 
		FROM 
			wms_vehicle_train_detail wvtd
		LEFT JOIN 
			wms_vehicle_train_header wvth 
		ON 
			wvtd.wh_code = wvth.wh_code
			AND wvtd.vh_train_no = wvth.vh_train_no
    ) a
    WHERE 
    	ranks=1
能帮忙看下为什么吗

**Comment by lykpass** [comment]
> @lykpass , 目前还不支持。 主要是 Debezium 底层设计是单并发的。
> 
> 目前社区正在开发 mysql-cdc 2.0 版本，解决多并发以及 checkpoint 问题，预计7月份发布。可以多关注下。

Jark snapshot.select.statement.overrides这个参数在新版的2.2版本中不生效了
