### ISSUE TITLE
mysql-cdc cannot capture data from mysql

### ISSUE THREAD

**Issue by echodyn** [ververica/flink-cdc-connectors#1880]
**Describe the bug(Please use English)**
mysql-cdc cannot capture data from mysql 

**Environment :**
 - Flink version :  1.16.0
 - Flink CDC version: flink-sql-connector-mysql-cdc-2.4-SNAPSHOT
 - Database and version: mysql-5.7.35

**To Reproduce**
I tried to follow the tutorial of the QUICKSTART "Streaming ETL for MySQL and Postgres with Flink CDC".
After I insert test data into table 'products'&'orders' and create tables that capture the change data from the corresponding database tables in Flink,tables in Flink seem cannot sync data from those in mysql.
However,it works well on Postgres.
1. The test data :
in mysql:
```
-- MySQL
CREATE DATABASE mydb;
USE mydb;
CREATE TABLE products (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512)
);
ALTER TABLE products AUTO_INCREMENT = 101;

INSERT INTO products
VALUES (default,"scooter","Small 2-wheel scooter"),
       (default,"car battery","12V car battery"),
       (default,"12-pack drill bits","12-pack of drill bits with sizes ranging from #40 to #3"),
       (default,"hammer","12oz carpenter's hammer"),
       (default,"hammer","14oz carpenter's hammer"),
       (default,"hammer","16oz carpenter's hammer"),
       (default,"rocks","box of assorted rocks"),
       (default,"jacket","water resistent black wind breaker"),
       (default,"spare tire","24 inch spare tire");
```
2. The test code :
in Flink:
```
CREATE TABLE products (
    id INT,
    name STRING,
    description STRING,
    PRIMARY KEY (id) NOT ENFORCED
  ) WITH (
    'connector' = 'mysql-cdc',
    'hostname' = 'localhost',
    'port' = '3306',
    'username' = 'root',
    'password' = '123456',
    'database-name' = 'mydb',
    'table-name' = 'products'
  );

SELECT * FROM default_catalog.default_database.products;
```
3. The error :
![image](https://user-images.githubusercontent.com/73233907/213341752-b30e7242-c8c5-43d0-98cb-8112faa637ef.png)
No data captured in table 'products' in Flink while it works well on Postgres.I tried insert data into mysql afterwards and it doesn't work as well.

**Comment by HongYangZheng** [comment]
Hello ! Did you solve it? I meet the same issue. It works well in java code with table environment but the same as you in sql-client mode.
