### ISSUE TITLE
Why mongodb cdc not support errors.tolerance connector options at 2.3?

### ISSUE THREAD

**Issue by wudihero2** [ververica/flink-cdc-connectors#1881]
**Is your feature request related to a problem? Please describe.**
I noticed mongodb cdc 2.2 has errors.tolerance option, why removed it at 2.3?
How to deal with processing messages if an error is encountered?
**Describe the solution you'd like**
None.

**Describe alternatives you've considered**
None.

**Comment by Jiabao-Sun** [comment]
The "errors.tolerance" and "exactly-once" semantics conflict with each other, so it has not been exposed.
