### ISSUE TITLE
mysql cdc with gtidSets mode, a few  update records are missing

### ISSUE THREAD

**Issue by hushuiwang** [ververica/flink-cdc-connectors#1885]
**Describe the bug(Please use English)**
source :mysql binlog
sink :kudu
mysql cdc with gtidsets mode, a few  update records are missing

**Environment :**
 - Flink version :  1.14.5
 - Flink CDC version: 2.3 
 - Database and version:  5.7.36-txsql-log
 - kudu : 1.10.0-cdh6.3.2 
 - Flink Kudu Connector: 1.1-SNAPSHOT

**reproduce**
It is difficult to reproduce this bug , seems like when change to the new binlog file ,the bug may occurs
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/12995631/215422908-df87a84b-bbe9-489b-844f-ac08eb937b65.png">

**Additional Description**
the logs was normal ,the checkpoints was  normal, everything look fines , but lose a few  update  records

**Comment by ruanhang1993** [comment]
If the problem still exists, please re-create your issue in English on Apache Jira under project Flink with component tag Flink CDC. Thank you!
