### ISSUE TITLE
请问需要怎么设置才能在服务崩溃或者重启后拿到上次使用的binlog位点继续同步数据

### ISSUE THREAD

**Issue by znzn007007** [ververica/flink-cdc-connectors#189]

**Comment by naive1992** [comment]
自反序列化的时自己保存offset位置，重启时候从offset位置接着读取，目前官方好像没有提供接着读取的方法

**Comment by leonardBang** [comment]
这个已经支持的，checkpoint时 state 里保存了offset 和 schema，从checkpoint回复时会从state加载并读取，可以看下DebeziumSourceFunction 中的state相关代码

**Comment by naive1992** [comment]
> 这个已经支持的，checkpoint时 state 里保存了offset 和 schema，从checkpoint回复时会从state加载并读取，可以看下DebeziumSourceFunction 中的state相关代码

实际操作，读取模式initial，latest等都没有这种模式对应上次消费位置，specialOffset需要填入指定binlog位置
