### ISSUE TITLE
flinkcdc同步mysql 数据时初始化镜像数据时每批数据中间有200多秒的中断

### ISSUE THREAD

**Issue by Ink00Bamboo** [ververica/flink-cdc-connectors#1892]
flinkcdc读取mysql数据，镜像数据初始化时，发现cdc在每个批次读取完数据后，会有200多秒的中断。之后再读取下一批数据，想请问这200多秒是做了什么吗？  执行日志如下
<img width="953" alt="image" src="https://user-images.githubusercontent.com/46698179/216503707-a786417d-4a61-45de-944a-77d998747569.png">
数据库实例下又30多个库，我单独抽取一个库下的一张表的数据。

flink cdc 配置:
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/46698179/216504086-6c81e4b5-c30a-4520-944f-f5ac3d4de2b5.png">

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
