### ISSUE TITLE
java.lang.ClassNotFoundException: com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction

### ISSUE THREAD

**Issue by sgpennebaker** [ververica/flink-cdc-connectors#190]
Flink 1.13.0
Veronica 1.4.0

Flink SQL>             CREATE TABLE mysql_binlog (
>              id INT NOT NULL,
>              name STRING,
>              description STRING
>             ) WITH (
>              'connector' = 'mysql-cdc',
>              'hostname' = 'localhost',
>              'port' = '3306',
>              'username' = 'flink1u',
>              'password' = 'flink1p',
>              'database-name' = 'flink1',
>              'table-name' = 'products'
>             );
> 
[INFO] Execute statement succeed.

Flink SQL> SELECT id, UPPER(name), description FROM mysql_binlog;
**[ERROR] Could not execute SQL statement. Reason:
java.lang.ClassNotFoundException: com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction**

**Comment by sgpennebaker** [comment]
per the instructions, i'm taking the jars from https://github.com/ververica/flink-cdc-connectors/releases/tag/release-1.4.0 and dropping them in FLINK_HOME/lib.  rooting around it looks possible that there should be a Vervica debezium jar, might be in there but i can't find that to download anywhere

**Comment by sgpennebaker** [comment]
for fun, i built the snap shot and put all these jars in lib and got the same error.

flink-connector-debezium-1.5-SNAPSHOT.jar
flink-connector-mysql-cdc-1.5-SNAPSHOT.jar
flink-connector-postgres-cdc-1.5-SNAPSHOT.jar
flink-format-changelog-json-1.5-SNAPSHOT.jar
flink-sql-connector-mysql-cdc-1.5-SNAPSHOT.jar
flink-sql-connector-postgres-cdc-1.5-SNAPSHOT.jar

**Comment by macdoor** [comment]
Exactly the same error. 
Flink 1.12.0 with flink-cdc-connectors 1.3.0 works

**Comment by macdoor** [comment]
where did you put flink-connector-mysql-cdc-xxx.jar? You should put them in flink client and flink server lib.

**Comment by sgpennebaker** [comment]
sorry to take so long to get back to this, other projects plus i wanted to be sure i was well past this before declaring victory.  in response to @macdoor, yes, the jars were in the right place.  basically the problem "fixed itself" because the machine crashed (probably unrelated LOL) and when it came back up the problem was gone.  so something left cached?  a process still running?  some kind of build fail?  don't know.  but i finally got a connection today, so closing.  thanks!
