### ISSUE TITLE
[Bug] oracle cdc Connection number problem

### ISSUE THREAD

**Issue by Soulmate76** [ververica/flink-cdc-connectors#1905]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.6

### Flink CDC version

2.3

### Database and its version

oraclce 11.2.0.4.0

### Minimal reproduce step

![image](https://user-images.githubusercontent.com/43566263/217800850-8bbd8091-4ad8-4a25-a572-7d10cbf7c27a.png)
In the full-volume phase, the data volume is about 3G. With the completion of chunk division and the transfer to the downstream, the number of oracle database connections is increasing according to the division of chunk to pull data, and the previous connections will not be released no matter whether the full data is being pulled or the full data is converted into an increment. The database failed due to excessive connections. No solution can be found.Oracle cdc is simply not usable with large amounts of data

### What did you expect to see?

Are there any Settings to control the number of connections or to release connections?

### What did you see instead?

I tried to fix the problem from the source code, but saw that pulling data from the oracle database didn't seem to use connection pooling, and while the code showed that the connection was shared, it wasn't in health!!

### Anything else?

The execute() method is called in the source code, but I added log printing to all the execute() methods in oracle cdc, and found that all the execute() methods did not print the log I added at runtime, that is, all execute() methods did not enter, which was very confusing. Want to modify but can't start!!
![image](https://user-images.githubusercontent.com/43566263/217804108-be847f14-148a-4413-994f-001653a3fb77.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lujiujiuyj** [comment]
mark!

**Comment by ruanhang1993** [comment]
Fix in #2254
