### ISSUE TITLE
读取多张表数据同步停止

### ISSUE THREAD

**Issue by maker-dong** [ververica/flink-cdc-connectors#192]
我使用flink-cdc读取mysql中多张表数据写入Doris，
cdc表如下：
CREATE TABLE `mysql_business_order` (
...
) WITH (
  'connector' = 'mysql-cdc',
  'hostname' = 'xxx',
  'port' = '3306',
  'username' = 'xxx',
  'password' = 'xxx',
  'database-name' = 'mcs_order100000054',
  'table-name' = 'business_order2021[0-9]*'
);

mysql中前五张表数据共800+条，但doris中数据只有501条，分组查看结果如下：
+---------+----------+
| date    | count(1) |
+---------+----------+
| 2021-01 |      135 |
| 2021-02 |       28 |
| 2021-03 |      192 |
| 2021-04 |      138 |
| 2021-05 |        8 |
+---------+----------+
通过对比，前四个月数据均正确，但5月份数据只有8条，实际有300+条
flink程序无报错，还在继续运行，但数据迟迟没有同步过来。

单独同步这五月这一张表是正常的。

**Comment by fsk119** [comment]
hi，能提供当时的flink log 吗？
