### ISSUE TITLE
[Bug] oracle服务器连接被占满

### ISSUE THREAD

**Issue by niaoshuai** [ververica/flink-cdc-connectors#1920]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.6

### Flink CDC version

2.3.0

### Database and its version

oracle 19c

### Minimal reproduce step

1. 开启检查点 并设置 检查点时间60s
2. 然后服务器运行一段时间时间，因报错 把oracle 连接池占满

### What did you expect to see?

oracle 内存占满

### What did you see instead?

NO

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by LiaoMinYu** [comment]
这个问题处理了吗，我三个流任务3天后连接数达到500+

**Comment by ruanhang1993** [comment]
Fixed in #2254
