### ISSUE TITLE
oracle-cdc 全量采集是字段名过长采集不到数据

### ISSUE THREAD

**Issue by luobo-te** [ververica/flink-cdc-connectors#1922]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.13

### Flink CDC version

2.3.0

### Database and its version

oracle 19c

### Minimal reproduce step

oracle在全量采集的时候，当有字段名长度超过31个字符时，只能采集到表的快照数据，无法采集到增量数据

### What did you expect to see?

这个问题是否通过某个配置项能规避，或者这是debezium本身的bug?

### What did you see instead?

这个问题是否通过某个配置项能规避，或者这是debezium本身的bug?

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
@luobo-te Can u show me your sql and table ddl scripts?

**Comment by GOODBOY008** [comment]
https://github.com/debezium/debezium/pull/4317 
@luobo-te  This is a known issue. Like @Naros explained. Thank you @Naros :)
