### ISSUE TITLE
mysql failed on flush_net

### ISSUE THREAD

**Issue by constantlyF** [ververica/flink-cdc-connectors#1923]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.13.6

### Flink CDC version

mysql-cdc 2.2.1

### Database and its version

阿里云mysql 8.0.13

### Minimal reproduce step
CREATE TABLE `test01` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `service_name` varchar(255) DEFAULT NULL,
  `request_param` text,
  `request_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
)

/**
 * flink 1.13.6
 * mysql-cdc 2.2.1
 * 阿里云mysql 8.0.13
 */
public class TestCDC {
    private static final Logger LOG = LoggerFactory.getLogger(TestCDC.class);

    public static void main(String[] args) throws Exception {
        StreamExecutionEnvironment streamExecutionEnvironment = StreamExecutionEnvironment.getExecutionEnvironment();
        MySqlSource<String> mySqlSource = MySqlSource.<String>builder()
                .hostname("xxx")
                .port(3306)
                .scanNewlyAddedTableEnabled(true)
                .databaseList("test")
                .tableList("test.test01", "test.test02")
                .username("xxx")
                .password("xxx")
                .connectTimeout(Duration.ofSeconds(60))
                .connectMaxRetries(1)
                .connectionPoolSize(3)
                .startupOptions(StartupOptions.initial())
                .serverId("5401-5501")
                .serverTimeZone("Asia/Shanghai")
                .fetchSize(1024)
                .heartbeatInterval(Duration.ofSeconds(60))
                .deserializer(new JsonDebeziumDeserializationSchema())
                .build();
        DataStreamSource<String> dataStreamSource = streamExecutionEnvironment.fromSource(mySqlSource, WatermarkStrategy.noWatermarks(), "MySQL Source");
        dataStreamSource.print("MYSQL_DATA");
        streamExecutionEnvironment.execute();
    }
}

### What did you expect to see?

您好，数据可以在控制台正常打印，但是mysql日志监控刷刷的报错 db: 'xxx' user: 'xxx' host: 'xxx' (failed on flush_net()).代码中全是基础的配置，我不清楚原因是什么？我搜索了mysql配置show variables like 'slave_net_timeout'; 为60，麻烦各位大佬帮忙看下感谢

### What did you see instead?

您好，数据可以在控制台正常打印，但是mysql日志监控刷刷的报错 db: 'xxx' user: 'xxx' host: 'xxx' (failed on flush_net()).代码中全是基础的配置，我不清楚原因是什么？我搜索了mysql配置show variables like 'slave_net_timeout'; 为60，麻烦各位大佬帮忙看下感谢

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! 

为了方便各个国家的贡献者交流，请在 [Apache Jira](https://issues.apache.org/jira)  的 `Flink` 项目下重新用英文创建问题，同时在问题上将 Component 标注为 `Flink CDC`。谢谢！
