### ISSUE TITLE
FlinkCDC Collect SqlServer, can only collect full data, cannot collect incremental data problem

### ISSUE THREAD

**Issue by echobigdata** [ververica/flink-cdc-connectors#1929]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink-1.13.0

### Flink CDC version

flink-sql-connector-sqlserver-cdc-2.2.1.jar

### Database and its version

sqlserver 2017

### Minimal reproduce step

CREATE TABLE sqlserver_source (
id INT NOT NULL,
name varchar(100),
description varchar(100)
)WITH('connector' = 'sqlserver-cdc',
'hostname' = 'localhost',
'port' = '1433',
'username' = 'sa',
'password' = 'xxx',
'database-name' = 'xf',
'schema-name' = 'dbo',
'table-name' = 'flinkcdc_test'
)

### What did you expect to see?

No incremental log was captured
1.The current user permission is sysadmin
2.CDC(Change Data Capture) is enabled for the current database
3.The current table has CDC(Change Data Capture) enabled
4.The SQL Server agent (MSSQLSERVER) has been started

### What did you see instead?

The full data can be collected. Subsequent operations to add, delete, or modify the table cannot be incremental collected。

![12EBE5C6-213D-45c3-A7A3-CE2D8B168B0B](https://user-images.githubusercontent.com/97231854/220227628-5af30228-24ef-4ff1-8e45-add986086cce.png)
![0058513D-74AF-4b1a-A35D-8EB1E5C1652C](https://user-images.githubusercontent.com/97231854/220227768-9eadcb73-9642-4ef9-8bcd-ac2fa032bf49.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
@echobigdata Please check this table's cdc schema, whether the cdc table have incremental records ?

**Comment by echobigdata** [comment]
> 查看了下表中没有增量记录，后边换了个库可以捕获到增量数据了
