### ISSUE TITLE
mysql master-slave switch, how to synchronize the CDC switch to the master

### ISSUE THREAD

**Issue by zck573693104** [ververica/flink-cdc-connectors#1943]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

When CDC synchronizes data from MySQL, if MySQL's master-slave switch happens at this time, it is not the master library becomes the slave library at the beginning to synchronize data to take, how do you solve it?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
We will make use of GTID set to read the data. And the job will failover.
