### ISSUE TITLE
[Bug] Flink CDC读取mongodb数据， 使用SQL client 报JSON解析异常flink.shaded.jackson2.com.fasterxml.jackson.core.JsonParseException

### ISSUE THREAD

**Issue by YRM2** [ververica/flink-cdc-connectors#1951]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink-1.16.1

### Flink CDC version

flink-2.3.0
flink-sql-connector-mongodb-cdc-2.3.0.jar

### Database and its version

MongoDB server version: 4.4.2

### Minimal reproduce step

1、Centos7安装flink-1.16.1-bin-scala_2.12.tgz
2、flink  lib包下放flink-sql-connector-mongodb-cdc-2.3.0.jar
3、在mongo中创建授权用户
4、使用sql-client.sh进去sql客户端
5、创建表，执行查询sql，报如图错误
![20230228150420](https://user-images.githubusercontent.com/43648673/221779105-e4a7bea6-68d1-4efc-b22a-88a47b18672e.png)

上面执行步骤参考了官方文档https://ververica.github.io/flink-cdc-connectors/master/content/connectors/mongodb-cdc.html

### What did you expect to see?

Flink CDC已mongodb为数据源的读取示例。

### What did you see instead?

Flink SQL> select * from helloabc;
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (org.apache.flink.shaded.netty4.io.netty.buffer.ByteBufInputStream); line: 1, column: 2]

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by syyfffy** [comment]
can u list the file path '/lib'

**Comment by syyfffy** [comment]
show the real data in the mongodb

**Comment by ranjinghang** [comment]
<img width="888" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/33278830/75acba65-9f85-4e37-88e0-2f773007993b">
我也是遇到这个问题，然后我去看到logs 日志，就在flink 安装文件夹下，发现是请求的远程服务器，返回了错误的结果，不是正常的json，返回的html 页面404 . 发现是启动的flink 有一个
StandaloneSessionClusterEntrypoint进程暂停失败 
<img width="593" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/33278830/33f3d258-ed44-4565-b802-a768d5897bad">手动删除这个一直暂停失败的进程，然后重新启动就没有报错了

**Comment by ranjinghang** [comment]
@YRM2 @syyfffy  you can close this issue
