### ISSUE TITLE
[Bug] oracle cdc  开启了provide.transaction.metadata后,flink 任务在获取到变更数据后会直接报错

### ISSUE THREAD

**Issue by DWhite1234** [ververica/flink-cdc-connectors#1957]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.2

### Flink CDC version

2.3.0

### Database and its version

11c

### Minimal reproduce step
       1.第一步配置开启事务元数据
        Properties properties = new Properties();
        properties.setProperty("log.mining.strategy", config.get(ConfigParameters.ONLINE_CATALOG));
        //把oracle的数据统一转成string
        properties.setProperty("decimal.handling.mode", "string");
        //开启事务元数据
        properties.setProperty("provide.transaction.metadata", "true");
        String schemas = config.get(ConfigParameters.SCHEMAS);
        String tables = config.get(ConfigParameters.TABLES);
        DebeziumSourceFunction<String> sourceFunction = OracleSource.<String>builder()
                .hostname(config.get(ConfigParameters.ORACLE_URL))
                .port(config.get(ConfigParameters.ORACLE_PORT))
                .database(config.get(ConfigParameters.DATABASE))
                .schemaList(schemas.split(","))
                .tableList(tables.split(","))
                .username(config.get(ConfigParameters.USERNAME))
                .password(config.get(ConfigParameters.PASSWORD))
                .startupOptions(StartupOptions.latest())
                .debeziumProperties(properties)
                .deserializer(new JsonDebeziumDeserializationSchema())
                .build();
      2.根据断点排查发现这里有问题
<img width="843" alt="Pasted image 20230302165828" src="https://user-images.githubusercontent.com/57745218/222659952-1a90deff-4991-4d36-87a8-af765fbde2b5.png">
这个方法在没有开启事务的时候是正常执行的,
<img width="925" alt="Pasted image 20230302170525" src="https://user-images.githubusercontent.com/57745218/222660105-7ba16159-615b-4371-956c-3925a6d81f15.png">
但是在开启了事务元数据后这里的就变成了
<img width="796" alt="Pasted image 20230302170518" src="https://user-images.githubusercontent.com/57745218/222660242-95b8b381-f329-45a0-b1ac-0f9c0d9e3d1c.png">

最后就导致报错枚举类中的source 字段不合法
<img width="771" alt="Pasted image 20230302165837" src="https://user-images.githubusercontent.com/57745218/222660347-b652c04f-0266-4827-80b3-2b37dd7ff7a0.png">
<img width="610" alt="Pasted image 20230302165823" src="https://user-images.githubusercontent.com/57745218/222660445-4dcc380a-749c-41f3-a158-5bd6db379acb.png">

### What did you expect to see?

<img width="480" alt="image" src="https://user-images.githubusercontent.com/57745218/222393403-4474f724-3222-45b5-b850-bf69c9ae7722.png">
预期事务字段应该有展示,不是null

### What did you see instead?

<img width="1698" alt="image" src="https://user-images.githubusercontent.com/57745218/222393654-92261368-e313-47f2-9cf4-83e94ec10dcc.png">

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
