### ISSUE TITLE
flink-cdc 写入es

### ISSUE THREAD

**Issue by 812406210** [ververica/flink-cdc-connectors#196]
请问，直接写入es,为啥会先删除数据，然后再插入，而且还很慢？

**Comment by leonardBang** [comment]
可以更详细地描述下场景吗？比如具体sql和数据

**Comment by 812406210** [comment]
我用的是flink1.12 ,kafka是0.10 ,好像用不了
![image](https://user-images.githubusercontent.com/22192011/120059337-889a6280-c083-11eb-9794-afae4c75638a.png)
发现没有数据
