### ISSUE TITLE
java.lang.NoSuchMethodError: 'org.apache.flink.table.catalog.CatalogTable org.apache.flink.table.factories.DynamicTableFactory$Context.getCatalogTable()'

### ISSUE THREAD

**Issue by bulolo** [ververica/flink-cdc-connectors#197]
https://www.bilibili.com/video/BV1zt4y1D7kt/
按照步骤最后错误

Flink.  1.13.1

## 问题一
```
Flink SQL> INSERT INTO enriched_orders
> SELECT o.*, p.name, p.description, s.shipment_id, s.origin, s.destination, s.is_arrived
> FROM orders AS o
> LEFT JOIN products AS p ON o.product_id = p.id
> LEFT JOIN shipments AS s ON o.order_id = s.order_id;
```
```
[ERROR] Could not execute SQL statement. Reason:
java.lang.NoSuchMethodError: 'org.apache.flink.table.catalog.CatalogTable org.apache.flink.table.factories.DynamicTableFactory$Context.getCatalogTable()'
```

发现和java的版本好像有关系,但是无论怎么样，最后进入的命令永远跑步起来

**Comment by WenSteven** [comment]
我也碰到了，应该是和jar有关系，主要错误是期望的是方法 `getCatalogTable()`返回`CatalogTable`，但是实际返回了
`ResolvedCatalogTable`

**Comment by bulolo** [comment]
> 我也碰到了，应该是和jar有关系，主要错误是期望的是方法 `getCatalogTable()`返回`CatalogTable`，但是实际返回了
> `ResolvedCatalogTable`

有没有解决方法😭，徘徊了一天

**Comment by leonardBang** [comment]
Hello，能把你们用的jar版本发下吗？应该是connector版本问题，不是java版本

**Comment by bulolo** [comment]
![image](https://user-images.githubusercontent.com/10026498/120303304-4d0ccc00-c301-11eb-90d2-f5c9be10ffc1.png)

**Comment by bulolo** [comment]
> Hello，能把你们用的jar版本发下吗？应该是connector版本问题，不是java版本

![image](https://user-images.githubusercontent.com/10026498/120303343-55650700-c301-11eb-9167-ac2a9314bf12.png)

**Comment by leonardBang** [comment]
sql es 的jar包需要升级到 1.13版本，升级了试下？

**Comment by CHARELS5202011** [comment]
最后咋解决的呀，能否提供下方法，我几个jar包都试过了，还是这个错误

**Comment by drinks5** [comment]
> 最后咋解决的呀，能否提供下方法，我几个jar包都试过了，还是这个错误

https://ververica.github.io/flink-cdc-connectors/master/content/about.html#supported-flink-versions

cdc的版本要合flink的版本匹配

**Comment by bulolo** [comment]
http://junyao.tech/posts/2ebdfea.html

**Comment by cherful** [comment]
各路神仙，请问如何解决的。我现在通过flink1.13.2的sql-client去访问iceberg的数据也是抛这个问题。
依赖包版本如下：flink-connector-hive_2.12-1.13.2.jar
iceberg-flink-runtime-0.12.0.jar。

**Comment by inertance** [comment]
flink1.13.0  对应编译了hudi-0.9_scala-2.11_flink-1.13.0_hive-2.1.1_hadoop-3.0.0.jar 也报这个问题。。。

**Comment by huangxianxin** [comment]
> flink1.13.0 对应编译了hudi-0.9_scala-2.11_flink-1.13.0_hive-2.1.1_hadoop-3.0.0.jar 也报这个问题。。。

一样的场景，我也碰到了

**Comment by AlienationX** [comment]
flink 1.13.6 + flink-connector-mysql-cdc 2.1.1 + hudi 0.9 也报以上错误，各种版本替换 都不行啊。。。。要崩溃了

**Comment by saimigo** [comment]
flink 1.14.2 + flink-connector-hive_2.12-1.14.2.jar + iceberg-flink-runtime-0.12.1.jar 同样的问题！！
请问有解决方案吗

**Comment by leonardBang** [comment]
这个问题和Flink CDC 没关系啊啊啊啊, 上面也给了答案，但是我还是再说一遍吧：
connector 的major版本 需要和 flink 的major版本保持一致，这里的connector是说flink **lib目录下的所有connector**，不只是你们作业里使用到的connector

**Comment by saimigo** [comment]
Update iceberg version from 0.12.1 to 0.13.1, and according to https://github.com/apache/iceberg/issues/4299, change iceberg-flink-runtime 0.13.1 to 
```
<dependency>
  <groupID>org.apache.iceberg</groupID>
  <artifactID>iceberg-flink-1.14</artifactID>
  <version>0.13.1</version>
</dependency>
```
Then it works fine.

**Comment by saimigo** [comment]
> 这个问题和Flink CDC 没关系啊啊啊啊, 上面也给了答案，但是我还是再说一遍吧： connector 的major版本 需要和 flink 的major版本保持一致，这里的connector是说flink **lib目录下的所有connector**，不只是你们作业里使用到的connector

确实是的，我将iceberg 版本从0.12.1升级到0.13.1就好了。

**Comment by wanghai345** [comment]
> 各路神仙，请问如何解决的。我现在通过flink1.13.2的sql-client去访问iceberg的数据也是抛这个问题。 依赖包版本如下：flink-connector-hive_2.12-1.13.2.jar iceberg-flink-runtime-0.12.0.jar。

你好，这个问题解决了吗，是版本的问题的吗

**Comment by cherful** [comment]
> 
我这里把iceberg-flink-runtime包升级就解决了。

**Comment by cherful** [comment]
> > 各路神仙，请问如何解决的。我现在通过flink1.13.2的sql-client去访问iceberg的数据也是抛这个问题。 依赖包版本如下：flink-connector-hive_2.12-1.13.2.jar iceberg-flink-runtime-0.12.0.jar。
> 
> 你好，这个问题解决了吗，是版本的问题的吗

我这里把iceberg-flink-runtime包版本升级就解决了。

**Comment by code-internet** [comment]
![image](https://github.com/apache/flink-cdc/assets/90761309/cdbfd7c1-0ac5-462d-91e7-4d788f6458f5)
崩溃了，啊。这个老六
