### ISSUE TITLE
FlinkSQL执行时候，提示No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

### ISSUE THREAD

**Issue by zzb980881** [ververica/flink-cdc-connectors#1971]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.2

### Flink CDC version

2.3.0

### Database and its version

mysql5

### Minimal reproduce step

通过FlinkSQL连接mysql数据库时报错，报错内容如下：
[ERROR] Could not execute SQL statement. Reason:
javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

通过jdbc连接可以在url添加useSSL=false可以解决，flinkcdc如何处理？有相关参数吗？

还有一个奇怪的现象，create表连接时，如果添加主键就报这个错误，去掉PRIMARY KEY可以执行，这是什么原因？

### What did you expect to see?

正常显示

### What did you see instead?

![image](https://user-images.githubusercontent.com/1118228/223691713-8fe53d4d-9fd3-461f-8a23-c9394380e8db.png)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
