### ISSUE TITLE
Sql-Clinet执行sql时缺乏依赖，耗费了几天时间都没有找全

### ISSUE THREAD

**Issue by zhangzemin2016** [ververica/flink-cdc-connectors#1985]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

先说一下我的操作步骤
1、下载flink包，目前下载过两个，flink-1.13.6-bin-scala_2.12.tgz和flink-1.16.1-bin-scala_2.12.tgz
2、下载flink-connector-mysql-cdc-2.3.0.jar以及文档中提及的包如flink-shaded-hadoop-2-uber-2.7.5-10.0.jar、iceberg-flink-runtime-1.13-0.13.2.jar等，并将它们放到flink安装目录对应的lib包下（我以为这样就可以运行了，实际上这是噩梦的开始）
3、启动flink 执行 bin/start-cluster.sh 启动 sql-client 执行./bin/sql-client.sh embedded（此时正常进入sql cli）
4、执行DDL 
CREATE TABLE user_source (
    database_name STRING METADATA VIRTUAL,
    table_name STRING METADATA VIRTUAL,
    `id` DECIMAL(20, 0) NOT NULL,
    name STRING,
    address STRING,
    phone_number STRING,
    email STRING,
    PRIMARY KEY (`id`) NOT ENFORCED
  ) WITH (
    'connector' = 'mysql-cdc',
    'hostname' = 'mysql',
    'port' = '3306',
    'username' = 'root',
    'password' = '123456',
    'database-name' = 'db_[0-9]+',
    'table-name' = 'user_[0-9]+'
  );
5、执行查询语句 select * from user_source ; 噩梦也就从这时开始了
一连串依赖缺少，找一个测试一个，不断的出错，耗费数个小时，依旧还是一直出错，我不知道是否有什么地方会列出需要的依赖清单，只有无休止的找jar包，然后测试，出错，继续不断循环的做这件事情。
综上所述，希望后面能将依赖都整合好，因为缺乏的依赖实在是太多太多了，像是无底洞一样，怎么都看不到成功的希望

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by gaotingkai** [comment]
please refer: 
https://ververica.github.io/flink-cdc-connectors/release-2.3/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/build-real-time-data-lake-tutorial-zh.html

If you just want to experience quickly, please use docker compose, It contains all jars

If you need to test in your own Flink environment refer to the figure below

<img width="910" alt="image" src="https://user-images.githubusercontent.com/34996528/225250449-ca36264d-582f-4d3d-b788-34199e588085.png">

Flink connector jar package difference refer to the figure below

<img width="971" alt="image" src="https://user-images.githubusercontent.com/34996528/225251071-d0dd7906-56b9-40b0-9439-80f4290a8dc1.png">

**Comment by zhangzemin2016** [comment]
Thank you, but according to this document, there is still a lack of dependency. The jar package is flink-connector-jdbc-3.0.0-1.16.jar

**Comment by HongYangZheng** [comment]
meeto i have add these jars, but still meet other problems;

![Uploading QQ截图20230506164633.png…]()
