### ISSUE TITLE
[Bug][Doc] The chunk-meta.group.size option is missing in the documentation for MongoDB CDC description

### ISSUE THREAD

**Issue by e-mhui** [ververica/flink-cdc-connectors#1986]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13.5

### Flink CDC version

2.3

### Database and its version

none.

### Minimal reproduce step

noen.

### What did you expect to see?

Add chunk-meta.group.size option in the documentation for MongoDB CDC

### What did you see instead?

none.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Jiabao-Sun** [comment]
Thanks @e-mhui for reporting this issue.
The configuration "chunk-meta.group.size" has no effect on the MongoDB connector, so we don't need to add it.
