### ISSUE TITLE
[Bug][Doc] Remove duplicate 'batch.size' options

### ISSUE THREAD

**Issue by e-mhui** [ververica/flink-cdc-connectors#1989]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13.5

### Flink CDC version

2.3, master

### Database and its version

none

### Minimal reproduce step

none

### What did you expect to see?

none

### What did you see instead?

none

### Anything else?

none

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Jiabao-Sun** [comment]
Closed by #1990
