### ISSUE TITLE
table-name能否支持正则匹配

### ISSUE THREAD

**Issue by zhouzach** [ververica/flink-cdc-connectors#20]
存储在mysql中的用户表，业务那边做了分表，分了100份，比如user_00,user_01,...,user_99,mysql-cdc的table-name能否支持正则匹配，一个flink table同时监测100个mysql表

**Comment by wuchong** [comment]
支持的。你可以填 `'table-name' = 'user_*'`.

**Comment by wuchong** [comment]
I have added this to the [FAQ](https://github.com/ververica/flink-cdc-connectors/wiki/MySQL-CDC-Connector#faq).
