### ISSUE TITLE
[Bug] 联合主键表，数据量较大，单个分片容量过大，内存被撑爆

### ISSUE THREAD

**Issue by damenghgk** [ververica/flink-cdc-connectors#2011]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink1.16

### Flink CDC version

flink cdc 2.3

### Database and its version

MySQL 8.0x

### Minimal reproduce step

create table (col1 int, col2 int, col3 int, col4 ......, primary key(col1, col2, col3))
insert 100000000 rows;
MySqlSourceBuilder.chunkKeyColumn("col1");
col1 values(1,2,3,4,5,6,7,8,9,10)
out of memory

### What did you expect to see?

data synchronized

### What did you see instead?

Error: out of memory

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
