### ISSUE TITLE
[Bug] TM hangs because of OOM and the job doesn't exit

### ISSUE THREAD

**Issue by ruanhang1993** [ververica/flink-cdc-connectors#2016]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.2

### Flink CDC version

2.3.0

### Database and its version

mysql 5.7

### Minimal reproduce step

TM occurs OOM error.

### What did you expect to see?

The job fails and exits.

### What did you see instead?

The job does not exit.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by syyfffy** [comment]
Please show the TM log
