### ISSUE TITLE
为什么要阻止sqlserver数据库做checkpoint

### ISSUE THREAD

**Issue by xiaohuazi123** [ververica/flink-cdc-connectors#2047]
### Search before asking

- [x] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

问一下，sqlserver cdc connector，刚初始化时候，connector会阻止数据库做checkpoint是不是这个意思？
为什么要阻止数据库做checkpoint，不是太明白
https://github.com/ververica/flink-cdc-connectors/blob/master/docs/content/connectors/sqlserver-cdc.md
![image](https://user-images.githubusercontent.com/45115671/227859716-5468418b-8891-4b48-b87d-79da29a60c37.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
If the savepoint is generated in the  snapshot phase, the sqlserver cdc connector cannot recover from a savepoint rightly.
So the checkpoint will be hold until the snapshot phase finishes.
