### ISSUE TITLE
Add support for connection.string property in the MongoDB CDC Connector

### ISSUE THREAD

**Issue by tonycombocurve** [ververica/flink-cdc-connectors#2049]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

[MongoDB Atlas](https://www.mongodb.com/atlas) has a new and better way to connect to a cluster. It would be easier to support this feature by adding a **connection.string** property similar to what is done in [Debezium MongoDB Connector](https://debezium.io/documentation/reference/2.1/connectors/mongodb.html#mongodb-property-mongodb-connection-string).

### Solution

Add a **connection.string** property so that the user can generate it from a template so it is easy to support newer versions of MongoDB. The generated connection string would look like this:
```
mongodb+srv://<username>:<password>@mycluster.gcp.mongodb.net/?retryWrites=true&w=majority
```

### Alternatives

As an alternative you could add a **connection.protocol** property so that you support the new protocol promoted by MongoDB. See this post for more details:https://www.mongodb.com/developer/products/mongodb/srv-connection-strings/

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ai-smalleryu** [comment]
please assign me

**Comment by Jiabao-Sun** [comment]
Thanks @asimansu.
Please feel free to submit a pull request.
