### ISSUE TITLE
[Bug] oralce 19c CONTINOUS_MINE is desupported

### ISSUE THREAD

**Issue by hbdrawn** [ververica/flink-cdc-connectors#2050]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.6

### Flink CDC version

2.3.0

### Database and its version

oracle 19c

### Minimal reproduce step

java.sql.SQLException: ORA-00308: cannot open archived log '/data/oradata/arch/1_5709_1070298155.dbf'

debeziumProperties.setProperty("log.mining.continuous.mine", "true");
Caused by: java.sql.SQLException: ORA-44609: CONTINOUS_MINE is desupported for use with DBMS_LOGMNR.START_LOGMNR.

### What did you expect to see?

support the scene 

### What did you see instead?

not support 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by MaoHJ-Official** [comment]
请参考 debezium 配置 https://github.com/debezium/debezium/blob/v1.6.4.Final/debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java#L135
oracle 19c 之后，DBMS_LOGMNR.START_LOGMNR 不再接收参数 CONTINOUS_MINE，此时使用 debezium 需要配置 "log.mining.continuous.mine"="false"

**Comment by supercena** [comment]
同样的问题 oracle 19c ，配置"log.mining.continuous.mine"="false" 获取不到数据

**Comment by cooltnt** [comment]
我用flink sql方式, 在with中增加后不报错, 可同步数据
'debezium.log.mining.continuous.mine'='false'

**Comment by GOODBOY008** [comment]
@hbdrawn Oracle 19c do not support continuous mine.
