### ISSUE TITLE
Consolidate connection properties so that they are not repeated on every MongoDB CDC table

### ISSUE THREAD

**Issue by tonycombocurve** [ververica/flink-cdc-connectors#2051]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Here is the configuration for a MongoDB CDC table:
```
CREATE TABLE products (
  _id STRING, // must be declared
  name STRING,
  weight DECIMAL(10,3),
  tags ARRAY<STRING>, -- array
  price ROW<amount DECIMAL(10,2), currency STRING>,
  suppliers ARRAY<ROW<name STRING, address STRING>>,
  PRIMARY KEY(_id) NOT ENFORCED
) WITH (
  'connector' = 'mongodb-cdc',
  'hosts' = 'localhost:27017,localhost:27018,localhost:27019',
  'username' = 'flinkuser',
  'password' = 'flinkpw',
  'database' = 'inventory',
  'collection' = 'products'
);
```
Most of the properties in the WITH clause have to be repeated for each table.

### Solution

Allow these duplicated properties to be defined when [creating the database](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/create/#create-database) that contains the tables:
```
CREATE DATABASE my_cdc_db
   WITH (
      'connector' = 'mongodb-cdc',
      'hosts' = 'localhost:27017,localhost:27018,localhost:27019',
      'username' = 'flinkuser',
      'password' = 'flinkpw'
)
```
Then you could create the tables in that database and inherit the connection properties:
```
CREATE TABLE my_cdc_db.products (
  _id STRING, // must be declared
  name STRING,
  weight DECIMAL(10,3),
  tags ARRAY<STRING>, -- array
  price ROW<amount DECIMAL(10,2), currency STRING>,
  suppliers ARRAY<ROW<name STRING, address STRING>>,
  PRIMARY KEY(_id) NOT ENFORCED
) WITH (
  -- No connection properties needed here!
  'database' = 'inventory',
  'collection' = 'products'
);
```
This will make maintenance much easier since all of the connection related properties can be changed in 1 place.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Jiabao-Sun** [comment]
Thanks @tonycombocurve for your suggestion.
The create statement depends on Flink SQL, at present, this optimization item cannot be solved in the flink-cdc project.

In some development tools, some variable injection functions are often provided.
I think we can temporarily use this method to reduce the complexity of parameter passing.

```sql
def mongo_conn: 
"""
      'connector' = 'mongodb-cdc',
      'hosts' = 'localhost:27017,localhost:27018,localhost:27019',
      'username' = 'flinkuser',
      'password' = 'flinkpw'
"""

CREATE TABLE my_cdc_db.products (
  _id STRING, // must be declared
  name STRING,
  weight DECIMAL(10,3),
  tags ARRAY<STRING>, -- array
  price ROW<amount DECIMAL(10,2), currency STRING>,
  suppliers ARRAY<ROW<name STRING, address STRING>>,
  PRIMARY KEY(_id) NOT ENFORCED
) WITH (
  ${mongo_conn},
  'database' = 'inventory',
  'collection' = 'products'
);
```

By the way, if we don't want to define the table repeatedly in each task, we can use the function of flink metastore.

**Comment by tonycombocurve** [comment]
@Jiabao-Sun 

Thanks for your reply. Can you please elaborate on what you said at the end of your message?

> By the way, if we don't want to define the table repeatedly in each task, we can use the function of flink ~metastore~ catalog.

What do you mean by Flink catalog?

-Tony
