### ISSUE TITLE
mongo-cdc support fullDocumentBeforeChange actions with mongo:6.0

### ISSUE THREAD

**Issue by syyfffy** [ververica/flink-cdc-connectors#2062]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

fullDocumentBeforeChange can show the data before deleting data.

### Solution

use the fullDocumentBeforeChange's data to distinction data

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Jiabao-Sun** [comment]
Thanks @syyfffy.
I think this is a good improvement.

**Comment by yuxiqian** [comment]
Is there any updates here? I'm willing to help implementing this feature if needed.

**Comment by syyfffy** [comment]
> Is there any updates here? I'm willing to help implementing this feature if needed.

u can ask the  schedule for @Jiabao-Sun

**Comment by Jiabao-Sun** [comment]
Thanks @yuxiqian.
Assigned to you.
