### ISSUE TITLE
[Bug] flink1.15.3 cdc2.3.0 oracle 无主键的表无法获取完整数据

### ISSUE THREAD

**Issue by LiaoMinYu** [ververica/flink-cdc-connectors#2071]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.3

### Flink CDC version

2.3.0

### Database and its version

Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production

### Minimal reproduce step

source:orale,sink:hudi 表没有主键,但有unique，开启了数据库级最小补充日志，表级为补充日志为all,在taskmaneger的日志是可以看到行总数：156，但是通过flinksql-client通过select * from table(cdc的映射表) 只能获取到一条数据，以及通过代码的方式在本地运行，也是只输出一条数据，同步到hudi的数据也是只有一条，但是当cdc版本切换2.2.1版本时，是可以输出完整数据的，请问这个是什么问题呢，现在只要oracle中的表没有主键，都无法获取完整数据，都是只读取到一条。hudi也是只有一条数据，有主键的却又是正常的

<img width="697" alt="03C15EE6-F9C7-4573-9C1B-0F98639DBC89" src="https://user-images.githubusercontent.com/40682369/230537006-1f43c131-4912-4506-acac-b7734a8cdf4c.png">

<img width="1119" alt="taskmaneger" src="https://user-images.githubusercontent.com/40682369/230537023-6e9f6e79-2569-4842-85d9-ffd0c99c8add.png">

<img width="499" alt="flinksql-client" src="https://user-images.githubusercontent.com/40682369/230537041-edefd413-a2cc-45d7-b188-9db1a34c57ad.png">

<img width="1216" alt="2 3 0-demo" src="https://user-images.githubusercontent.com/40682369/230537057-f5f1750e-5392-4b5e-a34f-31f279f1cb30.png">

<img width="877" alt="2 2 1-demo" src="https://user-images.githubusercontent.com/40682369/230537067-8185a0e9-3237-41eb-aef5-8cd3762d1b35.png">

### What did you expect to see?

flink 1.15.3 cdc 2.3.0 可以获取完整数据

### What did you see instead?

无法获取完整数据

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by LiaoMinYu** [comment]
cdc 2.3.0增量快照是默认开启的，而增量快照是依赖主键的，没有主键的情况下，需要关闭增量快照模式 scan.incremental.snapshot.enabled = false

**Comment by gongzexin** [comment]
> 



> cdc 2.3.0增量快照是默认开启的，而增量快照是依赖主键的，没有主键的情况下，需要关闭增量快照模式 scan.incremental.snapshot.enabled = false

这个参数支持在datastream中设置吗？没有找到对应设置该参数的方法。

**Comment by LiaoMinYu** [comment]
> > 
> 
> > cdc 2.3.0增量快照是默认开启的，而增量快照是依赖主键的，没有主键的情况下，需要关闭增量快照模式 scan.incremental.snapshot.enabled = false
> 
> 这个参数支持在datastream中设置吗？没有找到对应设置该参数的方法。
这个参数不是cdc的，是debezium 1.6.4的，所以应该都是支持的

**Comment by LinwangFan** [comment]
请问这个问题解决了吗？我也遇到同样的问题了，Oracle无主键的表只同步了一条数据，当cdc版本降到2.2.1版本时可以同步所有的数据
