### ISSUE TITLE
oracle no primary key table Data is lost in full phase

### ISSUE THREAD

**Issue by jeehe88** [ververica/flink-cdc-connectors#2073]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14

### Flink CDC version

2.3.0

### Database and its version

Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production

### Minimal reproduce step

1、Create a table with no primary key
CREATE TABLE "CDC"."TEST" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100), 
	"AGE" NUMBER(38,0)
   )
2、Use oracle-cdc
        Properties properties = new Properties();
        properties.setProperty("database.connection.adapter", "logminer");
        properties.setProperty("log.mining.strategy", "online_catalog");
        properties.setProperty("database.tablename.case.insensitive", "false");

        Properties debeziumProperties = new Properties();
        debeziumProperties.setProperty("log.mining.strategy", "online_catalog");
        debeziumProperties.setProperty("database.tablename.case.insensitive", "false");

        OracleSourceBuilder<String> oracleChangeEventSource =
                new OracleSourceBuilder()
                        .hostname("xxxxxx")
                        .port(1521)
                        .databaseList("orcl")
                        .schemaList("CDC")
                        .tableList("CDC.TEST")
                        .username("cdc")
                        .password("xxxx")
                        .debeziumProperties(debeziumProperties)
                        .deserializer(new JsonDebeziumDeserializationSchema())
                        .startupOptions(StartupOptions.initial());
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.fromSource(
                        oracleChangeEventSource.build(),
                        WatermarkStrategy.noWatermarks(),
                        "OracleParallelSource")
                .setParallelism(1)
                .print()
                .setParallelism(1);
        env.execute("Print Oracle Snapshot + RedoLog");
3、A lot of data is missed in the full phase, and no error is reported

### What did you expect to see?

data in the full phase is obtained normally

### What did you see instead?

data in the full phase is obtained normally

### Anything else?

The 126 rows of IncrementalSourceScanFetcher class are deduplicated. When there is no primary key, the key value is null, resulting in data loss

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by CabbageDu** [comment]
请问此问题是否已解决？

**Comment by CabbageDu** [comment]
用cdc3.0为什么还存在这个问题？
