### ISSUE TITLE
[Bug]  含有default的值的字段同步过程中数据不准确

### ISSUE THREAD

**Issue by WuChongYong** [ververica/flink-cdc-connectors#2084]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

13.6

### Flink CDC version

2.2.1

### Database and its version

mysql 8.0.18

### Minimal reproduce step

CREATE TABLE `test_bit` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `f1_bit1` bit(1) DEFAULT NULL COMMENT 'f1_bit1',
  `f1_bit10` bit(10) DEFAULT NULL COMMENT 'f1_bit10',
  `f1_tinyint1` tinyint(1) DEFAULT '1' COMMENT '0未全部签署1已全部签署',
  `f1_tinyint4` tinyint(4) DEFAULT '0' COMMENT '0=未扣缴（默认），1=已扣缴，2=欠缴',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

INSERT INTO test.test_bit
(id,f1_tinyint1,f1_tinyint4)
VALUES(29,null,null);

### What did you expect to see?

cdc 同步解析后的f1_tinyint1，f1_tinyint1的值应当为null，f1_tinyint4的值应当为null

### What did you see instead?

但cdc 解析出来的f1_tinyint1为默认值1，f1_tinyint4的默认值为0

### Anything else?

初始化过程中，有默认值的字段，数据为null，初始化时候是null，是正确的；初始化完成后，然后插入的数据为null，但cdc解析出来为默认值，是有问题的；在初始化完成后，程序发生故障（debug超时）造成重连数据源，插入的值为null，cdc解析的结果为null，是正确的；有三种不同的数据呈现情况

初始化完成后的的映射信息：
Tables {
  test.test_bit: {
    columns: {
      id BIGINT(20) NOT NULL AUTO_INCREMENTED GENERATED
      f1_bit1 BIT(1) DEFAULT VALUE NULL
      f1_bit10 BIT(10) DEFAULT VALUE NULL
      f1_tinyint1 TINYINT(1) DEFAULT VALUE 1
      f1_tinyint4 TINYINT(4) DEFAULT VALUE 0
    }
    primary key: [id]
    default charset: utf8mb4
  }
}
初始化和故障重连的映射信息：
Tables {
  test.test_bit: {
    columns: {
      id BIGINT(20) NOT NULL AUTO_INCREMENTED GENERATED
      f1_bit1 BIT(1) DEFAULT VALUE NULL
      f1_bit10 BIT(10) DEFAULT VALUE NULL
      f1_tinyint1 TINYINT(1) DEFAULT VALUE NULL
      f1_tinyint4 TINYINT(4) DEFAULT VALUE NULL
    }
    primary key: [id]
    default charset: utf8mb4
  }
}

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by z-haohao** [comment]
How are you going to solve this problem? I have encountered a similar problem.

**Comment by WuChongYong** [comment]
schema重新实现column实体，把默认值替换成null

**Comment by LJunJoy** [comment]
I also have this issue and hope someone can solve it.

**Comment by LJunJoy** [comment]
> schema重新实现column实体，把默认值替换成null

有具体的实现示例嘛，求救

**Comment by WuChongYong** [comment]
有的，要实现好几个类，改代码



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月10日 17:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ververica/flink-cdc-connectors] [Bug]  含有default的值的字段同步过程中数据不准确 (Issue #2084) |

schema重新实现column实体，把默认值替换成null

有具体的实现示例嘛，求救

**Comment by LJunJoy** [comment]
> 有的，要实现好几个类，改代码
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年09月10日 17:24 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ververica/flink-cdc-connectors] [Bug] 含有default的值的字段同步过程中数据不准确 (Issue #2084) | schema重新实现column实体，把默认值替换成null 有具体的实现示例嘛，求救 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

可以分享一下不，真心感谢

**Comment by WuChongYong** [comment]
有的，要实现好几个类，改代码
这是其中一个核心代码
Column newColumn =
                            new ColumnImpl(
                                    column.name(),
                                    column.position(),
                                    column.jdbcType(),
                                    column.nativeType(),
                                    column.typeName(),
                                    column.typeExpression(),
                                    column.charsetName(),
                                    null,
                                    column.length(),
                                    !column.scale().isPresent() ? null : column.scale().get(),
                                    column.isOptional(),
                                    column.isAutoIncremented(),
                                    column.isGenerated(),
                                    null,
                                    column.hasDefaultValue());
                    column = newColumn;



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月10日 17:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ververica/flink-cdc-connectors] [Bug]  含有default的值的字段同步过程中数据不准确 (Issue #2084) |

schema重新实现column实体，把默认值替换成null

有具体的实现示例嘛，求救

**Comment by z070204z** [comment]
我今天也遇到了这个问题，其实很简单，在JsonDeserializationSchema自定义反序列化器的时候
Struct midStr = (Struct) value.get(type);
Object fieldValue = midStr.get(field.name())；//这里获取的值，是带默认值的
改成
Object fieldValue = midStr.getWithoutDefault(field.name()); //使用getWithoutDefault这个方法即可

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
