### ISSUE TITLE
[Bug] use mongo-cdc connector sync date type  data to es example error

### ISSUE THREAD

**Issue by arvin-o-o** [ververica/flink-cdc-connectors#2085]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.4

### Flink CDC version

2.3.0

### Database and its version

mongodb: 4.0.16

### Minimal reproduce step

CREATE TABLE orders (
   _id STRING,
   order_id INT,
   order_date TIMESTAMP_LTZ(3),
   customer_id INT,
   price DECIMAL(10, 5),
   product ROW<name STRING, description STRING>,
   order_status BOOLEAN,
   PRIMARY KEY (_id) NOT ENFORCED
 ) WITH (
   'connector' = 'mongodb-cdc',
   'hosts' = 'localhost:27017',
   'username' = 'mongouser',
   'password' = 'mongopw',
   'database' = 'mgdb',
   'collection' = 'orders'
 );

CREATE TABLE enriched_orders (
   order_id INT,
   order_date TIMESTAMP_LTZ(3),
   customer_id INT,
   price DECIMAL(10, 5),
   product ROW<name STRING, description STRING>,
   order_status BOOLEAN,
   customer_name STRING,
   customer_address STRING,
   PRIMARY KEY (order_id) NOT ENFORCED
 ) WITH (
     'connector' = 'elasticsearch-7',
     'hosts' = 'http://localhost:9200',
     'index' = 'enriched_orders'
 );

INSERT INTO enriched_orders
 SELECT o.order_id,
        o.order_date,
        o.customer_id,
        o.price,
        o.product,
        o.order_status,
        c.name,
        c. address
   FROM orders AS o
   LEFT JOIN customers AS c ON o.customer_id = c.customer_id;

### What did you expect to see?

I expect have some record in Elasticsearch, and field "order_date" mapping type as `date`

### What did you see instead?

I`m executed step, then field "order_date" mapping type as `text`

### Anything else?

When I use create index in Elasticsearch, use `order_date` mapping type as `date`, and  Flink SQL let order_date type as `STRING`, and  executed, I`m successed.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Jiabao-Sun** [comment]
By default, all fields synchronized to ES will be of type STRING.
If type constraints are required, the index needs to be manually created in ES.
