### ISSUE TITLE
Unable to create a source for reading table

### ISSUE THREAD

**Issue by Owenmessizz** [ververica/flink-cdc-connectors#209]
when i use the cdc connector in flink1.13 and try to create the cdc table，i am using pyflink and flink sql. then i got this error：

py4j.protocol.Py4JJavaError: An error occurred while calling o7.executeSql.
: org.apache.flink.table.api.ValidationException: Unable to create a source for reading table 'default_catalog.default_database.test_lecture'.
Table options are:
'connector'='mysql-cdc'
'database-name'='xxxx'
'hostname'='xxxxx'
'password'='xxxx'
'port'='3306'
'table-name'='xxxx'
'username'='xxxx'
.....
Caused by: java.lang.NoSuchMethodError: org.apache.flink.table.factories.DynamicTableFactory$Context.getCatalogTable()Lorg/apache/flink/table/catalog/CatalogT
able;

i've tried to run the same code in flink 1.12 in the same way, it works,
so can anyone help me with this problem? thx

**Comment by Owenmessizz** [comment]
i've build the latest version of the connector and put it into my program, then it works!

**Comment by purechilde** [comment]
@Owenmessizz hello, I have encountered the same problem as you. Have you resolved it? my flink version is 1.15.2,flink-sql-connector-oracle-cdc-2.4.1,the connector is the latest version, but it do not work
