### ISSUE TITLE
[Bug] Oracle oracle.net.ns.NetException: Got minus one from a read call

### ISSUE THREAD

**Issue by zhangwl9** [ververica/flink-cdc-connectors#2091]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.1

### Flink CDC version

2.3.0

### Database and its version

oracle:11g

### Minimal reproduce step

使用flinkcdc读取oracle中100w的全量数据，程序执行一段时间，直接报错：
<img width="1143" alt="56d9b0b4700a986577ce72907693ac3" src="https://user-images.githubusercontent.com/28597328/232983706-45264495-eb6b-4bba-92d1-8fa85a021f7f.png">
当降低flink的并发，程序不报错，但是读取oracle的数据，延迟超级慢，100w条数据，全部读取完毕，需要2个多小时；
增大oracel的连接数，也没用

### What did you expect to see?

no

### What did you see instead?

no

### Anything else?

no

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by rbreejen** [comment]
This error seems to be due to a Docker proxy bug. In my case I solved it by using the [solution](https://stackoverflow.com/a/73150106) by malloc4k. I think it will work for container-registry.oracle.com/database/x images with version <= 21. New Oracle docker images will have this [fixed](https://github.com/oracle/docker-images/issues/2672).

> The fix was to log in into the container and modify sqlnet.ora in the following way:
> ```
> echo "DISABLE_OOB=ON" >> /opt/oracle/oradata/dbconfig/XE/sqlnet.ora
> ```
> and restart the container.

**Comment by GOODBOY008** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
