### ISSUE TITLE
[Oracle CDC] Use primary key as chunk key

### ISSUE THREAD

**Issue by e-mhui** [ververica/flink-cdc-connectors#2093]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

[Oracle CDC] Use primary key as chunk key

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Supported by pr https://github.com/ververica/flink-cdc-connectors/pull/2976 .
