### ISSUE TITLE
Read from specific MySQL Binlog position

### ISSUE THREAD

**Issue by Superainbower** [ververica/flink-cdc-connectors#21]
Does flink-cdc-connectors support configue mysql binlog position?

**Comment by wuchong** [comment]
Currently, it is not supported. Feel free to contribute :)

**Comment by wuchong** [comment]
Fixed in befb4adbd9d598f6ee2c64ab585196e3960f055d

**Comment by hushuiwang** [comment]
@wuchong 你好，我们生产
 Connector last known GTIDs are 0f26f321-9c39-11eb-bd94-043f72d8bdae:1-649435898,3f6645a0-1859-11ed-a419-b02628437420:1-1422544843,5a708966-7b33-11eb-bee5-b8599fe78491:1-454976300,9052647d-cfdd-11eb-805a-0c42a136700d:1-61724,99e061e5-b933-11eb-ade7-b02628435bb0:1-2029507171,a9c565bf-82d5-11e9-a939-246e9677024a:1-20762503,b60d32c7-82d5-11e9-8793-246e967649ca:1-1627324,ca53398f-0a0b-11ec-9b0b-0c42a1499c24:1-7906323934,d5516970-f296-11e9-a943-246e96765818:1-1128695945,e69cd1a6-0a0c-11ec-9e70-0c42a13662d8:1-113690,ef6cc78b-0a0b-11ec-b245-b02628630b20:1-3,fe19d3d8-2322-11eb-887a-0c42a1642115:1-693626810, but MySQL has 0f26f321-9c39-11eb-bd94-043f72d8bdae:1-649435898,3f6645a0-1859-11ed-a419-b02628437420:1-1505313905,5a708966-7b33-11eb-bee5-b8599fe78491:1-454976300,9052647d-cfdd-11eb-805a-0c42a136700d:1-61724,99e061e5-b933-11eb-ade7-b02628435bb0:1-2029507171,a9c565bf-82d5-11e9-a939-246e9677024a:1-20762503,b60d32c7-82d5-11e9-8793-246e967649ca:1-1627324,

 The connector is trying to read binlog starting at Struct{version=1.5.4.Final,connector=mysql,name=mysql_binlog_source,ts_ms=1665575615807,db=,server_id=0,file=mysql-bin.029467,pos=4358156,row=0}, but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.
从日志看，尽管是gtid的模式下，connector 任然感觉了binlog文件名去找，因此找不到binlog，因为新节点的binlog文件是不一致的，请问这是有什么好的解决办法吗
