### ISSUE TITLE
将数据从kafka读出，kafka部分数据有脏数据，导致入postgres失败，导致job任务一直处于重启状态

### ISSUE THREAD

**Issue by wanezu** [ververica/flink-cdc-connectors#2101]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

`	Caused by: java.sql.BatchUpdateException: Batch entry 3 INSERT INTO a(corp_address, corp_type_code) VALUES ('湖北省武汉市洪山区欢乐大道特一号德成国贸中心湖北省武汉市洪山区欢乐大道特一号德成国贸中心B1层??D区06-1号商铺', '900159') ON CONFLICT (corp_type_code) DO UPDATE SET corp_address=EXCLUDED.corp_address, corp_type_code=EXCLUDED.corp_type_code was aborted: ERROR: invalid byte sequence for encoding "UTF8": 0x00  Call getNextException to see other errors in the batch.`
将数据从kafka读出，kafka部分数据有脏数据，导致入postgres失败，导致job任务一直处于重启状态，如何跳过这一条数据，不会导致队列堵塞

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by wanezu** [comment]
![image](https://user-images.githubusercontent.com/7490236/233840099-38384fe5-7d3e-447d-aca1-392ca6ccfa3b.png)

**Comment by ruanhang1993** [comment]
It is not a problem in cdc connectors. Close the issue.
