### ISSUE TITLE
[Bug] flink sql runs well in java table env code, but it runs wrong in sql-client mode

### ISSUE THREAD

**Issue by HongYangZheng** [ververica/flink-cdc-connectors#2113]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13.6

### Flink CDC version

2.2.1

### Database and its version

msyql 5.7
doris 0.15

### Minimal reproduce step

I run the sql code in java with table environment ,everything goes well.
after i run them in sql-client mode, i cant see any data write to the doris.
Then i just run code that created source of mysql-cdc, and then i use select statement but no data get, also the logs from sql-client did not show any exception. I think cdc did not run chunk step but i dont know how to resolve it. 

### What did you expect to see?

Data write to sink

### What did you see instead?

no data write to sink

### Anything else?

If i use java code with table environment it works.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by HongYangZheng** [comment]
here is the simplified code 


set $internal.deployment.config-dir='/root/flink-1.13.6/conf';
set $internal.yarn.log-config-file='/root/flink-1.13.6/conf/log4j.properties';

SET 'execution.checkpointing.interval' = '300s';
SET 'execution.attached' = 'false';

CREATE TABLE cdc_order_info ( 
id BIGINT, 
.....
PRIMARY KEY (id) NOT ENFORCED 
) with (
    'connector' = 'mysql-cdc',
    'hostname' = 'sourcehost',
    'port' = '3306',
    'username' = '',
    'password' = '',
    'database-name' = 'db',
    'table-name' = 'table',
    'server-id' = '6208-6250',
    'scan.startup.mode' = 'initial',
    'server-time-zone' = 'Asia/Shanghai',
    'jdbc.properties.useSSL' = 'false',
    'debezium.snapshot.locking.mode' = 'none',
    'scan.incremental.snapshot.chunk.size' = '25'
);
CREATE TABLE doris_order_info ( 
id BIGINT, 
.....
) with ( 
  'connector' = 'doris', 
  'fenodes' = 'feip', 
  'table. Identifier' = 'db.table', 
  'username' = 'user', 
  'password' = '', 
  'sink.batch.size' = '10000', 
  'sink.batch.interval' = '20s', 
  'sink.properties.format' = 'json', 
   'sink.properties.function_column.sequence_col' = 'update_time' ,
  'sink.properties.strip_outer_array' = 'true', 
  'sink.enable-delete' = 'true' );

insert into doris_order_info 
select 
    * 
from cdc_order_info;



here i omit some information useless;

**Comment by ruanhang1993** [comment]
If you submit the sql to your mini cluster, you could find the job in http://localhost:8081/. And you will get more information about it in the JM/TM logs.

If the problem still exists, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
