### ISSUE TITLE
[Bug] ob-oracle用flinkcdc抽取nvarchar字段乱码

### ISSUE THREAD

**Issue by wanyujichun** [ververica/flink-cdc-connectors#2114]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

版本：flink-connector-oceanbase-cdc-2.3.0 / OB 3.2.2
<img width="1402" alt="截屏2023-05-06 15 19 19" src="https://user-images.githubusercontent.com/8925285/236616523-5295b2a8-e4af-4f0b-8bcd-29e44a98f4c9.png">

### Flink CDC version

flink-connector-oceanbase-cdc-2.3.0

### Database and its version

3.2.2

### Minimal reproduce step

insert nvarchar 字段中文

### What did you expect to see?

乱码

### What did you see instead?

。。。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by whhe** [comment]
Will try to fix it in #1854
