### ISSUE TITLE
[Bug]  RichSinkFunction  method invoke can‘t execute

### ISSUE THREAD

**Issue by kpioneer123** [ververica/flink-cdc-connectors#2121]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

2.15.4

### Flink CDC version

2.3.0

### Database and its version

        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>9.2.1.jre8</version>
        </dependency>

### Minimal reproduce step

RichSinkFunction  method invoke can‘t execute
but
SinkFunction  method invoke can  execute

    @Override
    public void invoke(String value, Context context) throws Exception {

}

### What did you expect to see?

RichSinkFunction  method invoke can execute

### What did you see instead?

RichSinkFunction  method invoke can execute

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by kpioneer123** [comment]
<flink.version>1.15.2</flink.version> 

<dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-java</artifactId>
            <version>${flink.version}</version>
            <scope>provided</scope>
        </dependency>

 
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.11</version>
        </dependency>


        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table</artifactId>
            <version>${flink.version}</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>


      
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-common</artifactId>
            <version>${flink.version}</version>
            <scope>provided</scope>
        </dependency>


        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-json</artifactId>
            <version>${flink.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-shaded-guava</artifactId>
            <version>30.1.1-jre-15.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-clients</artifactId>
            <version>${flink.version}</version>
        </dependency>

**Comment by gaotingkai** [comment]
Flink cdc is a flink source connector. Please go to the corresponding community to report the sink component.
