### ISSUE TITLE
[Bug] flink mysql cdc repeatly sync  data

### ISSUE THREAD

**Issue by lijunkai** [ververica/flink-cdc-connectors#2136]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16

### Flink CDC version

2.3

### Database and its version

mysql  5.7.11-log

### Minimal reproduce step

i don't know how to reproduce, i just sync one table in a seperate dataStream  union with other dataStream
my code is below!

![image](https://github.com/ververica/flink-cdc-connectors/assets/26005541/b387b329-dfd4-4d12-8e3f-789dc60848b4)

### What did you expect to see?

the same data accurs exactly once

### What did you see instead?

the same data accurs in both  full sync stage  and Incremental  sync stage

### Anything else?

![image](https://github.com/ververica/flink-cdc-connectors/assets/26005541/606411e8-274b-44c0-af31-0aa8105edb63)
CREATE TABLE `tbl_test` (
  `id` INT NOT NULL,
  `purchase_date` TIMESTAMP(0),
  `created_at` TIMESTAMP(0),
  `updated_at` TIMESTAMP(0),
  `processing_time` AS PROCTIME(),
  `offset` BIGINT METADATA VIRTUAL,
  `event_time` TIMESTAMP(3) METADATA FROM 'value.source.timestamp' VIRTUAL,
  `ts` TIMESTAMP(3) METADATA FROM 'timestamp',
  WATERMARK FOR `purchase_date` AS `purchase_date`,
  CONSTRAINT `PK_3386` PRIMARY KEY (`id`) NOT ENFORCED
) COMMENT 'tbl_test???'
WITH (
  'properties.isolation.level' = 'read_committed',
  'properties.bootstrap.servers' = 'hdfs-node01:9092,hdfs-node02:9092,hdfs-node03:9092',
  'connector' = 'kafka',
  'topic' = 'ods.test_db.tbl_test',
  'scan.startup.mode' = 'earliest-offset',
  'value.format' = 'debezium-json',
  'properties.group.id' = 'group_test'
);

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
If the problem still exists, please re-create your issue in English on Apache Jira under project Flink with component tag Flink CDC. Thank you!
