### ISSUE TITLE
FlinkDatabaseHistory在程序挂了重启后，能否重新获得表schema的信息

### ISSUE THREAD

**Issue by Karl-WangSK** [ververica/flink-cdc-connectors#214]
因为flink-cdc ddl的变更都是保存在FlinkDatabaseHistory内存中
所以假如在flink任务挂了之后，A表的结构是（a:String, b: Int）
在重启之前发生了ddl，变成（a:String, b: Int, c:String）
重启了之后获取binlog会不会报错，类似canal的问题 https://github.com/alibaba/canal/wiki/TableMetaTSDB

**Comment by leonardBang** [comment]
应该不会的，你可以测试下
