### ISSUE TITLE
How to use sql api create Array column and send elasticsearch ?

### ISSUE THREAD

**Issue by gaozuo** [ververica/flink-cdc-connectors#2147]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

I have a need to create a large materialized view in elasticsearch, which may contain some nested information (because page row count must equals root doucment length) , and now I use flik-sql to generate the subtable as a json array string , now how to convert the json string to Array<Row<>> and write it to elasticsarch?

---------------------------------------------------------------
CREATE TABLE es_members_info (
  id BIGINT PRIMARY KEY NOT ENFORCED,
  first_name STRING,
  last_name STRING,
  address STRING,
  address_city STRING,
  address_country STRING,
  claims_details ARRAY<ROW<
    claim_id BIGINT, 
    member_id BIGINT, 
    claim_total DECIMAL, 
    claim_total_receipt STRING,
    claim_currency STRING
  >>
) WITH (
  'connector' = 'elasticsearch-7',
  'hosts' = 'http://10.88.78.103:9200',
  'index' = 'members_info'
);

INSERT INTO es_members_info
SELECT 
    m.id,
    m.first_name,
    m.last_name,
    m.address,
    m.address_city,
    m.address_country,
    JSON_ARRAYAGG(JSON_OBJECT(
            'claim_id' VALUE ac.claim_id,
            'member_id' VALUE ac.member_id,
            'claim_total' VALUE ac.claim_total,
            'claim_total_receipt' VALUE ac.claim_total_receipt,
            'claim_currency' VALUE ac.claim_currency
    )) AS claims_details
 FROM accident_claims ac
 JOIN members m
 ON ac.member_id = m.id
 GROUP BY 
     m.id,
     m.first_name,
     m.last_name,
     m.address,
     m.address_city,
     m.address_country

-------------error-----------------------

Invalid query
Column types of query result and sink for 'vvp.default.es_members_info' do not match.
Cause: Incompatible types for sink column 'claims_details' at position 6.

Query schema: [id: INT NOT NULL, first_name: VARCHAR(50), last_name: VARCHAR(50), address: VARCHAR(50), address_city: VARCHAR(10), address_country: VARCHAR(10), claims_details: VARCHAR(2000) NOT NULL]
Sink schema:  [id: BIGINT, first_name: STRING, last_name: STRING, address: STRING, address_city: STRING, address_country: STRING, claims_details: ARRAY<ROW<`claim_id` BIGINT, `member_id` BIGINT, `claim_total` DECIMAL(10, 0), `claim_total_receipt` STRING, `claim_currency` STRING>>]

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by gaozuo** [comment]
how to only use the sql, better without udf,  or out of the box udf

**Comment by Jiabao-Sun** [comment]
@gaozuo

```java
package com.atta.flink.udf.scalar;

import org.apache.flink.table.api.DataTypes;
import org.apache.flink.table.api.ValidationException;
import org.apache.flink.table.catalog.DataTypeFactory;
import org.apache.flink.table.data.ArrayData;
import org.apache.flink.table.data.GenericArrayData;
import org.apache.flink.table.data.util.DataFormatConverters;
import org.apache.flink.table.functions.ScalarFunction;
import org.apache.flink.table.types.DataType;
import org.apache.flink.table.types.inference.TypeInference;
import org.apache.flink.table.types.logical.LogicalTypeRoot;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public class KeySet extends ScalarFunction {

    private static final long serialVersionUID = -458615156047330632L;

    private DataType elementType;

    @SuppressWarnings("unchecked")
    public ArrayData eval(Map<?, Integer> map) {
        if (map != null && !map.isEmpty()) {
            List<Object> result = new ArrayList<>();
            for (Map.Entry<?, Integer> entry : map.entrySet()) {
                if (entry.getValue() == null || entry.getValue() <= 0) {
                   continue;
                }
                Optional.of(entry.getKey())
                    .map(e -> DataFormatConverters
                            .getConverterForDataType(elementType).toInternal(e))
                    .ifPresent(result::add);
            }

            return new GenericArrayData(result.toArray());
        }
        return null;
    }

    @Override
    public TypeInference getTypeInference(DataTypeFactory typeFactory) {
        return TypeInference.newBuilder()
                .outputTypeStrategy(callContext -> {
                    List<DataType> argumentDataTypes = callContext.getArgumentDataTypes();
                    if (argumentDataTypes.size() < 1) {
                        return Optional.empty();
                    }
                    DataType argumentType = argumentDataTypes.get(0);
                    LogicalTypeRoot logicalTypeRoot = argumentType.getLogicalType().getTypeRoot();
                    if (logicalTypeRoot != LogicalTypeRoot.MULTISET && logicalTypeRoot != LogicalTypeRoot.MAP) {
                        throw new ValidationException("params should be MULTISET or MAP");
                    }
                    elementType = argumentType.getChildren().get(0);
                    return Optional.of(
                            DataTypes.ARRAY(elementType).bridgedTo(ArrayData.class)
                    );
                })
                .build();
    }

}
```

```sql
SELECT `entity_id`,
        KeySet(COLLECT(`info`)) as `infos`
  FROM (
    SELECT `entity_id`,
            ROW(`code`, `name`) `info`
      FROM (
        SELECT `entity_id`,
                       `code`,
                      `name`
        FROM table)
   )
GROUP BY `entity_id`;
```
