### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ysuwei** [ververica/flink-cdc-connectors#2157]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

阿里云flink 应该是1.15.3

### Flink CDC version

2.3.0

### Database and its version

阿里云mongo 4.2

### Minimal reproduce step

 MongoDBSource<String> mongoSource =
                MongoDBSource.<String>builder()
                        .hosts(ConfigurationUtils.getConfigValue(conf,"mongo_hostname"))
                        .databaseList(ConfigurationUtils.getConfigValue(conf,"mongo_databaselist"))
                        .collectionList(collections)
                        .username(ConfigurationUtils.getConfigValue(conf,"mongo_username"))
                        .password(ConfigurationUtils.getConfigValue(conf,"mongo_password"))
                        .copyExisting(true)
                        .splitSizeMB(1)
                        .batchSize(20)
                        .connectionOptions("replicaSet=mgset-304817713&connectTimeoutMS=300000")
                        .heartbeatIntervalMillis(1000)
                        .deserializer(new JsonDebeziumDeserializationSchema())
                        .build();
当mongo_hostname配置高可用链接（多链接）的时候报错：
com.mongodb.MongoQueryException: Query failed with error code 280 and error message 'cannot resume stream; the resume token was not found. {_data: "8264720EDE0000000A2B022C0100296E5A1004DBBC817EF8454E1B917F3F70603F167846645F6964006464720EDE1FFE6271C92A55BD0004"}' on server ip:port

配置单链接然后不设置connectionOptions 就正常了

### What did you expect to see?

文档写的支持上连接，希望能支持双链接

### What did you see instead?

文档写的支持上连接，希望能支持双链接

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ysuwei** [comment]
单链接的时候会报错：error code 280 and error message 'cannot resume stream; the resume token was not found

**Comment by Jiabao-Sun** [comment]
There are no other similar reports for this issue, so we will temporarily close it.
