### ISSUE TITLE
source finished  导致无法checkpoint

### ISSUE THREAD

**Issue by lykpass** [ververica/flink-cdc-connectors#216]
![image](https://user-images.githubusercontent.com/48595535/122343208-09a89380-cf78-11eb-904a-8bf935d39e4a.png)
![image](https://user-images.githubusercontent.com/48595535/122343254-19c07300-cf78-11eb-8da6-9f565db1c6cf.png)
![image](https://user-images.githubusercontent.com/48595535/122343332-2cd34300-cf78-11eb-8927-88a8cd28e99d.png)
我使用cdc做数据源，但是多出来一个source，任务刚启动就finished了，其它的source都正常running，导致程序无法进行checkpoint

**Comment by lykpass** [comment]
![image](https://user-images.githubusercontent.com/48595535/122343749-a1a67d00-cf78-11eb-9f89-4c61679f075e.png)和这些配置有关吗

**Comment by lykpass** [comment]
![image](https://user-images.githubusercontent.com/48595535/122372751-84cb7300-cf93-11eb-9dc1-f8a7d08dd8b4.png)

我用 = 逻辑替换掉 in 逻辑，就没那个source了，就能ck了，能解释下为什么吗

**Comment by Tandoy** [comment]
Hello, do you have any new progress on this issue?
I also encountered a similar problem

**Comment by lykpass** [comment]
> n

我在网上看到一种场景是Parallelism数多于kafka的分区数，会导致task finished,我碰到是某种sql语法导致的，我修改语法后就正常了，目前只能找出什么情况会导致finished，避免这种情况，希望能帮助到你。我感觉 flink后面几个版本会解决finished任务导致无法进行ck的问题。

**Comment by Tandoy** [comment]
好的，谢谢~

**Comment by leonardBang** [comment]
参考这里 https://issues.apache.org/jira/browse/FLINK-22764

**Comment by lykpass** [comment]
> 参考这里 https://issues.apache.org/jira/browse/FLINK-22764

好的  谢谢
