### ISSUE TITLE
[Bug] oracle采集的新增数据如果有单引号，会有问题

### ISSUE THREAD

**Issue by zroor1984** [ververica/flink-cdc-connectors#2163]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13.6

### Flink CDC version

2.3.0

### Database and its version

Oracle 11.2.0.4

### Minimal reproduce step

1、创建一个测试表
create table tb1 (id int,fname varchar2(200));
2、插入数据
insert into tb1 values (1,'aa''')；
3、观察输出的json数据，aa后面是2个单引号，
fname列的数据是"aa''"
4、如果是存量数据，则aa后面只有1个单引号
5、另外mysql做同样的实验，存量和新增数据输出的都是"aa'"，aa后面是1个单引号

### What did you expect to see?

我希望oracle采集的存量数据和新增数据能够一致

### What did you see instead?

如果数据中存在单引号，oracle采集的存量数据和新增数据不一致

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by e-mhui** [comment]
我按照你的步骤，发现数据是正常的。 

<img width="973" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/111486498/1bd17437-2726-4696-a715-6d90182cfb2b">

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
