### ISSUE TITLE
[Bug] MongoDB CDC incremental connector读取存量数据乱序

### ISSUE THREAD

**Issue by DarthVagen** [ververica/flink-cdc-connectors#2166]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.1

### Flink CDC version

2.3.0

### Database and its version

4.4.8

### Minimal reproduce step

1. 设置一个空的mongodb collection，依次插入{num: 1}, {num: 2}, ...... , {num: 1000}共1000条document
2. col.find()可以看到返回顺序与插入顺序相同
3. 在flink job中使用MongoDB CDC incremental connector连接该collection，不做处理，直接print，打印的顺序与插入顺序不同

### What did you expect to see?

期望看到print的顺序与插入顺序相同

### What did you see instead?

乱序。可能是由于connector将存量数据分片后并行送给下游导致的？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by DarthVagen** [comment]
查看日志推测是对Source做split后，每个splite分组内的document乱序，分组之间有序

**Comment by ruanhang1993** [comment]
Actually the records sent in the snapshot phase will not be guarded the order.
Multi reader subtasks cannot keep the order when send data.

Use the parallelism 1 will keep the order in the snapshot phase.

**Comment by DarthVagen** [comment]
> 
Thanks for your reply! There are two connectors in this project: _com.ververicaI.cdc.connector.mongodb.MongoDBSource_ and  _com.ververicaI.cdc.connector.mongodb.source.MongoDBSource_, the former works well in the snapshotphase(records in order), but the latter does not, even I have set parallelism of the whole job to 1(in fact my local flink cluster has only one task slot). Is there any setting configuration that may not be mentioned in the demo code?

**Comment by DarthVagen** [comment]
> 
Thanks for your reply! There are two connectors in this project: _com.ververicaI.cdc.connector.mongodb.MongoDBSource_ and  _com.ververicaI.cdc.connector.mongodb.source.MongoDBSource_, the former works well in the snapshotphase(records in order), but the latter does not, even I have set parallelism of the whole job to 1(in fact my local flink cluster has only one task slot). Is there any setting configuration that may not be mentioned in the demo code?
