### ISSUE TITLE
expected to support DDL statement synchronization

### ISSUE THREAD

**Issue by LEIHAOYUAN** [ververica/flink-cdc-connectors#2168]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

expected to support DDL statement synchronization

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
This feature should not be implemented in cdc source. CDC source could send the schema change data.
The flink engine and sink connector should deal with these messages. It is the most important thing.
