### ISSUE TITLE
[Bug] old change data that will be captured when the latest mode starts

### ISSUE THREAD

**Issue by fuyun2024** [ververica/flink-cdc-connectors#2175]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.13.5

### Flink CDC version

master

### Database and its version

sqlserver2012

### Minimal reproduce step

1. Configure from ` LATEST_ OFFSET ` Start CDC task
2. Observe that the captured data contains old change data.

### What did you expect to see?

Change data from now on

### What did you see instead?

Old change data

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
https://github.com/ververica/flink-cdc-connectors/pull/2176 merged.
