### ISSUE TITLE
[Bug] Sqlserver did not merge high and low watermark data during snapshot reading process

### ISSUE THREAD

**Issue by fuyun2024** [ververica/flink-cdc-connectors#2178]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.13.5

### Flink CDC version

master

### Database and its version

sqlserver 2019

### Minimal reproduce step

none

### What did you expect to see?

merge high and low watermark data during snapshot reading process

### What did you see instead?

Sqlserver did not merge high and low watermark data during snapshot reading process

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Pr https://github.com/ververica/flink-cdc-connectors/pull/2179 was merged.
