### ISSUE TITLE
mysql cdc从checkpoint重启，提示文件找不到[Bug] 

### ISSUE THREAD

**Issue by gongzexin** [ververica/flink-cdc-connectors#2182]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14

### Flink CDC version

mysql cdc 2.3

### Database and its version

5.7.41-log

### Minimal reproduce step

flink作业失败后，重新启动flink作业并指定execution.savepoint.path参数

### What did you expect to see?

能够从之前失败的地方恢复

### What did you see instead?

[flink_restart_err.log](https://github.com/ververica/flink-cdc-connectors/files/11662400/flink_restart_err.log)

### Anything else?

无

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
It seems like the checkpoint in `/opt/flink/checkpoints/e8f6e74c3bf4ad2a79d2693ef89afd7c/chk-1124/5364dc7f-61f7-42b7-b63a-5e7945436924` can not be found. Please make sure the directory.

**Comment by gongzexin** [comment]
> It seems like the checkpoint in `/opt/flink/checkpoints/e8f6e74c3bf4ad2a79d2693ef89afd7c/chk-1124/5364dc7f-61f7-42b7-b63a-5e7945436924` can not be found. Please make sure the directory exist.

First of all thank you for your reply.

There is indeed only one `_metadata` file in the directory chk-1124. I also found only one `_metadata` file in the checkpoint directory of other Flink jobs. I don't understand why the MySQL CDC source in this job needs to read the file `5364dc7f-61f7-42b7-b63a-5e7945436924`. Do you know the reason behind this?

**Comment by gaotingkai** [comment]
Do you have this parameter in your code?

env.getCheckpointConfig().setExternalizedCheckpointCleanup(CheckpointConfig.ExternalizedCheckpointCleanup.RETAIN_ON_CANCELLATION);

**Comment by gongzexin** [comment]
> Do you have this parameter in your code?
> 
> env.getCheckpointConfig().setExternalizedCheckpointCleanup(CheckpointConfig.ExternalizedCheckpointCleanup.RETAIN_ON_CANCELLATION);

Yes, I am running in Docker, and in the `docker-compose.yml` file, I have configured `services.jobmanager.environment.execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION`.

**Comment by gaotingkai** [comment]
> 

I haven't tested it in the docker environment. Is it convenient for you to use datastream api to verify whether this parameter can take effect normally? Normally, after this parameter is set, the checkpoint file will be retained.

**Comment by gongzexin** [comment]
> > 
> 
> I haven't tested it in the docker environment. Is it convenient for you to use datastream api to verify whether this parameter can take effect normally? Normally, after this parameter is set, the checkpoint file will be retained.



> > 
> 
> I haven't tested it in the docker environment. Is it convenient for you to use datastream api to verify whether this parameter can take effect normally? Normally, after this parameter is set, the checkpoint file will be retained.



> > 
> 
> I haven't tested it in the docker environment. Is it convenient for you to use datastream api to verify whether this parameter can take effect normally? Normally, after this parameter is set, the checkpoint file will be retained.

Yes, I'm using the DataStream API, and there is also a file named "chk-1124/_metadata" in the checkpoint directory, which is similar to my other Flink jobs. However, when trying to recover from a task failure using the checkpoint, it requires reading the file "chk-1124/5364dc7f-61f7-42b7-b63a-5e7945436924", and I'm not sure what happened there.

**Comment by gaotingkai** [comment]
> 

<img width="1217" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/34996528/319d2808-399d-4d48-8cec-7d407aa4903a">

Is your flink web ui like this?

**Comment by gongzexin** [comment]
> > 
> 
> <img alt="image" width="1217" src="https://user-images.githubusercontent.com/34996528/244252461-319d2808-399d-4d48-8cec-7d407aa4903a.png">
> Is your flink web ui like this?

![image](https://github.com/ververica/flink-cdc-connectors/assets/63918706/98c103fa-6ded-4fd2-912a-8c030c530604)
yes, this is my flink web ui

**Comment by gaotingkai** [comment]
> > > 
> > 
> > 
> > <img alt="image" width="1217" src="https://user-images.githubusercontent.com/34996528/244252461-319d2808-399d-4d48-8cec-7d407aa4903a.png">
> > Is your flink web ui like this?
> 
> ![image](https://user-images.githubusercontent.com/63918706/244254290-98c103fa-6ded-4fd2-912a-8c030c530604.png) yes, this is my flink web ui

 😫 I don't know why the parameters don't take effect. You can ask the flink community for help.

**Comment by gongzexin** [comment]
> > > > 
> > > 
> > > 
> > > <img alt="image" width="1217" src="https://user-images.githubusercontent.com/34996528/244252461-319d2808-399d-4d48-8cec-7d407aa4903a.png">
> > > Is your flink web ui like this?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/63918706/244254290-98c103fa-6ded-4fd2-912a-8c030c530604.png) yes, this is my flink web ui
> 
> 😫 I don't know why the parameters don't take effect. You can ask the flink community for help.

ok, thank you for your reply. I will consult the Flink community regarding this issue and if there are any new insights on this matter, I will provide updates in this thread.

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
