### ISSUE TITLE
[Bug] [mysql-cdc-2.2.1]开启scanNewlyAddedTableEnabled 去掉一张表，重新启动，其他表会重新同步，而不是重保存点同步

### ISSUE THREAD

**Issue by aLittleDonkey** [ververica/flink-cdc-connectors#2190]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.14

### Flink CDC version

flink-sql-mysql-cdc 2.2.1

### Database and its version

8.0

### Minimal reproduce step

1. 同步 t1 , t2, t3
2. 设置savepoint关闭任务
3. 从保存点启动，同步t1, t2

### What did you expect to see?

t1, t2 从保存点继续同步

### What did you see instead?

t1, t2 全量同步，并没有从保存点继续同步

### Anything else?

如果是新增表，已存在的表会从保存点继续同步，新增的表会全量同步，只要有一张表被去掉，所以表都会全量同步

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by gong** [comment]
@aLittleDonkey Maybe  PR https://github.com/ververica/flink-cdc-connectors/pull/2096 can fix this problem

**Comment by Level1Accelerator** [comment]
请问下老哥，你savepoint之前任务的启动模式是全量还是增量啊

**Comment by leesenlen** [comment]
> 请问下老哥，你savepoint之前任务的启动模式是全量还是增量啊

全量

**Comment by aLittleDonkey** [comment]
> @aLittleDonkey也许 PR #2096可以解决这个问题

请问大佬，这个问题在哪个版本修复了吗，还是未来会处理，PR https://github.com/ververica/flink-cdc-connectors/pull/2096 没有看明白怎么处理。
谢谢大佬。

**Comment by gong** [comment]
> > @aLittleDonkey也许 PR #2096可以解决这个问题
> 
> 请问大佬，这个问题在哪个版本修复了吗，还是未来会处理，PR #2096 没有看明白怎么处理。 谢谢大佬。
@aLittleDonkey I think this will be repaired in 2.5 version. Currently, this PR don't be merged.

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
