### ISSUE TITLE
Single machine version of MySQL, Flinkcdc reading MySQL error, how to solve it

### ISSUE THREAD

**Issue by zhbdesign** [ververica/flink-cdc-connectors#2197]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15

### Flink CDC version

2.3.0

### Database and its version

mysql5.7

### Minimal reproduce step

Single machine version of MySQL，gtid is on

### What did you expect to see?

no error

### What did you see instead?

![mmexport1686190611981](https://github.com/ververica/flink-cdc-connectors/assets/50901800/3fc4f543-7a6d-4d8d-8851-5bcc064bb07b)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lufzhangzitao** [comment]
Have you enabled binlog?
