### ISSUE TITLE
Flink Oracle CDC data loss[Bug] 

### ISSUE THREAD

**Issue by qiufang1314** [ververica/flink-cdc-connectors#2204]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

nothing

### Flink CDC version

2.3.0

### Database and its version

nothing

### Minimal reproduce step

multiple log events(commit log event) have the same scn value
<img width="842" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/10683318/801dc11e-54a3-4e13-ab9e-3292352b9f7b">

### What did you expect to see?

io.debezium.connector.oracle.logminer.TransactionalBuffer

offsetContext.getCommitScn().compareTo(scn) >= 0
'>= '  should be  '>'

    // On the restarting connector, we start from SCN in the offset. There is possibility to
        // commit a transaction(s) which were already committed.
        // Currently we cannot use ">=", because we may lose normal commit which may happen at the
        // same time. TODO use audit table to prevent duplications
        if ((offsetContext.getCommitScn() != null
                        && offsetContext.getCommitScn().compareTo(scn) >

 0)
                || lastCommittedScn.compareTo(scn) > 0) {
            LOGGER.debug(
                    "Transaction {} already processed, ignored. Committed SCN in offset is {}, commit SCN of the transaction is {}, last committed SCN is {}",
                    transactionId,
                    offsetContext.getCommitScn(),
                    scn,
                    lastCommittedScn);
            streamingMetrics.setActiveTransactions(transactions.size());
            return false;
        }

### What did you see instead?

` if ((offsetContext.getCommitScn() != null
                        && offsetContext.getCommitScn().compareTo(scn) **>=** 0)
                || lastCommittedScn.compareTo(scn) > 0) {
            LOGGER.debug(
                    "Transaction {} already processed, ignored. Committed SCN in offset is {}, commit SCN of the transaction is {}, last committed SCN is {}",
                    transactionId,
                    offsetContext.getCommitScn(),
                    scn,
                    lastCommittedScn);
            streamingMetrics.setActiveTransactions(transactions.size());
            return false;
        }`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Oracle cdc connector may fix this issue in 2.4.0. @qiufang1314 Would you mind helping to check whether this bug still exists in version 2.4.0?

**Comment by fuimaz** [comment]
> Oracle cdc connector may fix this issue in 2.4.0. @qiufang1314 Would you mind helping to check whether this bug still exists in version 2.4.0?

hello，which version has fixed this bug, we meet the same problem ,wo can check  whether  this bug exists in your version

**Comment by fuimaz** [comment]
> > Oracle cdc connector may fix this issue in 2.4.0. @qiufang1314 Would you mind helping to check whether this bug still exists in version 2.4.0?
> 
> hello，which version has fixed this bug, we meet the same problem ,we can check whether this bug exists in your version

@ruanhang1993

**Comment by GOODBOY008** [comment]
@qiufang1314  Had fixed in Release 3.0.1, Please update and retry.

If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
