### ISSUE TITLE
[Bug] SpringBoot环境+Flink CDC2.3 出现 java.lang.NoSuchMethodError: io.debezium.connector.mysql.MySqlConnection$MySqlConnectionConfiguration

### ISSUE THREAD

**Issue by wuchubuzai2018** [ververica/flink-cdc-connectors#2232]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

无Flink集群环境，单纯的是SpringBoot环境下

### Flink CDC version

Flink CDC 2.3  非SQL模式

### Database and its version

阿里云MySQL RDS

### Minimal reproduce step

1、搭建SpringBoot应用
2、引入Flink CDC2.3的包
3、开发环境没问题，打包编译后，启动会报错，好像是有个重写的类没有执行自己写的，还是执行了debezium原始的jar包方法
和这个ISSUE类似。 
#1812 
4、pom.xml如下：
`
 <dependency>
            <groupId>com.ververica</groupId>
            
            <artifactId>flink-connector-mysql-cdc</artifactId>
            
        </dependency>
    
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-clients</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-streaming-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-api-java-bridge</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-planner-loader</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-runtime</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-base</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-runtime-web</artifactId>
        </dependency>
`

其他错误如下：
`

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils.createMySqlConnection(DebeziumUtils.java:78)

The following method did not exist:

    io.debezium.connector.mysql.MySqlConnection$MySqlConnectionConfiguration.<init>(Lio/debezium/config/Configuration;Ljava/util/Properties;)V

The calling method's class, com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils, was loaded from the following location:

    jar:file/BOOT-INF/lib/flink-connector-mysql-cdc-2.3.0.jar!/com/ververica/cdc/connectors/mysql/debezium/DebeziumUtils.class

The called method's class, io.debezium.connector.mysql.MySqlConnection$MySqlConnectionConfiguration, is available from the following locations:

    jar:file/BOOT-INF/lib/debezium-connector-mysql-1.6.4.Final.jar!/io/debezium/connector/mysql/MySqlConnection$MySqlConnectionConfiguration.class
    jar:file/BOOT-INF/lib/flink-connector-mysql-cdc-2.3.0.jar!/io/debezium/connector/mysql/MySqlConnection$MySqlConnectionConfiguration.class

The called method's class hierarchy was loaded from the following locations:

    io.debezium.connector.mysql.MySqlConnection.MySqlConnectionConfiguration: jar:file/BOOT-INF/lib/debezium-connector-mysql-1.6.4.Final.jar!/

Action:

`

### What did you expect to see?

启动不报错,能好使，能解决这个错误

### What did you see instead?

无

### Anything else?

无

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by syyfffy** [comment]
U cannot deploy the flink‘s job  with SpringBoot application and u should deploy this work with flink's cluster

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
