### ISSUE TITLE
flink-sql-connector-oracle-cdc-2.4.0采集出现异常

### ISSUE THREAD

**Issue by zhbdesign** [ververica/flink-cdc-connectors#2234]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.2

### Flink CDC version

2.4.0

### Database and its version

Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

### Minimal reproduce step

CREATE TABLE product_view_source (
`a` String,
`b` String,
PRIMARY KEY (`a`) NOT ENFORCED
) WITH (
'connector' = 'oracle-cdc',
'hostname' = 'ip',
'port' = '1521',
'username' = 'flinkuser',
'password' = 'flinkpw',
'database-name' = 'name',
'schema-name' = 'schema',
'table-name' = 'mytable',
'debezium.log.mining.strategy' = 'online_catalog',
    'debezium.log.mining.continuous.mine' = 'true',
'scan.startup.mode' = 'latest-offset' 
);
select * from product_view_source;

### What did you expect to see?

正常采集

### What did you see instead?

java.lang.NoSuchMethodError: io.debezium.connector.oracle.logminer.LogMinerChangeRecordEmitter.addStaticHeader(Ljava/lang/String;Lcom/ververica/cdc/connectors/shaded/org/apache/kafka/connect/data/SchemaAndValue;)V

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by hzjhjjyy** [comment]
我也发现这个了，是否lib里同时存在了mysql-cdc或者其他cdc包？移除后就正常了，看了下关系，应该是mysql-cdc和oracle-cdc出现同类名了，然后用了mysql-cdc包中的类导致的，最终使用的类是io.debezium.relational.RelationalChangeRecordEmitter，mysql-cdc里没有addStaticHeader，而oracle-cdc里有

**Comment by zhbdesign** [comment]
> 我也发现这个了，是否lib里同时存在了mysql-cdc或者其他cdc包？移除后就正常了，看了下关系，应该是mysql-cdc和oracle-cdc出现同类名了，然后用了mysql-cdc包中的类导致的，最终使用的类是io.debezium.relational.RelationalChangeRecordEmitter，mysql-cdc里没有addStaticHeader，而oracle-cdc里有

lib下有一个mysql-cdc2.4.0，那这个怎么解决

**Comment by hzjhjjyy** [comment]
移除mysql-cdc包

**Comment by zhbdesign** [comment]
> 移除mysql-cdc包

那mysql就不能用了

**Comment by 2012215434** [comment]
把mysql-cdc 相关的逻辑和 oracle-cdc相关逻辑放在两个模块，然后build 时候 shade 到你对应的 模块jar里面应该就可以。

**Comment by zjb48000** [comment]
这个问题有比较 优雅的解决方案吗？比如改源码，重新编译？还是只能等2.4.1了

**Comment by zjb48000** [comment]
有问题哦。  
1、  RelationalChangeRecordEmitter---这个文件的包名字是不是写错了。也是在oracle-cdc工程里的吧
2、如果是oracle-cdc里的话，那个新增的方法，不是override方法呀。是不是少传了父类文件了
