### ISSUE TITLE
[Bug] High Disk read usage after submitting flink jobs with flinksql

### ISSUE THREAD

**Issue by Voigt1022** [ververica/flink-cdc-connectors#2236]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.1

### Flink CDC version

2.2.1 oracle

### Database and its version

source: oracle 11g
target: postgre

### Minimal reproduce step

submitting flink jobs with flinksql
debezium config is following:
```
    'debezium.log.mining.strategy'='online_catalog',
    'debezium.log.mining.batch.size.max'='100000000',
    'debezium.log.mining.sleep.time.increment.ms'='5000',
    'debezium.database.tablename.case.insensitive'='false'
```

### What did you expect to see?

Suitable disk read usage.

### What did you see instead?

The server where resource database runs takes very high disk usage to read db logs. 

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by Voigt1022** [comment]
By the way, I open 16 tables for CDC, does it cause the high IO?

**Comment by GOODBOY008** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
