### ISSUE TITLE
Release-2.5 Roadmap

### ISSUE THREAD

**Issue by ruanhang1993** [ververica/flink-cdc-connectors#2239]
Please comment under this issue to propose your wanted feature. 

## Feature Development
* [ ] #985 
* [ ] #986 
* [ ] #1152 

## Document Improvement
* [ ] #1729
* [x] #345

**Comment by rbreejen** [comment]
Upgrade to Debezium 2.3. Will solve a lot of bugs.
See #1788

**Comment by maver1ck** [comment]
@ruanhang1993 should we update guava to 31 as Flink 1.18 did this update ?

**Comment by sam2099** [comment]
> Upgrade to Debezium 2.3. Will solve a lot of bugs. See #1788
@ruanhang1993
should we hava plan to uupdate Debezium?

**Comment by rbreejen** [comment]
Why is this repo so inactive? So many issues and pull requests open. It has so much potential.

**Comment by sql96** [comment]
后面我们对oracle的支持会更全面吗，比如oracle 19c 的分区表和无主键表
