### ISSUE TITLE
[Bug] PostgresSourceBuilder can not be init with datastream api

### ISSUE THREAD

**Issue by syyfffy** [ververica/flink-cdc-connectors#2245]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

*

### Flink CDC version

2.4

### Database and its version

*

### Minimal reproduce step

no

### What did you expect to see?

![image](https://github.com/ververica/flink-cdc-connectors/assets/46524102/ff77ddfc-cfd7-4b47-9a1a-7f6e857371db)

user can not init the class

### What did you see instead?

public PostgresSourceBuilder() {
        this.configFactory = new PostgresSourceConfigFactory();
    }

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
I close this issue and please reopen it if you still find problems. Thanks~

**Comment by syyfffy** [comment]
use PostgresSourceBuilder.PostgresIncrementalSource.<String>builder().xxx , i can't get data from then source 

`StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.enableCheckpointing(1000);
        JdbcIncrementalSource<String> postgresIncrementalSource
                = PostgresSourceBuilder.PostgresIncrementalSource.<String>builder()
                .hostname("localhost")
                .port(5432)
                .database("postgres")
                .schemaList("public")
                .tableList("public.*")
                .username("postgres")
                .password("postgres")
                .slotName("flink")
//                        .decodingPluginName("decoderbufs") // use pgoutput for PostgreSQL 10+
                .deserializer(new JsonDebeziumDeserializationSchema())
                .includeSchemaChanges(true) // output the schema changes as well

                .splitSize(2) // the split size of each snapshot split
                .build();

        env.fromSource(
                        postgresIncrementalSource,
                        WatermarkStrategy.noWatermarks(),
                        "PostgresParallelSource")
                .setParallelism(2)
                .print();

        env.execute("Output Postgres Snapshot");
`
