### ISSUE TITLE
flink-cdc-mysql：不同库json字符串的before，after字段名大小写不一致[Bug] 

### ISSUE THREAD

**Issue by Toroidals** [ververica/flink-cdc-connectors#2250]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink.version：1.15.2

### Flink CDC version

flinkcdc.version：2.4.0

### Database and its version

mysql 5.7

### Minimal reproduce step

无

### What did you expect to see?

提供配置参数，指定生成json串before，after字段名为大写或者小写

### What did you see instead?

不同库json字符串的before，after字段名大小写不一致

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
@Toroidals Could you provide an example? I am not sure about what this problem says. Thanks~

**Comment by Toroidals** [comment]
一个mysql数据库同步的数据：{"before":{"id":79528005,"md_code":"100777418","status_code":"ACTV","created_source_code":"S00"},"source":{"connector":"mysql",...},"op":"u","ts_ms":1688110274100,"transaction":null}
before子串的字段名都是小写

另一个mysql数据库同步的数据：{"before":{"ID":79528005,"MD_CODE":"100777418","STATUS_CODE":"ACTV","CREATED_SOURCE_CODE":"S00"},"source":{"connector":"mysql",...},"op":"u","ts_ms":1688110274100,"transaction":null}
before子串的字段名都是大写

我想这个与mysql数据库的设置有关，但是我们作为数据查询者，没有权限修改mysql的配置，有没有flink-cdc参数指定before子串的字段名都是小写或者大小

**Comment by Toroidals** [comment]
> 你能举个例子吗？我不确定这个问题说了什么。谢谢~
一个mysql数据库同步的数据：{“before”：{“id”：79528005，“md_code”：“100777418”，“status_code”：“ACTV”，“created_source_code”：“S00”}，“source”：{“connector”：“mysql”,...}，“op”：“u”，“ts_ms”：1688110274100，“transaction”：null}
before子串的字段名都是小写

另一个mysql数据库同步的数据：{“before”：{“ID”：79528005，“MD_CODE”：“100777418”，“STATUS_CODE”：“ACTV”，“CREATED_SOURCE_CODE”：“S00”}，“source”：{“connector”：“mysql”,...}，“op”：“u”，“ts_ms”：1688110274100，“transaction”：null}
before子串的字段名都是大写

我想这个与mysql数据库的设置有关，但是我们作为数据查询者，没有权限修改mysql的配置，有没有flink-cdc参数指定before子串的字段名都是小写或者大小

**Comment by Toroidals** [comment]
@ruanhang1993 一个mysql数据库同步的数据：{“before”：{“id”：79528005，“md_code”：“100777418”，“status_code”：“ACTV”，“created_source_code”：“S00”}，“source”：{“connector”：“mysql”,...}，“op”：“u”，“ts_ms”：1688110274100，“transaction”：null}
before子串的字段名都是小写

另一个mysql数据库同步的数据：{“before”：{“ID”：79528005，“MD_CODE”：“100777418”，“STATUS_CODE”：“ACTV”，“CREATED_SOURCE_CODE”：“S00”}，“source”：{“connector”：“mysql”,...}，“op”：“u”，“ts_ms”：1688110274100，“transaction”：null}
before子串的字段名都是大写

我想这个与mysql数据库的设置有关，但是我们作为数据查询者，没有权限修改mysql的配置，有没有flink-cdc参数指定before子串的字段名都是小写或者大小

**Comment by Toroidals** [comment]
> @Toroidals Could you provide an example? I am not sure about what this problem says. Thanks~

@ruanhang1993 一个mysql数据库同步的数据：{“before”：{“id”：79528005，“md_code”：“100777418”，“status_code”：“ACTV”，“created_source_code”：“S00”}，“source”：{“connector”：“mysql”,...}，“op”：“u”，“ts_ms”：1688110274100，“transaction”：null}
before子串的字段名都是小写

另一个mysql数据库同步的数据：{“before”：{“ID”：79528005，“MD_CODE”：“100777418”，“STATUS_CODE”：“ACTV”，“CREATED_SOURCE_CODE”：“S00”}，“source”：{“connector”：“mysql”,...}，“op”：“u”，“ts_ms”：1688110274100，“transaction”：null}
before子串的字段名都是大写

我想这个与mysql数据库的设置有关，但是我们作为数据查询者，没有权限修改mysql的配置，有没有flink-cdc参数指定before子串的字段名都是小写或者大小

**Comment by ruanhang1993** [comment]
The returned field name is the corresponding field name in the MySQL Table. We cannot change it in settings.
