### ISSUE TITLE
[Bug] flink-cdc-oracle-2.4.0 启动之后执行Snapshot step 6 - Persisting schema history需要很长的时间（2小时左右）才能开始同步数据，flink-cdc-oracle-2.2.0正常

### ISSUE THREAD

**Issue by Toroidals** [ververica/flink-cdc-connectors#2263]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink.version：1.15.2

### Flink CDC version

flinkcdc.version：2.4.0

### Database and its version

oracle：12c

### Minimal reproduce step

public class CustomOracleCdcStreamSource {
    public static SourceFunction<String> getSource() {

        Properties prop = new Properties();
        prop.setProperty("converters", "DebeziumConverter");
        prop.setProperty("DebeziumConverter.type", "com.hand.utils.DebeziumConverter");
        prop.setProperty("DebeziumConverter.database.type", "oracle");

        prop.setProperty("log.mining.strategy", "online_catalog");
        prop.setProperty("log.mining.continuous.mine", "true");

        prop.setProperty("decimal.handling.mode", "string");
        prop.setProperty("interval.handling.mode", "string");

        prop.setProperty("database.tablename.case.insensitive","false");
        prop.setProperty("database.connection.adapter", "logminer");

        SourceFunction<String> sourceFunction = OracleSource.<String>builder()
                .url("jdbc:oracle:thin:@192.168.112.xxx:1521/orcl")
                .port(1521)
                .database("orcl") 
                .schemaList("c##FLINKUSER01") 
                .tableList("c##FLINKUSER01.test_table") 
                .username("c##FLINKUSER01")
                .password("xx")
                .startupOptions(StartupOptions.latest())
                .debeziumProperties(prop)
                .deserializer(new JsonDebeziumDeserializationSchema()) // converts SourceRecord to JSON String
                .build();

        return sourceFunction;
    }
}

### What did you expect to see?

启动flink任务后及时的同步到变更数据

### What did you see instead?

启动flink任务后需要等待2小时左右，才能及时的同步到变更数据
通过日志发现cdc-2.4.0版本比cdc-2.2.0版本多出许多如下日志：
io.debezium.relational.RelationalSnapshotChangeEventSource   [] - Adding table PITDB.NEWSIT.table_name_xx to the list of capture schema tables
io.debezium.connector.oracle.OracleSnapshotChangeEventSource [] - Capturing structure of table PITDB.NEWSIT.table_name_xx
通过日志发现io.debezium.connector.oracle.OracleSnapshotChangeEventSource [] - Capturing structure of table PITDB.NEWSIT.table_name_xx出现约1000多行，此操作占据了约两小时时间，.tableList("c##FLINKUSER01.test_table") 指定了只获取c##FLINKUSER01.test_table的日志数据，但是日志显示依然获取相同schema其它表的结构

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Toroidals** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/54655412/a504055a-da57-4f45-87de-850313f845da)

**Comment by ruanhang1993** [comment]
@Toroidals Thanks for the analysis.
It seems like to be a point that need to optimize in the debezium. I will check its code later.

**Comment by ruanhang1993** [comment]
@Toroidals Maybe you should set `database.history.store.only.captured.tables.ddl` to true (deafult is false).

**Comment by ruanhang1993** [comment]
```java
public static final Field STORE_ONLY_CAPTURED_TABLES_DDL = Field.create(CONFIGURATION_FIELD_PREFIX_STRING + "store.only.captured.tables.ddl")
            .withDisplayName("Store only DDL that modifies tables that are captured based on include/exclude lists")
            .withType(Type.BOOLEAN)
            .withWidth(Width.SHORT)
            .withImportance(Importance.LOW)
            .withDescription("Controls what DDL will Debezium store in database history. "
                    + "By default (false) Debezium will store all incoming DDL statements. If set to true, "
                    + "then only DDL that manipulates a captured table will be stored.")
            .withDefault(false);
```

**Comment by ruanhang1993** [comment]
We could find the logic in these classes.

In `RelationalTableFilters`:
```java
Predicate<TableId> eligibleSchemaPredicate = config.getBoolean(RelationalDatabaseConnectorConfig.TABLE_IGNORE_BUILTIN)
                ? systemTablesFilter::isIncluded
                : x -> true;

        this.schemaSnapshotFilter = config.getBoolean(DatabaseHistory.STORE_ONLY_CAPTURED_TABLES_DDL)
                ? eligibleSchemaPredicate.and(tableFilter::isIncluded)::test
                : eligibleSchemaPredicate::test;
```

In `RelationalSnapshotChangeEventSource`:
```java
private void determineCapturedTables(RelationalSnapshotContext<P, O> ctx) throws Exception {
Set<TableId> allTableIds = getAllTableIds(ctx);
        Set<TableId> snapshottedTableIds = determineDataCollectionsToBeSnapshotted(allTableIds).collect(Collectors.toSet());

        Set<TableId> capturedTables = new HashSet<>();
        Set<TableId> capturedSchemaTables = new HashSet<>();

        for (TableId tableId : allTableIds) {
            if (connectorConfig.getTableFilters().eligibleForSchemaDataCollectionFilter().isIncluded(tableId)) {
                LOGGER.info("Adding table {} to the list of capture schema tables", tableId);
                capturedSchemaTables.add(tableId);
            }
        }

        for (TableId tableId : snapshottedTableIds) {
            if (connectorConfig.getTableFilters().dataCollectionFilter().isIncluded(tableId)) {
                LOGGER.trace("Adding table {} to the list of captured tables for which the data will be snapshotted", tableId);
                capturedTables.add(tableId);
            }
            else {
                LOGGER.trace("Ignoring table {} for data snapshotting as it's not included in the filter configuration", tableId);
            }
        }

        ctx.capturedTables = sort(capturedTables);
        ctx.capturedSchemaTables = capturedSchemaTables
                .stream()
                .sorted()
                .collect(Collectors.toCollection(LinkedHashSet::new));
}
```

In `OracleSnapshotChangeEventSource` :
```java
protected void createSchemaChangeEventsForTables(ChangeEventSourceContext sourceContext,
                                                     RelationalSnapshotContext<OraclePartition, OracleOffsetContext> snapshotContext,
                                                     SnapshottingTask snapshottingTask)
            throws Exception {
        tryStartingSnapshot(snapshotContext);
        for (Iterator<TableId> iterator = snapshotContext.capturedSchemaTables.iterator(); iterator.hasNext();) {
            final TableId tableId = iterator.next();
            if (!sourceContext.isRunning()) {
                throw new InterruptedException("Interrupted while capturing schema of table " + tableId);
            }

            LOGGER.info("Capturing structure of table {}", tableId);
            ....
    }
}
```

**Comment by ruanhang1993** [comment]
This is a setting in the oracle debezium connector. I will close this issue now. If there is still errors, please reopen this issue later.

**Comment by Toroidals** [comment]
@ruanhang1993 问题已解决，感谢
