### ISSUE TITLE
[Bug]  table-name正则匹配bug

### ISSUE THREAD

**Issue by GuXianWei** [ververica/flink-cdc-connectors#2268]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.0

### Flink CDC version

2.4.0

### Database and its version

mysql: 8.0.32
clickhouse:  23.5.3.24

### Minimal reproduce step

mysql : 
create database sch_xs;
use sch_xs;
create table class_student
(
    id              bigint(64) auto_increment  primary key,
    name            varchar(255) charset utf8mb4 null comment '学生名称'
)  collate = utf8mb4_bin;

insert into class_student (name) values ('张三'),('李四'),('王五'),('赵六');

create table course_class_student
(
    id              bigint(64) auto_increment  primary key,
    name            varchar(255) charset utf8mb4 null comment '学生名称'
)  collate = utf8mb4_bin;

insert into course_class_student(name) values ('course_张三'),('course_李四'),('course_王五'),('course_赵六');

=================================================================================

java code:

StreamExecutionEnvironment executionEnvironment = StreamExecutionEnvironment.getExecutionEnvironment();
       executionEnvironment.getCheckpointConfig().setExternalizedCheckpointCleanup(CheckpointConfig.ExternalizedCheckpointCleanup.RETAIN_ON_CANCELLATION);
        executionEnvironment.enableCheckpointing(3000, CheckpointingMode.EXACTLY_ONCE);
        executionEnvironment.getCheckpointConfig().setMaxConcurrentCheckpoints(3);
        executionEnvironment.setStateBackend(new HashMapStateBackend());
        StreamTableEnvironment tableEnvironment = StreamTableEnvironment.create(executionEnvironment);
        tableEnvironment.getConfig().setLocalTimeZone(ZoneId.of("+8"));
        tableEnvironment.executeSql("CREATE TABLE source_class_student (\n" +
                "    database_name STRING METADATA VIRTUAL,\n" +
                "    table_name STRING METADATA VIRTUAL,\n" +
                "    `id` BIGINT,\n" +
                "    `name` STRING,\n" +
                "    PRIMARY KEY (`id`) NOT ENFORCED\n" +
                "  ) WITH (\n" +
                "    'connector' = 'mysql-cdc',\n" +
                "    'hostname' = '127.0.0.1',\n" +
                "    'port' = '3306',\n" +
                "    'username' = 'username',\n" +
                "    'password' = 'password',\n" +
                "    'database-name' = '^(sch_).*',\n" +
                "    'table-name' = 'class_student'\n" +
                "  );");
         Table table = tableEnvironment.sqlQuery("SELECT * FROM source_class_student");
         DataStream<Row> rowDataStream = tableEnvironment.toChangelogStream(table);
         rowDataStream.print().setParallelism(1);
         executionEnvironment.execute("Print MySQL Snapshot + Binlog");
 

### What did you expect to see?

+I[sch_xs, class_student, 2, 李四]
+I[sch_xs, class_student, 1, 张三]
+I[sch_xs, class_student, 4, 赵六]
+I[sch_xs, class_student, 3, 王五]

### What did you see instead?

+I[sch_xs, class_student, 2, 李四]
+I[sch_xs, class_student, 1, 张三]
+I[sch_xs, class_student, 4, 赵六]
+I[sch_xs, class_student, 3, 王五]
+I[sch_xs, course_class_student, 4, course_赵六]
+I[sch_xs, course_class_student, 3, course_王五]
+I[sch_xs, course_class_student, 2, course_李四]
+I[sch_xs, course_class_student, 1, course_张三]

### Anything else?

这个问题只有在设置 database-name' = '^(sch_).*'"或 database-name' = '^(sch_xs).*'"匹配时才会出现，如果设置database-name' = 'sch_xs'"则不会出现此问题

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
@GuXianWei I have optimized this part and docs.
