### ISSUE TITLE
怎么实现不同的数据源有不同的状态过期时间

### ISSUE THREAD

**Issue by lykpass** [ververica/flink-cdc-connectors#228]
![image](https://user-images.githubusercontent.com/48595535/123772869-c5fe4400-d8fe-11eb-930a-0e24dd79fc34.png)
![image](https://user-images.githubusercontent.com/48595535/123773031-ee863e00-d8fe-11eb-8758-21e2ac4b9538.png)
目前我就知道通过这两种方式设置全局的状态清理策略，但是 我们的场景是，事实表的状态不能无限增长，是肯定要设置状态过期时间的，但是存储维度表数据的状态，肯定会有一些长时间空闲的，比如人员信息，但又不能让它们过期，不然哪天join时又关联不上了。有什么好的建议吗

**Comment by leonardBang** [comment]
可以去flink邮件列表问这类问题

**Comment by LiangXiam** [comment]
> ![image](https://user-images.githubusercontent.com/48595535/123772869-c5fe4400-d8fe-11eb-930a-0e24dd79fc34.png)
> ![image](https://user-images.githubusercontent.com/48595535/123773031-ee863e00-d8fe-11eb-8758-21e2ac4b9538.png)
> 目前我就知道通过这两种方式设置全局的状态清理策略，但是 我们的场景是，事实表的状态不能无限增长，是肯定要设置状态过期时间的，但是存储维度表数据的状态，肯定会有一些长时间空闲的，比如人员信息，但又不能让它们过期，不然哪天join时又关联不上了。有什么好的建议吗

请问这个问题有找到什么好的解决方案吗

**Comment by lykpass** [comment]
> > ![image](https://user-images.githubusercontent.com/48595535/123772869-c5fe4400-d8fe-11eb-930a-0e24dd79fc34.png)
> > ![image](https://user-images.githubusercontent.com/48595535/123773031-ee863e00-d8fe-11eb-8758-21e2ac4b9538.png)
> > 目前我就知道通过这两种方式设置全局的状态清理策略，但是 我们的场景是，事实表的状态不能无限增长，是肯定要设置状态过期时间的，但是存储维度表数据的状态，肯定会有一些长时间空闲的，比如人员信息，但又不能让它们过期，不然哪天join时又关联不上了。有什么好的建议吗
> 
> 请问这个问题有找到什么好的解决方案吗

上次老徐建议我用event time temporal join仔细想了下不太符合场景

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
