### ISSUE TITLE
[Bug] Oracle CDC Connector fails on Oracle version 21

### ISSUE THREAD

**Issue by vladislavkeda** [ververica/flink-cdc-connectors#2291]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.1

### Flink CDC version

2.4.0

### Database and its version

Oracle 21.0

### Minimal reproduce step

Connecting to Oracle with version 21.0 by Oracle CDC connector

### What did you expect to see?

No exception

### What did you see instead?

 org.apache.flink.table.api.ValidationException: Currently Flink Oracle CDC connector only supports Oracle whose version is either 11, 12 or 19, but actual is 21.0.

### Anything else?

![image](https://github.com/ververica/flink-cdc-connectors/assets/139224206/bc77103e-aca4-46d1-bb6d-c0d59b18213a)

Documentation says that the Oracle CDC connector supports the Oracle version 21.0. But check in class com.ververica.cdc.connectors.oracle.OracleValidator says otherwise.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
@vladislavkeda Thanks for your report , I will open a pr to fix this.
