### ISSUE TITLE
[Bug][Oracle] oracle 单表全量阶段根据ROWID 字段 split chunk存在BUG

### ISSUE THREAD

**Issue by nidonglin** [ververica/flink-cdc-connectors#2296]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.2

### Flink CDC version

2.4.0

### Database and its version

oracle12c

### Minimal reproduce step

现象：
通过flink sql，同步5千万的表到mysql，'scan.incremental.snapshot.chunk.size' = '80960' ,理论上应该分成700+的chunks，但是实际只分了607就完了，导致最后一个chunk有1千万的数据，最终taskmanager内存被撑爆，出现OOM，多次执行结果一样

复现：
1.select min(ROWID),max(ROWID) FROM "MISNEW"."MIS_SALES_ORDER_LINE"
得到 minRowid AABzcmAAEAAD/GCAAA   maxRowid  AABzcmAB5AAB8B/ABB
2.在第606次获取的下一个rowid是 AABzcmABAAAD6HlAAt，通过代码OracleChunkSplitter.isChunkEndGeMax去比较当前值和最大maxRowid发现尽然比maxRowid大，导致返回null，进而导致最后一个分片数据量1千万

源sql如下
CREATE TABLE MIS_SALES_ORDER_LINE(
    ORDER_LINE_ID	INT,
    ORDER_ID	INT,
    ITEM_ID	INT,
    ITEM_CODE	STRING,
    ITEM_NAME	STRING,
    QUANTITY	INT,
    MARKER_PRICE	DECIMAL(10,2),
    SALES_PRICE	DECIMAL(10,2),
    DESCRIPTION	STRING,
    CREATE_DATE	TIMESTAMP,
    ITEM_TYPE	INT,
    CARDNUMBER	STRING,
    USEAMOUNT	INT,
    ITEM_VERSION	INT,
    SALESORIGINALPRICE	INT,
    PAY_TYPE	INT,
    EXCHANGEABLE	INT,
    EXPENSE_TYPE	INT,
    PACKAGE_TYPE	INT,
    SELLERID	INT,
    SELLERNAME	STRING,
    CATEGORY	INT,
    PRIMARY KEY (ORDER_LINE_ID) NOT ENFORCED
  ) WITH (
    'connector' = 'oracle-cdc',
    'hostname' = '****',
    'port' = '1521',
    'username' = '****',
    'password' = '****',
    'database-name' = '****',
    'schema-name' = '****', 
    'debezium.log.mining.strategy' = 'online_catalog',
    'debezium.log.mining.continuous.mine' = 'true',
    'debezium.include.schema.changes' = 'false',
    **'scan.incremental.snapshot.chunk.key-column' = 'ORDER_LINE_ID',**
    'scan.incremental.snapshot.chunk.size' = '80960' ,
    'scan.snapshot.fetch.size' = '10240',
    'table-name' = 'MIS_SALES_ORDER_LINE'
  );

### What did you expect to see?

按照ROWID split chunk可以正常拆分执行

### What did you see instead?

ROWID split chunk 存在BUG

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nidonglin** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/8099133/4853b449-c5d6-45e7-bff6-176f817bd8ec)
很明显在数据库里面AABzcmABAAAD6HlAAt是比AABzcmAB5AAB8B/ABB要小的

**Comment by nidonglin** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/8099133/308a6d90-2c76-42d3-b04b-382c270e3199)
代码中去执行比较大小，结果却与数据库的验证结果相反

**Comment by nidonglin** [comment]
设置scan.incremental.snapshot.chunk.key-column参数不生效的问题我已经修复

**Comment by ruanhang1993** [comment]
Thanks, @nidonglin .
Is there some bug in the compare code for ROWID? ;)

**Comment by nidonglin** [comment]
> Thanks, @nidonglin . Is there some bug in the compare code for ROWID? ;)
是的，ojdbc8带的ROWID.compareBytes 有问题

**Comment by ruanhang1993** [comment]
> > Thanks, @nidonglin . Is there some bug in the compare code for ROWID? ;)
> > 是的，ojdbc8带的ROWID.compareBytes 有问题

@nidonglin . Would you like to help to fix this issue?

**Comment by nidonglin** [comment]
> > > Thanks, @nidonglin . Is there some bug in the compare code for ROWID? ;)
> > > 是的，ojdbc8带的ROWID.compareBytes 有问题
> 
> @nidonglin . Would you like to help to fix this issue?

没有找到更好的通过代码比较ROWID的方法，感觉ROWID比较还是只能通过数据库来比较更准确，如果通过数据库比较的话又会涉及到一次针对数据库的IO读写操作，性能上可能不太好，不知道你有没有更好的建议？

**Comment by zhaomin1423** [comment]
> > > > Thanks, @nidonglin . Is there some bug in the compare code for ROWID? ;)
> > > > 是的，ojdbc8带的ROWID.compareBytes 有问题
> > 
> > 
> > @nidonglin . Would you like to help to fix this issue?
> 
> 没有找到更好的通过代码比较ROWID的方法，感觉ROWID比较还是只能通过数据库来比较更准确，如果通过数据库比较的话又会涉及到一次针对数据库的IO读写操作，性能上可能不太好，不知道你有没有更好的建议？

I would like to fix it, I have done similar work.

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
