### ISSUE TITLE
[mongodb cdc]Add parameter to control whether to add ChangelogNormalize operator

### ISSUE THREAD

**Issue by lintingbin** [ververica/flink-cdc-connectors#2297]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

The ChangelogNormalize operator can generate "before update" events, but "before update" is not required in some simple CDC scenarios (for example: synchronizing mongodb data to a database that supports upsert). But if you add the ChangelogNormalize operator, a huge state will be generated, which is completely unnecessary in those simple scenarios. So can we add a parameter to control whether to add the ChangelogNormalize operator?

<img width="1441" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/5699014/3a0be188-87d8-4b57-8139-4c88e495d618">

### Solution

Add a parameter to control whether to add the ChangelogNormalize operator.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yuxiqian** [comment]
Currently, MongoDB CDC registered itself to produce I/U+/D row data. Flink will check each source's produced row type, and determine whether source [isUpsertMode](https://github.com/apache/flink/blob/698b128e20d64db72939d54f7b153e31f261939b/flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/connectors/DynamicSourceUtils.java#L240). If so, [`ChangelogNormalize` node will be inserted](https://github.com/apache/flink/blob/698b128e20d64db72939d54f7b153e31f261939b/flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/stream/StreamPhysicalTableSourceScanRule.scala#L67-L90) automatically.

If I see it correctly, "Normalize upsert source" rule is enforced directly by Flink, and seems CDC-side doesn't have a simple way to circumvent it.

**Comment by lintingbin2009** [comment]
@yuxiqian Thank you for your reply. If we can add an additional parameter (for example: force-changelog-mode-all) to this [code](https://github.com/ververica/flink-cdc-connectors/blob/master/flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/table/MongoDBTableSource.java#L141-L149) to judge whether our source is of the type of ChangelogMode.all(), we can control whether the ChangelogNormalize node is generated. Full changelog is a very good feature, but it requires the mongo version, which is not easy to implement in a production environment.

**Comment by yuxiqian** [comment]
Yes, fixing `getChangelogMode` function should work. But my concern is that would cause inconsistent semantic, if MongoDB CDC declares itself as full changelog source while emitting upsert data only.

What do @leonardBang @Jiabao-Sun think?

**Comment by Jiabao-Sun** [comment]
Closed by #2229
