### ISSUE TITLE
[Bug][Oracle] Oracle增量快照参数scan.incremental.snapshot.chunk.key-column设置不生效的问题

### ISSUE THREAD

**Issue by nidonglin** [ververica/flink-cdc-connectors#2299]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.2

### Flink CDC version

2.4.0

### Database and its version

oracle12c

### Minimal reproduce step

split chunk阶段按照指定字段进行分块，目前参数scan.incremental.snapshot.chunk.key-column设置不生效，最终还是会采用ROWID

### What did you expect to see?

scan.incremental.snapshot.chunk.key-column设置可以生效

### What did you see instead?

scan.incremental.snapshot.chunk.key-column设置之后无效，获取不到

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by supercena** [comment]
flink 1.17 oracle 11g  cdc 2.4 我这边可以

**Comment by GOODBOY008** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
