### ISSUE TITLE
[Bug] [mysql] parameter  scan.incremental.close-idle-reader.enabled did not take effect

### ISSUE THREAD

**Issue by simenliuxing** [ververica/flink-cdc-connectors#2301]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.1

### Flink CDC version

2.4.0

### Database and its version

5.7.35

### Minimal reproduce step

```
-- parameter：
set parallelism.default=3;
set execution.checkpointing.checkpoints-after-tasks-finish.enabled=true;
set scan.incremental.close-idle-reader.enabled=true;

-- sql
CREATE TABLE source(
    client_id   STRING,
    client_name STRING,
    PRIMARY KEY (client_id) NOT ENFORCED
 )WITH(
    'connector'='mysql-cdc',
    'hostname'='xx.xx.xx.xx',
    'port'='3306',
    'username'='developer',
    'password' = '******',
    'database-name'='test_xm',
    'table-name'='test_syn'
 );


CREATE TABLE sink(
    client_id   STRING,
    client_name STRING
 )WITH(
    'connector'='print'
 );

insert  
into
    sink
    select
        *      
    from
        source;
```

### What did you expect to see?

it reads snapshot of table parallelly and then reads binlog of table with single parallelism.

### What did you see instead?

After Finished several checkpoint, the parallelism is still 3 , and I see in the logs 'Snapshot split assigner received all splits finished, waiting for a complete checkpoint to mark the assigner finished ' , but There are still 3 tm running, how can I automatically release the other two tm?

May I ask where is the problem?

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by simenliuxing** [comment]
@leonardBang Can you help me?

**Comment by ruanhang1993** [comment]
@simenliuxing Please add some log when invoking `signalNoMoreSplits` in `MySqlSourceEnumerator#assignSplits`.
After the enumerator send this event, the reader should close by itself.

**Comment by simenliuxing** [comment]
@ruanhang1993 Thanks for the support, I have solved it
scan.incremental.close-idle-reader.enabled=true;  should be set in the with(...) , not  in SQL CLI:
