### ISSUE TITLE
postgres cdc该如何获取指定时间戳开始的变更数据?

### ISSUE THREAD

**Issue by cooltnt** [ververica/flink-cdc-connectors#2303]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink1.17.1

### Flink CDC version

cdc 2.4.0

### Database and its version

postgres 14.8

### Minimal reproduce step

mysql cdc中可设置timestamp属性
'scan.startup.mode' = 'timestamp',
'scan.startup.timestamp-millis' = '时间戳ms'
从而达到可以从该设置时间点开始获取binlog,  而不用全量同步.  当然是在没有checkpoint和savepoint的情况下(也包含某些异常中断的情况),   请问pg如何实现?

### What did you expect to see?

其他cdc 连接器也可以实现指定时间戳获取日志

### What did you see instead?

无

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
This is not supported in PG CDC connector. It is duplicate to #2249 . 

Let's trace the issue in #2249. Closed this issue.
