### ISSUE TITLE
[Bug][Oracle]指定主键进行增量快照读取期间，如果发生数据修改，这些修改的数据会丢失，但默认使用ROWID进行split chunk就不会数据丢失

### ISSUE THREAD

**Issue by nidonglin** [ververica/flink-cdc-connectors#2309]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.2

### Flink CDC version

2.4.0

### Database and its version

oracle  12c

### Minimal reproduce step

[Bug][Oracle]指定主键进行增量快照读取期间，如果发生数据修改，事后数据无法同步修改数据，但默认使用ROWID进行split chunk就可以

### What did you expect to see?

1.使用指定'scan.incremental.snapshot.chunk.key-column' 字段的时候最后也可以获取到全量阶段修改的数据
2.或者有什么可以配置的选项？

### What did you see instead?

使用指定'scan.incremental.snapshot.chunk.key-column' 字段可以并行读取快照，但是却会丢失读取全量快照期间修改的数据，使用ROWID就不会丢失这期间修改的数据

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by e-mhui** [comment]
使用ROWID也可以并行快照读取呀

**Comment by nidonglin** [comment]
> 使用ROWID也可以并行快照读取呀

ROWID是可以，但是相比较使用数值类型的主键要慢几个数量级，大表尤其明显，而且使用ROWID的时候用到了大小比较，在某些时候这个比较有BUG，具体可以看我提的issu https://github.com/ververica/flink-cdc-connectors/issues/2296

**Comment by GOODBOY008** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
