### ISSUE TITLE
[Bug] [Oracle] Oracle CDC capture schema change event failed

### ISSUE THREAD

**Issue by e-mhui** [ververica/flink-cdc-connectors#2311]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13.5

### Flink CDC version

2.4
master

### Database and its version

oracle 11g

### Minimal reproduce step

Trigger schemaChange event.

<img width="1413" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/111486498/74488f27-4300-477f-ab27-9502dbea6167">

### What did you expect to see?

Processing schemaChange events normally

### What did you see instead?

Processing schemaChange events normally

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Fixed in #2315
