### ISSUE TITLE
[Bug] Could not execute DBMS_LOGMNR.START_LOGMNR: ORA-44609: CONTINOUS_MINE is desupported for use with DBMS_LOGMNR.START_LOGMNR

### ISSUE THREAD

**Issue by BigStone2018** [ververica/flink-cdc-connectors#2323]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13

### Flink CDC version

flink cdc.  2.1.1

### Database and its version

oracle 19c

### Minimal reproduce step

1.  install oracle version is 19c
2. use flink cdc to collect the cdc log of oracle database  and flink cdc version is 2.1.1

### What did you expect to see?

Successfully read the changelog

### What did you see instead?

19c: Could not execute DBMS_LOGMNR.START_LOGMNR: ORA-44609: CONTINOUS_MINE is desupported for use with DBMS_LOGMNR.START_LOGMNR.

### Anything else?

Urgent

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
@BigStone2018 Oracle 19c do not support continuous mine.
