### ISSUE TITLE
[Bug] 2.4版本下的sqlserver cdc 会监听所有同名不同库的表

### ISSUE THREAD

**Issue by yangrenqing** [ververica/flink-cdc-connectors#2333]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.7.0

### Flink CDC version

2.4

### Database and its version

sqlserver 2012 SP4

### Minimal reproduce step

首先准备一个sqlserver  实例。
在实例下建A、B俩个数据库。
在A、B数据库下建立 同名的表 比如 test_tb， 并且都开启CDC。

启动一个flink job监听 sqlserver,   sink我使用了kafka
代码片段如下:
...
.databaseList("A")
.tableList("dbo.test_tb")
...

### What did you expect to see?

kafka 中有A数据库下的 dbo.test_tb的表的实时监听数据。

### What did you see instead?

kafka 中发现   A、B数据库下的 dbo.test_tb的表的数据都被监听了。
实际上B数据库下的表并不需要。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Thanks for your report this issue , it had fixed in 2.4.1.
