### ISSUE TITLE
[Bug] java.lang.IllegalAccessError: failed to access class io.debezium.embedded

### ISSUE THREAD

**Issue by zzfzhou** [ververica/flink-cdc-connectors#2341]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.0

### Flink CDC version

2.3.0

### Database and its version

oracle19c

### Minimal reproduce step

数据有变化后者checkpoint的时候，关闭checkpoint就不会出现;但是到Oracle数据层读取以及sink中的操作都已执行完毕，checkpoint也创建成功，所有数据无异常，均执行成功

### What did you expect to see?

不出现异常

### What did you see instead?

checkpoint时有异常

### Anything else?

failed to access class io.debezium.embedded.EmbeddedEnginehangeEvent from class com.ververica,cdc ,debezium,internal,DebeziumChange(onsumer (io,debezium,embedded.EmbeddedEngineChangeEvent and com,ververica,cdc,debezium,internal.DebeziumChangeConsumeiare in unnamed module of loader 'app')

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
