### ISSUE TITLE
Please add some documentation notes

### ISSUE THREAD

**Issue by komiblog** [ververica/flink-cdc-connectors#2344]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Problems encountered:
When I program with the flink-connector-mysql-cdc package, which is using the provided scope, I customize a deserializer and package the project as a jar package. Then I downloaded the flink-connector-mysql-cdc package in the flink lib directory, started the flink cluster, uploaded the jar package to the flink webUI and reported this error:

2023-07-26 15:59:03,544 ERROR org.apache.flink.runtime.webmonitor.handlers.JarPlanHandler  [] - Unhandled exception.
org.apache.flink.util.FlinkRuntimeException: Error in serialization.
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/apache/kafka/connect/source/SourceRecord
Caused by: java.lang.NoClassDefFoundError: org/apache/kafka/connect/source/SourceRecord
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.connect.source.SourceRecord

I didn't find the root cause, probably because I didn't find a relevant dependency. This might indicate that the flink-connector-mysql-cdc package still has problems adapting in flink.

So I replaced both with the flink-sql-connector-mysql-cdc package. One thing to note here is that the package guide in the custom deserializer's file needs to be changed a bit:
import com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.Field;
import com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.Schema;
import com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.Struct;
import com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.source.SourceRecord;

Then you can run through it.

### Solution

I'm sure there are a lot of people using the datastream api who will run into this problem.
My suggestion:
In the official documentation it is stated that custom deserializers require the flink-sql-connector-mysql-cdc package.
Or adapt the flink-connector-mysql-cdc package, I noticed that the deserialization guide package is different in the two packages, which may be the cause of the problem.

### Alternatives

It is also possible to package the flink-connector-mysql-cdc package directly into the jar package.
But it's best to point this out so that no one encounters this problem again

### Anything else?

Maybe I'll have time to revise the docs in a while.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by rbreejen** [comment]
Better to not use provided scope and include the necessary dependencies in your jar. flink-connector-mysql-cdc is not an uber jar, so it does not include dependencies. Hence the NoClassDefFoundError I assume.

**Comment by komiblog** [comment]
> Better to not use provided scope and instead include the necessary dependencies in your jar. flink-connector-mysql-cdc is not an uber jar, so it does not include dependencies. Hence the NoClassDefFoundError I assume.


It could be for the reason you mentioned. It would be better to explain the difference between the two packages in the documentation, following the example in the documentation, the usage of the flink-connector-mysql-cdc package could be mistakenly assumed to be placed in the lib directory like the flink-sql-connector-mysql-cdc package. Alternatively, add a comment line stating that datastream api programming should be packaged in its entirety and not use "provided scope".

**Comment by komiblog** [comment]
I found an explanation of the difference in the FAQ

**Comment by jikuanyu** [comment]
太感谢了，浪费了我一天时间找原因。

**Comment by komiblog** [comment]
> 太感谢了，浪费了我一天时间找原因。

能帮到你就好

**Comment by yanye666** [comment]
我遇到问题，是少了包，打包的时候有的包不能 修改scope 为provide
