### ISSUE TITLE
[Bug] Oracle CDC：the CLOB type fileds can not be read

### ISSUE THREAD

**Issue by zhuyue66** [ververica/flink-cdc-connectors#2347]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.0

### Flink CDC version

2.4.1

### Database and its version

Oracle 11g deployed in docker

### Minimal reproduce step

1. Set up the Oracle database environment and create the test table using:
```
CREATE TABLE FLINKUSER.TEST (
	ID NUMBER(38,0) NOT NULL,
	DOC CLOB NULL,
	CONSTRAINT TEST_PK PRIMARY KEY (ID)
);
```
2. Launch the Flink cluster and the SQL Client.
3. Creat the table DDL in SQL Client using:
```
CREATE TABLE OTESTDOC (
   ID BIGINT,
   DOC STRING,
   PRIMARY KEY (ID) NOT ENFORCED
) WITH (
   'connector' = 'oracle-cdc',
   'hostname' = 'localhost',
   'port' = '1521',
   'username' = 'flinkuser',
   'password' = 'flinkpw',
   'database-name' = 'HELOWIN',
   'schema-name' = 'FLINKUSER',
   'debezium.log.mining.strategy'='online_catalog',
   'debezium.log.mining.continuous.mine'='true',
   'debezium.lob.enabled'='true',
   'table-name' = 'TESTDOC'
);
```
4. Then exec the collect job using:
```
SELECT * FROM OTESTDOC;
```

### What did you expect to see?

the CLOB-type fields value is NULL

### What did you see instead?

the actual value

### Anything else?

Is the Debezium<1.9.7.Final> version of Flink-CDC<2.4.1> based on support reading the CLOB-type fields?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liugddx** [comment]
refer to https://debezium.io/blog/2021/06/24/debezium-1-6-cr1-released/

**Comment by GOODBOY008** [comment]
@zhuyue66 Please check dbz configuration `lob.enabled`.

If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
