### ISSUE TITLE
[Bug] java.lang.NoSuchFieldError: ALLOW_UNALIGNED_SOURCE_SPLITS

### ISSUE THREAD

**Issue by heine0310** [ververica/flink-cdc-connectors#2348]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.1

### Flink CDC version

2.4.1

### Database and its version

PG15

### Minimal reproduce step

public class PostgresCDCExample2 extends BaseAppLocal {
    public static void main(String[] args) throws IOException {
        new PostgresCDCExample2().init(
                4007,
                2,
                "PostgresCDCExample2",
                "PGSQL"
        );
    }

    @Override
    protected void handle(StreamExecutionEnvironment env, DataStreamSource<byte[]> stream) {

        DebeziumDeserializationSchema<String> deserializer =
                new JsonDebeziumDeserializationSchema();

        JdbcIncrementalSource<String> postgresIncrementalSource =
                PostgresSourceBuilder.PostgresIncrementalSource.<String>builder()
                        .hostname("hadoop162")
                        .port(5432)
                        .database("test_db")
                        .schemaList("public")
                        .tableList("public.t_user")
                        .username("postgres")
                        .password("aaaaaaaa")
                        .slotName("flink2")
                        .decodingPluginName("pgoutput") // use pgoutput for PostgreSQL 10+
                        .deserializer(deserializer)
                        .includeSchemaChanges(true) // output the schema changes as well
                        .splitSize(2) // the split size of each snapshot split
                        .build();

        env.fromSource(
                        postgresIncrementalSource,
                        WatermarkStrategy.noWatermarks(),
                        "PostgresParallelSource")
                .setParallelism(2)
                .print();

        try {
            env.execute("Output Postgres Snapshot");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}

### What did you expect to see?

Changing data can be monitored

### What did you see instead?

3274 [Source: PostgresParallelSource -> Sink: Print to Std. Out (1/2)#0] WARN  org.apache.flink.runtime.taskmanager.Task  - Source: PostgresParallelSource -> Sink: Print to Std. Out (1/2)#0 (ea6f90bb6118a54fd1b7c175ba858911_cbc357ccb763df2852fee8c4fc7d55f2_0_0) switched from INITIALIZING to FAILED with failure cause: java.lang.NoSuchFieldError: ALLOW_UNALIGNED_SOURCE_SPLITS
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.<init>(SplitFetcherManager.java:143)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.<init>(SplitFetcherManager.java:107)
	at org.apache.flink.connector.base.source.reader.fetcher.SingleThreadFetcherManager.<init>(SingleThreadFetcherManager.java:80)
	at org.apache.flink.connector.base.source.reader.fetcher.SingleThreadFetcherManager.<init>(SingleThreadFetcherManager.java:63)
	at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceReader.<init>(IncrementalSourceReader.java:93)
	at com.ververica.cdc.connectors.base.source.IncrementalSource.createReader(IncrementalSource.java:124)
	at com.ververica.cdc.connectors.base.source.IncrementalSource.createReader(IncrementalSource.java:66)
	at org.apache.flink.streaming.api.operators.SourceOperator.initReader(SourceOperator.java:286)
	at org.apache.flink.streaming.runtime.tasks.SourceOperatorStreamTask.init(SourceOperatorStreamTask.java:94)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:692)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:669)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:935)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:904)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:728)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:550)
	at java.lang.Thread.run(Thread.java:748)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by kieryum** [comment]
我遇到一个问题是从kafka connecter 中 获取源的时候出现这个错误。
需要怎么做才能让这个代码跑起来呢？
下面是我的代码：
StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();


        KafkaSource<Event> jamKafka = KafkaSource.<Event>builder()
                .setBootstrapServers("192.168.100.100:9092")
                .setTopics("socket")
                .setGroupId("sk_group")
                .setStartingOffsets(OffsetsInitializer.latest())
                .setValueOnlyDeserializer(new EvenSchema())
                .build();

        DataStreamSource<Event> jamsSource = env.fromSource(jamKafka, WatermarkStrategy
                .<Event>forBoundedOutOfOrderness(Duration.ofSeconds(0))
                //.withIdleness(Duration.ZERO.withSeconds(1))
                .withTimestampAssigner((event, timestamp) -> {
                    System.out.println("kafak 获取到的：" + event.getTime());
                    return event.getTime();
                }), "Jams Source");

        jamsSource
                .process(new ProcessFunction<Event, Event>() {

                    @Override
                    public void processElement(Event value, ProcessFunction<Event, Event>.Context ctx, Collector<Event> out) throws Exception {
                        long l = ctx.timerService().currentWatermark();
                        System.out.println("当前水位线" + l);
                        out.collect(value);
                    }
                })
                .keyBy(Event::getValue)
                // .window(SlidingEventTimeWindows.of(Time.seconds(3), Time.seconds(6)))
                .reduce(new ReduceFunction<Event>() {
                    @Override
                    public Event reduce(Event value1, Event value2) throws Exception {
                        return value2;
                    }
                })

                .print();

**Comment by loserwang1024** [comment]
@heine0310 ,  It seems you have different `flink-connectors` dependencies in your flink usr lib. This ALLOW_UNALIGNED_SOURCE_SPLITS is added in  flink 1.17.

**Comment by loserwang1024** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
