### ISSUE TITLE
[Bug]oceanbase cdc 无法同步增量数据

### ISSUE THREAD

**Issue by ya724** [ververica/flink-cdc-connectors#2356]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.2

### Flink CDC version

2.4.0

### Database and its version

oceanbase 4.1.0.1

### Minimal reproduce step

        ResolvedSchema resolvedSchema =
                new ResolvedSchema(
                        Arrays.asList(
                                Column.physical("id", DataTypes.INT().notNull()),
                                Column.physical("name", DataTypes.STRING().nullable()),
                                Column.physical("age", DataTypes.INT().nullable()),
                                Column.physical("address", DataTypes.STRING().nullable())),
                        Collections.emptyList(),
                        UniqueConstraint.primaryKey("pk", Collections.singletonList("id")));

        RowType physicalDataType =
                (RowType) resolvedSchema.toPhysicalRowDataType().getLogicalType();
        TypeInformation<RowData> resultTypeInfo = InternalTypeInfo.of(physicalDataType);
        String serverTimeZone = "+00:00";

        OceanBaseDeserializationSchema<RowData> deserializer =
                RowDataOceanBaseDeserializationSchema.newBuilder()
                        .setPhysicalRowType(physicalDataType)
                        .setResultTypeInfo(resultTypeInfo)
                        .setServerTimeZone(ZoneId.of(serverTimeZone))
                        .build();
        
        SourceFunction<RowData> oceanBaseSource =
                OceanBaseSource.<RowData>builder()
                        .rsList("192.168.10.106:2882:2881")
                        .startupMode(StartupMode.INITIAL)
                        .username("root")
                        .password("xxxx")
                        .tenantName("sys")
                        .databaseName("^flink_test$")
                        .tableName("^test01$")
                        //.tableList("def.flink_test.test01")
                        .hostname("192.168.10.106")
                        .port(2881)
                        .compatibleMode("mysql")
                        .logProxyHost("192.168.10.106")
                        .logProxyPort(2983)
                        .jdbcDriver("com.mysql.cj.jdbc.Driver")
                        //.workingMode("memory")
                        //.connectTimeout(Duration.ofSeconds(120))
                        .serverTimeZone(serverTimeZone)
                        .deserializer(deserializer)
                        .build();

        return oceanBaseSource;

### What did you expect to see?

初始化数据之后能继续获取增量数据

### What did you see instead?

上面代码能正常初始化数据，但是无法继续获取增量数据

### Anything else?

无

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by jikuanyu** [comment]
我遇到同样的问题，刚开始可以增量不同。登一段时间就不可以了。也没有任务错误。
我使用的版本是  <groupId>com.ververica</groupId>
            <artifactId>flink-connector-oceanbase-cdc</artifactId>
            <version>2.4.1</version>

**Comment by 51anygo** [comment]
me too

**Comment by whhe** [comment]
OceanBase CE `4.1.0.1` is released with tag  [v4.1.0_CE_BP2](https://github.com/oceanbase/oceanbase/releases/tag/v4.1.0_CE_BP2), which is compatible with `oblogproxy` v1.1.2 or later version. Please make sure you are using the correct package of `oblogproxy`, which should be [v1.1.2](https://github.com/oceanbase/oblogproxy/releases/tag/v1.1.2) or [v1.1.3](https://github.com/oceanbase/oblogproxy/releases/tag/v1.1.3).


If you are using the correct packages and there is still the same exception, please provide the error log at oblogproxy `run/${client id}/log` and we can check it for further research.
