### ISSUE TITLE
[Bug] After mysql adds a table, only the increment is synchronized, no snapshot is taken

### ISSUE THREAD

**Issue by JNSimba** [ververica/flink-cdc-connectors#2359]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.0

### Flink CDC version

2.4.1

### Database and its version

mysql8

### Minimal reproduce step

cannot be reproduced stably

### What did you expect to see?

After adding a new table,   can synchronize the snapshot and incremental

### What did you see instead?

After the new table is added, only the increment is synchronized, not sync snapshot.

### Anything else?

step：
1. stop as savepoint
2. add table name is : GAIA_SALES_CATALOG
3. start from savepoint

in taskmanager log，I found this log:
```
2023-08-02 14:46:48,162 DEBUG io.debezium.connector.mysql.MySqlDatabaseSchema              [] - Processing snapshot DDL 'CREATE TABLE `GAIA_SALES_CATALOG` ( 
2023-08-02 14:46:48,791 INFO  com.ververica.cdc.connectors.mysql.source.reader.MySqlSourceReader [] - Source reader 0 discovers table schema for new added tables of binlog split binlog-split success
```

but in jobmanager log，No log for delivering snapshot split was found

[jobmanager_log.txt](https://github.com/ververica/flink-cdc-connectors/files/12237325/jobmanager_log.txt)
[taskmanager_container_e07_1689153219187_0129_01_000003_log.txt](https://github.com/ververica/flink-cdc-connectors/files/12237326/taskmanager_container_e07_1689153219187_0129_01_000003_log.txt)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Level1Accelerator** [comment]
我全量增量都一样的，配的*，mysql里加表，cdc同步不到。这估计是改批了，以前的版本还可以的
