### ISSUE TITLE
flink cdc可不可以支持，配置从最早或者最新的地方开始消费数据——postgresql

### ISSUE THREAD

**Issue by 409713427** [ververica/flink-cdc-connectors#2367]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.0

### Flink CDC version

2.3.0

### Database and its version

postgresql

### Minimal reproduce step

设置snapshotMode: never后
每次启动提示一下
Read xlogStart at 'LSN{61A/9824DB78}' from transaction '9086176'
No previous LSN found in Kafka, streaming from the latest xlogpos or flushed LSN...
于是每次启动都从日志开始的地方读取，为什么会找不到LSN呢

### What did you expect to see?

postgresql中没有schema_only这个选项，该如何实现呢

### What did you see instead?

MySQL中指定snapshotMode: schema_only可以实现

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by gtk96** [comment]
Are you using the incremental snapshot mode? if sure, you can " 'scan.startup.mode' = 'latest-offset'"  to verify whether it meets your needs.

**Comment by 409713427** [comment]
> 

Thank you for your reply, but it did not solve my problem
``` java
//1.创建执行环境
        Configuration configuration = new Configuration();
        configuration.setBoolean("scan.incremental.snapshot.enabled",true);
        configuration.setString("scan.startup.mode","latest-offset");
        configuration.setInteger(WebOptions.PORT, flinkConfig.getUiPort());
        StreamExecutionEnvironment env = StreamExecutionEnvironment.createLocalEnvironmentWithWebUI(
                configuration);
```
After I configure it this way, it still generates a snapshot when it starts for the first time

**Comment by gtk96** [comment]
Theoretically, this startup mode will not execute snapshots. I suggest using sql to do a verification.

**Comment by 409713427** [comment]
> Theoretically, this startup mode will not execute snapshots. I suggest using sql to do a verification.

Do you know how slots are automatically deleted when the spring boot project is stopped? Currently, deleting slots is a feasible method.

**Comment by gtk96** [comment]
> > Theoretically, this startup mode will not execute snapshots. I suggest using sql to do a verification.
> 
> Do you know how slots are automatically deleted when the spring boot project is stopped? Currently, deleting slots is a feasible method.

I haven't used flink in spring boot.

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
