### ISSUE TITLE
mysql整库同步到doris时报错

### ISSUE THREAD

**Issue by zhanghengdashuaibi** [ververica/flink-cdc-connectors#2373]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

java.lang.NoSuchMethodError: io.debezium.ddl.parser.mysql.generated.MySqlParser$DefaultValueContext.NULL_LITERAL()Lorg/antlr/v4/runtime/tree/TerminalNode

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
