### ISSUE TITLE
[Bug] Postgres Incremental Snapshot "slot.drop.on.stop" is always true

### ISSUE THREAD

**Issue by jalilalchy** [ververica/flink-cdc-connectors#2378]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.4

### Flink CDC version

2.4.1

### Database and its version

Postgres 11

### Minimal reproduce step

Create a postgres incremental source like so:

```
        Properties p = new Properties();
        p.put("scan.incremental.snapshot.enabled", true);
        p.put("debezium.slot.drop.on.stop", false);
        return PostgresSourceBuilder.PostgresIncrementalSource.<String>builder()
                .deserializer(new JsonDebeziumDeserializationSchema())
                .tableList("public.*") // , "public.customers", "public.comps"
                .database(secrets.postgresDb)
                .hostname(secrets.postgresHost)
                .port(secrets.postgresPort)
                .username(secrets.postgresUsername)
                .password(secrets.postgresPassword)
                .decodingPluginName("pgoutput")
                .slotName(slotName + "test")
                .debeziumProperties(p)
                .splitSize(4)
                .build();
```

Then use it. 

### What did you expect to see?

That the consumer does not produce the warn message: 

```
[Source Data Fetcher for Source: postgres_web_outbox (1/4)#0] WARN io.debezium.connector.postgresql.PostgresTaskContext - Connector has enabled automated replication slot removal upon restart (slot.drop.on.stop = true). This setting is not recommended for production environments, as a new replication slot will be created after a connector restart, resulting in missed data change events.
```

### What did you see instead?

```
[Source Data Fetcher for Source: <redacted> (1/4)#0] WARN io.debezium.connector.postgresql.PostgresTaskContext - Connector has enabled automated replication slot removal upon restart (slot.drop.on.stop = true). This setting is not recommended for production environments, as a new replication slot will be created after a connector restart, resulting in missed data change events.
```

### Anything else?

Not entirely sure if this is actually a bug or intended, but I think that it is worth specifying in the documents if it is intended. 

Also, if you pass a table list of `public.*` it seems that it reruns PostgresSchema for every table every close and reopen. 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by WilliamTan778** [comment]
最新版本使用正常 flink1.17.1 cdc2.4.1 @jalilalchy

**Comment by jalilalchy** [comment]
@WilliamTan778 just clarifying that this works as expected on 2.4.1 for 1.17.1? I still think for 1.15 it needs to be resolved as it is a supported version and certain Flink providers like AWS KDA do not support 1.17 yet.

**Comment by loserwang1024** [comment]
Hi, @jalilalchy , it's not depended on Flink version. It's a normal setting. 

Why Debezium Postgres connector is not recommended to set debezium.slot.drop.on.stop = true is that it has only one thread. If it's stop and debezium.slot.drop.on.stop = true, the slot will be removed, So it has to restart the snapshot peried.

In incremental.snapshot period, we will read backfill streaming data for each Snapshot split. Many replication slot is created in this period.So after one Snapshot split is done, we will remove its replication slot. 

The scan.incremental.snapshot.enabled of  Streaming spilt  is  false. You can verify this by stop the flink job during streaming period. You can see the slot is still here.
So it's better not use debezium.slot.drop.on.stop param, postgres cdc will do it. 

More over, I'd like to set scan.incremental.snapshot.enabled of  Streaming spilt always false later.

**Comment by loserwang1024** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
