### ISSUE TITLE
mysql的blob类型字段，而且数据是compress

### ISSUE THREAD

**Issue by zhbdesign** [ververica/flink-cdc-connectors#2386]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

mysql的blob类型字段，而且数据是compress压缩进去的，比如INSERT INTO table ( request) VALUES( compress('name') );，这个cdc采集后应该怎么解析处理

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
We have to add the UDF to handle the compressed fields. 
CDC connector only read these values from the binlog or by selecting. It has no ability to uncompress the values.
