### ISSUE TITLE
怎样用cdc读取mysql然后写入mysql新的表中，并创建一个持续运行的作业呢

### ISSUE THREAD

**Issue by LiangXiam** [ververica/flink-cdc-connectors#239]
我像用flink通过cdc读取mysql中的表，然后进行一定加工处理，计算当天实时新增的客户数，再写回到mysql中，并且作业要一直运行，应该怎么用flink sql实现呢。使用yarn的per job模式

**Comment by Tandoy** [comment]
sourece:mysql-cdc --> Transformation --> sink：mysql即可

**Comment by LiangXiam** [comment]
> sourece:mysql-cdc --> Transformation --> sink：mysql即可

使用flink SQL的cdc方式读取多张表，是每张表都会产生一个流吗，然后join的时候是怎样一个过程。比如使用cdc source方式建了2张表，A和B，A和B进行join，由于数据是一直过来的，然后处理了流向下游，如10分的时候，A中的一条数据可以关联上B中的一条数据，之后到20分的时候，A中的这条数据又可以关联到B中的新产生的一条数据，那么flink是怎么处理的呢，由于flink是不存储数据的，难道是把A和B到来的数据一直缓存在状态里吗，那随着程序一直运行，状态不是会原来越大，最后处理不了了吗。如果是3张flink的流表关联，不就是更复杂了吗，又是怎么处理的呢

**Comment by leonardBang** [comment]
双流join的数据是存在state里的，确保可以关联上，默认state中数据永久保留，保证语义正确，是会一直增大。
（1）状态是可以配置ttl的，根据你的业务需求配置即可，ttl过期的数据会自动清理。
（2）状态不是缓存，生产上一般是rocksdb，hdfs之类的分布式系统。

**Comment by LiangXiam** [comment]
> 双流join的数据是存在state里的，确保可以关联上，默认state中数据永久保留，保证语义正确，是会一直增大。
> （1）状态是可以配置ttl的，根据你的业务需求配置即可，ttl过期的数据会自动清理。
> （2）状态不是缓存，生产上一般是rocksdb，hdfs之类的分布式系统。

状态设置ttl清理了，那之后关联表的时候不会有问题吗，比如A表中的某条记录在状态中被清除了，那么B表中有新增的数据能跟A中的这条被删除的记录 join 上时，这样不会有问题吗

**Comment by afghl** [comment]
> 双流join的数据是存在state里的，确保可以关联上，默认state中数据永久保留，保证语义正确，是会一直增大。
> （1）状态是可以配置ttl的，根据你的业务需求配置即可，ttl过期的数据会自动清理。
> （2）状态不是缓存，生产上一般是rocksdb，hdfs之类的分布式系统。

1. 想请问这个双流join是基于flink的`intervalJoin`么？
2. 有一种场景，想问下处理结果和原理是怎样的：有tableA(流A)和tableB(流B)，tableA的更新每天只有几次，也就是流A非常稀疏，然后tableB更新较频繁，这样会join出来什么？如果流B的某一个消息过来，但在flink的state里没有对应的一条流A的事件，那么这条B的消息是会丢弃掉么？

**Comment by baisui1981** [comment]
> 态是可以配置ttl的，根据你的业务需求配置即可，ttl过期的数据会自动清理。
> （2）状态不是缓存，生产上一般是rocksdb，hdfs之类的分布式系统。

还有一个情况没有考虑到，双流join的程序是在，数据库里本来就有大量数据的情况下启动的，这时候 A表发生更新，然后B表数据在state中没有（数据库中是存在），这个时候flink的join就会执行不了
