### ISSUE TITLE
[Bug] flink cdc  can deal  the primary key with `bigint unsigned` type

### ISSUE THREAD

**Issue by zhangjun0x01** [ververica/flink-cdc-connectors#2401]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.0

### Flink CDC version

2.4.1

### Database and its version

8

### Minimal reproduce step

1. the date type of the primary key is `bigint unsigned`
2. start a flink job to read the table 

```
CREATE TABLE mysource (
    id DECIMAL(20,0),
    project_id BIGINT,
    PRIMARY KEY(id) NOT ENFORCED
    ) WITH (
    'connector' = 'mysql-cdc',
    'hostname' = 'localhost',
    'port' = '3306',
    'username' = 'root',
    'password' = 'root',
    'database-name' = 'xxx',
    'table-name' = 'xxx'
)


```

### What did you expect to see?

we can get the data 

### What did you see instead?

![image](https://github.com/ververica/flink-cdc-connectors/assets/25563794/ea376b8c-c4e6-4ca3-ad71-80c290411e47)

the job is blocked

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Maybe you should set a smaller chunk size when reading. 

If the problem still exists, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Comment by zhangjun0x01** [comment]
> Maybe you should set a smaller chunk size when reading.
> 
> If the problem still exists, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

it is a bug of mysql jdbc connector, I have found the reason.
