### ISSUE TITLE
pgsql 主从复制 的集群 如果主从切换了 CDC是不是就没办法了 只能手动改代码？

### ISSUE THREAD

**Issue by JasonFang1993** [ververica/flink-cdc-connectors#2419]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

pgsql 主从复制 的集群 如果主从切换了 CDC是不是就没办法了 只能手动改代码？ 希望能支持这种情况

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by wallkop** [comment]
This should not be supported by the CDC.
Master-slave switching is the behavior of the database itself. Users should develop peripheral programs for automatic monitoring, such as using timed tasks or notification mechanisms.

**Comment by loserwang1024** [comment]
Hi, @JasonFang1993 , See https://debezium.io/documentation/reference/connectors/postgresql.html#how-the-postgresql-connector-works
`Logical decoding replication slots are supported on only primary servers When there is a cluster of PostgreSQL servers, the connector can run on only the active primary server. It cannot run on hot or warm standby replicas. If the primary server fails or is demoted, the connector stops. After the primary server has recovered, you can restart the connector. If a different PostgreSQL server has been promoted to primary, adjust the connector configuration before restarting the connector.`

It's the limitation of the mechanism of the  postgresql database itself. Now that only  primary servers has logical decoding replication slots,  postgres cdc can do nothing without replication slot

**Comment by loserwang1024** [comment]
Hi, @JasonFang1993 , from pg16, can [read replication data from slave databse](https://www.decodable.co/blog/logical-replication-from-postgres-16-stand-by-servers-part-1-of-2), and we also  upgrade version of debezium to support it, SEE https://github.com/ververica/flink-cdc-connectors/pull/3034. 

Please closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
