### ISSUE TITLE
[Bug] oracle clob type update could not be synced

### ISSUE THREAD

**Issue by caoliang-web** [ververica/flink-cdc-connectors#2434]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17

### Flink CDC version

2.4.1

### Database and its version

oracle 11c

### Minimal reproduce step

create table:
CREATE TABLE "ADMIN"."T_FLINK_DORIS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"C1" CLOB, 
	"D1" DATE, 
	"V1" VARCHAR2(255), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("C1") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))

insert :
INSERT INTO "ADMIN"."T_FLINK_DORIS" ("ID", "C1", "D1", "V1") VALUES ('3', '12345', TO_DATE('2023-08-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '12666');
INSERT INTO "ADMIN"."T_FLINK_DORIS" ("ID", "C1", "D1", "V1") VALUES ('1', '1234567', TO_DATE('2023-08-23 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '123wq32');
INSERT INTO "ADMIN"."T_FLINK_DORIS" ("ID", "C1", "D1", "V1") VALUES ('2', '123456555', TO_DATE('2023-08-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '1243434');
INSERT INTO "ADMIN"."T_FLINK_DORIS" ("ID", "C1", "D1", "V1") VALUES ('4', '1245622', TO_DATE('2023-08-28 17:01:25', 'SYYYY-MM-DD HH24:MI:SS'), '2111');

update:
UPDATE "ADMIN"."T_FLINK_DORIS" SET "C1" = '12456223', "D1" = TO_DATE('2023-08-28 17:01:25', 'SYYYY-MM-DD HH24:MI:SS'), "V1" = '2111' WHERE "ID" = '4';

### What did you expect to see?

"C1" = '12456223' 
Synchronize to the target library

### What did you see instead?

The update update statement is not captured，Resulting in no change in the target database data

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Duplicated with another issue, Please refer to https://github.com/ververica/flink-cdc-connectors/issues/2434.
