### ISSUE TITLE
Flink cdc限制同步速度

### ISSUE THREAD

**Issue by huigesv123** [ververica/flink-cdc-connectors#2444]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

我们使用阿里云Flink cdc sql将mysql 某个表同步到本地doris，由于我们与公司其他共用一条带宽，而且是小带宽，那个表的数据也比较多，一启动全量同步时，把带宽打爆了。

### Solution

希望后续cdc sql和jar升级时可以考虑设置同步速度。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by gong** [comment]
@huigesv123 Hi, maybe you can set debezium.query.fetch.size=512 and scan.incremental.snapshot.chunk.size = 4096 to reduce speed.

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
