### ISSUE TITLE
OceanBase CDC DataStream Source不支持.deserializer(new JsonDebeziumDeserializationSchema() 必须配置ResolvedSchema导致无法在同一程序获取多张不同结构表的数据

### ISSUE THREAD

**Issue by Toroidals** [ververica/flink-cdc-connectors#2450]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

flink版本：flink-1.15.2
cdc版本：2.4.1
OceanBase版本：企业版3.2.4
oblogproxy版本：2.3.0
支持deserializer(new JsonDebeziumDeserializationSchema()) 配置

### Solution

注释掉以下代码：
        /*ResolvedSchema resolvedSchema =
                new ResolvedSchema(
                        Arrays.asList(
                                Column.physical("id", DataTypes.INT().notNull()),
                                Column.physical("name", DataTypes.STRING().notNull())),
                        Collections.emptyList(),
                        UniqueConstraint.primaryKey("pk", Collections.singletonList("id")));

        RowType physicalDataType =
                (RowType) resolvedSchema.toPhysicalRowDataType().getLogicalType();
        TypeInformation<RowData> resultTypeInfo = InternalTypeInfo.of(physicalDataType);
        String serverTimeZone = "+00:00";

        OceanBaseDeserializationSchema<RowData> deserializer =
                RowDataOceanBaseDeserializationSchema.newBuilder()
                        .setPhysicalRowType(physicalDataType)
                        .setResultTypeInfo(resultTypeInfo)
                        .setServerTimeZone(ZoneId.of(serverTimeZone))
                        .build();*/

配置为可运行：
        SourceFunction<RowData> oceanBaseSource =
                OceanBaseSource.<RowData>builder()
                        .rsList("127.0.0.1:2882:2881")
                        .startupMode(StartupMode.INITIAL)
                        .username("user@test_tenant")
                        .password("pswd")
                        .tenantName("test_tenant")
                        .databaseName("^test_db$")
                        .tableName("^test_table$")
                        .hostname("127.0.0.1")
                        .port(2881)
                        .compatibleMode("mysql")
                        .jdbcDriver("com.mysql.jdbc.Driver")
                        .logProxyHost("127.0.0.1")
                        .logProxyPort(2983)
                        .serverTimeZone(serverTimeZone)
                        **.deserializer(new JsonDebeziumDeserializationSchema()**
                        .build();

### Alternatives

无

### Anything else?

无

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by phoeph** [comment]
Hi @whhe , may I know is there any update now?

**Comment by whhe** [comment]
> Hi @whhe , may I know is there any update now?

I will raise a pull request in this week to implement this feature.

**Comment by phoeph** [comment]
I found JsonDebeziumDeserializationSchema is useful while we use version

<dependency>
    <groupId>com.ververica</groupId>
    <artifactId>flink-sql-connector-oceanbase-cdc</artifactId>
    <version>2.2.1</version>
</dependency>

**Comment by phoeph** [comment]
> > Hi @whhe , may I know is there any update now?
> 
> I will raise a pull request in this week to implement this feature.

when we can use this feature? maybe 2.4.2 ? or I can just copy your code in my project :)

**Comment by whhe** [comment]
> > > Hi @whhe , may I know is there any update now?
> > 
> > 
> > I will raise a pull request in this week to implement this feature.
> 
> when we can use this feature? maybe 2.4.2 ? or I can just copy your code in my project :)

This feature will be back in next release of minor or major version, and before that you can have a try with my fork branch.

**Comment by phoeph** [comment]
many thanks.

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
