### ISSUE TITLE
[Bug] Flink CDC is not working with Flink 1.18

### ISSUE THREAD

**Issue by maver1ck** [ververica/flink-cdc-connectors#2452]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.18-SNAPSHOT

### Flink CDC version

2.4.1 but 2.5-SNAPSHOT is also affected.

### Database and its version

MySQL 8.0.31

### Minimal reproduce step

Create Flink project with Flink version 1.18 and Flink-CDC connector

### What did you expect to see?

Project should compile

### What did you see instead?

Caused by: java.lang.ClassNotFoundException: org.apache.flink.shaded.guava30.com.google.common.util.concurrent.ThreadFactoryBuilder

### Anything else?

The reason of this problem is update of guava version to 31 in Flink 1.18 when Flink-CDC is still using 30.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by gtk96** [comment]
@maver1ck 
<img width="879" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/34996528/b87e3444-6209-4cba-bddc-b2a7a5694724">
Keep the version here consistent with Flink 1.18 and recompile the cdc master branch

**Comment by maver1ck** [comment]
@gtk96 
Do you have plan to upgrade this in 2.5 when Flink 1.18 will come ?

**Comment by maver1ck** [comment]
I created PR for this issue.
https://github.com/ververica/flink-cdc-connectors/pull/2463

**Comment by gtk96** [comment]
> @gtk96 Do you have plan to upgrade this in 2.5 when Flink 1.18 will come ?
> 
> Also changing only pom.xml will result in:
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project flink-connector-debezium: Compilation failure: Compilation failure:
> [ERROR] /Users/maverick/src/ezdihar/flink-cdc-connectors/flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumSourceFunction.java:[39,73] package org.apache.flink.shaded.guava30.com.google.common.util.concurrent does not exist
> [ERROR] /Users/maverick/src/ezdihar/flink-cdc-connectors/flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumSourceFunction.java:[219,21] cannot find symbol
> [ERROR]   symbol:   class ThreadFactoryBuilder
> [ERROR]   location: class com.ververica.cdc.debezium.DebeziumSourceFunction<T>
> ```

<img width="828" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/34996528/2fa1f4a1-ff41-4a5c-97c4-8b4590f1bbc7">
I think we also need to make corresponding modifications here
