### ISSUE TITLE
[Bug] flink-connector-oracle-cdc.version：2.4.0监听了oracle所有的schema的表数据变更？而不是我指定的schema

### ISSUE THREAD

**Issue by jasonhewg** [ververica/flink-cdc-connectors#2467]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.2

### Flink CDC version

flink-connector-oracle-cdc.version：2.4.0

### Database and its version

oracle19c

### Minimal reproduce step

SourceFunction sourceOracle = OracleSource.builder()
.hostname("172.16.131.xxx")
.port(1521)
.database("ORCL")
.schemaList("FILE_MINIO")
.tableList("FILE_MINIO.FILE_DETAIL")
.username("FILE_MINIO")
.password("xxx")
.debeziumProperties(properties)
.deserializer(new JsonDebeziumDeserializationSchema())
.build();

通过上面的OracleSource我指定了具体需要监控的某一个schema，如：FILE_MINIO，但RelationalSnapshotChangeEventSource输出日志显示，会监听oracle所有的schema，部分日志：
INFO [debezium-oracleconnector-oracle_logminer-change-event-source-coordinator][192]io.debezium.relational.RelationalSnapshotChangeEventSource : Adding table ORCL.GL_YDW.A202_XPHARMA_USER_DETAIL to the list of capture schema tables
2023-09-06 23:08:07.559
INFO [debezium-oracleconnector-oracle_logminer-change-event-source-coordinator][192]io.debezium.relational.RelationalSnapshotChangeEventSource : Adding table ORCL.GROUP_YDW.XPHARMA_GROUPING_USER_BU_SYNC to the list of capture schema tables
2023-09-06 23:08:07.560
INFO [debezium-oracleconnector-oracle_logminer-change-event-source-coordinator][192]io.debezium.relational.RelationalSnapshotChangeEventSource : Adding table ORCL.EBR_SF_YDW.A202_XPHARMA_MAT_CUSTOM_MAN to the list of capture schema tables
2023-09-06 23:08:07.560
INFO [debezium-oracleconnector-oracle_logminer-change-event-source-coordinator][192]io.debezium.relational.RelationalSnapshotChangeEventSource : Adding table ORCL.SF_YDW.A202_XPHARMA_AUTOCODE_SN to the list of capture schema tables
2023-09-06 23:08:07.560
INFO [debezium-oracleconnector-oracle_logminer-change-event-source-coordinator][192]io.debezium.relational.RelationalSnapshotChangeEventSource : Adding table ORCL.NACOS_CONFIG.USERS to the list of capture schema tables
2023-09-06 23:08:07.560
INFO [debezium-oracleconnector-oracle_logminer-change-event-source-coordinator][192]io.debezium.relational.RelationalSnapshotChangeEventSource : Adding table ORCL.GL_YDW.A202_XPHARMA_NL_PRINT_TEMPLATE to the list of capture schema tables
2023-09-06 23:08:07.560
INFO [debezium-oracleconnector-oracle_logminer-change-event-source-coordinator][192]io.debezium.relational.RelationalSnapshotChangeEventSource : Adding table ORCL.EBR_SF_YDW.A202_XPHARMA_MAT_ENCRYPTION to the list of capture schema tables
2023-09-06 23:08:07.560

### What did you expect to see?

期望只监听代码中指定的schema

### What did you see instead?

不是监听oracle所有的schema的表

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GoyaDo** [comment]
i have same question !!!!

**Comment by guziwen-lab** [comment]
+1

**Comment by guziwen-lab** [comment]
// 2.4.0之后增加这个，不需要初始化扫描全库
debeziumProperties.put("database.history.store.only.captured.tables.ddl", String.valueOf(true));

加上这个亲测有效🥳

**Comment by jasonhewg** [comment]
> 

大佬牛X，确实有效！

**Comment by guziwen-lab** [comment]
> 大佬牛X，确实有效！但为啥只能监听到r(查询)的操作事件，不能监听到插入、删除、更新的SQL操作？
> ![image](https://user-images.githubusercontent.com/88084634/266246648-e6a38196-160d-450c-b6b6-d185cffc894e.png)

我这边是正常的，可以读到插入更新操作，可能需要稍微多等一会儿。

**Comment by jasonhewg** [comment]
> 
我这边是配置的oracle用户权限问题，已解决，可以监听到插入、更新、删除 操作了，但如何屏蔽(r)查询的操作？我不需要触发(r)查询的操作。

**Comment by guziwen-lab** [comment]
> 

我是获取到数据之后会判断当前是什么操作，如果是 ’READ‘ 就不做任何操作。

**Comment by guziwen-lab** [comment]
> 我这边是配置的oracle用户权限问题，已解决，可以监听到插入、更新、删除 操作了，但如何屏蔽(r)查询的操作？我不需要触发(r)查询的操作。

我是获取到数据之后会判断当前是什么操作，如果是 ’READ‘ 就不做任何操作。

**Comment by jasonhewg** [comment]
https://github.com/ververica/flink-cdc-connectors/issues/2467#issuecomment-1709803355
目前看也只能先这样处理。另外，可以留个联系方式么？方便后续问题一起讨论，比如oracle的blob大类型字段处理等

**Comment by guziwen-lab** [comment]
> [#2467 (comment)](https://github.com/ververica/flink-cdc-connectors/issues/2467#issuecomment-1709803355)
> 目前看也只能先这样处理。另外，可以留个联系方式么？方便后续问题一起讨论，比如oracle的blob大类型字段处理等

wx: 1254654945

**Comment by GOODBOY008** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。

**Comment by GOODBOY008** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Comment by chenguosnake** [comment]
> 大佬牛X，确实有效！但为啥只能监听到r(查询)的操作事件，不能监听到插入、删除、更新的SQL操作？ ![image](https://github.com/ververica/flink-cdc-connectors/assets/88084634/e6a38196-160d-450c-b6b6-d185cffc894e)

兄弟找到问题了吗？
