### ISSUE TITLE
如何获取到transaction_id

### ISSUE THREAD

**Issue by Karl-WangSK** [ververica/flink-cdc-connectors#247]
flinkcdc如何获取到transaction_id
![image](https://user-images.githubusercontent.com/53078090/125432346-45640dcf-aa0a-427e-9d08-4eea63bcc80a.png)
读取binlog拿到的transaction_id为null

**Comment by JesseAtSZ** [comment]
I also encountered the same problem. Why was this issues closed before? Is there a solution?

**Comment by XuMengEnEli** [comment]
请问这个问题解决了么，我也遇到同样问题
