### ISSUE TITLE
[Bug] psotgrescdc抽取数据首次全量正常，后续增加value中的字段都是乱码

### ISSUE THREAD

**Issue by dadalongvs** [ververica/flink-cdc-connectors#2471]
### Search before asking

- [x] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

13.6

### Flink CDC version

2.2.1

### Database and its version

postgres版本是9.2.24

### Minimal reproduce step

![image](https://github.com/ververica/flink-cdc-connectors/assets/108457248/d8970dc9-8e6c-4db2-869c-71a9fdd4abc5)

![image](https://github.com/ververica/flink-cdc-connectors/assets/108457248/016a1e2e-a09e-4409-80ad-f1b2dcb036e2)

### What did you expect to see?

后续增量中也不出现乱码，每一次都能正常抽取

### What did you see instead?

想问一下postgrescdc为什么首次全量的时候获取到的value里的字段名称是没问题的，后续增量的时候字段名称就都变成乱码了？
![image](https://github.com/ververica/flink-cdc-connectors/assets/108457248/88570b2b-5b0c-439a-abe5-6a34bcdf1605)

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by dadalongvs** [comment]
我按照要求把postgres换成11.21，结果一样，增量还是乱码

**Comment by JasonFang1993** [comment]
感觉像是数据库的编码问题 我用的pgsql 12没问题

**Comment by dadalongvs** [comment]
> 感觉像是数据库的编码问题 我用的pgsql 12没问题

那我也用12试一下，你有特意设置过pgsql 的编码？

**Comment by dadalongvs** [comment]
> 



> 感觉像是数据库的编码问题 我用的pgsql 12没问题

还是不行，换成12.16版本的，用的反序列方式还是原本的JsonDebeziumDeserializationSchema，但我没有特意设置psql的编码格式

**Comment by dadalongvs** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/108457248/d58e9135-4e19-4df0-bef5-692e4ce6a0ac)
这是我postgres查询出来的编码格式

**Comment by dadalongvs** [comment]
![image](https://github.com/ververica/flink-cdc-connectors/assets/108457248/4583f565-2d34-436e-974f-4fb4900461d6)
这是我查询出来的数据库编码。

![image](https://github.com/ververica/flink-cdc-connectors/assets/108457248/2edd54ed-edd2-48dc-beda-60a0285f326f)
而且增量的时候数据库里的中文数据是正常的，不会乱码，乱码的只是中文字段

**Comment by dadalongvs** [comment]
> 字段是中文？我指的没问题是字段里面的数据 这个生产环境就是这样？

字段里的数据是正常的，就字段是错误的，无论采用原本的JsonDebeziumDeserializationSchema还是我自定义的反序列化，我都会去打印每次抽取的Struct value = (Struct) sourceRecord.value()，这个value的结果里就显示增量时中文数据正常不乱码，但中文字段就乱码。你曾使用过postgres里字段是中文来抽取吗？

**Comment by dadalongvs** [comment]
> 



> 字段是中文？我指的没问题是字段里面的数据 这个生产环境就是这样？

字段里的数据是正常的，就字段是错误的，采用原本的JsonDebeziumDeserializationSchema，显示数据抽取失败，当我自定义的反序列化，我会去打印每次抽取的Struct value = (Struct) sourceRecord.value()，这个value的结果里就显示增量时中文数据正常不乱码，但中文字段就乱码。你曾使用过postgres里字段是中文来抽取吗？

**Comment by rw12306** [comment]
老铁，问题解决没得哇，我也是中文字段或者中文表名乱码，但是字段值不乱码。
