### ISSUE TITLE
[Bug] flink cdc connector oracle，在不引入分布式锁的条件下(如zk、redis)，通过xStream或Debezium的简单配置，如何保证在多flink OracleSource实例下，只有一个实例可以捕获到变更数据？

### ISSUE THREAD

**Issue by jasonhewg** [ververica/flink-cdc-connectors#2480]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.2

### Flink CDC version

2.4.1

### Database and its version

oracle19c

### Minimal reproduce step

SourceFunction<String> sourceOracle = OracleSource.<String>builder()
                .hostname("172.16.130.203")
                .port(1521)
                .database("ORCL")
                .schemaList("xxx")
                .tableList(xxx)
                .username("aa")
                .password("bb")
                .debeziumProperties(properties)
                // converts SourceRecord to JSON String
                .deserializer(new JsonDebeziumDeserializationSchema())
                .build();

DataStreamSource<String> source = env.addSource(sourceOracle);
............
addSink(new SinkToOracle());
............
env.setParallelism(1);
env.getCheckpointConfig().setCheckpointingMode(CheckpointingMode.EXACTLY_ONCE);

IDEA同时启动多个实例运行后，每个实例都会监听到变更数据。在不引入外部第三方分布锁的组件的前提下等(如zk、redis)，如何保证只有一个实例能捕获到数据？

### What did you expect to see?

多实例同时运行的情况下，我需要保证只有一个实例能捕获到变更数据

### What did you see instead?

而不是同时都捕获到数据

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
