### ISSUE TITLE
[Bug] Flink-CDC 全量数据抽取 mysql 数据, 拆分Chunk 存在bug,在nextChunkEnd() 方法中当主键是string类型的情况不能正确拆分Chunk

### ISSUE THREAD

**Issue by binbin360** [ververica/flink-cdc-connectors#2489]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.4

### Flink CDC version

2.2.1  
2.3.0
2.4.0
2.4.1

### Database and its version

mysql   5.7.23-log

### Minimal reproduce step

![16946004789729](https://github.com/ververica/flink-cdc-connectors/assets/47972153/9f3205d7-65c0-4617-ad2e-15cd05eaea39)

bjectUtils.compare(chunkEnd, max) >= 0   进行 chunkEnd和 max对比是调用jdk的字符串方法进行对比的 .
现在存在一种情况,当业务数据库是utf8mb4数据集,主键是varchar类型并且不是一种生成策略(例如: 主键为:  23d13d66eb7211ea949300163e047741,622799eee91611ea949300163e047741,b4c7d16beb7311ea949300163e047741,***,***,VISITID20230525100000001241,VISITID20230525100000001242,VISITID20230525100000001243):
数据表述:
min=23d13d66eb7211ea949300163e047741
max=VISITID20230525100000001243
其他数据为 SELECT MAX(`visitId`) FROM (SELECT `visitId` FROM `studentservice`.`SsVisit7` WHERE `visitId` >= ? ORDER BY `visitId` ASC LIMIT 8096) AS T  的中间值
结果:
当拿着 b4c7d16beb7311ea949300163e047741 与 VISITID20230525100000001243进行对比 结果是>0的,cdc认为已经超过最大值返回null了,其实在数据order by  排序中 他并不是 最大值

结论:
  数据库对 varchar  的排序策略 和  jdk中 string 的 compare()方法 比较策略不一致,,导致 chunk不能正确拆分,导致后续的数据分到 一个 chunk中,造成数据hang住

### What did you expect to see?

采用一种 比较策略,不要数据库 的 order by  排序策略和  jdk 的 string比较方法compare()一起使用,,当主键生成规则不一致的情况下,存在漏洞
修改 bjectUtils.compare(chunkEnd, max) >= 0  代码

### What did you see instead?

flink cdc   抽取mysql  全量数据 hang 住不动 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by METONLIULEI** [comment]
why not change database collation from utf8mb4_bin to utf8mb4_general_ci。 Is it necessary to implement and support all character set collations of mysql。

**Comment by taizilongxu** [comment]
遇到同样问题,  实测数据库中字符串大小写字母的比较和 java 中不一致,
测试用 https://stackoverflow.com/questions/33999947/java-sorting-is-not-the-same-with-mysql-sorting  可以

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。

**Comment by taizilongxu** [comment]
@ruanhang1993 如果需要用英语请在项目里标明, 你这样关闭一个 bug 是不是有些不妥
