### ISSUE TITLE
Oracle cdc lose data，incremental snapshot based [Bug] 

### ISSUE THREAD

**Issue by JavaMrGuo** [ververica/flink-cdc-connectors#2500]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

Version: 1.16.2 

### Flink CDC version

2.5-SNAPSHOT

### Database and its version

Oracle 11g

### Minimal reproduce step

DataStream Source
The Oracle CDC connector can also be a DataStream source. There are two modes for the DataStream source:

incremental snapshot based, which allows parallel reading
SourceFunction based, which only supports single thread reading

incremental snapshot based, which allows parallel reading .Extracting data from official documents reveals that there is always one record missing

![2](https://github.com/ververica/flink-cdc-connectors/assets/49862133/4cfc7eea-9a1f-4961-8be0-27bd02348592)
![1](https://github.com/ververica/flink-cdc-connectors/assets/49862133/77de38a7-86a5-49b9-a421-7c297a66bbb3)

### What did you expect to see?

Obtain accurate record count

### What did you see instead?

Missing data records

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
@JavaMrGuo  Had fixed in Release 3.0.1, Please update and retry.
