### ISSUE TITLE
[Bug] Flink CDC Sqlserver Jobstopped. Table is locked

### ISSUE THREAD

**Issue by shuxian6688** [ververica/flink-cdc-connectors#2528]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.1

### Flink CDC version

2.4.1

### Database and its version

sqlserver2014

### Minimal reproduce step

sqlserver表，千万级订单表全量cdc，字符串主键，执行了24小时，没同步到一条数据，停止任务很久后，运维发现数据库中仍在执行  (@P0 nvarchar(4000))SELECT MAX([InterID]) FROM (SELECT TOP (8096) [InterID] FROM [dbo].[Acc_Charge] WHERE [InterID] >= @P0 ORDER BY [InterID] ASC ) AS T

### What did you expect to see?

job停止后，停止数据库中切片的判断逻辑

### What did you see instead?

![image](https://github.com/ververica/flink-cdc-connectors/assets/42971202/6f5e0193-fab8-4fd2-b399-8b208eb70af6)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
@shuxian6688 现在sqlserver 支持增量无锁的实现，可以切换尝试。
