### ISSUE TITLE
FlinkDatabaseHistory导致State无限大

### ISSUE THREAD

**Issue by yanghuaiGit** [ververica/flink-cdc-connectors#253]
FlinkDatabaseHistory 会将ddl语句存储在FlinkDatabaseHistory内部ConcurrentLinkedQueue<HistoryRecord> records  队列中。

如果监听的ddl语句很多，FlinkDatabaseHistory会不会导致historyRecordsState无限大，FlinkDatabaseHistory有限制吗

**Comment by leonardBang** [comment]
确实会，不过已经在 https://github.com/ververica/flink-cdc-connectors/pull/207 中 fix了
