### ISSUE TITLE
supports CDC consuming apache paimon table in full and incremental mode (全量+增量)

### ISSUE THREAD

**Issue by ChenShuai1981** [ververica/flink-cdc-connectors#2533]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Currently if we want to consume apache paimon table in full and incremental mode we need launch batch and streaming job respectively, it is not convenient, so could we make flink cdc supports that just like it supports consuming mysql table?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! 

为了方便各个国家的贡献者交流，请在 [Apache Jira](https://issues.apache.org/jira)  的 `Flink` 项目下重新用英文创建问题，同时在问题上将 Component 标注为 `Flink CDC`。谢谢！
