### ISSUE TITLE
flinkcdc有可能支持clickhosue或达梦数据库吗？

### ISSUE THREAD

**Issue by dadalongvs** [ververica/flink-cdc-connectors#2541]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

flinkcdc有可能支持clickhosue或达梦数据库吗？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Jiabao-Sun** [comment]
Due to the difficulty in collecting change logs from clickHouse and 达梦 database, support for them is currently not being considered.

**Comment by louislu007** [comment]
不获取达梦数据库的变更日志，是否可以支持sink 达梦 数据库，比如 从 mysql to 达梦？

**Comment by saidkind** [comment]
> 不获取达梦数据库的变更日志，是否可以支持sink 达梦 数据库，比如 从 mysql to 达梦？

可以自定义sink ，只要继承了RichSinkFunction，你可以对invoke方法进行重写，实现你自己的逻辑
