### ISSUE TITLE
[Oceanbase cdc 无法正常同步百万级以上表的数据 ]

### ISSUE THREAD

**Issue by ya724** [ververica/flink-cdc-connectors#2559]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink版本：flink-1.15.2

### Flink CDC version

cdc版本：2.4.1

### Database and its version

OceanBase版本：企业版3.2.4
oblogproxy版本：2.3.0

### Minimal reproduce step

SourceFunction oceanBaseSource =
OceanBaseSource.builder()
.configUrl( 'http://127.0.0.1:8080/services?Action=ObRootServiceInfo&User_ID=xxx&UID=xxx&ObRegion=xxx')
 .startupMode(StartupMode.LATEST_OFFSET)
.username("user@test_tenant")
.password("pswd")
.tenantName("test_tenant")
.tableList("test_db.test_table")
.hostname("127.0.0.1")
.port(2881)
.compatibleMode("oracle")
.jdbcDriver("com.oceanbase.jdbc.Driver")
.logProxyHost("127.0.0.1")
.logProxyPort(2983)
.workingMode("storage")
.serverTimeZone(serverTimeZone)
.deserializer(new JsonDebeziumDeserializationSchema()
.build();

### What did you expect to see?

我希望它持续监控和同步数据（running）而不是同步完数据就结束(finished)了。
希望
![image](https://github.com/ververica/flink-cdc-connectors/assets/48872435/39b859b5-14ae-4dfc-8216-24cff176349d)
不希望
![image](https://github.com/ververica/flink-cdc-connectors/assets/48872435/5b18f815-b35e-4c45-86e9-6e45e3eec9ec)

### What did you see instead?

无

### Anything else?

无

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by whhe** [comment]
正常情况下增量任务是不会退出的，麻烦确认下日志里有没有报异常。

**Comment by ya724** [comment]
flink日志中没有异常，我们怀疑是oblogproxy有问题, oblogproxy版本：2.3.0,
配置为：{
  "service_port": 2983,
  "encode_threadpool_size": 8,
  "encode_queue_size": 20000,
  "max_packet_bytes": 67108864,
  "record_queue_size": 20000,
  "read_timeout_us": 2000000,
  "read_fail_interval_us": 1000000,
  "read_wait_num": 20000,
  "send_timeout_us": 2000000,
  "send_fail_interval_us": 1000000,
  "check_quota_enable": false,
  "command_timeout_s": 10,
  "log_quota_size_mb": 5120,
  "log_quota_day": 7,
  "log_gc_interval_s": 43200,
  "oblogreader_path_retain_hour": 168,
  "oblogreader_lease_s": 300,
  "oblogreader_path": "./run",
  "allow_all_tenant": true,
  "auth_user": true,
  "auth_use_rs": false,
  "auth_allow_sys_user": true,
  "ob_sys_username": "xxx",
  "ob_sys_password": "xxx",
  "counter_interval_s": 2,
  "metric_enable": true,
  "metric_interval_s": 10,
  "debug": false,
  "verbose": false,
  "verbose_packet": false,
  "readonly": false,
  "count_record": false,
  "channel_type": "plain",
  "tls_ca_cert_file": "",
  "tls_cert_file": "",
  "tls_key_file": "",
  "tls_verify_peer": true,
  "liboblog_tls": false,
  "liboblog_tls_cert_path": ""
}

**Comment by GOODBOY008** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
