### ISSUE TITLE
[Bug] flinkcdc采用api方式读取Tidb乱码

### ISSUE THREAD

**Issue by tuoluzhe8521** [ververica/flink-cdc-connectors#2561]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink1.16.2/flink1.14.2

### Flink CDC version

2.4.1/2.3.0

### Database and its version

Tidb 7.1.1

### Minimal reproduce step

flinkcdc api方式连接Tidb读取数据乱码

### What did you expect to see?

正常的数据

### What did you see instead?

数据乱码

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Matthew-Mazq** [comment]
我用flinkCDC读mysql也是发生乱码了，你后面怎么解决的吗

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
