### ISSUE TITLE
[Improve][Oracle] Support capturing only target tables to improve Debezium's efficiency and reduce resource consumption

### ISSUE THREAD

**Issue by aiwenmo** [ververica/flink-cdc-connectors#2579]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

When Debezium executes an Oracle CDC task, it will load all tables which the data will be snapshotted, causing unnecessary resource consumption and increasing latency, and may even cause the task to fail due to issues with other unrelated tables.

### Solution

io.debezium.relational.RelationalSnapshotChangeEventSource.determineCapturedTables

### Alternatives

After modifying the source code of Debezium, only the target table can be captured, improving job efficiency and reducing resource consumption.

### Anything else?

This optimization has been applied in production.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Naros** [comment]
All Debezium connectors OOTB will capture the schema of all existing tables, this is normal behavior.  If you want to avoid that and only capture the schema for tables based on your include/exclude lists, you can override this behavior with Debezium's configuration by specifying the `database.history.store.only.captured.tables.ddl` with a value of `true`.

**Comment by aiwenmo** [comment]
You're right, thank you.
