### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lizhongze1** [ververica/flink-cdc-connectors#2590]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.6.0 standalone

### Flink CDC version

2.4.0

### Database and its version

mysql 5.7

### Minimal reproduce step

创建mysql任务
修改时区数据库时区，修改时区连接参数
再次提交任务
还是使用上次连接参数进行连接，会提示时区不对

### What did you expect to see?

正常连接

### What did you see instead?

创建mysql任务
修改时区数据库时区，修改时区连接参数
再次提交任务
还是使用上次连接参数进行连接，会提示时区不对

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! 

为了方便各个国家的贡献者交流，请在 [Apache Jira](https://issues.apache.org/jira)  的 `Flink` 项目下重新用英文创建问题，同时在问题上将 Component 标注为 `Flink CDC`。谢谢！
