### ISSUE TITLE
[flink-cdc-composer] Core interfaces exposed to CLI frontend

### ISSUE THREAD

**Issue by PatrickRen** [ververica/flink-cdc-connectors#2608]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Core composer interfaces exposed to the client (CLI frontend)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Jiabao-Sun** [comment]
Closed by #2656
