### ISSUE TITLE
Debugging Flink CDC

### ISSUE THREAD

**Issue by yonghaozhang** [ververica/flink-cdc-connectors#261]
Hi guys,

Flink cdc is a greate framework and useful. Good job ~.
BTW, is anyway to run Flink CDC in debug mode (e.g. in Intelij IDE), so that I can debug some application issue by myself ?

Thanks a lot

**Comment by leonardBang** [comment]
You can build the project just like other maven project, and then run the test in the project,
```
git clone https://github.com/ververica/flink-cdc-connectors.git
cd flink-cdc-connectors
mvn clean install -DskipTests
```
