### ISSUE TITLE
[Bug]  [PostgreSQL] 14.6  FlinkCDC 2.4.2 Flink 1.17.1 打开增量快照后 计算结果错误

### ISSUE THREAD

**Issue by JasonFang1993** [ververica/flink-cdc-connectors#2611]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.1

### Flink CDC version

2.4.2

### Database and its version

[PostgreSQL] 14.6

### Minimal reproduce step

用flink sql的方式消费测试表 当开启增量快照的配置选项计算的结果有明显的错误
步骤如下
PGsql建表
CREATE TABLE public."data" (
	a varchar NOT NULL,
	b int4 NULL,
	c varchar NULL,
	CONSTRAINT data_pk PRIMARY KEY (a)
);
插入数据
INSERT INTO public."data"
(a, b, c)
VALUES('1', 1, 'zhangsan');
INSERT INTO public."data"
(a, b, c)
VALUES('2', 1, 'lisi');
INSERT INTO public."data"
(a, b, c)
VALUES('3', 1, 'wangwu');
INSERT INTO public."data"
(a, b, c)
VALUES('4', 1, 'zhaoliu');
INSERT INTO public."data"
(a, b, c)
VALUES('5', 3, 'lisi');
INSERT INTO public."data"
(a, b, c)
VALUES('6', 0, 'lisi');

然后可以看到lisi 目前应该是sum 是 4
然后数据库把 id为6的lisi 的值 修改成为1之后 本应该是5的
如果最后一个增量参数打开  得到的结果就还是4 

代码如下 
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        StreamTableEnvironment tableEnv = StreamTableEnvironment.create(env);
        Configuration configuration = tableEnv.getConfig().getConfiguration();
        configuration.setString("slot.drop.on.stop", "true");

        //SELECT pg_drop_replication_slot('slot_name');

        tableEnv.executeSql("CREATE TABLE newtable (  " +
                "  a STRING,  " +
                "  b int,  " +
                "  c STRING  " +
                ") WITH (  " +
                "  'connector' = 'postgres-cdc',  " +
                "  'hostname' = '*',  " +
                "  'port' = '5432',  " +
                "  'username' = 'username',  " +
                "  'password' = 'password',  " +
                "  'database-name' = 'postgres',  " +
                "  'schema-name' = 'public',  " +
                "  'decoding.plugin.name' = 'pgoutput',  " +
                "  'slot.name' = 'flinksql',  " +
                "  'table-name' = 'data'  " +
                //"   ,'scan.incremental.snapshot.enabled' = 'true'" +
                ")");
        TableResult tableResult = tableEnv.executeSql("select c, sum(b) b from newtable group by c");
        tableResult.print();
        env.execute();

### What did you expect to see?

打开增量快照之后计算结果错误

### What did you see instead?

增量快照关闭
  //"   ,'scan.incremental.snapshot.enabled' = 'true'" +

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by loserwang1024** [comment]
@JasonFang1993 , Thanks for your report. I have some problems to reproduce  :
*  when you update date, before or between job execution?
* when you execute `SELECT pg_drop_replication_slot`, before or between job execution? And which slot do you drop?

**Comment by loserwang1024** [comment]
Hi,  @JasonFang1993 .Please use English later, then foreign users can also see the issue.

Why remove `configuration.setString("slot.drop.on.stop", "true"); `? See https://github.com/ververica/flink-cdc-connectors/issues/2431
Before 2.4.2, `configuration.setString("slot.drop.on.stop", "true"); ` will remove slot after the job is closed, then the log will be recycled. When user restart this job again, data will lose.

Flink CDC can not distinguish whether the job will not use anymore or just for restart.So, In 2.4.2 version, we not remove the slot of stream phase anymore, so data will not loss. However, it may cause the slot sum is exceed the limit , so user should remove the slot by themselves, depending on their real need.

**Comment by 2606090723** [comment]
楼主你好, 能分享一下pgsql的flinkcdc教程链接吗

**Comment by loserwang1024** [comment]
@2606090723 , See https://ververica.github.io/flink-cdc-connectors/master/content/connectors/postgres-cdc.html

**Comment by loserwang1024** [comment]
Whether does you use this slot in not only one job? They influences each other? Please not use a job named "flinkcdc_db_1000w_tb_1000w_all4", and another named "flinkcdc_db_1000w_tb_1000w_all4_2". To read snapshot split's backfill log  in multiple subtasks, will created a slot named ${slot_name}_${subtask_id}, then will remove it after read backfill log.(Becasue each slot can only establish one connection),)

**Comment by loserwang1024** [comment]
Hi, @JasonFang1993 , please closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
