### ISSUE TITLE
[flink-cdc-composer] Shared factory discovery utils for loading DataSource and DataSink by SPI

### ISSUE THREAD

**Issue by PatrickRen** [ververica/flink-cdc-connectors#2616]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Similar to the factory mechanism in Flink Table / SQL API, we need some shared factory utilizations for searching and loading source and sink, which can be used in further job composing.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Jiabao-Sun** [comment]
Hi @PatrickRen, I'm willing to finish this task.

**Comment by leonardBang** [comment]
Closed by https://github.com/ververica/flink-cdc-connectors/pull/2662
