### ISSUE TITLE
org.apache.flink.table.api.TableException: Window aggregate can only be defined over a time attribute column, but TIMESTAMP(3) encountered.

### ISSUE THREAD

**Issue by LiangXiam** [ververica/flink-cdc-connectors#262]
我在flink sql cli中定义了这样一个流表，建表语句如下
create table `scrm_external_follow_user_part`
(
    `id`                       bigint    not null comment '内部id',
    `external_userid`          string    not null comment '外部联系人的userid',
    `user_id`                  bigint    not null comment '添加了此外部联系人的企业成员id',
    `source_id`                bigint comment '来源id(来源为资料库时，为资料库的id；为网页搜索时，为事件表的id)',
    `e2u_lost_time`            timestamp(3) comment '客户删除员工时间',
    `u2e_lost_time`            timestamp(3) comment '员工删除客户时间',
    `create_time`              timestamp(3) not null comment '创建时间',
    `update_time`              timestamp(3) not null comment '更新时间'
)
WITH (
    'connector' = 'mysql-cdc',
    'username' = 'root',
    'password' = 'asfdasfewet',
    'hostname' = '172.17.23.10',
    'port' = '3306',
    'database-name' = 'senaf',
    'table-name' = 'scrm_external_follow_user')

MySQL的原表是这样的
CREATE TABLE `scrm_external_follow_user` (
  `id` bigint(20) NOT NULL COMMENT '内部id',
  `external_userid` varchar(128) NOT NULL COMMENT '外部联系人的userid',
  `user_id` bigint(20) NOT NULL COMMENT '添加了此外部联系人的企业成员id',
  `source_id` bigint(20) DEFAULT NULL COMMENT '来源id(来源为资料库时，为资料库的id；为网页搜索时，为事件表的id)',
  `e2u_lost_time` timestamp NULL DEFAULT NULL COMMENT '客户删除员工时间',
  `u2e_lost_time` timestamp NULL DEFAULT NULL COMMENT '员工删除客户时间',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='企业成员对外部联系人详情表';
这里我直接用flink SQL的 timpstamp 类型接的 mysql 的 timestamp 类型

，然后在 flink sql cli 中执行
SELECT
    HOUR(TUMBLE_START(create_time, INTERVAL '1' HOUR)) hour_of_day,
    COUNT(distinct external_userid) uv
FROM scrm_external_follow_user_part
GROUP BY TUMBLE(create_time, INTERVAL '1' HOUR);
结果报如下错误
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.table.api.TableException: Window aggregate can only be defined over a time attribute column, but TIMESTAMP(3) encountered.
![image](https://user-images.githubusercontent.com/87113955/126153231-5c1bcb87-f85a-474a-b24a-142472ab158d.png)

**Comment by fsk119** [comment]
没定义 watermark 吧

**Comment by LiangXiam** [comment]
> 没定义 watermark 吧

加上 watermark后，
````sql
create table `scrm_external_follow_user_part`
(
    `id`                       bigint    not null comment '内部id',
    `external_userid`          string    not null comment '外部联系人的userid',
    `user_id`                  bigint    not null comment '添加了此外部联系人的企业成员id',
    `source_id`                bigint comment '来源id(来源为资料库时，为资料库的id；为网页搜索时，为事件表的id)',
    `e2u_lost_time`            timestamp(3) comment '客户删除员工时间',
    `u2e_lost_time`            timestamp(3) comment '员工删除客户时间',
    `create_time`              timestamp(3) comment '创建时间',
    `update_time`              timestamp(3) comment '更新时间',
    WATERMARK FOR create_time AS create_time - INTERVAL '0.1' SECOND
)
WITH (
    'connector' = 'mysql-cdc',
    'username' = 'root',
    'password' = 'ebTfkZdMWpyZHK95',
    'hostname' = '172.17.16.10',
    'port' = '3306',
    'database-name' = 'willing_base',
    'table-name' = 'scrm_external_follow_user')
```
再执行
```sql
SELECT
    HOUR(TUMBLE_START(create_time, INTERVAL '1' HOUR)) hour_of_day,
    COUNT(distinct external_userid) uv
FROM scrm_external_follow_user_part
GROUP BY TUMBLE(create_time, INTERVAL '1' HOUR);
```
报下面的错误：
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.table.api.TableException: GroupWindowAggregate doesn't support consuming update and delete changes which is produced by node TableSourceScan(table=[[default_catalog, default_database, scrm_external_follow_user_part]], fields=[id, external_userid, user_id, source_id, e2u_lost_time, u2e_lost_time, create_time, update_time])
![image](https://user-images.githubusercontent.com/87113955/127628391-a4857db1-30d2-4070-bc9e-589002d874a2.png)

**Comment by LiangXiam** [comment]
> 没定义 watermark 吧
```sql
create table `scrm_external_follow_user_part`
(
    `id`                       bigint    not null comment '内部id',
    `external_userid`          string    not null comment '外部联系人的userid',
    `user_id`                  bigint    not null comment '添加了此外部联系人的企业成员id',
    `source_id`                bigint comment '来源id(来源为资料库时，为资料库的id；为网页搜索时，为事件表的id)',
    `e2u_lost_time`            timestamp(3) comment '客户删除员工时间',
    `u2e_lost_time`            timestamp(3) comment '员工删除客户时间',
    `create_time`              timestamp(3) comment '创建时间',
    `update_time`              timestamp(3) comment '更新时间',
    WATERMARK FOR create_time AS create_time - INTERVAL '0.1' SECOND
)
WITH (
    'connector' = 'mysql-cdc',
    'username' = 'root',
    'password' = 'ebTfkZdMWpyZHK95',
    'hostname' = '172.17.16.10',
    'port' = '3306',
    'database-name' = 'willing_base',
    'table-name' = 'scrm_external_follow_user')
```
再执行
```sql
SELECT
    HOUR(TUMBLE_START(create_time, INTERVAL '1' HOUR)) hour_of_day,
    COUNT(distinct external_userid) uv
FROM scrm_external_follow_user_part
GROUP BY TUMBLE(create_time, INTERVAL '1' HOUR);
```
报下面的错误：
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.table.api.TableException: GroupWindowAggregate doesn't support consuming update and delete changes which is produced by node TableSourceScan(table=[[default_catalog, default_database, scrm_external_follow_user_part]], fields=[id, external_userid, user_id, source_id, e2u_lost_time, u2e_lost_time, create_time, update_time])
![image](https://user-images.githubusercontent.com/87113955/127628391-a4857db1-30d2-4070-bc9e-589002d874a2.png)

**Comment by leonardBang** [comment]
这个错误是 window 算子不支持消费 changelog

**Comment by LiangXiam** [comment]
> changelog

那是不是使用mysql-cdc建flink sql表，都没法使用 TUMBLE 进行窗口聚合操作了
