### ISSUE TITLE
[flink-cdc-common] Introduce Event  related APIs

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#2624]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Introduce Event API for CDC 3.0 which represents the data in the pipeline

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lvyanquan** [comment]
This may has a higher priority because both `Source` and `Sink` rely on `Event` definitions.
