### ISSUE TITLE
[flink-cdc-common] Introduce DataSink related APIs

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#2626]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Introduce DataSink related APIs

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lvyanquan** [comment]
I'm willing to complete this.

**Comment by Jiabao-Sun** [comment]
Thanks @lvyanquan, but I'm going to complete it right away.
