### ISSUE TITLE
[flink-cdc-common] Introduce TableID to describe the identifier for data or collection

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#2629]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Introduce TableID to describe the identifier for data or collection

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
@Jiabao-Sun  https://github.com/ververica/flink-cdc-connectors/pull/2631 had completed this issue ?

**Comment by Jiabao-Sun** [comment]
> @Jiabao-Sun #2631 had completed this issue ?

Thanks @GOODBOY008, we can close it by #2631.
