### ISSUE TITLE
flink-connector-oracle-cdc-2.4.1，the CPU has been consistently high, accepting 100% load

### ISSUE THREAD

**Issue by jasonhewg** [ververica/flink-cdc-connectors#2630]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink.version-1.14.2

### Flink CDC version

flink-connector-oracle-cdc:2.4.1

### Database and its version

oracle19c ，Standalone  mode

### Minimal reproduce step

After starting the Flink CDC Oracle data capture service, it was found that the CPU has been consistently high, accepting 100% load. In addition, archive logs only retain a data volume of one day, with a size of 70GB. Capturing listening logs with a delay of about 30 minutes. How can I handle it to reduce data capture latency and high CPU load：
![Uploading data-sync-hight-cpu.png…]()

### What did you expect to see?

Reduce CPU load and capture change data with low latency

### What did you see instead?

it was found that the CPU has been consistently high, accepting 100% load

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
