### ISSUE TITLE
[flink-cdc-common] Add RecordData implementation

### ISSUE THREAD

**Issue by lvyanquan** [ververica/flink-cdc-connectors#2644]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

add implementation class of [DataRecord](https://github.com/ververica/flink-cdc-connectors/blob/5481d436c66ccc539dc0d1fb815f2d103a8ec97b/flink-cdc-common/src/main/java/com/ververica/cdc/common/event/DataRecord.java#L23), you can refer to [GenericRowData](https://github.com/apache/flink/blob/fa8ea3f9a443f555de5c5479d725e16befefc957/flink-table/flink-table-common/src/main/java/org/apache/flink/table/data/GenericRowData.java#L48) in Flink, so that we can create DataRecord for source.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by joyCurry30** [comment]
I'm willing to do this task, can you assign this to me?
