### ISSUE TITLE
[flink-cdc-pipeline-connectors] Add Implementation of DataSink In StarRocks

### ISSUE THREAD

**Issue by lvyanquan** [ververica/flink-cdc-connectors#2645]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

[StarRocks](https://www.starrocks.io/) is a fast and unified Massively Parallel Processing Database, we can try to add it to the first pipeline.

You may need to wait for https://github.com/ververica/flink-cdc-connectors/issues/2642 completed in order to deal with different kinds of SchemaChangeEvent.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by banmoy** [comment]
@lvyanquan I'd like to take it.
