### ISSUE TITLE
[flink-cdc-pipeline-connectors] Add Implementation of DataSink In Doris

### ISSUE THREAD

**Issue by lvyanquan** [ververica/flink-cdc-connectors#2646]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

[Apache Doris](https://doris.apache.org/) is an open Source MPP database, and it‘s being used by more and more enterprises.
we can try to add it to the first pipeline.

You may need to wait for https://github.com/ververica/flink-cdc-connectors/issues/2642 completed in order to deal with different kinds of SchemaChangeEvent..

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JNSimba** [comment]
I'd like to take it.

**Comment by lvyanquan** [comment]
@JNSimba Hi, now you can try to add Doris pipeline connector as Sink related APIs are done.

**Comment by leonardBang** [comment]
Resolved by 4abd86a50082ed92d3f62f5cf66e1686e423205d
