### ISSUE TITLE
[flink-cdc-pipeline-connectors] Add Implementation of DataSource in MySQL

### ISSUE THREAD

**Issue by lvyanquan** [ververica/flink-cdc-connectors#2647]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

After https://github.com/ververica/flink-cdc-connectors/pull/2638 merged, we can try to add implementation in MySQL to simulate enterprise scenarios.

You may need to wait for https://github.com/ververica/flink-cdc-connectors/issues/2642 https://github.com/ververica/flink-cdc-connectors/issues/2644 completed. 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by joyCurry30** [comment]
I'm willing to do this task, can you assign this to me?

**Comment by lvyanquan** [comment]
Hi @joyCurry30, One thing you can do in advance is to create a class implemented [DebeziumDeserializationSchema](https://github.com/ververica/flink-cdc-connectors/blob/de45676faa262d7c770a967f841c79a4ef79f62b/flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumDeserializationSchema.java#L34) that can convert SourceRecord to Event.

**Comment by joyCurry30** [comment]
> Hi @joyCurry30, One thing you can do in advance is to create a class implemented [DebeziumDeserializationSchema](https://github.com/ververica/flink-cdc-connectors/blob/de45676faa262d7c770a967f841c79a4ef79f62b/flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/src/main/java/com/ververica/cdc/debezium/DebeziumDeserializationSchema.java#L34) that can convert SourceRecord to Event(include DataChangeEvent and SchemaChangeEvent).

Ok, do I need to open a new issue to do this?
