### ISSUE TITLE
Introduce annotation for marking compatibility with Flink

### ISSUE THREAD

**Issue by PatrickRen** [ververica/flink-cdc-connectors#2658]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

It will become inevitable to depend some internal class or method in Flink, even with hacky refections in our project. As the code base grows, compatibility issues with Flink might become a heavy technical debt. Having an annotation system in advance could help reminding developers and maintainers about compatibility issues, and enables automatic compatibility check in the future.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lvyanquan** [comment]
closed as it's already done
