### ISSUE TITLE
[flink-cdc-common] add implementation for DataChangeEvent

### ISSUE THREAD

**Issue by lvyanquan** [ververica/flink-cdc-connectors#2665]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Add implementation for [DataChangeEvent](https://github.com/ververica/flink-cdc-connectors/blob/99d1ad5e528e9531ed1eb703479e7f064f910930/flink-cdc-common/src/main/java/com/ververica/cdc/common/event/DataChangeEvent.java#L28).

you can change `DataChangeEvent` from `interface` to `class`,  as It may have only one implementation class.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by joyCurry30** [comment]
I'm willing to do this task, can you assign this to me?
