### ISSUE TITLE
[cdc-common] Factory should provide ConText for Source/Sink initialization

### ISSUE THREAD

**Issue by lvyanquan** [ververica/flink-cdc-connectors#2666]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

https://github.com/ververica/flink-cdc-connectors/pull/2661 introduce Connector Factory for Source/Sink creation, what's more, we need to provide some context for initialization. We can refer to [Context in Flink](https://github.com/apache/flink/blob/master/flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/DynamicTableFactory.java#L81C10-L81C10), as it's an interface, you need to add an implementation class too.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by joyCurry30** [comment]
I'm willing to do this task, can you assign this to me?
