### ISSUE TITLE
[cdc-common] Introduce all ConfigOptions for CDC 3.0

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#2668]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

[cdc-common] Introduce all ConfigOptions for CDC 3.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lvyanquan** [comment]
one reference [ConfigOption](https://github.com/apache/flink/blob/92951a05127f1e0e2ab0ea04ae022659fc5276ab/flink-core/src/main/java/org/apache/flink/configuration/ConfigOption.java#L42), in addition, [Configuration](https://github.com/apache/flink/blob/92951a05127f1e0e2ab0ea04ae022659fc5276ab/flink-core/src/main/java/org/apache/flink/configuration/Configuration.java#L51) is also necessary.

**Comment by joyCurry30** [comment]
I'm willing to do this task, can you assign this to me?
