### ISSUE TITLE
[3.0][prepare] Translate the design docs to English

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#2689]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Translate the design docs to English, and then all contributors can work smoothly 

* Original Chinese design docs: [Flink CDC 3.0 ZH](https://docs.google.com/document/d/1yWLlcIKqIvVm1g54F3unFpnE-UNa9qNGouh5q6DzSYg/edit#heading=h.9eybbegbhrws)

* Expected English design docs: [Flink CDC 3.0 EN](https://docs.google.com/document/d/1yWLlcIKqIvVm1g54F3unFpnE-UNa9qNGouh5q6DzSYg)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by qidian99** [comment]
Interested. Please assign this task to me:)

**Comment by leonardBang** [comment]
Thanks @qidian99 for the translation work, LGTM and close this task.
