### ISSUE TITLE
[Bug] [oracle-cdc] oracle cdc will lose data during the snapshot to incremental process

### ISSUE THREAD

**Issue by yunqingmoswu** [ververica/flink-cdc-connectors#2706]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.13.5

### Flink CDC version

flink 2.4.1

### Database and its version

oracle 11g

### Minimal reproduce step

1. Create a oracle table 
2. Insert some data before synchronizing data
3. Write data to oracle continuously
4. Start sync task using the the following flink sql 
 ```
CREATE TABLE `oracle_table`(
     PRIMARY KEY (`ID`) NOT ENFORCED,
    `ID` NUMBER(11),
    `NAME` STRING,
    `AGE` NUMBER(3)
) WITH (
    'connector' = 'oracle-cdc',
    'hostname' = 'localhost',
    'username' = 'flinkuser',
    'password' = '******',
    'database-name' = 'XE',
    'schema-name' = 'FLINKUSER',
    'table-name' = 'FLINKUSER.STUDENT',
    'debezium.database.tablename.case.insensitive' = 'false',
    'debezium.log.mining.strategy' = 'online_catalog',
    'debezium.log.mining.continuous.mine' = 'true',
    'port' = '1521',
    'scan.startup.mode' = 'initial'
);

CREATE TABLE `mysql_table`(
     PRIMARY KEY (`ID`) NOT ENFORCED,
    `ID` INT,
    `NAME` STRING,
    `AGE` INT
) WITH (
    'connector' = 'jdbc',
    'url' = 'jdbc:mysql://localhost:3306',
    'username' = 'user',
    'password' = '******',
    'table-name' = 'student'
);
INSERT INTO mysql_table SELECT ID,NAME,AGE  FROM oracle_table;
```

### What did you expect to see?

Oracle cdc can fully synchronize the existing data of Oracle database tables and then incrementally synchronize the new data without data loss.

### What did you see instead?

I found that the target table data is always less than the source table data. I further found that the data in the full snapshot phase was synchronized to the target table, but part of the redo log data generated in the full snapshot phase was not synchronized to the target table.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
@yunqingmoswu Had fixed in Release 3.0.1, Please update and retry.
