### ISSUE TITLE
连接器停止的时间太长，MySQL 服务器将清除旧的 binlog 文件

### ISSUE THREAD

**Issue by lykpass** [ververica/flink-cdc-connectors#271]
If the Debezium MySQL connector stops for too long, the MySQL server purges older binlog files and the connector’s last position may be lost. When the connector is restarted, the MySQL server no longer has the starting point and the connector performs another initial snapshot. If the snapshot is disabled, the connector fails with an error.

这是debezium官网上的一句话

但是程序还是会

org.apache.kafka.connect.errors.ConnectException: The connector is trying to read binlog starting at GTIDs 02910242-ee5c-11e4-9a7e-ac853d9f54d6:1,1c3f6625-0bed-11e5-9b4b-288023a0e9c8:1-497910078,1dba8a2c-0bed-11e5-9b4b-288023a0f1ac:1-728318312,2ef5b315-4b4b-11e7-832b-6c92bf296fae:1-23149389,6b71ee1c-50ef-11eb-bd49-0c42a1e81720:1-407326628,b65953d7-6b72-11e7-94d7-7cd30ab8a822:1-1357427191,b9b297fa-04d0-11e7-b797-7cd30abda492:1-92015130,d709ba24-6b72-11e7-94d8-7cd30abeafe4:1-14049462,f780ac6c-ee5b-11e4-9a7e-ac853d9f54d4:1-708287 and binlog file 'mysql-bin.001073', pos=86097934, skipping 0 events plus 0 rows, but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.

是哪个参数没配置吗

**Comment by fsk119** [comment]
不太理解你的意思... 如果发现binlog被清除，你预期的行为是什么？

**Comment by lykpass** [comment]
> 不太理解你的意思... 如果发现binlog被清除，你预期的行为是什么？

我的预期是 程序从ck点重启后 如果找不到binlog点  直接重新做快照  而不是抛出异常 
 
原因应该是 我少配置了一个参数

debezium.snapshot.mode = when_needed

**Comment by a120610114** [comment]
> > 不太理解你的意思... 如果发现binlog被清除，你预期的行为是什么？
> 
> 我的预期是 程序从ck点重启后 如果找不到binlog点 直接重新做快照 而不是抛出异常
> 
> 原因应该是 我少配置了一个参数
> 
> debezium.snapshot.mode = when_needed

想问一下，这个问题 你解决了吗？是否会存在其它隐患呢？

**Comment by z070204z** [comment]
可以，完美！

**Comment by zhilinli123** [comment]
What is the binlog clearing mechanism? Never clean up or nearly 7 days?
