### ISSUE TITLE
[Bug] 2.4.2 CDC启动之后新增的数据库和里面的表不会监听到.

### ISSUE THREAD

**Issue by opcooc** [ververica/flink-cdc-connectors#2712]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13.2

### Flink CDC version

2.4.2

### Database and its version

mysql 5.7

### Minimal reproduce step

-

### What did you expect to see?

新增加的数据库可以被捕获并被监听

### What did you see instead?

-

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by gong** [comment]
Maybe you can supplement your config.

**Comment by opcooc** [comment]
> 也许你可以补充一下你的配置。

        Map<String, Object> map = new HashMap<>();
        map.put(JsonConverterConfig.DECIMAL_FORMAT_CONFIG, DecimalFormat.NUMERIC.name());

        Properties jdbcProperties = new Properties();
        jdbcProperties.put("useSSL", "false");

        return MySqlSource.<String>builder()
                .hostname("192.168.1.xx")
                .port(3307)
                .username("root")
                .password("password")
                .serverId("1000-10001")
                .serverTimeZone("UTC")
                .startupOptions(StartupOptions.latest())
                .scanNewlyAddedTableEnabled(true)
                .databaseList("[a-z0-9]{32}")
                .tableList("[a-z0-9]{32}.Elements")
                .jdbcProperties(jdbcProperties)
                .deserializer(new JsonDebeziumDeserializationSchema(false, map))
                .build();

**Comment by opcooc** [comment]
> Maybe you can supplement your config.
我们这每天都会生成一个UUID.replace("-","")格式的数据库 最近升级最新版本之后发现不会自动监听了， 降级到2.3.0就可以

**Comment by shiyiky** [comment]
Scan Newly Added Tables only can take it effect by savepoint or checkpoint

**Comment by shiyiky** [comment]
> Scan Newly Added Tables only can take it effect by savepoint or checkpoint with retstart flink applicaiton

In my test , i cann't use flink-cdc-connector-mysql-2.3 version to capture new db when the job is running

**Comment by opcooc** [comment]
> 扫描新添加的表只能通过保存点或检查点并重新启动flink应用程序才能生效

我刚刚从新看了下，从新运行后新增加的数据库里面的表数据可以监听到...
![image](https://g
![image](https://github.com/ververica/flink-cdc-connectors/assets/34977303/abfdebd6-c5d6-449f-848e-717edc7b1172)
ithub.com/ververica/flink-cdc-connectors/assets/34977303/85fd9c22-7849-45b1-b8dc-07be76581e63)
![image](https://github.com/ververica/flink-cdc-connectors/assets/34977303/1be2b429-640b-4449-b85a-7136fb19df57)

**Comment by shiyiky** [comment]
u can wait the flink-cdc 3.0 version and it will support capture new db without restarting job

**Comment by opcooc** [comment]
> 你可以等待flink-cdc 3.0版本，它将支持捕获新表而无需重新启动作业

好

**Comment by shiyiky** [comment]
u can close this issuse

**Comment by zhongyuandong** [comment]
> u can wait the [flink-cdc](https://issues.apache.org/jira/browse/FLINK-cdc) 3.0 version and it will support capture new table without restarting job

3.0.1支持无需重启作业捕获到新表吗？为什么我设置了scanNewlyAddedTableEnabled=true and tablelist(正则表达式) 无法支持捕获到新表呢？
