### ISSUE TITLE
flink-connector-oracle-cdc-2.4.1, delaying data capture for a long time

### ISSUE THREAD

**Issue by jasonhewg** [ververica/flink-cdc-connectors#2725]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.2

### Flink CDC version

2.4.1

### Database and its version

oracle19c

### Minimal reproduce step

After the service is started, the change data can be captured normally. However, if there is a long period of time after inserting, deleting, or modifying the table, such as more than 10 hours, it is found through logs that no capture action of the table data has been triggered. After the service restarts and returns to normal, the change data can be captured normally

### What did you expect to see?

Near real-time can trigger data capture

### What did you see instead?

 rather than delaying data capture for a long time

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
@jasonhewg Please refer the FAQ : https://github.com/ververica/flink-cdc-connectors/wiki/FAQ#oracle-cdc-faq
