### ISSUE TITLE
MySQL 8.0  运行报错 Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by robin-ming** [ververica/flink-cdc-connectors#278]
MySQL 8.0  运行报错 Public Key Retrieval is not allowed
我知道改数据源链接可以修改 但是怎么配置呢？

**Comment by yangbin09** [comment]
我写了一篇文章说这个问题
https://www.yuque.com/docs/share/f3ca167a-3e45-4d88-8de4-d35871d29c37?#%20%E3%80%8AFlink%20cdc%20mysql8.0%20%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98%E3%80%8B

**Comment by leonardBang** [comment]
@yangbin09 Would you like to open a PR to add this Q&A to [document](https://ververica.github.io/flink-cdc-connectors/master/content/connectors/mysql-cdc.html#faq) ?

**Comment by robin-ming** [comment]
> 我写了一篇文章说这个问题
> https://www.yuque.com/docs/share/f3ca167a-3e45-4d88-8de4-d35871d29c37?#%20%E3%80%8AFlink%20cdc%20mysql8.0%20%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98%E3%80%8B

我去试试

**Comment by leonardBang** [comment]
fixed in 6d2cc41
