### ISSUE TITLE
flink sql client支持yarn per job吗

### ISSUE THREAD

**Issue by ghost** [ververica/flink-cdc-connectors#279]
flink sql client支持yarn per job模式吗，现在是可以启动一个yarn session，然后启动flink sql client，然后提交的 intsert into 语句都会转换成 flink job 提交到 这个 Flink session cluster，但是生成上一般用 flink per job模式提交 job，flink sql client支持这种方式吗？

看到一个博客https://www.shangmayuan.com/a/d94b8711c29d48f8b627de25.html，说他们是用的 flink sql client 使用 yarn per job 模式提交 flink job，但是文章里没看到具体怎么使用的

**Comment by LiangXiam** [comment]
> flink sql client支持yarn per job模式吗，现在是可以启动一个yarn session，然后启动flink sql client，然后提交的 intsert into 语句都会转换成 flink job 提交到 这个 Flink session cluster，但是生成上一般用 flink per job模式提交 job，flink sql client支持这种方式吗？
> 
> 看到一个博客[https://www.shangmayuan.com/a/d94b8711c29d48f8b627de25.html，说他们是用的](https://www.shangmayuan.com/a/d94b8711c29d48f8b627de25.html%EF%BC%8C%E8%AF%B4%E4%BB%96%E4%BB%AC%E6%98%AF%E7%94%A8%E7%9A%84) flink sql client 使用 yarn per job 模式提交 flink job，但是文章里没看到具体怎么使用的

仔细又看了下，之前没注意到，在 flink-conf.yaml 中配置 exectuion.engine 为 yarn-per-job，这样通过 ./bin/sql-client.sh embedded 启动 flink sql client，提交sql就可以使用 yarn per job模式了

**Comment by LiangXiam** [comment]
![image](https://user-images.githubusercontent.com/87113955/127725977-41ce732c-5d9f-4cae-b61c-d52b3b9ff7d8.png)
如何指定 flink sql提交的 job名呢

**Comment by KelvinChi** [comment]
大佬，除了在flink-conf.yaml中修改配置外，还需要做什么操作？从官网（https://nightlies.apache.org/flink/flink-docs-release-1.14/zh/docs/deployment/config/#execution-target）看，1.14参数名是exectuion.target这个了，但在yaml中设置之后，启动flinksql client，结果却是：
`[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.`

求大佬们帮助

**Comment by haojiawei111** [comment]
我在Flink1.14实验，应该是execution.target:设置为yarn-session，而不是 exectuion.engine

**Comment by moutains** [comment]
> 我在Flink1.14实验，应该是execution.target:设置为yarn-session，而不是 exectuion.engine

类推的话，yarn-application模式就设置为yarn-application了？有知道的也可以确认下，下周自己再做个测试看下

**Comment by chachabu** [comment]
> 

不行 似乎flink sql 只支持在yarn-session 下执行

**Comment by sam2099** [comment]
flink sql 支持 yarn-application 模式吗？

**Comment by LinMingQiang** [comment]
> flink sql 支持 yarn-application 模式吗？

我了解下来是不支持，其他per-job和session我测试都没问题，一换 application就报错

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
