### ISSUE TITLE
[Bug] 使用 SQL CDC 从 mongoDB 同步数据到 Doris，自行测试发现，任务无法从 checkpoint 恢复

### ISSUE THREAD

**Issue by maben996** [ververica/flink-cdc-connectors#2844]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.16.1

### Flink CDC version

release 2.4

### Database and its version

mongo4.0，使用 flink-sql-connector-mongodb-cdc-2.4.0.jar
doris 1.2.1，使用 flink-doris-connector-1.16-1.3.0.jar

### Minimal reproduce step

1. 确认 cp 清理策略为 RETAIN_ON_CANCELLATION
2. CDC SQL 任务读 mongo 数据到 doris，source sink 表如下，先用SET 'state.backend.incremental' = 'true'增量CP来测试是否可以恢复。
<img width="1214" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/44827813/bebc7e0b-f411-4042-8eae-8256efe1ad34">
<img width="754" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/44827813/db09ef64-6c25-4ff9-85a2-19266a04d32d">
3. 任务正常写数据到doris，等待几个cp之后，cancel任务
![image](https://github.com/ververica/flink-cdc-connectors/assets/44827813/74c14fd0-ec8e-4d05-9446-da6f525ed2c5)
4. 确认hdfs上的增量CP，并将CP地址配置到SQL中，准备重启SQL恢复任务
![image](https://github.com/ververica/flink-cdc-connectors/assets/44827813/02b1bfb0-3aa0-414c-8115-ba67147731ed)
<img width="1233" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/44827813/c87589de-670b-4818-9f32-793a72ef2b05">

5. 重启任务后，观察最新CP是从 id=20开始，认为已经读取到历史CP。经过2个CP，已经有数据输出到doris

6. 但是doris中表的数据行没变。

7. 因为 doris使用的是unique key表模型，当写入的数据和表中主键一致时进行update操作。

8. 所以 认为 CDC SQL 任务消费到的mongo数据还是从头开始消费，没有从重启任务前的 CP_id = 19 的地方开始消费。

9. 同样的场景，切换到全量CP的模式，恢复任务时也是会从mongo最早的数据开始消费

### What did you expect to see?

同样的操作流程，使用CDC SQL 任务消费mysql数据到doris，就可以cancel后从指定的CP恢复任务。
mysql5.7，使用的jar为flink-sql-connector-mysql-cdc-2.4.0.jar 
想确认一下mongo CDC 是否支持CP恢复任务？

### What did you see instead?

也可能是我使用的方法不对，有没有人遇到类似的情况，欢迎复现或者测试指出问题

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Jiabao-Sun** [comment]
If `scan.incremental.snapshot.enabled` is not set to true, it is not possible to restore from a checkpoint while the snapshot phase is not yet completed. If you need to restore from a checkpoint while the snapshot phase is not yet completed, please set `scan.incremental.snapshot.enabled` to true.
