### ISSUE TITLE
[3.1][cdc-common] Use name instead of column in DropColumnEvent/AddColumnEvent

### ISSUE THREAD

**Issue by lvyanquan** [ververica/flink-cdc-connectors#2857]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

When applying DropColumnEvent, we use column name to drop column from schema, and column type is hard to be extracted from Source. Thus we don't actually need to keep a list of column, instead, we can keep a list of name.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by joyCurry30** [comment]
Hi, @lvyanquan I am will to do this task, can you assign this to me?

**Comment by ruanhang1993** [comment]
@joyCurry30 Thanks. Assign this to you.
