### ISSUE TITLE
[Bug] Only MySql connector support the schema change event right now

### ISSUE THREAD

**Issue by YesOrNo828** [ververica/flink-cdc-connectors#2865]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

Flink1.18

### Flink CDC version

master

### Database and its version

Oracle, SQL server, and db2.

### Minimal reproduce step

[Here](https://github.com/ververica/flink-cdc-connectors/blob/92e9d9ea582ef2864b9eb0c4985a4701f701d0c2/flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/utils/SourceRecordUtils.java#L98) will check if it is a schema change event. But `SCHEMA_CHANGE_EVENT_KEY_NAME` = "io.debezium.connector.mysql.SchemaChangeKey", so this method only work valid for MySql connector.

[Oracle's](https://debezium.io/documentation/reference/stable/connectors/oracle.html#oracle-schema-change-topic) Schema.name() is "io.debezium.connector.oracle.SchemaChangeKey" 

[SQL server's](https://debezium.io/documentation/reference/stable/connectors/sqlserver.html#about-the-debezium-sqlserver-connector-schema-change-topic) Schema.name() is  "io.debezium.connector.sqlserver.SchemaChangeKey"

[DB2's](https://debezium.io/documentation/reference/stable/connectors/db2.html#about-the-debezium-db2-connector-schema-change-topic) Schema.name() is "io.debezium.connector.db2.SchemaChangeKey",

### What did you expect to see?

Oracle, SQL server, and DB2 Sources should emit the schema change events.

### What did you see instead?

Update the SourceReordUtils.isSchemaChangeEvent() to work available for other connectors.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by YesOrNo828** [comment]
@leonardBang  @ruanhang1993  Do you have any idea about it? 

If you agree with me, please assign it to me. I'll try to fix it.

**Comment by GOODBOY008** [comment]
@YesOrNo828 Greate catch for this, Feel free to fix it.

**Comment by loserwang1024** [comment]
@YesOrNo828, I have also used to ask a issue to do it(https://github.com/ververica/flink-cdc-connectors/issues/2545), but seems someone else have already done it in https://github.com/ververica/flink-cdc-connectors/pull/2315.

It seems that this PR has existed for a long time and has not been merged yet
