### ISSUE TITLE
[Discuss] Mark old source with Deprecated annotation when increamental source implemented

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#2872]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

After more and more connectors had implemented increamental source and old source will be remove in future ,so we want to tell users to migrate their datastream api.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lvyanquan** [comment]
closes by https://github.com/ververica/flink-cdc-connectors/commit/08beca52d0ec15b42dd2f0290161056189cfb733.
