### ISSUE TITLE
[3.1][doc] Add  Supported Connectors and Supported Flink Versions to Overview. 

### ISSUE THREAD

**Issue by lvyanquan** [ververica/flink-cdc-connectors#2881]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

add Supported Connectors and Supported Flink Versions to [cdc-pipeline](https://ververica.github.io/flink-cdc-connectors/master/content/overview/cdc-pipeline.html) like [cdc-connectors](https://ververica.github.io/flink-cdc-connectors/master/content/overview/cdc-connectors.html)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ToJ112** [comment]
Hi, @lvyanquan  I am willing to try this task, can you assign this task to me?

**Comment by Jiabao-Sun** [comment]
Closed by #2920
