### ISSUE TITLE
[Bug] mysql分表合并同步时异常（flink-cdc-3.0.0 pipline connectoer）

### ISSUE THREAD

**Issue by spihiker** [ververica/flink-cdc-connectors#2890]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink -1.18.0

### Flink CDC version

flink-cdc-3.0.0

### Database and its version

mysql-8.0.35
doris-2.0.3

### Minimal reproduce step

mysql:
   mydb.t1_2022,mydb.t1_2023
  问题1：
         alter table mydb.t1_2023 add column c3 varchar(10);      ### 此时正常
         alter table mydb.t1_2022 add column c3 varchar(10);      ### 由于doris表已经有这个字段，sink端报错。flink job异常。
  问题2：
         create table mydb.t1_2024 like mydb.t1_2023;                 ### 新建的表，不会同步到sink端。

doris:
    mydb.t1

flink job
   mydb.t1_[0-9]+    --->>   mydb.t1

### What did you expect to see?

1.分表合并同步时，sink端只执行一次ddl或者跳过ddl错误。
2.新建分表的所有操作可以同步到sink端。

### What did you see instead?

跳过非必要的ddl日志点位来恢复同步任务。

### Anything else?

1.这种场景下，同步作业异常，该如何处理？
2.恢复作业后，能不能基于checkpoint继续同步。出问题期间的，ddl，dml会不会丢失？

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lvyanquan** [comment]
Thanks for your feedback, we will support this in the next two versions.

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
