### ISSUE TITLE
[Bug] Postgres CDC 不能获取update事件时before 信息为null，after正常

### ISSUE THREAD

**Issue by moresun** [ververica/flink-cdc-connectors#2898]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

FLink 1.17

### Flink CDC version

cdc 2.4.2

### Database and its version

Postgres 1.14

### Minimal reproduce step

在pg库中update table set col=val后，cdc捕获sourcerecord数据中before没有值，after有更新后有值，怀疑pg cdc不能获取event berfore事件

### What did you expect to see?

请确认，提供步骤

### What did you see instead?

请确认

### Anything else?

无

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by gong** [comment]
@moresun 
ALTER TABLE yourtablename REPLICA IDENTITY FULL
you can see this doc [debezium-postgresql](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-update-events)

**Comment by loserwang1024** [comment]
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!
