### ISSUE TITLE
Upgrade Debezium to 1.9.8.Final

### ISSUE THREAD

**Issue by gunnarmorling** [ververica/flink-cdc-connectors#2899]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

The Debezium team released another 1.9.x release the other day with a few bug fixes, including support for [ingesting changes from Postgres 16 read replicas](https://www.decodable.co/blog/logical-replication-from-postgres-16-stand-by-servers-part-1-of-2). I would like to suggest to update to that release therefore. Will send a PR in a bit.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
Fixed in https://github.com/ververica/flink-cdc-connectors/pull/3034.
