### ISSUE TITLE
flink-cdc sql-client

### ISSUE THREAD

**Issue by yinlingshishangS** [ververica/flink-cdc-connectors#29]
云邪老师好，我想使用sql-client flink-cdc 只用写sql的将我们上游的多张表进行聚合，打到下游mysql中，但目前测试下来，发现sql-client 即使checkpoint保存了，也无法指定checkpoint重启，那我执行group by因为其他原因需要重启，是否会导致数据出问题？这种情况有木有什么好的解决方案

**Comment by wuchong** [comment]
只要你配置了 flink 的失败重启参数，那么如果 flink sql 作业挂了，是会自动从之前的 checkpoint 处恢复的。
如果你想从指定的 checkpoint 重启，sql-client 目前还不支持。需要写 Table program 的形式，打成 jar 包，通过 flink run 命令来指定恢复。
