### ISSUE TITLE
[feature] speedup search mysql binlog when mysql-cdc-connector consume binlog by timestamp

### ISSUE THREAD

**Issue by TJX2014** [ververica/flink-cdc-connectors#2914]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

When there are many binlogs exists in mysql server, we use flink-mysql-cdc-connector to consume by a new now timestamp, flink-cdc will consume all the binlog before and continue to consume, it is very time costly and pressure hard for mysql server, network busy for network.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by YesOrNo828** [comment]
This is a valuable feature. Looking forward to the PR.

**Comment by TJX2014** [comment]
This feature has already tested on production env and I will give my PR in 3 days : )
