### ISSUE TITLE
[Bug][starrocks] SchemaChangeEvent or applyDataChangeEvent serialization will fail  after recovery.

### ISSUE THREAD

**Issue by loserwang1024** [ververica/flink-cdc-connectors#2926]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.18

### Flink CDC version

3.0

### Database and its version

anyway

### Minimal reproduce step

Current , in `EventRecordSerializationSchema`, there is a `tableInfoMap` which keeps the relationship of TableId and table information.

When SchemaChangeEvent or DataChangeEvent come, EventRecordSerializationSchema will get table info from `tableInfoMap` by tableId. If no table info , exception will occur:
```java
private void applySchemaChangeEvent(SchemaChangeEvent event) {
          // ...
            TableInfo tableInfo = tableInfoMap.get(tableId);
            if (tableInfo == null) {
                throw new RuntimeException("schema of " + tableId + " is not existed.");
            }
            // ....
    }

```
```java
    private StarRocksRowData applyDataChangeEvent(DataChangeEvent event) {
        TableInfo tableInfo = tableInfoMap.get(event.tableId());
        Preconditions.checkNotNull(tableInfo, event.tableId() + " is not existed");
       // ...
```

As a non-consistent memory variable, tableInfoMap will be empty after restore. When a new SchemaChangeEvent or DataChangeEvent come, problem occurs

### What did you expect to see?

SchemaChangeEvent or applyDataChangeEvent serialization will success after recovery.

### What did you see instead?

SchemaChangeEvent or applyDataChangeEvent serialization will fail after recovery.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by loserwang1024** [comment]
@banmoy ,CC

**Comment by lvyanquan** [comment]
[DataSinkWriterOperator](https://github.com/ververica/flink-cdc-connectors/blob/8eba91006314a814181f2af2fe44eb46e370fc1a/flink-cdc-runtime/src/main/java/com/ververica/cdc/runtime/operators/sink/DataSinkWriterOperator.java#L144-L154) will emit a CreateTableEvent after recovery.
