### ISSUE TITLE
RowDataDebeziumDeserializeSchema#convertToLong方法中，将Integer强转成Long导致bug

### ISSUE THREAD

**Issue by liaooo** [ververica/flink-cdc-connectors#293]
![image](https://user-images.githubusercontent.com/34901569/128473831-081b9ede-6478-4326-900b-c19539e703d5.png)
发现Bug。。。RowDataDebeziumDeserializeSchema#convertToLong

**Comment by leonardBang** [comment]
看下最新master，记得已经 fix了

**Comment by liaooo** [comment]
> 看下最新master，记得已经 fix了

谢谢
