### ISSUE TITLE
支持 FlinkDeployment 部署

### ISSUE THREAD

**Issue by potterhe** [ververica/flink-cdc-connectors#2930]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Flink 社区提供了 [flink-kubernetes-operator](https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-release-1.7/docs/concepts/overview/) ，为在k8s中运行flink任务提供了全生命周期管理。为配合这个operator，社区的容器镜像`flink:1.17.1` 内置了非常多的脚本(路径在镜像内的/opt/flink/bin/)。当前通过`flink-cdc.sh`提交任务的方式，无法复用这种能力。

### Solution

建议将flink-cdc的 `pipiline` 建设成一个普通的flink应用，通过flink本身提交任务的方式运行，这样就可以复用Flink社区的能力。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by fanqiejiang8** [comment]
现在FlinkCDC-3.0整库同步的业务逻辑代码和提交Flink应用的代码应该分离开，而不是只支持remote和minicluster这两种模式。
我现在已经把FlinkCDC的 pipiline 改成一个普通的flink应用，然后写了一个提交Flink应用的客户端(支持Standalone、Yarn-session、YARN-application、k8s-application)等方式提交FlinkCDC的pipeline，用来整库同步，有需要的话可以创建一个pr

**Comment by icchux** [comment]
> 现在FlinkCDC-3.0整库同步的业务逻辑代码和提交Flink应用的代码应该分离开，而不是只支持remote和minicluster这两种模式。 我现在已经把FlinkCDC的 pipiline 改成一个普通的flink应用，然后写了一个提交Flink应用的客户端(支持Standalone、Yarn-session、YARN-application、k8s-application)等方式提交FlinkCDC的pipeline，用来整库同步，有需要的话可以创建一个pr

我也是需要这个，希望可以解耦分离，能通过一个普通的flink应用，提交到阿里云的实时计算平台，可以加个微信交流一下么

**Comment by fanqiejiang8** [comment]
@icchux 可以的啊  我加你

**Comment by icchux** [comment]
> @icchux 可以的啊 我加你

@fanqiejiang8 vx: ilycheeya

**Comment by edhe1988** [comment]
> 现在FlinkCDC-3.0整库同步的业务逻辑代码和提交Flink应用的代码应该分离开，而不是只支持remote和minicluster这两种模式。 我现在已经把FlinkCDC的 pipiline 改成一个普通的flink应用，然后写了一个提交Flink应用的客户端(支持Standalone、Yarn-session、YARN-application、k8s-application)等方式提交FlinkCDC的pipeline，用来整库同步，有需要的话可以创建一个pr

这个我也需要，要不你先上传到你的github，供我参考下。嘿嘿

**Comment by potterhe** [comment]
#2934

**Comment by ykmx** [comment]
> 现在FlinkCDC-3.0整库同步的业务逻辑代码和提交Flink应用的代码应该分离开，而不是只支持remote和minicluster这两种模式。 我现在已经把FlinkCDC的 pipiline 改成一个普通的flink应用，然后写了一个提交Flink应用的客户端(支持Standalone、Yarn-session、YARN-application、k8s-application)等方式提交FlinkCDC的pipeline，用来整库同步，有需要的话可以创建一个pr

vx:   jinjin727696201  带带弟弟

**Comment by 504097723** [comment]
> @icchux 可以的啊 我加你

我需要这个,可以加个微信交流一下么,感谢

**Comment by potterhe** [comment]
flink-cdc 3.3.0 已经支持。https://nightlies.apache.org/flink/flink-cdc-docs-release-3.3/docs/deployment/kubernetes/#kubernetes-operator-mode
