### ISSUE TITLE
[Bug] flind-cdc 2.4 oracle 读取数据有丢失现象

### ISSUE THREAD

**Issue by maco6096** [ververica/flink-cdc-connectors#2945]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17

### Flink CDC version

2.4

### Database and its version

oracle19c

### Minimal reproduce step

1. 通过cdc同步oracle数据到es
2. 使用streamapi方式
3. 系统已经运行几天， 发现有数据丢失现象
4. 通过打印SourceRecored发现，数据源没有同步到丢失的数据
5. 通过logminer在oracle里分析，log是也正常的

### What did you expect to see?

不要丢失数据啊

### What did you see instead?

丢失数据是很严重的问题

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
@maco6096  Had fixed in `Release 3.0.1`, Please update and retry.
