### ISSUE TITLE
[Bug] sendSplitRequest condition optimization

### ISSUE THREAD

**Issue by yanghuaiGit** [ververica/flink-cdc-connectors#2949]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.18

### Flink CDC version

3.0

### Database and its version

mysql

### Minimal reproduce step

![image](https://github.com/ververica/flink-cdc-connectors/assets/38883656/2df13395-a7bd-4b61-9ea2-5d636c5a051f)
com.ververica.cdc.connectors.mysql.source.reader.MySqlSourceReader#start
这个地方判断条件是否应该是 <=0 而不是 <=1

### What did you expect to see?

判断条件是否应该是 <=0,checkpoint恢复后。没有分片，需要申请新的分片，如果有的话不应该申请分片，而是在splitfinished时申请分片

如果cdc这边必须是<=1，能给出原因吗

### What did you see instead?

![image](https://github.com/ververica/flink-cdc-connectors/assets/38883656/8258055a-a822-48c4-b1b7-58a1a80a5b10)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
This condition using <=1 is for the `scan.newly-added-table.enabled`. 

When restoring from a savepoint, a job may be sent the BinlogSplit. If the parallelism = 1, the source reader will not request new splits and the newly added tables will not be read.
