### ISSUE TITLE
Do you support the Neo4j plan.

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [ververica/flink-cdc-connectors#2951]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

I hope to support Neo4j as a connector for use.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lvyanquan** [comment]
There is almost no demand for this database in the community, and there are no plans for the next few versions. Need to implement it ourselves.
