### ISSUE TITLE
[Bug] flinkcdc ddl时报错file is not a valid field name，dml没问题

### ISSUE THREAD

**Issue by donsmile** [ververica/flink-cdc-connectors#2962]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17

### Flink CDC version

flink-connector-oracle-cdc 2.4.1

### Database and its version

oracle12c

### Minimal reproduce step

        String checkPointPath = "file:///flink/chk";
        String source_database = "ORCLPDB";
        String source_hostname = 
        int source_port = 8888;
        String source_schema = "C##DBZUSER";
        String source_username = 
        String source_password = 
        String source_tablelist = "C##DBZUSER.TEST_DDL";

        String sink_url = 
        String sink_username = 
        String sink_password = 
        String s_table = "FLINK.test_ddl";

        Properties debeziumProperties = new Properties();
        debeziumProperties.setProperty("converters", "oracleDate");
        debeziumProperties.setProperty("oracleDate.type", "com.cdc.converter.OracleDateConverter");
        debeziumProperties.setProperty("log.mining.strategy", "online_catalog");//redo_log_catalog
        debeziumProperties.setProperty("log.mining.continuous.mine", "true");
        debeziumProperties.setProperty("database.tablename.case.insensitive", "false");
        debeziumProperties.setProperty("database.pdb.name", source_database);
        debeziumProperties.setProperty("decimal.handling.mode", "double");

        Map<String, Object> customConverterConfigs = new HashMap<>();
        customConverterConfigs.put(JsonConverterConfig.DECIMAL_FORMAT_CONFIG, "numeric");

        JdbcIncrementalSource<String> oracleChangeEventSource =
                new OracleSourceBuilder()
                        .hostname(source_hostname)
                        .port(source_port)
                        .databaseList(source_database)
                        .schemaList(source_schema)
                        .tableList(source_tablelist)
                        .username(source_username)
                        .password(source_password)
                        .deserializer(new JsonDebeziumDeserializationSchema())
                        .includeSchemaChanges(true) // output the schema changes as well
                        .startupOptions(StartupOptions.initial())
                        .debeziumProperties(debeziumProperties)
                        .splitSize(1)
                        .build();

        Properties props = new Properties();
        props.setProperty("format", "json");
        props.setProperty("read_json_by_line", "true");
        DorisOptions dorisOptions = DorisOptions.builder()
                .setFenodes(sink_url)
                .setTableIdentifier(s_table)
                .setUsername(sink_username)
                .setPassword(sink_password).build();

        DorisExecutionOptions.Builder executionBuilder = DorisExecutionOptions.builder();
        executionBuilder.setLabelPrefix("label-doris" + UUID.randomUUID())
                .setStreamLoadProp(props);

        DorisSink.Builder<String> builder = DorisSink.builder();
        builder.setDorisReadOptions(DorisReadOptions.builder().build())
                .setDorisExecutionOptions(executionBuilder.build())
                .setDorisOptions(dorisOptions)
                .setSerializer(JsonDebeziumSchemaSerializer.builder().setDorisOptions(dorisOptions).build());

        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        // enable checkpoint
        env.enableCheckpointing(3000L);
        // set the source parallelism to 4
        env.fromSource(
                        oracleChangeEventSource,
                        WatermarkStrategy.noWatermarks(),
                        "OracleParallelSource")
                .setParallelism(1)
                .filter(new FilterFunction<String>() {
                    @Override
                    public boolean filter(String s) throws Exception {
                        log.info(s);
                        return true;
                    }
                })
                .sinkTo(builder.build())
                .setParallelism(1);
        env.execute("Print Oracle Snapshot + RedoLog");

### What did you expect to see?

输出表结构变更日志

### What did you see instead?

log.info没有输出表结构，且进行debug时，没有到断点就进行了报错

### Anything else?
ORACLE的库名、SCHEMA名、表名均是大写

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lvyanquan** [comment]
Will be fixed in https://github.com/ververica/flink-cdc-connectors/pull/2315.

**Comment by donsmile** [comment]
> Will be fixed in #2315.

SchemaChangeEventHandler，这个接口在哪个版本里，我找了一下，最新版的flink-cdc-base 3.0.0 没有看到2315的相关代码

**Comment by GOODBOY008** [comment]
https://github.com/ververica/flink-cdc-connectors/issues/1792
