### ISSUE TITLE
timestamp(3)时间取值自动删减

### ISSUE THREAD

**Issue by xuanzhi201111** [ververica/flink-cdc-connectors#2969]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.1

### Flink CDC version

2.4.2

### Database and its version

8.0.28

### Minimal reproduce step

mysql表结构定义：
update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间'
存放的数据：2024-01-04 11:00:12.200

flink cdc拿到后的数据总会把后面的00去掉，拿到的时间是：2024-01-04 11:00:12.2 导致程序在处理格式的时候会报错。
如果mysql存的时间是2024-01-04 11:00:12.220  ， cdc拿到发给kafka的就是  2024-01-04 11:00:12.22

### What did you expect to see?

无

### What did you see instead?

我

### Anything else?

无

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on Apache Jira under project Flink with component tag 'Flink CDC'. Thanks.

为了便于各个国家的开发者合作，请用英文在 Apache Jira 的 Flink项目下重新提交问题，同时将 issue 的 Component 标注为 Flink CDC。谢谢。
