### ISSUE TITLE
[Bug] [Postgres CDC] postgresSQL database connection leak

### ISSUE THREAD

**Issue by ic4y** [ververica/flink-cdc-connectors#2980]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

any

### Flink CDC version

master branch

### Database and its version

any

### Minimal reproduce step

Generating a large number of snapshotSplits during the snapshot synchronization phase can reproduce this issue.

### What did you expect to see?

A small number of connections.

### What did you see instead?

Abnormal Increase in Connection Count。

select client_addr,count(1) from pg_stat_activity group by client_addr

### Anything else?

https://github.com/ververica/flink-cdc-connectors/blob/557944488bf7e1d383365a16c68fac311989e7d8/flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresSourceFetchTaskContext.java#L193-L199

This code segment is executed once for each shard, which leads to the creation of a new connection each time and results in a leak.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by loserwang1024** [comment]
But PostgresReplicationConnection will be closed after each snapshot split read. See com.ververica.cdc.connectors.postgres.source.fetch.PostgresScanFetchTask#maybeDropSlotForBackFillReadTask.
```java
    /** Drop slot for backfill task and close replication connection. */
    private void maybeDropSlotForBackFillReadTask(
            PostgresReplicationConnection replicationConnection, boolean skipSnapshotBackfill) {
        // if skip backfill, no need to create slot here
        if (skipSnapshotBackfill) {
            return;
        }

        try {
            replicationConnection.close(true);
        } catch (Throwable t) {
            LOG.info("here exception occurs");
            throw new FlinkRuntimeException(t);
        }
    }
```

Could you please give me your cdc version?

**Comment by loserwang1024** [comment]
Thanks, i get it, I will modify it @ic4y
