### ISSUE TITLE
[hotfix] Rectify 2.5-SNAPSHOT version in release-3.0 and master branch

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#2989]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

Rectify 2.5-SNAPSHOT version in release-3.0 and master

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
@gong Hi, I found you fixed this in https://github.com/ververica/flink-cdc-connectors/pull/2870 . Are you willing to fix globally?

**Comment by gong** [comment]
> Hi @gong , I found you fixed db2 docs version in #2870 . Are you willing to fix this globally?

@GOODBOY008 ok, I will fix it.
