### ISSUE TITLE
mysql-cdc 使用flink-sql在程序中创建表，查询时报错

### ISSUE THREAD

**Issue by whsqjss** [ververica/flink-cdc-connectors#30]
mysql-cdc 使用flink-sql在程序中创建表，查询时报错，似乎是mysql-cdc table不支持update，delete等ddl语句？但是在flink sql-client中运行没有报错，数据可以查询到

`StreamExecutionEnvironment bsEnv = StreamExecutionEnvironment.getExecutionEnvironment();

EnvironmentSettings bsSettings = EnvironmentSettings.newInstance().useBlinkPlanner().inStreamingMode().build();

StreamTableEnvironment bsTableEnv = StreamTableEnvironment.create(bsEnv, bsSettings);
String createSql = " CREATE TABLE qc_day_setting ( " +
				" mn STRING, " +
				" param_code STRING, " +
				" span_value DECIMAL(12,6), " +
				" check_time TIMESTAMP(3), " +
				" status INT " +
				" ) WITH ( " +
				"   'connector' = 'mysql-cdc', " +
				"   'hostname' = '*******', " +
				"   'port' = '*******', " +
				"   'username' = '*******', " +
				"   'password' = '*******', " +
				"   'database-name' = '*******', " +
				"   'table-name' = '*******' " +
				" )";

bsTableEnv.executeSql(createSql);

TableResult results = bsTableEnv.executeSql("SELECT * FROM qc_day_setting");

results.print();

bsTableEnv.execute("123");`

**Exception in thread "main" org.apache.flink.table.api.TableException: AppendStreamTableSink doesn't support consuming update and delete changes...**

**Comment by shizhengchao** [comment]
直接执行 SELECT * FROM xxx;  这样的语句目前flink只支持在 flink-sql-client里执行。executeSql目前还不支持，所以想看输出，可以定义一个print的sink表。 insert into sink_print select * from qc_day_setting

**Comment by whsqjss** [comment]
学习了，谢谢！
