### ISSUE TITLE
[Bug] mongo-db-cdc开启scanFullChangelog模式下,如果collectionList中有多个集合会报错

### ISSUE THREAD

**Issue by yuliang0912** [ververica/flink-cdc-connectors#3008]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink 1.18

### Flink CDC version

Flink CDC 3.0

### Database and its version

mongodb 6.0

### Minimal reproduce step

当collectionList中设置超过一个collection时,且开启scanFullChangelog模式,那么只要是同一个DB中的任意一个collection发生变动时(不在collectionList中),都会报错 Query failed with error code 47 with name 'NoMatchingDocument' and error message 'Executor error during getMore :: caused by :: Change stream was configured to require a pre-image for all update, delete and replace events, but the pre-image was not found for event; 

### What did you expect to see?

我的期望是没有在collectionList中的集合发生变动不要影响程序的正常运行, 一个DB中有N个集合, 我只想侦听指定的集合,然后针对指定的集合开启前像后像功能; 

### What did you see instead?

如果collectionList中只指定一个集合时,这个问题不会发生,当超过一个满足匹配条件时,就会发生这个错误

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yuxiqian** [comment]
In current implementation, [the entire database will be watched](https://github.com/ververica/flink-cdc-connectors/blob/9abf2cf900e48df8ee314f10bac28589d77a3617/flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/utils/MongoUtils.java#L181) when an regex was provided to specify required collections. According to [MongoDB docs](https://www.mongodb.com/docs/manual/reference/method/db.watch/), `pipeline` performs filtering in the output side, which adds constraints to all collections even for those excluded by the regex.

Seems there are two ways to solve this: a) Change the method of creating stream cursor, and limit watched collection ranges; b) Change pre- & post- image option from `Required` to `WhenAvailable` [](https://github.com/ververica/flink-cdc-connectors/blob/9abf2cf900e48df8ee314f10bac28589d77a3617/flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/main/java/com/ververica/cdc/connectors/mongodb/source/utils/MongoUtils.java#L227) to suppress the error coming from unused collections.
