### ISSUE TITLE
[Bug] When using Spring Boot version 3.2.2, addSink is unable to retrieve beans

### ISSUE THREAD

**Issue by twelvet-s** [ververica/flink-cdc-connectors#3041]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.18.1

### Flink CDC version

3.0.1

### Database and its version

8

### Minimal reproduce step

Get Spring Bean

### What did you expect to see?

If it is confirmed that there is no problem with this method, the bean cannot be obtained in the Flink CDC job
```java
SpringUtils.getBean(EsProperties.class)
```

### What did you see instead?

Failed to obtain Bean, it seems that all static variables cannot be obtained, so not only Spring's beans

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lvyanquan** [comment]
The issue of integrating with Spring is not something that needs to be considered on the FlinkCDC framework.

**Comment by twelvet-s** [comment]
> The issue of integrating with Spring is not something that needs to be considered on the FlinkCDC framework.

ok
