### ISSUE TITLE
Oracle ddl has bug 

### ISSUE THREAD

**Issue by ccczhouxin** [ververica/flink-cdc-connectors#3073]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.18.1

### Flink CDC version

3.0.1

### Database and its version

oracle 11g

### Minimal reproduce step

oracle create a table，then add a new column，then flinkcdc has eoor

### What did you expect to see?

when i add column，the event can return correct data

### What did you see instead?

The event has ddl data，and the next step is sourceInfo.getString("file")，but the sourceInfo has not file attribute。
![image](https://github.com/ververica/flink-cdc-connectors/assets/43168824/9a3e0fe0-3a94-46d5-afd6-13a3bfc1a6de)
![image](https://github.com/ververica/flink-cdc-connectors/assets/43168824/919c08f5-0f9e-4a2a-ae43-4338ef478843)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by gong** [comment]
It is duplication https://github.com/ververica/flink-cdc-connectors/issues/2311. And this PR https://github.com/ververica/flink-cdc-connectors/pull/2315 will fix it. We can close it. cc @GOODBOY008.

**Comment by ccczhouxin** [comment]
> 它是重复 #2311。这个 PR #2315 将修复它。我们可以关闭它。抄送 .

ok
