### ISSUE TITLE
[Feature] Flink-CDC supports MySQL 5.6 version

### ISSUE THREAD

**Issue by zhiyuan192shine** [ververica/flink-cdc-connectors#314]
Now，Flink-CDC friendly support for MySQL5.7，but some companies still use MySQL5.6。
Please support for MySQL5.6，thanks。

**Comment by leonardBang** [comment]
@xingtao Do you want to take this one ?

**Comment by xiangtao** [comment]
yes i wish it @leonardBang

**Comment by xiangtao** [comment]
flink-cdc support mysql 5.6 depends on debezium, debezium only test in mysql 5.7, 8.0.x.   but i found debezium 
1.2.x version also add mysql 5.5 and 5.6 test matrix. see [https://issues.redhat.com/browse/DBZ-1953?jql=text%20~%20%22mysql%205.6%22 ](url). 

I'm going to add some test case for mysql 5.6.  if you has some good test condition  , you can provide here.

**Comment by james9203** [comment]
supports MySQL 5.6 ,please
