### ISSUE TITLE
[Feature] CDC 2.0 supports Flink 1.12 version

### ISSUE THREAD

**Issue by zhiyuan192shine** [ververica/flink-cdc-connectors#316]
Now，Hudi0.9 use Flink-1.12，but cdc2.0 use Flink.1.13，Flink version is not compatible.
Please，CDC2.0 Support flink multiple version, thanks.

**Comment by fsk119** [comment]
The feedback from the DingTalk.
![image](https://user-images.githubusercontent.com/33114724/131323499-9d18665d-73a4-4818-9186-6f8ad9c3fdc4.png)

**Comment by fsk119** [comment]
Same request from the dingtalk. 
![1630653152435-28cacd7d-3963-40f9-9b84-fa0bc377f17a](https://user-images.githubusercontent.com/33114724/132158451-e2c01c9c-5f7c-47af-a265-e2f5998a84c6.png)
