### ISSUE TITLE
flink sql用kafka作为源建表多分区问题

### ISSUE THREAD

**Issue by LiangXiam** [ververica/flink-cdc-connectors#319]
CREATE TABLE topic_products (
  -- schema is totally the same to the MySQL "products" table
  id BIGINT,
  name STRING,
  description STRING,
  weight DECIMAL(10, 2)
) WITH (
 'connector' = 'kafka',
 'topic' = 'products_binlog',
 'properties.bootstrap.servers' = 'localhost:9092',
 'properties.group.id' = 'testGroup',
 'format' = 'maxwell-json'
)
kafka中products_binlog这个topic是maxwell同步到kafka写入的，但是如果这个topic有多个分区，
如插入两条数据，产生2条binlog到products_binlog这个topic的 分区1中，
之后又删除了这两条数据，产生的binlog到roducts_binlog这个topic的 分区0中，
flink sql读取kafka数据的时候，先读取分区0中的数据，然后才读取分区1中的数据，
这样会不会flink sql查出来的结果是有 2 条数据，但实际表中已经没有数据了

**Comment by fsk119** [comment]
We should keep the record whose primary key is same shouble be in the same partition.

**Comment by LiangXiam** [comment]
> We should keep the record whose primary key is same shouble be in the same partition.

OK, I know. Another question, if there are binlogs of multi tables in one topic, what if defining a table like this, would this occur some problem. 
for example, there is another table with 2 columns besides table topic_products in topic products_binlog

**Comment by fsk119** [comment]
Do you mean the schema of the tables are totally different? Flink SQL requires the source/sink has explicit schema... I think you should send the binlog of the different table to the different topic or partition. Flink Kafka connector also supports to read data from the specific partition[1].

[1] https://ci.apache.org/projects/flink/flink-docs-master/docs/connectors/table/kafka/#scan-startup-specific-offsets

**Comment by fsk119** [comment]
By the way, we should discuss about CDC here. If you have any questions about the usage of the Flink Kafka connector, you should send your questions to the Flink mail list[1].

[1] https://flink.apache.org/community.html#mailing-lists
