### ISSUE TITLE
多个sink对于checkpoint的影响

### ISSUE THREAD

**Issue by Kaiux** [ververica/flink-cdc-connectors#32]
我们目前从MySQL拉取增量数据，处理后分别写入到kafka和pika，但是由于pika写入的性能远小于kafka，导致在checkpoint的时候，kafka sink会等待pika sink很长一段时间。考虑过把kafka sink和pika sink拆分成2个不同的job，但是拆分成2个job意味着有2个debezium连接mysql，会对mysql造成较大的压力。请问这种情况有什么好的解法吗，谢谢。 @wuchong

**Comment by zengqingdong** [comment]
如果你的两个sink使用的都是mysql的同一张表的话，可以使用StreamTableEnvironment（tEnv）的executeSql方法创建source table和sink table，使用StatementSet statementSet = tEnv.createStatementSet()把生成的steam放在statementSet里，使用statementSet.addInsertSql分别执行不同的作业（输出多个sink端），这个方法在我们的项目也有使用

**Comment by Kaiux** [comment]
> 如果你的两个sink使用的都是mysql的同一张表的话，可以使用StreamTableEnvironment（tEnv）的executeSql方法创建source table和sink table，使用StatementSet statementSet = tEnv.createStatementSet()把生成的steam放在statementSet里，使用statementSet.addInsertSql分别执行不同的作业（输出多个sink端），这个方法在我们的项目也有使用

这也是一个办法，感谢！

**Comment by wuchong** [comment]
Close this question then.
