### ISSUE TITLE
The Debezium doc url  in doc and class is not mismatch debezium actual version.

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#322]
Hi,@leonardBang.
I finded that debezium doc url  in doc and class is mismatch debezium actual version.
![image](https://user-images.githubusercontent.com/13617900/129541238-a3200bc9-377b-4631-a52f-948ae24b0a42.png)
I'm willing to contrubute and fix it.
Thank you!

**Comment by leonardBang** [comment]
Nice catch, after we upgraded the Debezium version to `1.5.2.Final`, we should have update them but not, welcome to contribute.

**Comment by GOODBOY008** [comment]
> Nice catch, after we upgraded the Debezium version to `1.5.2.Final`, we should have update them but not, welcome to contribute.

I will submit a pr.Please code review for me.Thank you!
