### ISSUE TITLE
initial模式只执行表快照，表的变更并没有捕捉到，有遇到同样问题的吗

### ISSUE THREAD

**Issue by liaooo** [ververica/flink-cdc-connectors#338]
scan.startup.mode设置为initial模式下，启动后成功执行了全量快照。但是通过对表记录的修改操作后，从日志上并没有看到有捕捉到相应的修改

**Comment by liaooo** [comment]
貌似过了好几分钟之后同步过来了

**Comment by leonardBang** [comment]
为了确保全局有序，2.0里有个机制是在全量读完后等一个checkpoint之后再发送binlog数据，如果是测试，可以把checkpoint时间设置短一点，线上生产正常设置。如果不设置，多并发时，可能会存在binlog和snapshot数据乱序问题。

**Comment by liaooo** [comment]
> 为了确保全局有序，2.0里有个机制是在全量读完后等一个checkpoint之后再发送binlog数据，如果是测试，可以把checkpoint时间设置短一点，线上生产正常设置。如果不设置，多并发时，可能会存在binlog和snapshot数据乱序问题。

多谢解答，通过日志我也发现了
