### ISSUE TITLE
Tracking User Requirements

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#341]
## New Feature Requirement
* [x] #11 
* [x] #88 
* [x] #76 
* [x] #313
* [ ] #316 
* [ ] #74 
* [x] #145
* [x] #144  
* [x] #174 
* [x] #94 

## Usability Requirement
* [x] #175 
* [x] #48 
* [x] #162
* [ ] #82

**Comment by lugela** [comment]
支持使用stream api情况下不锁表

**Comment by miaogr86** [comment]
source 支持自定义并行度吗

**Comment by cbwn123** [comment]
debezium升级，1.5.4太旧了

**Comment by lizhuoxuan** [comment]
可以支持PostgreSQL 14吗？

**Comment by metathrone** [comment]
db2 connector支持

**Comment by junjiecheng1** [comment]
flink cdc source schema 自动同步至sink 库

**Comment by junjiecheng1** [comment]
flink cdc  同一个库，多个表的job 合并执行，减少  源库的全量读取次数

**Comment by junjiecheng1** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38483436/204318947-5d391b8e-521c-48f9-acf2-efbac466b8af.png">
这两个功能有开源计划吗

**Comment by leonardBang** [comment]
> <img alt="image" width="1512" src="https://user-images.githubusercontent.com/38483436/204318947-5d391b8e-521c-48f9-acf2-efbac466b8af.png">
> 
> 这两个功能有开源计划吗

这两个功能需要阿里云上 Flink（VVR） + Flink CDC 配合实现，单独的 Flink CDC Connector 无法实现这种效果，所以 单独依赖 Flink CDC 这个项目没法实现 ，而VVR主要包括阿里云的的Flink企业版的一些商业化功能，我个人理解就是在开源基础为商业版用户做的增强，应该是不会开源的。

**Comment by switlen** [comment]
support sqlserver 2008 R2

**Comment by BrokenWingsIcarus** [comment]
support neo4j

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
