### ISSUE TITLE
[docs] The example in tutorials doc missed checkpoint and primary key setting

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#342]
The example in tutorials doc [tutorials](https://ververica.github.io/flink-cdc-connectors/master/content/tutorials/tutorial.html) missed checkpoint and primary key setting.
Since CDC 2.0， checkpoint and primary key in CDC table are required,
Thus we should fix the doc for master branch and release-2.0 branch

**Comment by frey66** [comment]
assigned me
