### ISSUE TITLE
[build] Optimize the document scripts to push only if current PR modified docs 

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#343]
Optimize the document scripts `docs/build_docs.sh` to run only if current change modified docs,
rather than executing for every PR.

**Comment by GOODBOY008** [comment]
@leonardBang I'm willing to contribute this optimiziton.

**Comment by leonardBang** [comment]
@GOODBOY008 Thanks, assign to you.

**Comment by caidezhi** [comment]
GOODBOY008  seems not working on it. submit a PR for this. @leonardBang

**Comment by GOODBOY008** [comment]
> GOODBOY008 seems not working on it. submit a PR for this. @leonardBang

Do you have interest on this issue ? I will assign to you. @caidezhi
