### ISSUE TITLE
[build] Add docker scripts for document site

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#346]
Currently it's hard to preview document site in local environment, we can add a docker scripts to build the document site in local environment to help developers contributing document easily.

**Comment by luoyuxia** [comment]
I would like to take it

**Comment by linqichen2020** [comment]
@leonardBang  hello,  it seem that luoyuxia is not working on this. I would like to take this job. Can you offer me more info about this issue ???

**Comment by leonardBang** [comment]
Have fixed in https://github.com/ververica/flink-cdc-connectors/pull/430

**Comment by leonardBang** [comment]
> @leonardBang hello, it seem that luoyuxia is not working on this. I would like to take this job. Can you offer me more info about this issue ???

Sorry for the late reply, I close this ticket as @luoyuxia  has fixed this issue but we forgot to close this issue.
