### ISSUE TITLE
[SUPPORT] Support the integration with TiCDC

### ISSUE THREAD

**Issue by SteNicholas** [ververica/flink-cdc-connectors#355]
TiCDC is TiDB's change data capture framework, which supports replicating change data to various downstreams, including MySQL protocol-compatible databases, message queues via the open CDC protocol and other systems such as local file storage. 
Does the Flink CDC connector consider to integrate with the TiCDC directly?

**Comment by findczk** [comment]
+1

**Comment by wuchong** [comment]
https://github.com/TiFlink/TiFlink  this is a good project which integrates TiCDC and Flink SQL .

**Comment by yangyongyongyong** [comment]
+1

**Comment by deadwind4** [comment]
+1

**Comment by baisui1981** [comment]
+1

**Comment by DKfengyi** [comment]
+1

**Comment by eastfisher** [comment]
Will it support full and incremental migration?

**Comment by leonardBang** [comment]
Duplicated issue, let's track in #243
