### ISSUE TITLE
[mysql] Optimize the checkpoint be optional under single parallelism

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#360]
Throw exception message if the checkpoint is not set when `incremental.snapshot` enable , because `scan.incremental.snapshot.enabled` feature requires checkpoint setting.

**Comment by todd5167** [comment]
Can it be verified in MySqlParallelSource#createReader.
The `scan.incremental.snapshot.enabled` parameter is used to create a ParallelSource. When the createReader method is executed, the SourceReaderContext can be used to determine whether to enable checkpoint.

**Comment by leonardBang** [comment]
Implemented in a26096910e52f2aec261177435e38c350e1eedba
