### ISSUE TITLE
[CDC2.0] 完成快照阶段后,没有进行增量阶段

### ISSUE THREAD

**Issue by findczk** [ververica/flink-cdc-connectors#368]
cdc2.0 部分mysql实例在完成快照阶段后,没有进入增量阶段 (有些mysql实例可正常进入增量阶段),是否需要另外设置什么配置?
mysql-version:5.7.20
**ddl :**
`CREATE TABLE forums_post_12_source (
`pid` BIGINT,
`tid` BIGINT,
`uid` BIGINT,
`ip` STRING,
`dateline` BIGINT,
`message` STRING,
`isthread` INT,
`update_time` BIGINT,
`status` INT,
`nick` STRING,
`privatize` BIGINT,
`tagid` INT,
`src` INT,
`terminal` STRING,
`origin_floor` INT,primary key (pid)  not enforced) WITH (
      'connector' = 'mysql-cdc',
      'hostname' = 'xxx',
      'port' = 'xxx',
      'username' = 'cnbbsReadonly',
      'password' = 'LLKFN*k2412',
      'server-time-zone' = 'Asia/Shanghai',
      'database-name' = '4399_cnbbs',
      'table-name' = 'forums_post_12',
      'server-id' = '5400-5410'      
    )`

**Comment by smile710** [comment]
请问下解决了嘛？我也遇到了同样的问题。
