### ISSUE TITLE
flink sql postgres cdc 模式下报错

### ISSUE THREAD

**Issue by lzzcj** [ververica/flink-cdc-connectors#37]
[ERROR] Could not execute SQL statement. Reason:
org.postgresql.util.PSQLException: 错误: 无法访问文件 "decoderbufs": No such file or directory
请问这是什么原因，貌似是pg的问题，用的pg10 window版本，请问有什么解决办法吗？

**Comment by shizhengchao** [comment]
加上这个options试下
```
'debezium.plugin.name' = 'pgoutput'
```

**Comment by lzzcj** [comment]
> 加上这个options试下
> 
> ```
> 'debezium.plugin.name' = 'pgoutput'
> ```

可以的，解决了！

**Comment by future94** [comment]
> 加上这个options试下
> 
> ```
> 'debezium.plugin.name' = 'pgoutput'
> ```

datastream怎么版啊大佬，不是table sql

**Comment by future94** [comment]
> 

table sql加在`WITH('decoding.plugin.name' = 'pgoutput')`

dataStream加在`PostgreSQLSource.<String>builder().decodingPluginName("pgoutput").build()`

**Comment by future94** [comment]
> 'debezium.plugin.name' = 'pgoutput' 加在哪里呀

table sql加在`WITH('decoding.plugin.name' = 'pgoutput')`

dataStream加在`PostgreSQLSource.<String>builder().decodingPluginName("pgoutput").build()`
