### ISSUE TITLE
[docs] Add FAQ about mysql server timezone in DataStream API

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#370]
User who use DataStream API should deal the timezone in their custom `deserializer` like `RowDataDebeziumDeserializeSchema`

**Comment by MonsterChenzhuo** [comment]
Hi @leonardBang I am very interested in this，and I want do some job for flink-cdc，can I help to do that？
Thank you

**Comment by leonardBang** [comment]
Thanks @MonsterChenzhuo , but this should have been implemented in #634 , thus I close it now.
I'll prepare more tasks for newbie.
