### ISSUE TITLE
flink jobmanage 挂掉，报错 produced an uncaught exception. Stopping the process

### ISSUE THREAD

**Issue by ZhuJiang121** [ververica/flink-cdc-connectors#375]
当我使用 flink mysql cdc 2.01 版本时，当一张表中的数据读取完毕时, 会出现这种问题，导致flink jobmanage挂掉。

_13436 2021-08-30 10:38:11,378 ERROR org.apache.flink.runtime.util.FatalExitExceptionHandler      [] - FATAL: Thread 'SourceCoordinator-Source: TableSourceScan(table=[[default_catalog, default_database, source_blackli      stloghis]], fields=[pid, id, businessNo, bornTime, acquirerNo, tellerNo, clientName, certNo, creditNo, conversionType, conversionCause, field, createTime, createBy, updateTime, updateBy, remove, sign, insertTyp      e, operationType]) -> DropUpdateBefore -> Calc(select=[CAST(pid) AS pid, id, businessNo, CAST(TimeStampChangeUDF(CAST(bornTime))) AS bornTime, acquirerNo, tellerNo, clientName, certNo, creditNo, conversionType,       conversionCause, field, CAST(TimeStampChangeUDF(CAST(createTime))) AS createTime, CreatePartitionUDF(CAST(createTime)) AS dt, createBy, CAST(TimeStampChangeUDF(CAST(updateTime))) AS updateTime, updateBy, remov      e, sign, insertType, operationType]) -> NotNullEnforcer(fields=[pid]) -> Map' produced an uncaught exception. Stopping the process...
13437 java.lang.Error: This indicates that a fatal error has happened and caused the coordinator executor thread to exit. Check the earlier logsto see the root cause of the problem.
13438         at org.apache.flink.runtime.source.coordinator.SourceCoordinatorProvider$CoordinatorExecutorThreadFactory.newThread(SourceCoordinatorProvider.java:114) ~[flink-dist_2.12-1.13.1.jar:1.13.1]
13439         at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:619) ~[?:1.8.0_201]
13440         at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:932) ~[?:1.8.0_201]
13441         at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025) ~[?:1.8.0_201]
13442         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[?:1.8.0_201]13443         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201]
13444         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
13445 2021-08-30 10:38:11,389 INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Shutting StandaloneSessionClusterEntrypoint down with application status UNKNOWN. Diagnostics Cluster entrypoint h      as been closed externally..
13446 2021-08-30 10:38:11,391 INFO  org.apache.flink.runtime.dispatcher.DispatcherRestEndpoint   [] - Shutting down rest endpoint._

**Comment by ZhuJiang121** [comment]
我使用的 flink 版本时 1.13.1, mysql 5.7, cdc 版本时 2.0.1。我使用flink sql api 去运行程序，sql 参数如下：
`CREATE TABLE source_user_info (  `UserId` INT, `UserName` STRING, `IsAdmin` TINYINT, `LastLogin` TIMESTAMP(3), `TestTime` TIMESTAMP(3),PRIMARY KEY( UserId ) NOT ENFORCED ) WITH (
  'connector' = 'mysql-cdc',
  'scan.startup.mode' = 'initial',
  'hostname' = '172.16.10.6',
  'port' = '3306',
  'username' = 'root',
  'password' = 'root',
  'database-name' = 'hcdsj',
  'table-name' = 'user_info',
  'server-time-zone' = 'Asia/Shanghai',
  'scan.incremental.snapshot.chunk.size' = '100000',
  'debezium.snapshot.locking.mode' = 'none'
)`

**Comment by hwzp99** [comment]
same problem...

**Comment by nienie** [comment]
用stream-api 采集也有同样的问题。

Flink    1.13
Mysql    5.7
Flink-CDC 2.2.0-SNAPSHOT

```text
2021-11-29 19:29:03,990 INFO  org.apache.flink.runtime.checkpoint.CheckpointCoordinator    [] - Triggering checkpoint 230 (type=CHECKPOINT) @ 1638185343990 for job b7e1fb2446f6d8a368377c73660f0880.
2021-11-29 19:29:04,391 ERROR org.apache.flink.runtime.util.FatalExitExceptionHandler      [] - FATAL: Thread 'SourceCoordinator-Source: MySQL Source' produced an uncaught exception. Stopping the process...
java.lang.Error: This indicates that a fatal error has happened and caused the coordinator executor thread to exit. Check the earlier logsto see the root cause of the problem.
	at org.apache.flink.runtime.source.coordinator.SourceCoordinatorProvider$CoordinatorExecutorThreadFactory.newThread(SourceCoordinatorProvider.java:114) ~[flink-dist_2.11-1.13.0.jar:1.13.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:619) ~[?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:932) ~[?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025) ~[?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
```

**Comment by nienie** [comment]
关闭吧。

定位原因，大致是因为job manager 的 参数配置的原因。

加大job manager内存吧~
