### ISSUE TITLE
flink cdc如何保存state？

### ISSUE THREAD

**Issue by liuyong19892** [ververica/flink-cdc-connectors#38]
flink是如何保存大量的所有数据的？
从头到尾全部放内存吗？
如果会部分持久化到statebackend 那怎么再次用到的时候如何读取出来的呢？

**Comment by wuchong** [comment]
这个和 flink cdc 没有什么关系哈。 
关于 flink state 可以阅读有关文档：https://ci.apache.org/projects/flink/flink-docs-release-1.11/zh/dev/stream/state/
