### ISSUE TITLE
[docs] Improve the CDC DataStream API docs

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#381]
* Change the [DataStream Source](https://ververica.github.io/flink-cdc-connectors/master/content/connectors/mysql-cdc.html) use `JsonDeserializationSchema `
* Add explanation for input and output data, we can refer [debezium mysql]( https://debezium.io/documentation/reference/1.6/connectors/mysql.html#mysql-events)

**Comment by leonardBang** [comment]
CC @mincwang Would you like to take this one ?

**Comment by mincwang** [comment]
> CC @mincwang Would you like to take this one ?

ACK
