### ISSUE TITLE
[mysql] 出现'Data row is smaller than a column index, internal schema representation is probably out of sync with real database schema'错误

### ISSUE THREAD

**Issue by opcooc** [ververica/flink-cdc-connectors#383]
jar 版本 -> flink-sql-connector-mysql-cdc:2.0.0
sql -> `CREATE TEMPORARY TABLE element_cdc (
PId INT,
ElementId STRING, 
proc_time AS PROCTIME(), 
primary key (PId) not enforced
) WITH (
  'connector' = 'mysql-cdc',
  'hostname' = '192.168.1.xxx',
  'port' = '3306',
  'username' = 'root',
  'password' = 'xxx',
  'database-name' = '[a-z0-9]{32}',
  'table-name' = 'ElementInfos'
)`

错误信息 -> 
[issues.txt](https://github.com/ververica/flink-cdc-connectors/files/7083376/issues.txt)

**Comment by fsk119** [comment]
Could you share more details about how you produce the exception? 

Do you restore from the checkpoint?  

What schema changes from the time that the checkpoint is made to the time you recover from the checkpoint?  

Could you also share the schema for the table in the DB?

**Comment by opcooc** [comment]
> 您能否分享有关如何产生异常的更多详细信息？
> 
> 您是否从检查点还原？
> 
> 从创建检查点到您从检查点恢复时，哪些架​​构发生了变化？
> 
> 您还可以共享数据库中表的架构吗？

稍等 抱歉回复晚了

**Comment by opcooc** [comment]
> Could you share more details about how you produce the exception?
> 
> Do you restore from the checkpoint?
> 
> What schema changes from the time that the checkpoint is made to the time you recover from the checkpoint?
> 
> Could you also share the schema for the table in the DB?

> 异常log摘要 ->
[ex.txt](https://github.com/ververica/flink-cdc-connectors/files/7091059/ex.txt)

> 开启了检查点还原，flink配置摘要 
[config.txt](https://github.com/ververica/flink-cdc-connectors/files/7091067/config.txt)

> 从创建检查点到您检查点恢复时间，环境没有发生可疑情况
> 数据库为32 uuid 表结构
[Cqcs.txt](https://github.com/ververica/flink-cdc-connectors/files/7091060/Cqcs.txt)

**Comment by opcooc** [comment]
> Could you share more details about how you produce the exception?
> 
> Do you restore from the checkpoint?
> 
> What schema changes from the time that the checkpoint is made to the time you recover from the checkpoint?
> 
> Could you also share the schema for the table in the DB?

抱歉回复晚了

**Comment by opcooc** [comment]
升级 2.0.1 问题解决
