### ISSUE TITLE
The db history topic or its content is fully or partially missing

### ISSUE THREAD

**Issue by peterjqy** [ververica/flink-cdc-connectors#391]
**Describe the bug**

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version: 2.0
 - Database and version: mysql 5.7

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**
![image](https://user-images.githubusercontent.com/90038595/131990601-982a9210-d94d-4dd5-8437-f7793ab0c9e4.png)
1.使用的flinksql
2.多个cdc source表 union all
3.第一次失败（java.io.IOException: Insufficient number of network buffers: required 2, but only 0 available. The total number of network buffers is currently set to 10977 of 32768 bytes each. You can increase this number by setting the configuration keys 'taskmanager.memory.network.fraction', 'taskmanager.memory.network.min', and 'taskmanager.memory.network.max'.）后，第二次重启报Caused by: io.debezium.DebeziumException: The db history topic or its content is fully or partially missing

**Comment by Jiabao-Sun** [comment]
Hi, @peterjqy 
This issue seems the same as #326.
It was resolved by Flink CDC version: 2.0.1.
Could you please upgrade the flink cdc connector version to 2.0.1 and try it again?

**Comment by peterjqy** [comment]
ok
