### ISSUE TITLE
Position update problem when multiple pieces of data are consumed in a transaction

### ISSUE THREAD

**Issue by yanghuaiGit** [ververica/flink-cdc-connectors#401]
**Describe the bug**

**Environment :**
 - Flink version :  
 - Flink CDC version:  release-2.0
 - Database and version: mysql 8.0

**To Reproduce**
1. Thes test data :
MySQL has multiple DML statements in a transaction, such as inserting two pieces of data into a table in a transaction
2. The test code :
  SourceFunction<String> sourceFunction =
                MySqlSource.<String>builder()
                        .hostname("127.0.0.1")
                        .port(3306)
                        .databaseList("test") // monitor all tables under inventory
                        // database
                        .username("uname")
                        .password("pw")
                        .deserializer(new StringDebeziumDeserializationSchema())
                        .build();

        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.addSource(sourceFunction).print().setParallelism(1);

        env.execute("Print MySQL Snapshot + Binlog");

3. The error :

![image](https://user-images.githubusercontent.com/38883656/132169820-5833d402-30ad-4a02-838e-90bf92953e2e.png)

com.ververica.cdc.debezium.internal.DebeziumChangeFetcher#handleBatch the param changeEvents has two record，but update position when consumer  first record。
i think we should update position when all record has consumer(sourceContext.collect(record))
**Additional Description**

**Comment by luoyuxia** [comment]
@yanghuaiGit 
> but update position when consumer first record
Hi, I'm not sure about what you means. I think the code will always update position not only for the first record.

**Comment by yanghuaiGit** [comment]
每条dml的消费都应该伴随position的更新，但是在一个事务中出现多个dml语句时，每个dml语句的position是这个事务的结束位置而不是此dml语句的position。导致第一条dml语句更新position且被存储到state里，那么在恢复时，此事务后续dml丢失，因为记录的position是这整个事务的commit position
简而言之 dml消费更新的position应该是这个dml语句的position而不是其所在事务的commit position

**Comment by yanghuaiGit** [comment]
record.sourceOffset() 取得是所在事务的position，应该取record里的source属性值里的position 与 file 这个是此record的position

![image](https://user-images.githubusercontent.com/38883656/135008885-47dfaf7a-7af0-48a0-9312-dfc4be477540.png)
