### ISSUE TITLE
none change data is captured while testing postgreSQL cdc

### ISSUE THREAD

**Issue by Fisher666** [ververica/flink-cdc-connectors#402]
**Describe the bug**

none change data is captured while testing postgreSQL cdc.
not sure if this's a bug, more likely it might be a configuration problem.

**Environment :**
 - Flink version :  1.13.1
 - Flink CDC version: 1.1.1 ~ 1.4.0
 - Database and version: PostgreSQL 13.4 on x86_64-apple-darwin20.4.0, compiled by Apple clang version 12.0.5 (clang-1205.0.22.9), 64-bit

**To Reproduce**
1. The test data : inserting any data to these very tables "stud","data_input","data_output" would do the trick.
2. The test code : 
DebeziumSourceFunction<String> pgSourceDeb = PostgreSQLSource.<String>builder()
                .hostname("localhost")
                .port(5432)
                .username("repl")
                .password("repl")
                .database("flink_cdc")
                .tableList("stud","data_input","data_output")
//                .decodingPluginName("wal2json_rds_streaming")
                .decodingPluginName("pgoutput")
                .slotName("flink_cdc_test_fisher1")
                .schemaList("public")
                .deserializer(new StringDebeziumDeserializationSchema()) // converts SourceRecord to String
                .build();

3. The error : none change data is captured  but some infos:
INFO io.debezium.connector.postgresql.PostgresStreamingChangeEventSource - Retrieved latest position from stored offset 'LSN{0/16967D8}'
[debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO io.debezium.connector.postgresql.connection.WalPositionLocator - Looking for WAL restart position for last commit LSN 'null' and last change LSN 'LSN{0/16967D8}'
[debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO io.debezium.connector.postgresql.connection.PostgresReplicationConnection - Initializing PgOutput logical decoder publication
[debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO io.debezium.connector.postgresql.connection.PostgresConnection - Obtained valid replication slot ReplicationSlot [active=false, latestFlushedLsn=LSN{0/16966B8}, catalogXmin=555]
[pool-3-thread-1] INFO io.debezium.jdbc.JdbcConnection - Connection gracefully closed

**Additional Description**

full log: 
[flink_cdc_postgres_log.log](https://github.com/ververica/flink-cdc-connectors/files/7118293/flink_cdc_postgres_log.log)

**Comment by leonardBang** [comment]
Sorry for the late reply, please check your Postgres publication contains the tables you want to capture, and the table name in `tableList()` should be full path like `schemaName.tableName`.

**Comment by Fisher666** [comment]
> Sorry for the late reply, please check your Postgres publication contains the tables you want to capture, and the table name in `tableList()` should be full path like `schemaName.tableName`.

many thx for help, it worked the other day and Im considering contributing cdc by docs improvements and source code interpretation.

**Comment by Fisher666** [comment]
tableList() in dataStream API should be filled w/ the full path of the table as indicated in source code :
postgresql: schemaName.tableName
mysql : databaseName.tableName
