### ISSUE TITLE
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.MissingTableMapEventException: No TableMapEventData has been found for table id:116. Usually that means that you have started reading binary log 'within the logical event group' (e.g. from WRITE_ROWS and not proceeding TABLE_MAP

### ISSUE THREAD

**Issue by peterjqy** [ververica/flink-cdc-connectors#411]
**Describe the bug**

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version: 2.0.0
 - Database and version: mysql  5.7.28

![image2021-9-9_10-48-11](https://user-images.githubusercontent.com/90038595/132624768-e30d70f7-57f1-4c8e-a0c5-21fd62284fc8.png)
![1631163477504](https://user-images.githubusercontent.com/90038595/132625296-a794e87a-239f-423c-b5a7-f6ec284e3ae0.jpg)

**Comment by opcooc** [comment]
https://github.com/ververica/flink-cdc-connectors/issues/276
