### ISSUE TITLE
[test] Add end-to-end tests for all uber jars

### ISSUE THREAD

**Issue by wuchong** [ververica/flink-cdc-connectors#419]
We introduced `flink-sql-connectors-xxx` for all `mysql-cdc`, `postgres-cdc` and `mongodb-cdc`. This module is used to shade kafka and build an uber jar which is mainly used for SQL clusters. However, we don't have any tests for the uber jars, e.g. does the shading work? do we exclude any needed classes? This can be covered by e2e tests, just like Flink does, see https://github.com/apache/flink/tree/master/flink-end-to-end-tests

**Comment by wuchong** [comment]
Hi @Jiabao-Sun , I can help to finish this issue if you don't have much time, would you mind that? :)

**Comment by Jiabao-Sun** [comment]
Thanks @wuchong, that's good.
Sorry for not having time to finish it.
