### ISSUE TITLE
Is it possible to customize the configuration items of debezium `include.schema.changes` ??

### ISSUE THREAD

**Issue by DemonJun** [ververica/flink-cdc-connectors#427]
in me case, I want use cdc to watch mysql table change, but I found this - `include.schema.changes` is always false in class `DebeziumSourceFunction` at method `run`. 
Is it possible to customize the configuration items of debezium `include.schema.changes` ??

**Comment by pokerWu** [comment]
开启include schema changes来说，是没有用的。在sql模式下，使用Row方式解析SourceRecord.

如果你想消费ddl信息。可以用json反序列化类。

如果使用stream api写代码，则可以用自定义反序列化。

目前我也在研究怎么实现schema演进。通过flink framework传递似乎不是很好的方式，目前在参考confluence avro的模式做。
