### ISSUE TITLE
DataStream API能否指定MySQL的binlog位点

### ISSUE THREAD

**Issue by dushang2016** [ververica/flink-cdc-connectors#43]
Sql API 有指定mysqlbinlog位点的参数，那DataStream API可有指定位点的参数

**Comment by shizhengchao** [comment]
mysql指定位点现在还没支持，提的pr还没merge，可以参考这个 [指定mysql位点](https://github.com/ververica/flink-cdc-connectors/pull/39)，也是可以用DataStream API的，在MysqlSource的builder中指定就可以了
