### ISSUE TITLE
多个分片并行初始化会不会丢失数据

### ISSUE THREAD

**Issue by gaoxiancan** [ververica/flink-cdc-connectors#447]
com.alibaba.ververica.cdc.connectors.mysql.source.utils.RecordUtils#splitKeyRangeContains
这个方法进行了分片范围内数据过滤，相当于丢失了分片范围外的数据

举例：
splits (null，10],(10，20],(20，30],(30，40],(40，null]
	当前分片(10,20]
	拉取到的全量数据				(12,13,14,15,19)
	拉取到的binlog数据			(1_update,2_delete,10_update,11_insert,12_update,13_delete)
	过滤之后满足条件的binlog数据	(11_insert,12_update,13_delete)
	合并之后的数据				(11,12,14,15,19)
问题是，1_update,2_delete,10_update这个数据是不是就丢失了？
因为后面拉取的都是越来越大的分片数据，没有机会再获取之前分片的数据了，不知道理解的对不对

**Comment by leonardBang** [comment]
理解的不对，记录了拉取当前分片的high watermark位点， binglog 阶段过了 high watermark 位点又属于该分片的记录会继续下发，你再看下代码

**Comment by todd5167** [comment]
@gaoxiancan   https://www.imooc.com/article/320897   写了下CDC处理过程，你可以看看

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
