### ISSUE TITLE
mysql cdc 连接mysql 的用户权限问题?

### ISSUE THREAD

**Issue by Brainhu** [ververica/flink-cdc-connectors#45]
需要有服务器的 binlog 权限？能不能详细列一下赋予权限？

**Comment by shizhengchao** [comment]
1. 首先mysql的服务需要配置如下：
```
server-id         = 223344 
log_bin           = mysql-bin 
binlog_format     = ROW 
binlog_row_image  = FULL 
expire_logs_days  = 10 
```
2. 权限如下，详情可以看[debezium](https://debezium.io/documentation/reference/1.2/connectors/mysql.html)文档
```
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'user' IDENTIFIED BY 'password';
```

**Comment by Brainhu** [comment]
> 1. 首先mysql的服务需要配置如下：
> 
> ```
> server-id         = 223344 
> log_bin           = mysql-bin 
> binlog_format     = ROW 
> binlog_row_image  = FULL 
> expire_logs_days  = 10 
> ```
> 
> 1. 权限如下，详情可以看[debezium](https://debezium.io/documentation/reference/1.2/connectors/mysql.html)文档
> 
> ```
> GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'user' IDENTIFIED BY 'password';
> ```

还有个 lock tables
