### ISSUE TITLE
mysql 字段是datetime类型时,flink-cdc接收到数据会+8个小时

### ISSUE THREAD

**Issue by XianPengcheng** [ververica/flink-cdc-connectors#457]
**Describe the bug**
mysql 字段是datetime类型时,flink-cdc接收到数据会+8个小时

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version: 2.0.1
 - Database and version: 8.0.26

**To Reproduce**
1. Thes test data :
mysql的表:
`CREATE TABLE `test_data` (
  `custom_info_id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '个人信息标识',
  `custom_no` varchar(16) NOT NULL COMMENT '用户编号',
  `regist_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `last_login_time` timestamp NULL DEFAULT NULL COMMENT '最后登录时间'
  PRIMARY KEY (`custom_info_id`),
  UNIQUE KEY `idx_cust_info_cust_no` (`custom_no`)
) ENGINE=InnoDB AUTO_INCREMENT=38297 DEFAULT CHARSET=utf8mb3 COMMENT='一张测试表';`
`INSERT INTO test_data(custom_no,regist_time,last_login_time) VALUES ('123456','2019-03-16 11:28:27','2019-03-16 11:28:27');`
2. The test code :
`private static String SourceCustomInfoDDL = "CREATE TABLE c_custom_info (\n" +
            "  custom_info_id bigint,  \n" +
            "  custom_no varchar,\n" +
            "  last_login_time varchar,\n" +
            "  regist_time varchar,\n" +
            "  PRIMARY KEY (custom_info_id) NOT ENFORCED" +
            ")" ;`

`public static String sourceConnParam = " WITH (\n" +
                        " 'connector' = 'mysql-cdc',\n" +
                        " 'hostname' = '"+mysqlCdcHostname+"',\n" +
                        " 'port' = '"+mysqlCdcPort+"',\n" +
                        " 'username' = '"+mysqlCdcUsername+"',\n" +
                        " 'password' = '"+mysqlCdcPassword+"',\n" +
                        " 'database-name' = '"+mysqlCdcDatabaseName+"',\n" +
                        " 'scan.incremental.snapshot.enabled' = 'false',\n" +
                        " 'debezium.min.row.count.to.stream.results' = '0',\n" +
                        " 'server-time-zone' = 'Asia/Shanghai',\n" +
                        " 'table-name' = '%s'\n"+
                        ")";`
`public static void main(String[] args) throws Exception {
        //1.创建执行环境
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.setParallelism(5);
        EnvironmentSettings bsSettings = EnvironmentSettings.newInstance().useBlinkPlanner().inStreamingMode().build();
        StreamTableEnvironment tEnv = StreamTableEnvironment.create(env, bsSettings);
        tEnv.getConfig().getConfiguration().setBoolean("table.dynamic-table-options.enabled", true);
        env.setStateBackend(new FsStateBackend("file:///tmp/checkpoints/lookup"));

        tEnv.executeSql(SourceCustomInfoDDL + String.format(DDLScript.sourceConnParam,"test_data"));

        Table dimCustomSourceTable = tEnv.sqlQuery(
      "select cast(a.custom_no as BigInt) customNo,a.last_login_time lastLoginTime,a.regist_time registTime  from c_custom_info a");

        DataStream<Object> dimCustomSinkStream = tEnv.toRetractStream(dimCustomSourceTable, Row.class).map(new MapFunction<Tuple2<Boolean, Row>, Object>() {
            @Override
            public Object map(Tuple2<Boolean, Row> sourceRow) throws Exception {
                if (!sourceRow.f0) {
                    return null;
                }
                log.info("来源: " + sourceRow.f1);

                return sourceRow.f1;
            }
        });
        dimCustomSinkStream.print();
        env.execute("DateTimeErrTest");
    }`

3. The error :

![image](https://user-images.githubusercontent.com/26914367/134493765-662766de-7e39-4f1d-b6e4-5c5ef16147a1.png)
![image](https://user-images.githubusercontent.com/26914367/134493832-696ddffc-109b-4ca9-8ea9-864ef920e1c4.png)
![image](https://user-images.githubusercontent.com/26914367/134494935-ec1aae08-50c4-48bd-984a-2bc6a1c2fbee.png)
mysql   datetime类型的多了8个小时

**Comment by leonardBang** [comment]
the root cause is you defined the field  type is not match with the field type in MySQL, please refer
