### ISSUE TITLE
使用flink-sql-connector-mysql-cdc同步多张表的时候如何只拉取binlog一次？

### ISSUE THREAD

**Issue by dushang2016** [ververica/flink-cdc-connectors#46]
使用flink-sql-connector-mysql-cdc同步mysql的binlog的时候一个job同步一张表,同时拉取一次binlog。那要是同步10张表的话如何只拉取一次binlog?

**Comment by wuchong** [comment]
目前 SQL 还不支持。 你可以使用 `MySQLSource` 使用 DataStream API 来操作。 `MySQLSource` 可以抓取一整个库的变更。
