### ISSUE TITLE
CDC同步MysqlHA集群，切换同步实例checkpoint恢复出现异常

### ISSUE THREAD

**Issue by hzh2955** [ververica/flink-cdc-connectors#469]
**Describe the bug**

**Environment :**
 - Flink version :  1.13.1
 - Flink CDC version:  2.0.2
 - Database and version:  mysql  5.7

**To Reproduce**
1. Thes test data :    
2. The test code :
3. The error :  2021-09-27 15:47:42.770 INFO  io.debezium.connector.mysql.MySqlConnectorTask               - Connector last known GTIDs are 4e2a97f0-49b1-11eb-b1af-18ded781aa84:192-449,af960e6a-f994-11ea-90af-00e0ed7b8b00:1-37858, but MySQL has 8d471c24-1eae-11ec-944a-00e0ed7b8b00:1-232,af960e6a-f994-11ea-90af-00e0ed7b8b00:35821-37876。  but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.

**Additional Description**
caes：一个 master，两个 slave. Flink CDC 监听slave1实例同步binlog，生成checkpoint，然后调整任务中的host和port为slave2。

任务从checkpoint恢复，下图异常。
![image](https://user-images.githubusercontent.com/33930776/135014018-0faa5068-2b37-4b34-a3f3-46ec58d25563.png)

关键日志： 2021-09-27 15:47:42.770 INFO  io.debezium.connector.mysql.MySqlConnectorTask               - Connector last known GTIDs are 4e2a97f0-49b1-11eb-b1af-18ded781aa84:192-449,af960e6a-f994-11ea-90af-00e0ed7b8b00:1-37858, but MySQL has 8d471c24-1eae-11ec-944a-00e0ed7b8b00:1-232,af960e6a-f994-11ea-90af-00e0ed7b8b00:35821-37876。

从checkpoint中恢复的gtid为消费slave1的gtid，在与slave2的gtid进行可用性检测异常。 下图：
![image](https://user-images.githubusercontent.com/33930776/135014226-6f5e3343-e7d0-4fb0-a69e-f1ad3dd0eae6.png)

问题分析：
因为slave1和slave2的gtid set中包含有两个gtid值，其中一个为自身，另一个为ha集群全局的。  监听slave1时，记录的gtid中包含有slave1自身的gtid值。调整为slave2之后，checkpoint恢复后时判断gtid是否可用就通不过。 slave2中的gtid set中没有包含slave1中特有的那个。 

GTID slave1： 8d471c24-1eae-11ec-944a-00e0ed7b8b00:1-232,af960e6a-f994-11ea-90af-00e0ed7b8b00:35821-37880
GTID slave2： 4e2a97f0-49b1-11eb-b1af-18ded781aa84:1-715,af960e6a-f994-11ea-90af-00e0ed7b8b00:37832-37881

af960e6a-f994-11ea-90af-00e0ed7b8b00  这个uuid对应为全局。

**Comment by luoyuxia** [comment]
假设MySQL集群 为master, slave1, slave2.
Flink CDC监听slave

1: 一开始，master，slave1，slave2的`Executed_Gtid_Set`都会记录来自 自己这个server的事务；
2: 接下来 slave1，slave2则开始监听master1的事务，此时slave1，slave2则只会记录来自master的事务。
3: slave1挂了，Flink CDC切换到slave2，此时Flink CDC从slave1对应的state恢复，恢复出slave1的`Executed_Gtid_Set`，但slave1的`Executed_Gtid_Set`与slave2的`Executed_Gtid_Set` 不兼容，直接从slave1的state切换到slave2就会fail。

不兼容的原因是 ：
在step 1的时候，slave1和slave2分别记录了 自己这个server的事务，类似`slave1:1-2，slave2:1-3`；
step3的时候 恢复出的slave1的`Executed_Gtid_Set`类似 `slave1:1-2, master:1-10`，这作为 `gtidSet`; 但slave2目前的`Executed_Gtid_Set`类似 `slave2:1-3, master:1-10`，这作为`availableGtidStr` 。 这就导致通不过 `gtidSet.isContainedWithin(availableGtidSet)`，于是就会出现恢复异常。

`如果在step2的时候，通过命令``reset master ; ` reset slave1，slave2的master，把slave记录的来自自己这个server的事务清空，之后 slave1，slave2就只会记录了master的事务，这样就不会出现不兼容的情况。
但是生产环境下，比较难做到。

另外一种方式是：
重启恢复的时候，restore出之前的`Executed_Gtid_Set`，`gtidSet`，然后与目前监听的server的`Executed_Gtid_Set`，`availableGtidStr`进行比较，强行让`gtidSet.isContainedWithin(availableGtidSet)`。
直观的做法是：得到`availableGtidStr`的记录的server的uuid，如果`gtidSet`记录的server的uuid不包含于`availableGtidStr`，则直接在`gtidSet`中删掉该server对应的事务。
比如：
`gtidSet`: `slave1:1-2, master:1-10`
`availableGtidStr`: `slave2:1-3, master:1-10`

直接删掉 `gtidSet`记录的`slave1:1-2`.

@leonardBang  你怎么看呢。

**Comment by camelus0211** [comment]
> 解决方案：在checkpoin恢复时，获取到当前连接实例的gtid set， 与从checkpoint中恢复的checkpoint进行一个判断。判断UUID在checkpoint中和当前实例均存在的gtid值保留，去除gtid set中 slave1自身的gtid值，然后进行恢复监听。
> 
> 需要验证点： 从仅包含全局GTID值恢复，能够保证断点续传。
> 
> 大伙一起讨论下。

这里有没有尝试过订阅master的binlog?

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.

**Comment by minchowang** [comment]
I met this same issue when using the `DebeziumSourceFunction` today. So this issue should reopen. 

@leonardBang

**Comment by minchowang** [comment]
> 

按照你的思路，我在flink-cdc项目里对`io.debezium.connector.mysql.MySqlConnectorTask`进行了部分重写，旨在reset为一个全局事务ID，效果看起来不错
![image](https://github.com/ververica/flink-cdc-connectors/assets/33626973/c96b6f68-f733-460f-8024-04d5ba32290f)
<img width="1367" alt="image" src="https://github.com/ververica/flink-cdc-connectors/assets/33626973/82da8b10-2389-435d-9e12-c092f9b3005d">
