### ISSUE TITLE
Expose record metadata to mongo-cdc

### ISSUE THREAD

**Issue by bobby-richard** [ververica/flink-cdc-connectors#476]
**Is your feature request related to a problem? Please describe.**
It's possible to capture data from multiple mongo databases and collections with the connector, but there is no way to know which database or collection each record came from. 

**Describe the solution you'd like**
The official flink debezium format provides a way to read debezium metadata fields when creating a table DDL (https://nightlies.apache.org/flink/flink-docs-release-1.13/docs/connectors/table/formats/debezium/#available-metadata). Something similar could be done to expose db and collection from the mongo source connector document.

I'm happy to take a stab at this if someone could point me in the right direction.

**Comment by fsk119** [comment]
I think you can take a look at the FLIP about the design of the metadadta column. Flink has an good example in the PR[2].

[1] https://cwiki.apache.org/confluence/display/FLINK/FLIP-107%3A+Handling+of+metadata+in+SQL+connectors
[2] https://github.com/apache/flink/pull/13732

**Comment by wuchong** [comment]
I'm going to support metadata columns for mysql-cdc, see #249 in the next days. I think it can be a good example for other connectors.

**Comment by leonardBang** [comment]
Implemented in 65665eb
