### ISSUE TITLE
Reading incremental data from MySQL in parallel not work

### ISSUE THREAD

**Issue by Sam-Tsui** [ververica/flink-cdc-connectors#486]
**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version:  2.0.2
 - Database and version: Mysql5.7

**To Reproduce**
 jobManager: 1
 taskManager: 2
 flink deploy with standalone mode.
 taskmanager.numberOfTaskSlots: 2
 parallelism.default: 2

**Additional Description**
My job is simply sync mysql data(ps. only 1 table) to es7 , and the job is created by SQL CLI. The incremental snapshot reading 
is Not Work after snapshot phase. But I've tried to set the 'parallelism.default = 1' and the incremental snapshot reading worked fine.I'm so confused.

**Comment by wuchong** [comment]
You may forget to enable checkpoint `SET 'execution.checkpointing.interval' = '3min'; `.  Binlog phase will wait for at least one complete checkpoint.

**Comment by wuchong** [comment]
@Sam-Tsui , this is an optimization for 1 parallelism. The checkpoint is required to guarantee the global order of update events for multiple source tasks. However, for single task, the update events is natually ordered, so we don't need a complete checkpoint.
