### ISSUE TITLE
Project push down for mysql cdc source

### ISSUE THREAD

**Issue by civetming** [ververica/flink-cdc-connectors#489]
I use flink-cdc 2.0.2 in the full synchronization stage, select * from table will be executed, a large amount of data in a single table will cause slow queries. How to solve it

 - Flink version :  1.13
 - Flink CDC version: 2.0.2
 - Database and version: mysql 8.0+

**Comment by wuchong** [comment]
@robin-ming , you can increase the source parallelism to speed up for now. 
In the future, we can support project push down to only read the required columns.

**Comment by robin-ming** [comment]
But,the SQL query statements will take a long time, how to solve it.

**Comment by wuchong** [comment]
@robin-ming , how long will it take? We introduced incremental-snapshot in v2.0, usually, it won't take too long for each chunk query.
