### ISSUE TITLE
[feature] Add new tables to an existing Flink CDC job

### ISSUE THREAD

**Issue by wuchong** [ververica/flink-cdc-connectors#513]
Sometimes, a Flink CDC job may only read [t1, t3, t5], but after some days we would like the job can also read [t4, t6] but don't want to lose the savepoint of the job. For example, update the `table-name` value of the job to include t4 and t6 and restore the job from previous savepoint. 

This is a feature like Debezium's `snapshot.new.tables` feature. But it's not an easy work for Flink CDC to integerate it. Because since v2.0, we refatored the mysql-cdc to support parallel reading which only uses some internal readers of Debezium instead of a whole Debezium engine. So the `snapshot.new.tables` option can't transparently supported.

**Comment by leonardBang** [comment]
I post the design document here,   [API design]( https://docs.google.com/document/d/1XVS6opo8adTqJK3KiJibKXjloKB_hW22PBNzvHRa0GU/edit#heading=h.y0mtz6aggfrd), feel free to comment.

**Comment by Juneryang** [comment]
+1

**Comment by wangyusong001** [comment]
+1+1

**Comment by luguanxing** [comment]
[+10086](https://github.com/ververica/flink-cdc-connectors/issues/258)

**Comment by z070204z** [comment]
这个问题在新发布的release-2.2.0版本中解决了么？我新增表报错

2022-03-30 14:30:36,906 ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource  [] - Encountered change event 'Event{header=EventHeaderV4{timestamp=1648610706000, eventType=TABLE_MAP, serverId=3987113322, headerLength=19, dataLength=127, nextPosition=84261, flags=0}, data=TableMapEventData{tableId=1383, database='ng_kboss_customer', table='transfer_clue', columnTypes=15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 18, 18, 1, 15, -4, -4, columnMetadata=128, 800, 128, 80, 800, 400, 20000, 128, 128, 800, 800, 400, 400, 800, 400, 400, 128, 400, 400, 400, 400, 0, 0, 0, 800, 2, 2, columnNullability={5, 6, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26}, eventMetadata=null}}' at offset {transaction_id=null, ts_sec=1648610705, file=mysql-bin.017987, pos=83520, gtids=a12d4889-92bf-11ec-b97c-fa163e6b36e5:1-1006238, server_id=3987113322, event=2} for table ng_kboss_customer.transfer_clue whose schema isn't known to this connector. One possible cause is an incomplete database history topic. Take a new snapshot in this case.
Use the mysqlbinlog tool to view the problematic event: mysqlbinlog --start-position=84115 --stop-position=84261 --verbose mysql-bin.017987
2022-03-30 14:30:36,907 ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource  [] - Error during binlog processing. Last offset stored = null, binlog reader near position = mysql-bin.017987/84115
2022-03-30 14:30:36,907 WARN  com.ververica.cdc.connectors.mysql.debezium.task.context.MySqlErrorHandler [] - Schema for table ng_kboss_customer.transfer_clue is null

**Comment by zhjwpku** [comment]
> 这个问题在新发布的release-2.2.0版本中解决了么？我新增表报错
> 
> 2022-03-30 14:30:36,906 ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource [] - Encountered change event 'Event{header=EventHeaderV4{timestamp=1648610706000, eventType=TABLE_MAP, serverId=3987113322, headerLength=19, dataLength=127, nextPosition=84261, flags=0}, data=TableMapEventData{tableId=1383, database='ng_kboss_customer', table='transfer_clue', columnTypes=15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 18, 18, 1, 15, -4, -4, columnMetadata=128, 800, 128, 80, 800, 400, 20000, 128, 128, 800, 800, 400, 400, 800, 400, 400, 128, 400, 400, 400, 400, 0, 0, 0, 800, 2, 2, columnNullability={5, 6, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26}, eventMetadata=null}}' at offset {transaction_id=null, ts_sec=1648610705, file=mysql-bin.017987, pos=83520, gtids=a12d4889-92bf-11ec-b97c-fa163e6b36e5:1-1006238, server_id=3987113322, event=2} for table ng_kboss_customer.transfer_clue whose schema isn't known to this connector. One possible cause is an incomplete database history topic. Take a new snapshot in this case. Use the mysqlbinlog tool to view the problematic event: mysqlbinlog --start-position=84115 --stop-position=84261 --verbose mysql-bin.017987 2022-03-30 14:30:36,907 ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource [] - Error during binlog processing. Last offset stored = null, binlog reader near position = mysql-bin.017987/84115 2022-03-30 14:30:36,907 WARN com.ververica.cdc.connectors.mysql.debezium.task.context.MySqlErrorHandler [] - Schema for table ng_kboss_customer.transfer_clue is null

The problem was solved by #965 , which was included in release-2.2.0, thanks for the test.

**Comment by johncai0** [comment]
我这里还在抛这个异常，我的操作是先启动一个cdc任务，只捕获t1表，等生成checkpoint后，在停止任务，加入t2表，这个时候，再从checkpoint启动后，当t2表发生变化后，会抛出这个异常，然后整个cdc都捕获不到数据了。

版本；
<dependency>
            <groupId>com.ververica</groupId>
            <artifactId>flink-connector-mysql-cdc</artifactId>
            <version>2.2.1</version>
        </dependency>

配置：
MySqlSource<String> mySqlSource = MySqlSource.<String>builder()
                .hostname("johnwork")
                .port(3306)
                .databaseList("cdctest")
//                .tableList("cdctest.orders")
                .tableList("cdctest.orders,cdctest.t_user")
                .username("root")
                .password("123Abc@!@#")
                .includeSchemaChanges(true)
                .scanNewlyAddedTableEnabled(true)
                .serverId("5400-5401")
                .splitSize(20)
                .startupOptions(StartupOptions.latest())
                .debeziumProperties(pop)
                .deserializer(new JsonDebeziumDeserializationSchema())
                .build();

异常：
21:26:26,317 ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource   - Encountered change event 'Event{header=EventHeaderV4{timestamp=1660051586000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=48, nextPosition=61983, flags=0}, data=TableMapEventData{tableId=115, database='cdctest', table='t_user', columnTypes=3, 1, 3, 15, 17, 18, columnMetadata=0, 0, 0, 384, 0, 0, columnNullability={3, 4, 5}, eventMetadata=TableMapEventMetadata{signedness={}, defaultCharset=33, charsetCollations=null, columnCharsets=null, columnNames=null, setStrValues=null, enumStrValues=null, geometryTypes=null, simplePrimaryKeys=null, primaryKeysWithPrefix=null, enumAndSetDefaultCharset=null, enumAndSetColumnCharsets=null}}}' at offset {transaction_id=null, ts_sec=1660051573, file=binlog.000002, pos=61821, gtids=236958b9-edfa-11ec-b8d3-fa163e884df0:1-18109, server_id=1, event=1} for table cdctest.t_user whose schema isn't known to this connector. One possible cause is an incomplete database history topic. Take a new snapshot in this case.
Use the mysqlbinlog tool to view the problematic event: mysqlbinlog --start-position=61916 --stop-position=61983 --verbose binlog.000002
21:26:26,318 ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource   - Error during binlog processing. Last offset stored = null, binlog reader near position = binlog.000002/61916
21:26:26,318 WARN  com.ververica.cdc.connectors.mysql.debezium.task.context.MySqlErrorHandler  - Schema for table cdctest.t_user is null
21:26:26,318 INFO  io.debezium.connector.mysql.MySqlStreamingChangeEventSource   - Error processing binlog event, and propagating to Kafka Connect so it stops this connector. Future binlog events read before connector is shutdown will be ignored.


是我的配置不对吗？

**Comment by wangyusong001** [comment]
startup模式必须去init



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月10日 10:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ververica/flink-cdc-connectors] [feature] Add new tables to an existing Flink CDC job (Issue #513) |

我这里还在抛这个异常，我的操作是先启动一个cdc任务，只捕获t1表，等生成checkpoint后，在停止任务，加入t2表，这个时候，再从checkpoint启动后，当t2表发生变化后，会抛出这个异常，然后整个cdc都捕获不到数据了。

版本；

com.ververica
flink-connector-mysql-cdc
2.2.1


配置：
MySqlSource mySqlSource = MySqlSource.builder()
.hostname("johnwork")
.port(3306)
.databaseList("cdctest")
// .tableList("cdctest.orders")
.tableList("cdctest.orders,cdctest.t_user")
.username("root")
.password("123Abc@!@#")
.includeSchemaChanges(true)
.scanNewlyAddedTableEnabled(true)
.serverId("5400-5401")
.splitSize(20)
.startupOptions(StartupOptions.latest())
.debeziumProperties(pop)
.deserializer(new JsonDebeziumDeserializationSchema())
.build();

异常：
21:26:26,317 ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource - Encountered change event 'Event{header=EventHeaderV4{timestamp=1660051586000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=48, nextPosition=61983, flags=0}, data=TableMapEventData{tableId=115, database='cdctest', table='t_user', columnTypes=3, 1, 3, 15, 17, 18, columnMetadata=0, 0, 0, 384, 0, 0, columnNullability={3, 4, 5}, eventMetadata=TableMapEventMetadata{signedness={}, defaultCharset=33, charsetCollations=null, columnCharsets=null, columnNames=null, setStrValues=null, enumStrValues=null, geometryTypes=null, simplePrimaryKeys=null, primaryKeysWithPrefix=null, enumAndSetDefaultCharset=null, enumAndSetColumnCharsets=null}}}' at offset {transaction_id=null, ts_sec=1660051573, file=binlog.000002, pos=61821, gtids=236958b9-edfa-11ec-b8d3-fa163e884df0:1-18109, server_id=1, event=1} for table cdctest.t_user whose schema isn't known to this connector. One possible cause is an incomplete database history topic. Take a new snapshot in this case.
Use the mysqlbinlog tool to view the problematic event: mysqlbinlog --start-position=61916 --stop-position=61983 --verbose binlog.000002
21:26:26,318 ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource - Error during binlog processing. Last offset stored = null, binlog reader near position = binlog.000002/61916
21:26:26,318 WARN com.ververica.cdc.connectors.mysql.debezium.task.context.MySqlErrorHandler - Schema for table cdctest.t_user is null
21:26:26,318 INFO io.debezium.connector.mysql.MySqlStreamingChangeEventSource - Error processing binlog event, and propagating to Kafka Connect so it stops this connector. Future binlog events read before connector is shutdown will be ignored.

是我的配置不对吗？

**Comment by johncai0** [comment]
> 
感谢，init的时候可以去拉一次schema，这个能理解。
但是如果从检查点启动，是否就无法去init？

我尝试了指定启动模式init和不指定任何启动模式的配置方式从原来的检查点启动还是存在问题。
方式1（将启动模式改成了init）：
 MySqlSource<String> mySqlSource = MySqlSource.<String>builder()
                .hostname("johnwork")
                .port(3306)
                .databaseList("cdctest")
                .tableList("cdctest.orders,cdctest.t_user")
                .startupOptions(StartupOptions.initial())
                .username("root")
                .password("123Abc@!@#")
                .scanNewlyAddedTableEnabled(true)
                .deserializer(new JsonDebeziumDeserializationSchema())
                .build();
方式2（不指定启动模式）：
 MySqlSource<String> mySqlSource = MySqlSource.<String>builder()
                .hostname("johnwork")
                .port(3306)
                .databaseList("cdctest")
                .tableList("cdctest.orders,cdctest.t_user")
                .username("root")
                .password("123Abc@!@#")
                .scanNewlyAddedTableEnabled(true)
                .deserializer(new JsonDebeziumDeserializationSchema())
                .build();

**Comment by wangyusong001** [comment]
2.2版本方式1应该是没问题的，这个我是测试过的，不过这种方式新表会同步全量数据。
方式2不指定但他是有个默认值的，点进去源码可以看到，忘记默认值是哪种了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月10日 11:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ververica/flink-cdc-connectors] [feature] Add new tables to an existing Flink CDC job (Issue #513) |

感谢，init的时候可以去拉一次schema，这个能理解。
但是如果从检查点启动，是否就无法去init？

我尝试了指定启动模式init和不指定任何启动模式的配置方式从原来的检查点启动还是存在问题。
方式1（将启动模式改成了init）：
MySqlSource mySqlSource = MySqlSource.builder()
.hostname("johnwork")
.port(3306)
.databaseList("cdctest")
.tableList("cdctest.orders,cdctest.t_user")
.startupOptions(StartupOptions.initial())
.username("root")
.password("123Abc@!@#")
.scanNewlyAddedTableEnabled(true)
.deserializer(new JsonDebeziumDeserializationSchema())
.build();
方式2（不指定启动模式）：
MySqlSource mySqlSource = MySqlSource.builder()
.hostname("johnwork")
.port(3306)
.databaseList("cdctest")
.tableList("cdctest.orders,cdctest.t_user")
.username("root")
.password("123Abc@!@#")
.scanNewlyAddedTableEnabled(true)
.deserializer(new JsonDebeziumDeserializationSchema())
.build();

**Comment by johncai0** [comment]
我刚才有测试了一下，
这张新增的表t2如果是cdc启动后，新建的表才可以加入。
如果，这张表已经存在的表(很早以前建的表)，就会出现这个问题。

**Comment by dik111** [comment]
我也遇到同样的问题了，如果我只想从latest启动，然后从savepoint启动时新增表，要怎么样操作呢？

**Comment by dik111** [comment]
> 我刚才有测试了一下， 这张新增的表t2如果是cdc启动后，新建的表才可以加入。 如果，这张表已经存在的表(很早以前建的表)，就会出现这个问题。
> 
> 方式2不指定但他是有个默认值，默认值也是init

https://github.com/ververica/flink-cdc-connectors/pull/1464
