### ISSUE TITLE
请问CDC 如何同步DDL语句

### ISSUE THREAD

**Issue by zanmeipaul** [ververica/flink-cdc-connectors#53]
请问 CDC 如何同步DDL语句
我的需求是通过 Flink 同步mysql 表，表结构发生变化新增也需要同步过去，请问有什么方案可以做到

**Comment by MINCWANG** [comment]
使用api的方式实现DebeziumDeserializationSchema，进源码里修改传进去的prop对ddl的解析。代码里添加    
properties.setProperty("include.schema.changes", "true")
properties.setProperty("value.converter.schemas.enable", "true")即可实现。

**Comment by zanmeipaul** [comment]
@MINCWANG    谢谢，按照你的方式已解决
