### ISSUE TITLE
希望能增加一个SQL server 2012版本以上的cdc功能

### ISSUE THREAD

**Issue by cleverblue** [ververica/flink-cdc-connectors#549]
希望能增加一个SQL server 2012版本以上的cdc功能

**Comment by leonardBang** [comment]
@cleverblue 能描述下你们使用的业务场景和sql server版本吗？

**Comment by cleverblue** [comment]
我们目前使用的版本是SQLserver2019，业务场景是想通过 pulsar接收到的消息，用flink计算后sink到SQL Server中，然后我们做串行计算，flink-->SQL server(table1)(update,insert)-->flink计算-->sinktable2(update,insert)-->flink计算-->sinktable3(update,insert)..........
这样做计算是因为每个表的数据必须sink，table1，table2,table3的数据是相关联的。后面再通过table1，table2,table3用flink做并行计算。文字不知描述清楚没！

**Comment by leonardBang** [comment]
就是现有业务场景，你们需要很多个 pulsar  队列做中转，如果有sqlserver-cdc，你们就可以不用消息队列了，对吧？省掉这部分成本

**Comment by cleverblue** [comment]
是的、也可以这样说，如果有了sql server-cdc会方便很多了，也简单很多。

**Comment by cymuye** [comment]
是的，我们也需要SqlServer-cdc支持

**Comment by ynzzxc** [comment]
> 
> 
> 就是现有业务场景，你们需要很多个 pulsar 队列做中转，如果有sqlserver-cdc，你们就可以不用消息队列了，对吧？省掉这部分成本
是的，我们也需要SqlServer-cdc支持

**Comment by ynzzxc** [comment]
我们也需要SqlServer-cdc支持，和楼上差不多的场景

**Comment by leonardBang** [comment]
close this one, merge requirements to #88
