### ISSUE TITLE
Add documentation for available metadata columns

### ISSUE THREAD

**Issue by wuchong** [ververica/flink-cdc-connectors#556]
We already supported metadata columns for various connectors. However, they are not documented. 

see https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/table/kafka/#available-metadata

**Comment by leonardBang** [comment]
I think we have documented for all connectors, you can see the documentation in master.

**Comment by wuchong** [comment]
Thanks @leonardBang , you are right.
