### ISSUE TITLE
希望官网能提供flink-sql-connector-oracle-cdc-2.1-SNAPSHOT.jar下载

### ISSUE THREAD

**Issue by HQLboy** [ververica/flink-cdc-connectors#559]

**Comment by leonardBang** [comment]
。。。SNAPSHOT包是开发分支打出来的包，开发分支一般每天都更新的。。。
我觉得你的需求是尽快发布2.1。。。

**Comment by GOODBOY008** [comment]
@HQLboy 其实如果公司要用，最好自己打包，因为一些bug的修复而你的场景刚好遇到，你不可能等到下个release版本的。

**Comment by HQLboy** [comment]
> 。。。SNAPSHOT包是开发分支打出来的包，开发分支一般每天都更新的。。。 我觉得你的需求是尽快发布2.1。。。

抱歉当时不清楚这一点，后面在钉钉群里了解到了，然后也拿mysql在测试环境做了测试
