### ISSUE TITLE
streaming api读取cdc只能到8192条

### ISSUE THREAD

**Issue by ayida** [ververica/flink-cdc-connectors#57]
使用stream api 读取cdc数据，固定读取到8192条就报错，目前没有特殊配置debezium的属性，错误日志贴在下面了
现在不知道具体是什么问题，数据库是mysql 5.7.32，连接数给的1000，cdc版本是1.1.0，下游处理速度可能有点慢，处理完是sink到kafka，求大佬帮忙看看什么问题

> 2020-11-15 12:05:30,489 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Step 8: - 10000 of 25424 rows scanned from table 'sentiment_t.stm_weibo' after 00:00:00.812
> 2020-11-15 12:17:02,433 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Step 8: committing transaction
> 2020-11-15 12:17:02,434 ERROR io.debezium.connector.mysql.SnapshotReader                   [] - Failed due to error: Aborting snapshot due to error when last running 'SELECT * FROM `sentiment_t`.`stm_weibo`': Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@4893ebd7 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
> org.apache.kafka.connect.errors.ConnectException: Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@4893ebd7 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries. Error code: 0; SQLSTATE: S1000.
> 	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:230) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:207) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:831) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
> Caused by: java.sql.SQLException: Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@4893ebd7 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at com.mysql.cj.jdbc.ConnectionImpl.commit(ConnectionImpl.java:813) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:747) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	... 3 more
> 2020-11-15 12:17:02,446 WARN  io.debezium.connector.mysql.SnapshotReader                   [] - Failed to close the connection properly
> java.sql.SQLException: Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@4893ebd7 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at com.mysql.cj.jdbc.ConnectionImpl.rollbackNoChecks(ConnectionImpl.java:1961) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1855) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1720) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:720) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at io.debezium.jdbc.JdbcConnection.close(JdbcConnection.java:849) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:850) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
> 2020-11-15 12:19:48,223 INFO  io.debezium.connector.common.BaseSourceTask                  [] - Stopping down connector
> 2020-11-15 12:19:48,223 INFO  io.debezium.connector.mysql.MySqlConnectorTask               [] - Stopping MySQL connector task
> 2020-11-15 12:19:48,223 INFO  io.debezium.connector.mysql.ChainedReader                    [] - ChainedReader: Stopping the snapshot reader
> 2020-11-15 12:19:48,229 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Discarding 7243 unsent record(s) due to the connector shutting down
> 2020-11-15 12:19:48,229 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Discarding 0 unsent record(s) due to the connector shutting down
> 2020-11-15 12:19:48,232 INFO  io.debezium.connector.mysql.MySqlConnectorTask               [] - Connector task finished all work and is now shutdown
> 2020-11-15 12:19:48,234 ERROR com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction    [] - Reporting error:
> org.apache.kafka.connect.errors.ConnectException: Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@4893ebd7 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries. Error code: 0; SQLSTATE: S1000.
> 	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:230) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:207) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:831) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
> Caused by: java.sql.SQLException: Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@4893ebd7 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at com.mysql.cj.jdbc.ConnectionImpl.commit(ConnectionImpl.java:813) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:747) ~[blob_p-de95de383555477f43fe55225c577ef339176930-358bd41572f076779c3dee0445c89d29:?]
> 	... 3 more
> 2020-11-15 12:19:53,194 INFO  io.debezium.embedded.EmbeddedEngine                          [] - Stopping the embedded engine
> 2020-11-15 12:19:53,202 INFO  io.debezium.embedded.EmbeddedEngine                          [] - Stopping the embedded engine

**Comment by Kaiux** [comment]
遇到了一样的问题，请问楼主解决了吗，可以交流下不？

**Comment by ayida** [comment]
猜测是下游消费太慢，消费完之后cdc那边已经超时了
具体原因没找到，我增加了kafka，cdc处理到kafka，再去消费kafka的数据

**Comment by wolgy** [comment]
一样的问题。数据量大的表偶然出现。但是下游消费不慢（只做了print

**Comment by Kaiux** [comment]
用Flink的application mode可以绕过这个问题

**Comment by lykpass** [comment]
有解决吗

**Comment by lcp5674** [comment]
Hi，I looked up the same question in that DBZ-1926, hope it helps。

DBZ-1926：https://issues.redhat.com/browse/DBZ-1926
