### ISSUE TITLE
mongodb-cdc加了心跳就报空指针错

### ISSUE THREAD

**Issue by aokinba** [ververica/flink-cdc-connectors#579]
**Describe the bug**
mongodb-cdc加了心跳就报空指针错

**Environment :**
 - Flink version :  1.13.1
 - Flink CDC version: mongodb-cdc，最新master
 - Database and version: mongodb

![1636341697563_13E917EC-2CAC-46a3-AEE5-DA9C30319FB6](https://user-images.githubusercontent.com/6531769/140679512-1e16afe2-10d0-4f6e-85b7-66b9197d2ecb.png)
![1636341697589_5F151C52-FEA7-493a-A814-09244856402A](https://user-images.githubusercontent.com/6531769/140679523-20de375f-6ec4-4756-a185-86a6529014d7.png)

**Comment by Jiabao-Sun** [comment]
Thanks @aokinba to report this problem. I'll fix it.
