### ISSUE TITLE
MongoDBConnectorITCase is timeout on Azure

### ISSUE THREAD

**Issue by wuchong** [ververica/flink-cdc-connectors#584]
See the instance: https://dev.azure.com/ververica/flink-cdc-connectors/_build/results?buildId=666&view=logs&j=e0f7c6c4-6c56-5ca5-511d-b91cbc4c1a53&t=35f661f6-a91b-58bc-c86e-9c0883818913&l=906

```
Nov 08 04:41:23 04:41:23.117 [INFO] Running com.ververica.cdc.connectors.mongodb.table.MongoDBConnectorITCase
==========================================================================================
=== WARNING: This task took already 95% of the available time budget of 239 minutes ===
==========================================================================================
==============================================================================
The following Java processes are running (JPS)
==============================================================================
```

**Comment by wuchong** [comment]
@Jiabao-Sun would you like to have a look?

**Comment by Jiabao-Sun** [comment]
OK

**Comment by wuchong** [comment]
Another instance: https://dev.azure.com/ververica/flink-cdc-connectors/_build/results?buildId=695&view=logs&jobId=e0f7c6c4-6c56-5ca5-511d-b91cbc4c1a53&j=e0f7c6c4-6c56-5ca5-511d-b91cbc4c1a53&t=35f661f6-a91b-58bc-c86e-9c0883818913

**Comment by leonardBang** [comment]
https://dev.azure.com/ververica/flink-cdc-connectors/_build/results?buildId=708&view=logs&j=e0f7c6c4-6c56-5ca5-511d-b91cbc4c1a53&t=35f661f6-a91b-58bc-c86e-9c0883818913
