### ISSUE TITLE
Unstable test: MySqlSnapshotSplitAssignerTest. testAssignMultipleTableSplits

### ISSUE THREAD

**Issue by Jiabao-Sun** [ververica/flink-cdc-connectors#589]
Nov 09 07:19:10 07:19:10.865 [ERROR]   MySqlSnapshotSplitAssignerTest.testAssignMultipleTableSplits:109 

<[customers null [462], customers [462] [823], customers [823] [1184], customers [1184] [1545], customers [1545] [1906], customers [1906] null, customers_1 null [462], customers_1 [462] [823], customers_1 [823] [1184], customers_1 [1184] [1545], customers_1 [1545] [1906], customers_1 [1906] null]> 

<[customers null [462], customers [462] [823], customers [823] [1184], customers [1184] [1545], customers [1545] [1906], customers [1906] null, customers_1 null [481], customers_1 [481] [861], customers_1 [861] [1241], customers_1 [1241] [1621], customers_1 [1621] null]>

**Comment by leonardBang** [comment]
Thanks @Jiabao-Sun for report this, I'll fix it later
