### ISSUE TITLE
Mysql Binlog文件拆分之后不能监听到更新数据库的信息。

### ISSUE THREAD

**Issue by kelvenlaw** [ververica/flink-cdc-connectors#590]
**Is your feature request related to a problem? Please describe.**
我们用的是云上数据库，在数据库中开启了binlog，由于binlog都文件会被拆分，分成多个文件。在flink-cdc中不能监听的数据库的任何变化，请问是我这边的配置有问题，还是说flinkcdc需要优化一下？

![image](https://user-images.githubusercontent.com/1327174/140900384-d98f4aa7-7e4f-4cd4-93b4-7cc96db14561.png)

我们的使用方法：
![image](https://user-images.githubusercontent.com/1327174/140900621-aac8b388-4f82-44a8-aef3-27785a0ca9c6.png)
数据提取到的只有数据库原有的信息，没有后续增量的数据内容。

**Comment by leonardBang** [comment]
可以说明下是什么云数据库以及对应的rds版本吗？

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
