### ISSUE TITLE
Can we support a lower version of MySQL under 5.6 in the future

### ISSUE THREAD

**Issue by WenfengJ** [ververica/flink-cdc-connectors#593]
1. Many companies that want to rely  flinkcdc and  must base on MySQL 
 environment.  However, modern Internet companies have more components to replace mysql,   such as tidb..... Etc...

2. Traditional companies  used to use  lower MySQL version for many years  .
 so it is difficult to promote each business team line to upgrade mysql version. 
3. As our  big data platform's Data Engineer job is collect different data type ,like as mysql ,,, ,we can rely debezium,cannel,maxwell, or flinkcdc.   but  we  cannot force the business team to actively upgrade the MySQL version, so it is difficult to promote the flinkcdc to our prod 
4. Therefore, if you could support this function,  make the flinkcdc more perfectly in the future.

**Comment by leonardBang** [comment]
I‘ll try to support MySQL 5.6 soon
