### ISSUE TITLE
在oraclecdc中存在的问题

### ISSUE THREAD

**Issue by liyichencc** [ververica/flink-cdc-connectors#595]
我运行ORACLEcdc作业时发现日志中输出错误

```
Caused by: io.debezium.DebeziumException: Supplemental logging not configured for table HELOWIN.FLINKUSER.demo.  Use command: ALTER TABLE FLINKUSER.demo ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS
	at io.debezium.connector.oracle.logminer.LogMinerHelper.checkSupplementalLogging(LogMinerHelper.java:407)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:132)
	... 7 more
```
但我已经为DEMO表配置了补充日志记录，通过定位我发现是在`io.debezium.connector.oracle.logminer.LogMinerHelper#isTableSupplementalLogDataAll` 
校验时返回了不通过的结果，校验逻辑是会查询 ALL_LOG_GROUPS 表是否有TABLE_NAME = tableId.table() ，通过报错日志可以发现，我的tableId.table()为 'demo',
当我查询数据库是当SQL为` select * from ALL_LOG_GROUPS where TABLE_NAME = 'DEMO'` ,则可以看到一条数据 

`FLINKUSER	SYS_C0011569	DEMO	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME`

但当我把SQL改为  `select * from ALL_LOG_GROUPS where TABLE_NAME = 'demo'` 时，却查不出数据，也就是上面报错的原因，其实我已经开启了补充日志记录，但程序却告诉我没有开启。

请问这是否是一个bug？

**Comment by luoyuxia** [comment]
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

在 oracle 中执行这条命令再试试。

**Comment by liyichencc** [comment]
是的，我已经按照文档的操作执行过这个命令了，还是会有这个问题。我觉得本质上是因为大小写敏感的导致的。

**Comment by luoyuxia** [comment]
看之前有人反馈过：

“原因已经查找出来了，对oracle11 版本， debezium-connector-oracle-1.5.4.Final.jar, 默认会帮我tableIdCaseInsensitive
 设置为true, 导致表名被更新为小写，因此在oracle中查询不到 这个表补全日志设置，导致误报这个Supplemental logging not configured for table 错误”
![image](https://user-images.githubusercontent.com/20389154/141453457-a17c15e1-1b4e-4fba-ba60-8a890bc9fb59.png)

看起来需要加上一个配置项，在代码里面加上这个配置项再重新打包一下看看。

**Comment by liyichencc** [comment]
是的，增加这个配置项后问题得到解决了。谢谢你。
