### ISSUE TITLE
Could not execute SQL statement.

### ISSUE THREAD

**Issue by jeffreyWaaaaaaa** [ververica/flink-cdc-connectors#6]
执行插入的时候报错，
错误信息：
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.table.api.ValidationException: Could not find any factory for identifier 'mysql-cdc' that implements 'org.apache.flink.table.factories.DynamicTableSinkFactory' in the classpath.

Available factory identifiers are:

blackhole
print

**Comment by vissul** [comment]
没加lib包

**Comment by jeffreyWaaaaaaa** [comment]
> 没加lib包

我把包下载后放在了flink/lib下也不可以，请问还需要配置yaml 文件吗？

**Comment by wuchong** [comment]
@jeffreyWaaaaaaa , 放入 flink/lib 下之后，还需要重启 Flink 集群。

**Comment by zqyltx2008** [comment]
@jeffreyWaaaaaaa 执行插入报错 flink-connector-mysql-cdc应该是还不支持创建结果表 创建结果表的时候还是要用原来的connector

**Comment by wuchong** [comment]
原来你在做 insert into 。 mysql-cdc 目前确实只支持读。 如果要写的话，可以用 flink 官方提供的 jdbc connector.

**Comment by jeffreyWaaaaaaa** [comment]
> 原来你在做 insert into 。 mysql-cdc 目前确实只支持读。 如果要写的话，可以用 flink 官方提供的 jdbc connector.

Hi @wuchong  谢谢您的解答，我其实是按照你视频里的教程来做的，但是在在写到es的时候报如下的错，我吧jar包放在lib下了，也一样的错。
![image](https://user-images.githubusercontent.com/22926969/89905047-3daa7e00-dc1c-11ea-870a-bdb328a07fbd.png)

**Comment by wuchong** [comment]
@jeffreyWaaaaaaa ， 重启 SQL Client 了么？
