### ISSUE TITLE
When will we support MySQL 5.6

### ISSUE THREAD

**Issue by dongweizhao** [ververica/flink-cdc-connectors#603]
When will we support MySQL 5.6？

**Comment by yandavid163** [comment]
同问

**Comment by lykpass** [comment]
他们上次在群里说10月底尽量把2.1发布出来，感觉这个月应该会上吧。

**Comment by rookiegao** [comment]
https://github.com/ververica/flink-cdc-connectors/pull/396
我看这边有个测试，不知道具体情况如何了。

**Comment by xhkyyy** [comment]
Please make this feature available ASAP.❤️

**Comment by lykpass** [comment]
![image](https://user-images.githubusercontent.com/48595535/141930383-6c91e883-803a-4e1e-8f50-2fd69a55720b.png)
![image](https://user-images.githubusercontent.com/48595535/141930452-36ea6b55-f384-4f84-9b65-be9f219e8aa6.png)

2.1昨天发布了以为会支持没想到移到2.2了

**Comment by 1105220927** [comment]
翘首以盼~

**Comment by ruanhang1993** [comment]
Duplicate to #593.
