### ISSUE TITLE
strange NoSuchMethodError 

### ISSUE THREAD

**Issue by 5661954** [ververica/flink-cdc-connectors#610]
**Describe the bug**
there's strange NoSuchMethodError just like picture 
![image](https://user-images.githubusercontent.com/3392074/141938596-f3ca4162-45e6-4fc5-899d-d115d7c9898f.png)
the jars in flink 1.14.0 lib as  picture
![image](https://user-images.githubusercontent.com/3392074/141938769-02b7ff55-f1de-4b49-be0a-f7a2980494d5.png)
the method sign is org.apache.flink.api.connector.source.SourceReaderContext metricGroup()Lorg/apache/flink/metrics/groups/SourceReaderMetricGroup; org.apache.flink.metrics.groups.SourceReaderMetricGroup is subinterface of org.apache.flink.metrics.MetricGroup. it's very strange

**Environment :**
 - Flink version :  1.14.0
 - Flink CDC version:  flink-sql-connector-mysql-cdc-2.1.0
 - Database and version:  mysql 8

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**

**Comment by leonardBang** [comment]
Flink CDC 2.1.0 doesn't support Flink 1.14 yet

**Comment by hebeichegu** [comment]
> Flink CDC 2.1.0 doesn't support Flink 1.14 yet

2.1.1 still has this issue. 
Does 2.1.1 not support Flink 1.14 yet?

**Comment by Grypse** [comment]
> > Flink CDC 2.1.0 doesn't support Flink 1.14 yet
> 
> 2.1.1 still has this issue. Does 2.1.1 not support Flink 1.14 yet?

2.1.1 also does not support Flink 1.14.
