### ISSUE TITLE
oracle cdc 2.1.0 一定需要锁表的权限吗？

### ISSUE THREAD

**Issue by dik111** [ververica/flink-cdc-connectors#612]
GRANT CREATE TABLE TO flinkuser;
GRANT LOCK ANY TABLE TO flinkuser;
GRANT ALTER ANY TABLE TO flinkuser;
GRANT CREATE SEQUENCE TO flinkuser;

flink oracle cdc 2.1.0一定需要上面的权限吗？
会像cdc 1.0x版本那样进行锁表的操作吗？

**Comment by rookiegao** [comment]
目前只有mysql cdc 和 mongo cdc 是无锁操作。

**Comment by dik111** [comment]
oracle cdc 配置了 'debezium.snapshot.locking.mode' = 'none'  好像也还是需要锁表权限

**Comment by qiufang1314** [comment]
flink-cdc 2.1版本依赖的 debezium.version 是1.5.4.Final ，对Oracle，改版本是不支持 snapshot.locking.mode参数，1.6后的版本才有支持；而Mysql又是支持的

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
