### ISSUE TITLE
mysql数据库表字符串主键格式生成规则变动导致分片失败

### ISSUE THREAD

**Issue by lgh1122** [ververica/flink-cdc-connectors#618]
**Describe the bug**
在使用cdc做数据同步时，我们的一张业务表，由于前期字符串主键id跟后期id的生成规则不一样，在进行分片时，使用ObjectUtils.compare(chunkEnd, max)并不能正确的返回期望值，导致分片失败，所有数据都集中在一个分片中
前期id格式 ：logistics2018092521000003  
后期id格式 ：ORLOGIAP202111041130281601000001 

**Environment :**
 - Flink version :  1.3.2
 - Flink CDC version: 2.1.0
 - Database and version: 5.7

**To Reproduce**
1. Thes test data :  
 min : logistics2018092521000003  max ORLOGIAP202111041130281601000001 chunkEnd: logistics2018111811000003  

![1637130476278_6F8574C5-8500-4442-9654-EDC9047E77D5](https://user-images.githubusercontent.com/31307232/142147548-fc9dd898-cd3b-4742-b409-d1156bffad47.png)
![1637130557145_7A684A27-D376-4bf3-8AF4-49F93D13A389](https://user-images.githubusercontent.com/31307232/142147604-564dbdd6-f2c1-4d18-a5ff-75e1333c2868.png)

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.

**Comment by lgh1122** [comment]
OK, I have edited the problem description
