### ISSUE TITLE
Is MySQL5.6 be supported?

### ISSUE THREAD

**Issue by sudddenly** [ververica/flink-cdc-connectors#62]
My Database version is 5.6 I wanted to know how can I use cdc?

**Comment by lcp5674** [comment]
Yes,cdc supports mysql version 5.6。Code example:
CREATE TABLE order_info_test_flink(
create_time TIMESTAMP(3),
 id BIGINT,
 consignee STRING,
consignee_tel STRING,
total_amount DECIMAL(10,2),
order_status STRING,
user_id BIGINT,
payment_way STRING,
delivery_address STRING,
order_comment STRING,
out_trade_no STRING,
trade_body STRING,
operate_time TIMESTAMP(3),
expire_time TIMESTAMP(3),
tracking_no STRING,
parent_order_id BIGINT,
img_url STRING,
province_id INT
) WITH(
  'connector' = 'mysql-cdc',
  'hostname' = 'localhost',
  'port' = '3306',
  'username' = 'username',
  'password' = 'password',
  'database-name' = 'test',
  'table-name' = 'order_info',
  'server-time-zone' = 'Asia/Shanghai',
  'debezium.snapshot.locking.mode' = 'none',
  'debezium.snapshot.fetch.size' = '1000',
  'debezium.database.jdbc.driver' = 'com.mysql.jdbc.Driver',
  'debezium.database.ssl.mode' = 'disabled'
);

**Comment by lcp5674** [comment]
> My Database version is 5.6 I wanted to know how can I use cdc?

Yes,cdc supports mysql version 5.6。Code example:
CREATE TABLE order_info_test_flink(
create_time TIMESTAMP(3),
id BIGINT,
consignee STRING,
consignee_tel STRING,
total_amount DECIMAL(10,2),
order_status STRING,
user_id BIGINT,
payment_way STRING,
delivery_address STRING,
order_comment STRING,
out_trade_no STRING,
trade_body STRING,
operate_time TIMESTAMP(3),
expire_time TIMESTAMP(3),
tracking_no STRING,
parent_order_id BIGINT,
img_url STRING,
province_id INT
) WITH(
'connector' = 'mysql-cdc',
'hostname' = 'localhost',
'port' = '3306',
'username' = 'username',
'password' = 'password',
'database-name' = 'test',
'table-name' = 'order_info',
'server-time-zone' = 'Asia/Shanghai',
'debezium.snapshot.locking.mode' = 'none',
'debezium.snapshot.fetch.size' = '1000',
'debezium.database.jdbc.driver' = 'com.mysql.jdbc.Driver',
'debezium.database.ssl.mode' = 'disabled'
);

**Comment by wuchong** [comment]
应该是能用的，不过 5.6 没有完整测过。
