### ISSUE TITLE
Percona版本mysql cdc表创建成功后，select查询失败

### ISSUE THREAD

**Issue by 1932937611** [ververica/flink-cdc-connectors#622]
**Describe the bug**
在flink sql client 创建mysql cdc表，mysql cdc表创建成功后，执行select操作报错！

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version: 2.1.0
 - Mysql version: Server version: 8.0.16-7 Percona Server (GPL), Release 7, Revision 613e312

**To Reproduce**

1.
Flink SQL> CREATE TABLE IF NOT EXISTS `canal_test`.`student_src` (
>   `id` INT NOT NULL,
>   `name` STRING NOT NULL,
>   `sex` STRING NOT NULL,
>   `score` INT NOT NULL,
>   PRIMARY KEY(`id`)
>  NOT ENFORCED
> ) with (
>   'table-name' = 'student',
>   'connector' = 'mysql-cdc',
>   'hostname' = 'xxx.xx.xx.xxx',
>   'port' = '3306',
>   'username' = 'root',
>   'password' = '123456',
>   'database-name' = 'canal_test'
> );
[INFO] Execute statement succeed.

![image](https://user-images.githubusercontent.com/24518467/142175580-3ffea1dc-af34-4219-89a4-432e7369aa20.png)

2.
执行select * from canal_test.student_src;
报错:[ERROR] Could not execute SQL statement. Reason:
java.sql.SQLException: The connection property 'zeroDateTimeBehavior' only accepts values of the form: 'exception', 'round' or 'convertToNull'. The value 'CONVERT_TO_NULL' is not in this set.

![image](https://user-images.githubusercontent.com/24518467/142175700-a7953635-038e-411d-89ea-c26270c8bdbd.png)

**Additional Description**
附上flink/lib
![image](https://user-images.githubusercontent.com/24518467/142176363-c36116bf-8ced-4784-b11a-7d11aafd64fa.png)

网上相关资料显示由于MySql废弃了convertToNull该写法，改为 CONVERT_TO_NULL

猜想：flinkcdc目前没有完全兼容Percona版本mysql，相关属性没有进行修改适配

**Comment by paul8263** [comment]
Hi @1932937611 ,
You might change flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/connection/PooledDataSourceFactory.java.
`public static final String JDBC_URL_PATTERN =
            "jdbc:mysql://%s:%s/?useInformationSchema=true&nullCatalogMeansCurrent=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL";`
and recompile it.

**Comment by 1932937611** [comment]
> Hi @1932937611 , You might change flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/connection/PooledDataSourceFactory.java. `public static final String JDBC_URL_PATTERN = "jdbc:mysql://%s:%s/?useInformationSchema=true&nullCatalogMeansCurrent=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL";` and recompile it.

Thank you. According to your method, we have solved this problem

**Comment by dq1201** [comment]
请问这个问题会在哪个版本进行修复呢？

**Comment by 1932937611** [comment]
> 

小众的版本估计不会专门修复了，就用上面那种方式修改也是可以解决问题的

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
