### ISSUE TITLE
mysql 升级2.1版本后，只能引用8.0.21的mysql-connector-java

### ISSUE THREAD

**Issue by LouisGuo** [ververica/flink-cdc-connectors#627]
pom文件中如果引入其他版本的jar包会启动失败。 这一点最好在升级文档中说明，不然我升级时浪费几个小时来排查这个问题

Caused by: java.lang.NoSuchMethodError: com.mysql.cj.CharsetMapping.getJavaEncodingForMysqlCharset(Ljava/lang/String;)Ljava/lang/String;
  at io.debezium.connector.mysql.MySqlValueConverters.charsetFor(MySqlValueConverters.java:331)
  at io.debezium.connector.mysql.MySqlValueConverters.converter(MySqlValueConverters.java:298)

![lQLPDhrfkGBV-ePNBQPNCfGwaby0CnAtQJwBm4euJ4BDAA_2545_1283](https://user-images.githubusercontent.com/7236537/142342695-9d26126d-0f8e-4e47-97e5-faf7505d5f40.png)

**Comment by leonardBang** [comment]
Thanks @LouisGuo for report this, but I wonder why you need to introduce other version of `mysql-connector-java` in your pom.xml ? it should be a transitive dependency.

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.

**Comment by davideuler** [comment]
Hi Leonard,  I've came across the same issue. 

I use TableEnvironment to execute sql in java code.  flink-connector-mysql-cdc 2.1.1 introduced mysql-connector-java 8.0.28, and it fails with this error:

`Caused by: java.lang.NoSuchMethodError: com.mysql.cj.CharsetMapping.getJavaEncodingForMysqlCharset(Ljava/lang/String;)Ljava/lang/String;
	at io.debezium.connector.mysql.MySqlValueConverters.charsetFor(MySqlValueConverters.java:331)
	at io.debezium.connector.mysql.MySqlValueConverters.converter(MySqlValueConverters.java:298)`

My code 

`StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();

        EnvironmentSettings settings = EnvironmentSettings.newInstance().useBlinkPlanner().inStreamingMode().build();
        TableEnvironment tableEnvironment = StreamTableEnvironment.create(env, settings);

        //enable checkPoint
        env.enableCheckpointing(3000);

        String createSourceTable = "CREATE TABLE flink_users (\n"
            + "    id BIGINT,\n"
            + "    operation_ts TIMESTAMP_LTZ(3) METADATA FROM 'op_ts' VIRTUAL,\n"
            + "    url STRING,\n"
            + "    updated_time BIGINT,\n"
            + "    PRIMARY KEY(id) NOT ENFORCED\n"
            + "    ) WITH (\n"
            + "    'connector' = 'mysql-cdc',\n"
            + "    'hostname' = 'xxxx.mysql.xxx.com',\n"
            + "    'port' = '3306',\n"
            + "    'username' = 'xxxx',\n"
            + "    'password' = 'xxxx,\n"
            + "    'database-name' = 'xxxx',\n"
            + "    'table-name' = 'xxxx')";
       tableEnvironment.executeSql(createSourceTable); `

And I must include the specified version of mysql connector as 8.0.21, then it works. 

`        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.21</version>
        </dependency>
`

The reason is flink-connector-mysql-2.11 introduce dependency to  io.debezium:debezium-connector-mysql:jar:1.5.4.Final.
And debezium-connector-mysql introduces dependency of mysql:mysql-connector-java:jar:8.0.28.

So the method is not found. com.mysql.cj.CharsetMapping.getJavaEncodingForMysqlCharset(String): String 
It is a problem caused by debezium connector.

The method exists in mysql:mysql-connector-java:jar:8.0.21. It is the whole story.

Thanks guys.

**Comment by leonardBang** [comment]
@davideuler Would you like to update the driver version in document here https://ververica.github.io/flink-cdc-connectors/master/content/about.html#supported-connectors ?

**Comment by fanxl12** [comment]
> Hi Leonard, I've came across the same issue.
> 
> I use TableEnvironment to execute sql in java code. flink-connector-mysql-cdc 2.1.1 introduced mysql-connector-java 8.0.28, and it fails with this error:
> 
> `Caused by: java.lang.NoSuchMethodError: com.mysql.cj.CharsetMapping.getJavaEncodingForMysqlCharset(Ljava/lang/String;)Ljava/lang/String; at io.debezium.connector.mysql.MySqlValueConverters.charsetFor(MySqlValueConverters.java:331) at io.debezium.connector.mysql.MySqlValueConverters.converter(MySqlValueConverters.java:298)`
> 
> My code
> 
> `StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
> 
> ```
>     EnvironmentSettings settings = EnvironmentSettings.newInstance().useBlinkPlanner().inStreamingMode().build();
>     TableEnvironment tableEnvironment = StreamTableEnvironment.create(env, settings);
> 
>     //enable checkPoint
>     env.enableCheckpointing(3000);
> 
>     String createSourceTable = "CREATE TABLE flink_users (\n"
>         + "    id BIGINT,\n"
>         + "    operation_ts TIMESTAMP_LTZ(3) METADATA FROM 'op_ts' VIRTUAL,\n"
>         + "    url STRING,\n"
>         + "    updated_time BIGINT,\n"
>         + "    PRIMARY KEY(id) NOT ENFORCED\n"
>         + "    ) WITH (\n"
>         + "    'connector' = 'mysql-cdc',\n"
>         + "    'hostname' = 'xxxx.mysql.xxx.com',\n"
>         + "    'port' = '3306',\n"
>         + "    'username' = 'xxxx',\n"
>         + "    'password' = 'xxxx,\n"
>         + "    'database-name' = 'xxxx',\n"
>         + "    'table-name' = 'xxxx')";
>    tableEnvironment.executeSql(createSourceTable); `
> ```
> 
> And I must include the specified version of mysql connector as 8.0.21, then it works.
> 
> ` <dependency> <groupId>mysql</groupId> <artifactId>mysql-connector-java</artifactId> <version>8.0.21</version> </dependency>`
> 
> The reason is flink-connector-mysql-2.11 introduce dependency to io.debezium:debezium-connector-mysql:jar:1.5.4.Final. And debezium-connector-mysql introduces dependency of mysql:mysql-connector-java:jar:8.0.28.
> 
> So the method is not found. com.mysql.cj.CharsetMapping.getJavaEncodingForMysqlCharset(String): String It is a problem caused by debezium connector.
> 
> The method exists in mysql:mysql-connector-java:jar:8.0.21. It is the whole story.
> 
> Thanks guys.

安装这个思路排查，解决了冲突问题，需要根据debezium-connector-mysql里面的mysql版本设置项目里面的版本，不一致就会报错
