### ISSUE TITLE
升级2.1版本后，本地能启动，flink集群无法启动== No suitable driver

### ISSUE THREAD

**Issue by LouisGuo** [ververica/flink-cdc-connectors#628]
问题原因： 2.1中引入的Hikari连接池没有指定driver。 所以算子在启动时只会从已加载的driver中获取可用driver。如果没有体检加载，就启动不了

目前我只能在static方法中提前手动加载。。。

![1637052582802_04385B1D-B0EE-415f-9946-B84F4D153385](https://user-images.githubusercontent.com/7236537/142342820-c8541439-235e-411a-b1a7-a140e2468aa1.png)
![lQLPDhrfpw07cZfM880CX7CBl1hBPXHnlAGbrNVbgFkA_607_243](https://user-images.githubusercontent.com/7236537/142342918-1d971c59-4ab7-4b1c-b15d-3e4c1b251eee.png)

**Comment by leonardBang** [comment]
Thanks @LouisGuo for report this,  would you like to open a PR to reproduce and fix it ?

**Comment by xiaoshijiang523** [comment]
我也遇到了这个问题，请问您的这个static是在源码里加的吗还是自己的job里加的，我在自己job里加了但还是出现这个问题

**Comment by leonardBang** [comment]
@xiaoshijiang523 你可以分享下你的集群lib下的包和你的job配置吗？我还没能复现这个问题

**Comment by xiaoshijiang523** [comment]
> @xiaoshijiang523 你可以分享下你的集群lib下的包和你的job配置吗？我还没能复现这个问题
好的，这是lib下的包
![截屏2021-11-23 下午3 37 11](https://user-images.githubusercontent.com/48743153/142986084-e5b0235d-2fe5-406c-86fc-b1c9fc42f714.png)

flink conf没有特殊配置，flink1.13.3版本，Flink CDC 是2.1.0

**Comment by leonardBang** [comment]
@xiaoshijiang523 是 stand alone 集群吗？ 作业是怎么提交方便发下吗？

**Comment by xiaoshijiang523** [comment]
> @xiaoshijiang523 是 stand alone 集群吗？ 作业是怎么提交方便发下吗？

是stand alone 集群，提交命令是./flink run -c org.example.flinkcdc /tmp/demo.jar

**Comment by leonardBang** [comment]
谢谢 @xiaoshijiang523 ，我复现下

**Comment by xiaoshijiang523** [comment]
> 谢谢 @xiaoshijiang523 ，我复现下

好的，感谢，如果需要别的详细信息，我再提供。

**Comment by wysstartgo** [comment]
@leonardBang I think we should config driverClassName when we build HikariDataSource instance in com.ververica.cdc.connectors.mysql.source.connection.PooledDataSourceFactory#createPooledDataSource method。

The HikariConfig need this param as well。

<img width="802" alt="00B00BDD-1FB1-4084-993F-712A074201CA" src="https://user-images.githubusercontent.com/10540192/142988922-acee8f6c-24c9-4c07-8208-85254f019457.png">

**Comment by LouisGuo** [comment]
> @leonardBang I think we should config driverClassName when we build HikariDataSource instance in com.ververica.cdc.connectors.mysql.source.connection.PooledDataSourceFactory#createPooledDataSource method。
> 
> The HikariConfig need this param as well。
> 
> <img alt="00B00BDD-1FB1-4084-993F-712A074201CA" width="802" src="https://user-images.githubusercontent.com/10540192/142988922-acee8f6c-24c9-4c07-8208-85254f019457.png">

是的。 这里提供下配置入口就好了

**Comment by zhuxiaoshang** [comment]
我用2.0版本也遇到这个问题
