### ISSUE TITLE
MongoDB | the int-type fields in the fullDocument changed to double-type.

### ISSUE THREAD

**Issue by nienie** [ververica/flink-cdc-connectors#630]
**Describe the bug**
MongoDB | the Int-type fields in the fullDocument changed to double-type.

**Environment :**
 - Flink version :  1.13
 - Flink CDC version:  2.2-SNAPSHOT
 - Database and version: MongoDB 4.0-xenial

**To Reproduce**
1. MongoDB Data
Insert a document into Mongo.

```shell
db.orders.insert({
    order_id: 104,
    order_date: ISODate("2021-07-30T12:00:30.001Z"),
    customer_id: 1003,
    price: NumberDecimal("75.25"),
    order_status: false
});
```

```mongo
rs0:PRIMARY> db.orders.find({})
{ "_id" : ObjectId("6194cc36a571216749e9c44a"), "order_id" : 104, "order_date" : ISODate("2021-07-30T12:00:30.001Z"), "customer_id" : 1003, "price" : NumberDecimal("75.25"), "order_status" : false }
```

The field `order_id` and `customer_id` are `int-type`.

2. Mongo-CDC StreamAPI Code

We use `StringDebeziumDeserializationSchema` to deserialize mongo-cdc data.

```java
        SourceFunction<String> sourceFunction = MongoDBSource.<String>builder()
                .hosts("localhost:27017")
                .username("mongouser")
                .password("mongopw")
                .database("mgdb")
                .collection("orders")
                .deserializer(new StringDebeziumDeserializationSchema())
                .build();
```

3. Deserialization Result

we got the Mongo-cdc data like this.

```text
SourceRecord{
    sourcePartition={ns=mongodb://localhost:27017/mgdb.orders}, 
    sourceOffset={_id={"_data": "8261932D82000000012B022C0100296E5A1004D90B94A598424C18A1F1919766CC3D4A46645F6964006461932D8213BAC2D8EBCEFCBB0004"}}
} 
ConnectRecord{
    topic='mgdb.orders', 
    kafkaPartition=null, 
    key=Struct{_id={"_data": "8261932D82000000012B022C0100296E5A1004D90B94A598424C18A1F1919766CC3D4A46645F6964006461932D8213BAC2D8EBCEFCBB0004"}}, 
    keySchema=Schema{keySchema:STRUCT},
    value=Struct{
        _id={"_data": "8261932D82000000012B022C0100296E5A1004D90B94A598424C18A1F1919766CC3D4A46645F6964006461932D8213BAC2D8EBCEFCBB0004"},
        operationType=insert,
        fullDocument={"_id": {"$oid": "61932d8213bac2d8ebcefcbb"}, "order_id": 104.0, "order_date": {"$date": 1627646430001}, "customer_id": 1003.0, "price": {"$numberDecimal": "75.25"}, "order_status": false},
        source=Struct{ts_ms=1637035394000},
        ns=Struct{db=mgdb,coll=orders},
        documentKey={"_id": {"$oid": "61932d8213bac2d8ebcefcbb"}},
        clusterTime={"$timestamp": {"t": 1637035394, "i": 1}}
    },
    valueSchema=Schema{ChangeStream:STRUCT},  
    timestamp=null, 
    headers=ConnectHeaders(headers=)
}
```

The field `order_id` in the `fullDocument` is a double-type(`104.0`), also the field `customer_id` in the `fullDocument` is a double-type(`1003.0`). But in the MongoDB, `order_id` and `customer_id` are int-type, values are `104` and `1003`.

**Comment by Jiabao-Sun** [comment]
Hi @nienie ,

https://docs.mongodb.com/v4.0/core/shell-types/#numberdecimal
> The mongo shell treats all numbers as 64-bit floating-point double values by default.

Mongo shell treat the literal number 104 as a double value.

![image](https://user-images.githubusercontent.com/27403841/142963319-3081e5b3-f1cb-4807-9c27-f68224200edc.png)

If we need to use `Int` or `Long` type, we need to explicitly declare `order_id` as `NumberInt(105)` or `NumberLong(105)`
```
db.orders.insert({
    order_id: NumberInt(105),
    order_date: ISODate("2021-07-30T12:00:30.001Z"),
    customer_id: NumberInt(1003),
    price: NumberDecimal("75.25"),
    order_status: false
});
```
![image](https://user-images.githubusercontent.com/27403841/142963842-ec799c97-1191-45e0-bf52-4c3194e68374.png)
