### ISSUE TITLE
Runing Job is abnormal,but there is no exception! 同步job无法正常工作，但是并没有任何报错信息和异常报告！

### ISSUE THREAD

**Issue by vrhappy** [ververica/flink-cdc-connectors#635]
**Describe the bug**
按照官方给的例子[https://ververica.github.io/flink-cdc-connectors/master/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/mysql-postgres-tutorial-zh.html](https://ververica.github.io/flink-cdc-connectors/master/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/mysql-postgres-tutorial-zh.html )，在flink上配置source table 和 sink table，之后执行insert into target_products select * from products;启动迁移数据的任务。刚开始是可以同步的，放置一两个小时后，从flink的web上查看，insert-into的job还是Running运行状态，但是实际在source table中增加的数据已经无法同步到target表了。但是，在exceptions里看不到任何异常报错信息。

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version: 2.0.0
 - Database and version: MySQL 5.7.26

**To Reproduce**
参考[官方文档的例子](https://ververica.github.io/flink-cdc-connectors/master/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/mysql-postgres-tutorial-zh.html)
新建一个product表指向源表，新建一个target_products表指向目标库的表。insert into target_products select * from product;来开启迁移job。
1. Thes test data : CREATE TABLE products (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512)
) WITH (
‘connector'='mysql-cdc',
'hostname'='10.121.89.41',
'port'='3306',
'username'='root',
'password'='password',
'database-name'='mydb',
'table-name'='products'
);
CREATE TABLE target_products (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512)
) WITH (
‘connector'='jdbc',
'url'='jdbc:mysql://10.121.89.41:3306/example',
'username'='root',
'password'='password',
'table-name'='products',
'sink.buffer-flush.interval'='0',
'sink.buffer-flush.max-rows'='1'
);
SET execution.checkpointing.interval = 3s;
insert into target_products select * from products;
2. The test code :
3. The error : job开始运行后，放置一个小时后，job仍然是running状态，但是没办法同步源表的数据变更和新增到目标表，从flink:8081中查看没有exception和报错信息。

**Additional Description**

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
