### ISSUE TITLE
mongo cdc username cannot be empty

### ISSUE THREAD

**Issue by yuanxingkang** [ververica/flink-cdc-connectors#640]
**Describe the bug**
use mongo cdc, username cannot be empty

**Environment :**
 - Flink version :  1.13
 - Flink CDC version:  2.1.0
 - Database and version: Mongodb 4.0, flink-sql-connector-mongodb-cdc-2.1.0.jar

**To Reproduce**
1. Thes test data : 
```sql
create table futuniuniuinformation(
_id STRING,
url STRING,
title STRING,
db_name STRING METADATA FROM 'database_name' VIRTUAL,
collection_name STRING METADATA FROM 'collection_name' VIRTUAL,
PRIMARY KEY(_id) NOT ENFORCED
)with (
'connector'='mongodb-cdc',
'hosts'='localhost:27017',
'username'='',
'password'='',
'database'='niuniu',
'collection'='niuniu_informations'
);
```
2. The test code :
3. The error :
<img width="367" alt="a3547c13c9b0da398eb9805cd8f88d6" src="https://user-images.githubusercontent.com/93037616/142993939-ab1ada88-90a4-4c70-bdfe-a947adc6ee22.png">

**Additional Description**
### Error message
<img width="367" alt="a3547c13c9b0da398eb9805cd8f88d6" src="https://user-images.githubusercontent.com/93037616/142993983-f5b6f6e6-293b-4744-b635-a1475e80a449.png">

```
[ERROR] Could not execute SQL statement. Reason:
java.lang.IllegalArgumentException: No username is provided in the connection string
```

**Comment by Jiabao-Sun** [comment]
Hi @yuanxingkang, this problem was fixed by #642.
