### ISSUE TITLE
[mysql] Support heartbeat event for table that update infrequently

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#641]
If the table updates infrequently, the binlog file may have been cleaned in its last committed binlog position

**Comment by camelus0211** [comment]
I am very interested in this, please assign it to me.

**Comment by camelus0211** [comment]
At present, i investigated two options: one add the heartbeat table of the subscription table, and send data to the heartbeat table regularly to achieve the logic of gtid heartbeat; the other is to monitor the binlog full table events in real time at the bottom layer, and update the latest gtid as heartbeat logic.
@leonardBang Do you have any other suggestions? thanks.

**Comment by leonardBang** [comment]
@camelus0211  Thanks for your investigation very much,  the later one is more graceful, I think we can use the heartbeat event from underlying debeizum reader. Could you check `EventDispatcher#dispatchHeartbeatEvent()` in `MySqlBinlogSplitReadTask` and `MySqlStreamingChangeEventSource`?

**Comment by camelus0211** [comment]
thanks, i will check it.

**Comment by camelus0211** [comment]
I post the design document here, [API design](https://docs.google.com/document/d/1XVS6opo8adTqJK3KiJibKXjloKB_hW22PBNzvHRa0GU/edit#heading=h.259eqklad6hn), feel free to comment. 
@leonardBang thanks.

**Comment by leonardBang** [comment]
> I post the design document here, [API design](https://docs.google.com/document/d/1XVS6opo8adTqJK3KiJibKXjloKB_hW22PBNzvHRa0GU/edit#heading=h.259eqklad6hn), feel free to comment. @leonardBang thanks.

The design makes sense to me @camelus0211 , please open the PR and we can discuss under the PR later.
