### ISSUE TITLE
是否有可能将增量同步的数据源改为kafka消息中的binlog

### ISSUE THREAD

**Issue by robinWuYW** [ververica/flink-cdc-connectors#647]
由于使用的是tdsql，无法通过mysql-binlog-connector获得binlog，只能通过订阅kafka获得。
所以想请教下是否有可能通过改动部分源码实现保留全量同步部分，单独将增量同步部分的数据源改为解析kafka消息中的Binlog。

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
