### ISSUE TITLE
[bug]address wrong class type in MysqlSource and MysqlSourceBuilder comments 

### ISSUE THREAD

**Issue by YesOrNo828** [ververica/flink-cdc-connectors#650]
**Describe the bug**
There are wrong class type description in class comments(`MysqlSource`, `MysqlSourceBuilder`). Should be `MySqlSource.<String>builder()`, but now `MySqlSource.<RowData>builder()`.

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version: 2.2-snapshot

**Comment by YesOrNo828** [comment]
@leonardBang  I want to address it, can you assign it to me?

**Comment by leonardBang** [comment]
> @leonardBang I want to address it, can you assign it to me?

Thanks @YesOrNo828, assigned you.
