### ISSUE TITLE
使用oracle cdc报错

### ISSUE THREAD

**Issue by HQLboy** [ververica/flink-cdc-connectors#654]
使用flink 1.13.3进行mysql cdc能成功，把mysql-cdc的jar包删除，然后把oracle-cdc-2.1.0的jar包放到lib目录下，报错：
[ERROR] Could not execute SQL statement. Reason:
java.io.InvalidClassException: com.ververica.cdc.debezium.table.RowDataDebeziumDeserializeSchema; local class incompatible: stream classdesc serialVersionUID = 2, local class serialVersionUID = -4852684966051743776

**Comment by HQLboy** [comment]
提交到之前创建的yarn session导致这个问题，提交到本地无此问题

**Comment by justdoit-code** [comment]
你好，我也遇到这个问题，请问怎么解决呢，我用的版本如下，应该是你提交bug后的版本了
flink:1.13.1 flink-sql-connector-oracle-cdc:2.2.1
