### ISSUE TITLE
oracle cdc 取到的历史快照数据和增量数据 是会一直放在内存吗 ？

### ISSUE THREAD

**Issue by szs903** [ververica/flink-cdc-connectors#655]
**Describe the bug**
oracle cdc 取到的历史快照数据和增量数据 是会一直放在内存吗 ？我用下面这种方式可以吗，谢谢答复~

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version: 2.1
 - Database and version: 11.2.0.4

StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
		env.setParallelism(1);
		StreamTableEnvironment tableEnv = StreamTableEnvironment.create(env);
		String oracleDDL = "CREATE TABLE ORACLE_TABLE (" +
				" ID INT," +
				" BIGINT_ID BIGINT," +
				" VAR_NAME STRING," +
				"PRIMARY KEY(ID) NOT ENFORCED" +
				") WITH (" +
				"  'connector' = 'oracle-cdc'," +
				"  'hostname' = '127.0.0.1'," +
				"  'port' = '1521'," +
				"  'username' = 'dbzuser'," +
				"  'password' = 'dbzuser'," +
				"  'database-name' = 'PROD'," +
				"  'schema-name' = 'DBZUSER'," +
				"  'table-name' = 'FLINK_CDC'," +
				" 'scan.startup.mode' = 'initial'" +
				")";

		String filterSql = "select ID from ORACLE_TABLE";
		tableEnv.executeSql(oracleDDL).print();
		Table resultTable = tableEnv.sqlQuery(filterSql);
		tableEnv.toRetractStream(resultTable, Row.class).print("result");

		env.execute();

**Comment by xuexh0816** [comment]
不会吧 数据会一直往下流 不会一直在这个算子里的 除非你后面的算子堵住了，然后barrier也发不下去 然后ck 就没法进行了 然后就挂了 。。。我的job就是这样失败的-.-

**Comment by szs903** [comment]
> 不会吧 数据会一直往下流 不会一直在这个算子里的 除非你后面的算子堵住了，然后barrier也发不下去 然后ck 就没法进行了 然后就挂了 。。。我的job就是这样失败的-.-

我以这样的方式创建两个或者多个表 ， 多个表之间join，业务中就难免会出现一个表A中的数据晚于另一个表B中的数据很久，那此时B表的数据是会存放在哪里 ，是state中吗

**Comment by xuexh0816** [comment]
join 方式很多种，得看哪种，数据是存在state里的 但是有state 清除的配置 ttl

**Comment by szs903** [comment]
> join 方式很多种，得看哪种，数据是存在state里的 但是有state 清除的配置 ttl

感谢回答 ，regular join

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
