### ISSUE TITLE
debezium 1.7或1.8版本支持

### ISSUE THREAD

**Issue by wittech** [ververica/flink-cdc-connectors#660]
目前已经使用了postgresql14，需要debezium 1.7或1.8版本支持，请问可以直接升级debezium的版本吗？

**Comment by fsk119** [comment]
Flink Mysql  CDC uses some inner class in debeizum. It may have some conflicts when bump the debeizum version. You can make a try and submit a PR. 

Also could you share the release notes from debezium 1.6,1.7,1.8. The break changes may also influence the upgrade.

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
