### ISSUE TITLE
oracle 19c版本的float数据类型对应flink sql的float失败

### ISSUE THREAD

**Issue by HQLboy** [ververica/flink-cdc-connectors#667]
**Describe the bug**

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version: 2.1.0
 - Database and version: oracle 19c

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :
4. 
[ERROR] Could not execute SQL statement. Reason:
java.lang.NumberFormatException: For input string: "Struct{scale=0,value=[B@7696705f}"
**Additional Description**

把flink sql里的类型改为string，能正常select，但是该2字段会显示为Struct{scale=0,value=[B@7696705f}，改为其他数据类型都会失败。

**Comment by HQLboy** [comment]
该字段只有一个值：0

**Comment by HQLboy** [comment]
> 该字段只有一个值：0

修正：该字段只有0和null两个值

**Comment by ashulin** [comment]
https://github.com/ververica/flink-cdc-connectors/pull/560

**Comment by GOODBOY008** [comment]
@leonardBang PR:https://github.com/ververica/flink-cdc-connectors/pull/560 have merged.
