### ISSUE TITLE
[Feature] Support oceanbase cdc connector

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#668]
OceanBase Database[1] is a native distributed relational database, it's an open source  project with many users especially in the financial industry. With the Oceanbase CDC connector,  we  can help users to integrate data easily.

[1] https://github.com/oceanbase

**Comment by wuchong** [comment]
We can consume oceanbase transaction log using https://github.com/oceanbase/oblogclient,  there is also a pull request in Canal community to add support for oceanbase: https://github.com/alibaba/canal/pull/3867. 

Supporting oceanbase-cdc connector can help users to do streaming ETL and build real-time materialize view on Oceanbase very easy using Flink SQL.  I think we can cooperate on this with Oceanbase community.

**Comment by whhe** [comment]
Hello team, I am the maintainer of [oblogclient](https://github.com/oceanbase/oblogclient) and will have a try on this in next few days.

**Comment by leonardBang** [comment]
> Hello team, I am the maintainer of [oblogclient](https://github.com/oceanbase/oblogclient) and will have a try on this in next few days.

Happy to hear that @whhe , assigned this ticket to you.
