### ISSUE TITLE
按照例子，表都是千万级的，任务一直无法完成

### ISSUE THREAD

**Issue by laifulin** [ververica/flink-cdc-connectors#67]
INSERT INTO enriched_orders
SELECT o.*, p.name, p.description, s.shipment_id, s.origin, s.destination, s.is_arrived
FROM orders AS o
LEFT JOIN products AS p ON o.product_id = p.id
LEFT JOIN shipments AS s ON o.order_id = s.order_id;
您好，按照这个例子，假如orders表与products表都是千万级数据的表，任务一直没法完成，数据处理到一部分，整个任务就挂了，想问下，这个有没有办法解决呀？

**Comment by swjsj** [comment]
请问最后有解决吗 ？
