### ISSUE TITLE
mysql的连接无法设置一些参数

### ISSUE THREAD

**Issue by zackyoungh** [ververica/flink-cdc-connectors#674]
代码如下
```java
public static final String JDBC_URL_PATTERN =
            "jdbc:mysql://%s:%s/?useInformationSchema=true&nullCatalogMeansCurrent=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL";
```
如果我想加上userSSL=false,这时候应该怎么弄；
不让老是碰到
```
No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
```
得手动修改java.security才能解决

> 希望这连接参数配置优化一下

**Comment by leonardBang** [comment]
It makes sense to me, could you change the title and description in English ?

**Comment by ashulin** [comment]
I have the same requirement，maybe we can add a 'connection.pool.url.*' options similar to 'debezium.*';

**Comment by miaogr86** [comment]
![image](https://user-images.githubusercontent.com/5835603/154455981-8bd8dfbb-2059-4b69-88b9-0bcf24851dd8.png)

![image](https://user-images.githubusercontent.com/5835603/154456173-0474c67d-47cc-418b-b62e-a8b6204451f5.png)

@leonardBang 数据库连接地址上增加userSSL=false 可以解决，但是怎么可以增加这个参数

**Comment by qq443672581** [comment]
1. 下载对应版本的源码
2. 找到 PooledDataSourceFactory 添加useSSL=false 参数
3. flink-connector-mysql-cdc 模块下 mvn spotless:apply
4. flink-connector-mysql-cdc 模块下 mvn install 替换maven仓库中官方的jar即可

**Comment by paul8263** [comment]
Hi @leonardBang ,
This issue is related to https://github.com/ververica/flink-cdc-connectors/issues/674

I think we should allow user to add or even customize the JDBC URL parameters by configurations.

I'd like to help . Could you please assign this issue to me?

**Comment by paul8263** [comment]
Hi @leonardBang ,
Considering https://github.com/ververica/flink-cdc-connectors/issues/674 , can we only set 
```
useInformationSchema=true&nullCatalogMeansCurrent=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8
```
as mandatory parameters and 
```
zeroDateTimeBehavior=CONVERT_TO_NULL
```
as default value?
Thus the user will be able to overwrite 'zeroDateTimeBehavior=CONVERT_TO_NULL' and add custom ones so that those compatibility issues can be avoided.

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.

**Comment by ruanhang1993** [comment]
When fix the bug https://github.com/ververica/flink-cdc-connectors/pull/1188, I find that the jdbc properties are not set to the connection rightly. This issue should be reopened and fixed again.

**Comment by ruanhang1993** [comment]
I am willing to help to fix this ticket and add some IT tests.

**Comment by leonardBang** [comment]
Thanks @ruanhang1993 for taking this, I've assigned this ticket to you.
