### ISSUE TITLE
The data defined as number in the table field read by Oracle CDC in Oracle 11 does not display the result correctly, but the encoded value is displayed

### ISSUE THREAD

**Issue by DouglasJun** [ververica/flink-cdc-connectors#675]
**Describe the bug**
Oracle 11 Oracle CDC has some problems in obtaining the data of number field. If it is the definition of number (3) and number (4,3), there is no problem after deserialization of string debezium deserialization schema. However, JSON debezium deserialization schema cannot correctly obtain the data of number (4,3). You can get number (3). If you directly define number, you define the size without parentheses. For example, number (a, b), neither serializer can get the result correctly

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version: 2.1.p
 - Database and version: oracle11.2.0.1

**To Reproduce**
1. Thes test data :
2. The test code :
        Properties properties = new Properties();
        properties.setProperty(
                "log.mining.strategy",
                "online_catalog");
        properties.setProperty("log.mining.continuous.mine","true");
  
        SourceFunction<String> build = OracleSource.<String>builder()
                .hostname("172.16.10.218")
                .port(1521)
                .database("orcl")
                .schemaList("sdt_xjb")
                .tableList("sdt_xjb.test_cdc1")
                .username("flink_cdc")
                .password("flink_cdc")
                .deserializer(new JsonDebeziumDeserializationSchema())
                .startupOptions(StartupOptions.initial())
                .debeziumProperties(properties)
                .build();
        env.addSource(build)
                .print()
                .setParallelism(1);

        env.execute("FlinkCDC");
3. The error :
**Additional Description**
_**Table definitions that do not display correctly:**_
![image](https://user-images.githubusercontent.com/32092231/144373672-ffeecbf9-033e-490c-8459-0fcc294fa17c.png)
table data:
![image](https://user-images.githubusercontent.com/32092231/144377509-ff160c12-bbea-441d-9ad7-372389035573.png)
Deserialization results with JSON debezium deserialization schema:
![jsonS](https://user-images.githubusercontent.com/32092231/144374329-23386abc-df23-4446-9589-4b8a15207754.png)
Deserialization results with String debezium deserialization schema:
![image](https://user-images.githubusercontent.com/32092231/144374558-aab05ea9-a7de-44e0-8d7e-1b17d7ddeda4.png)

**_Table definition that can be displayed correctly:_**
![image](https://user-images.githubusercontent.com/32092231/144375155-63edff06-fd88-4c6d-a838-b2f007e31de7.png)
table data:
![image](https://user-images.githubusercontent.com/32092231/144377533-081cd809-fecc-42de-a993-dba4950bd8c8.png)
Deserialization results with JSON debezium deserialization schema:
![image](https://user-images.githubusercontent.com/32092231/144377043-29e4dd31-59eb-4d66-8da2-a931272b5c8f.png)
Deserialization results with String debezium deserialization schema:
![image](https://user-images.githubusercontent.com/32092231/144376026-8f76de7f-eac7-44a8-a85b-069d07bd5386.png)

**Comment by leonardBang** [comment]
could you change the title and description in English? thanks.

**Comment by DouglasJun** [comment]
> could you change the title and description in English? thanks.

already changed

**Comment by QQZZAZ** [comment]
> **Describe the bug** Oracle 11 Oracle CDC has some problems in obtaining the data of number field. If it is the definition of number (3) and number (4,3), there is no problem after deserialization of string debezium deserialization schema. However, JSON debezium deserialization schema cannot correctly obtain the data of number (4,3). You can get number (3). If you directly define number, you define the size without parentheses. For example, number (a, b), neither serializer can get the result correctly
> 
> **Environment :**
> 
> * Flink version :  1.13.3
> * Flink CDC version: 2.1.p
> * Database and version: oracle11.2.0.1
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Thes test data :
> 2. The test code :
>    Properties properties = new Properties();
>    properties.setProperty(
>    "log.mining.strategy",
>    "online_catalog");
>    properties.setProperty("log.mining.continuous.mine","true");
>    ```
>     SourceFunction<String> build = OracleSource.<String>builder()
>             .hostname("172.16.10.218")
>             .port(1521)
>             .database("orcl")
>             .schemaList("sdt_xjb")
>             .tableList("sdt_xjb.test_cdc1")
>             .username("flink_cdc")
>             .password("flink_cdc")
>             .deserializer(new JsonDebeziumDeserializationSchema())
>             .startupOptions(StartupOptions.initial())
>             .debeziumProperties(properties)
>             .build();
>     env.addSource(build)
>             .print()
>             .setParallelism(1);
>    
>     env.execute("FlinkCDC");
>    ```
> 3. The error :
>    **Additional Description**
>    _**Table definitions that do not display correctly:**_
>    ![image](https://user-images.githubusercontent.com/32092231/144373672-ffeecbf9-033e-490c-8459-0fcc294fa17c.png)
>    table data:
>    ![image](https://user-images.githubusercontent.com/32092231/144377509-ff160c12-bbea-441d-9ad7-372389035573.png)
>    Deserialization results with JSON debezium deserialization schema:
>    ![jsonS](https://user-images.githubusercontent.com/32092231/144374329-23386abc-df23-4446-9589-4b8a15207754.png)
>    Deserialization results with String debezium deserialization schema:
>    ![image](https://user-images.githubusercontent.com/32092231/144374558-aab05ea9-a7de-44e0-8d7e-1b17d7ddeda4.png)
> 
> **_Table definition that can be displayed correctly:_** ![image](https://user-images.githubusercontent.com/32092231/144375155-63edff06-fd88-4c6d-a838-b2f007e31de7.png) table data: ![image](https://user-images.githubusercontent.com/32092231/144377533-081cd809-fecc-42de-a993-dba4950bd8c8.png) Deserialization results with JSON debezium deserialization schema: ![image](https://user-images.githubusercontent.com/32092231/144377043-29e4dd31-59eb-4d66-8da2-a931272b5c8f.png) Deserialization results with String debezium deserialization schema: ![image](https://user-images.githubusercontent.com/32092231/144376026-8f76de7f-eac7-44a8-a85b-069d07bd5386.png)

you can set db settings like:
Properties properties = new Properties();
properties.setProperty("decimal.handling.mode","STRING");
SourceFunction<String> sourceFunction = OracleSource.<String>builder()
		.hostname("xx.xx.xx.xx")
		.port(1521)
		.database("ORCL")
		.schemaList("AUTOTEST") 
		.tableList("AUTOTEST.ZDB_TEST") 
		.username("flinkuser")
		.password("flinkpw")
		.debeziumProperties(properties)
		.deserializer(new JsonDebeziumDeserializationSchema(false))
//                .deserializer(new StringDebeziumDeserializationSchema()) 
		.startupOptions(StartupOptions.initial())
		.build();

**Comment by DouglasJun** [comment]
> 

Thanks , It's working

**Comment by DouglasJun** [comment]
> you can set Debezium settings like: Properties properties = new Properties(); properties.setProperty("decimal.handling.mode","STRING"); SourceFunction sourceFunction = OracleSource.builder() .hostname("xx.xx.xx.xx") .port(1521) .database("ORCL") .schemaList("AUTOTEST") .tableList("AUTOTEST.ZDB_TEST") .username("flinkuser") .password("flinkpw") .debeziumProperties(properties) .deserializer(new JsonDebeziumDeserializationSchema(false)) // .deserializer(new StringDebeziumDeserializationSchema()) .startupOptions(StartupOptions.initial()) .build();

Thanks,It's working
