### ISSUE TITLE
flink-cdc mysql-connector 1.4.0 报错db history topic is missing, 无法恢复。

### ISSUE THREAD

**Issue by zzq55307** [ververica/flink-cdc-connectors#678]
环境配置：
flink版本：1.13.2
cdc版本：1.4.0
mysql版本：5.6.28

报错情况：
1. flink-cdc运行一段时间后( 数据库有binlog变更 )，报错 ：the db history is missing. You may attempt to recover it by reconfiguring the connector to SCHEMA_ONLY_RECOVERY.
![企业微信截图_16384420683099](https://user-images.githubusercontent.com/71960940/144407726-c5ffddb5-2a17-4e17-9a2f-1d78fbac090e.png)
2. 根据报错提示，修改connector配置为 'snapshot.mode'='schema_only_recovery'，并由savepoint恢复任务，又发生报错：
![image](https://user-images.githubusercontent.com/71960940/144409143-54f1d19b-efbf-4e04-9b06-aa181bfb5a25.png)
检查mysql数据库参数均正确：binlog_row_image: FULL binlog_format:ROW   

求大佬帮看下

**Comment by zzq55307** [comment]
binlog_row_image:FULL
binlog_format:ROW

**Comment by leonardBang** [comment]
This is a known bug, please use 2.0.2 or 2.10 version which has fixed it

**Comment by zzq55307** [comment]
因为使用的mysql版本比较低，1.4.0 是目前能用的最高版本了。 期待新版本能早日支持上5.6版本的mysql

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.

**Comment by gnikgnaw** [comment]
> This is a known bug, please use 2.0.2 or 2.10 version which has fixed it

Hi,May I ask what is causing this problem. thank you!
