### ISSUE TITLE
flinkcdc 同步oracle，数据缺失

### ISSUE THREAD

**Issue by HQLboy** [ververica/flink-cdc-connectors#686]
**Describe the bug**

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version: 2.1.0
 - Database and version: oracle 19c
**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

步骤：
1.创建flink yarn session: ./yarn-session.sh -s 4 -jm 2048 -tm2048-nm lis1 -d
2.登录flink sql客户端，创建10个oracle,flink的映射表，然后创建对应的10个flink,kafka的映射表，配置参数：
SET execution.checkpointing.tolerable-failed-checkpoints= 100;
SET restart-strategy= fixed-delay;
SET restart-strategy.fixed-delay.attempts=2147483647;
SET execution.checkpointing.interval = 3600s;
3.提交作业语句如下：
BEGIN STATEMENT SET;
insert into kafka_A
select * from A;
insert into B
select * from B;
insert into C
select * from C ;
insert into D
select * from D;
insert into E
select * from E;
insert into F
select * from F;
insert into H
select * from H;
insert into I
select * from I;
insert into J
select * from J;
insert into K
select * from K;
end;
4.表的数据量如下count(1)
1	588633	
2	4149	
3	30518108	
4	8484259	
5	64649	
6	18573	
7	427	
8	1983474	
9	106	
10	2856959	
作业启动之前其中一张表的kafka偏移量是55315002，1个小时之后，偏移量是63799197，63799197-55315002=8484195，StarRocks里的数据量也是8484195，但是这张表查询的数据量是8484259，kafka的偏移量至于63799197一直未更新，flink web ui，taskmanager日志未报错(其中一行日志：Finished exporting 8484195 records for table 'A'; total duration '00:25:08.608')
![image](https://user-images.githubusercontent.com/55019221/144637633-6c08b6f2-a5e1-4232-b3f1-09500564f8ef.png)
![image](https://user-images.githubusercontent.com/55019221/144640065-598c988f-d5bf-428a-b6ee-f9fe084e672f.png)

**Comment by HQLboy** [comment]
运行一晚上之后报错：Online REDO LOG files or archive log files do not contain the offset scn 713870265.  Please perform a new snapshot

**Comment by HQLboy** [comment]
![image](https://user-images.githubusercontent.com/55019221/145660526-5bc6d0c2-f29c-4f76-8d72-d912654e2b37.png)

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
