### ISSUE TITLE
Flink cdc 2.0.2运行正常，升级Flink cdc 2.1.0在其他环境不变的情况下运行报错

### ISSUE THREAD

**Issue by JamesIsHuang** [ververica/flink-cdc-connectors#691]
![image](https://user-images.githubusercontent.com/12915720/145138860-224459e8-8ce3-476d-aafd-9fe5033fa184.png)
![image](https://user-images.githubusercontent.com/12915720/145138921-a2812475-94e9-41af-b09a-9ab5b5c4e53f.png)

**Comment by 260998215** [comment]
请问解决了吗，我也遇到这个问题

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
