### ISSUE TITLE
Match multiple database and collection names using a regular expression in MongoDB

### ISSUE THREAD

**Issue by samuelyyl** [ververica/flink-cdc-connectors#699]
希望能够参考mongodb kafka-connector 读取多个源的语法，支持在自定义正则表达式同步多个库/表的。
> 当前2.1.0的版本支持将db或collection设置为空字符串，这将同步全部库或某库下全部表。
> https://docs.mongodb.com/kafka-connector/v1.4/source-connector/usage-examples/multiple-sources/

**Comment by samuelyyl** [comment]
主要是处于性能考虑，将多个表的同步放在一个任务中，否则同步n个表将有n个连接去使用Mongo UpdateStream，对Mongo有比较大的影响。

建立宽表同步多个表，目前看来我遇到的问题：不同Mongo表同名字段类型冲突概率大大提高，这将让我转而使用DataStream的语法去手动处理类型冲突。

**Comment by bobby-richard-sed** [comment]
I would like to see this functionality as well. I sent PR a while back, but it was never merged https://github.com/ververica/flink-cdc-connectors/pull/475. I'm happy to fix the merge conflicts if it will be merged.

**Comment by samuelyyl** [comment]
来信已收到~                叶运隆

**Comment by bobby-richard** [comment]
I would love to see this functionality as well. I sent this PR https://github.com/ververica/flink-cdc-connectors/pull/475, but it was never merged. I'm happy to fix the merge conflicts if it will be merged.

**Comment by Jiabao-Sun** [comment]
Thanks @samuelyyl, @bobby-richard for the suggestion for improvement.
I'll close this issued because this feature is supported by #940.

**Comment by samuelyyl** [comment]
来信已收到~                叶运隆
