### ISSUE TITLE
DataStream API Demo 修改后出现 UnsupportedOperationException

### ISSUE THREAD

**Issue by hsh075623201** [ververica/flink-cdc-connectors#7]
![image](https://user-images.githubusercontent.com/7548881/89901355-8f9cd500-dc17-11ea-993b-423ce1e43346.png)

如上图所示：
目的是为了获取对象，而不是字符串，但是出现报错，请问应该如何处理呢？

**Comment by wuchong** [comment]
SourceRecord 是不能序列化的，还是需要将 SourceRecord 转成自己的数据结构（可序列化）

**Comment by hsh075623201** [comment]
@wuchong 感谢！

**Comment by 812406210** [comment]
> ![image](https://user-images.githubusercontent.com/7548881/89901355-8f9cd500-dc17-11ea-993b-423ce1e43346.png)
> 
> 如上图所示：
> 目的是为了获取对象，而不是字符串，但是出现报错，请问应该如何处理呢？

你好，请问下，如果不进行序列化，这个demo是不是不能解析SourceRecord
