### ISSUE TITLE
Oracle CDC Connector only support SID instead of Service Name

### ISSUE THREAD

**Issue by dingyang0519** [ververica/flink-cdc-connectors#701]
The "database-name" option is now directly translated into SID instead of Service Name in the codes below: (selected from com.ververica.cdc.connectors.oracle.OracleValidator)

    public static Connection openConnection(Properties properties) throws SQLException {
        DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
        String hostname = properties.getProperty("database.hostname");
        String port = properties.getProperty("database.port");
        String dbname = properties.getProperty("database.dbname");
        String userName = properties.getProperty("database.user");
        String userpwd = properties.getProperty("database.password");
        return DriverManager.getConnection(
                "jdbc:oracle:thin:@" + hostname + ":" + port + ":" + dbname, userName, userpwd);
    }

Notice that in the Oracle RAC system, Service name is widely used insted of SID. So it is suggested that the JDBC URL here should be add the choice of connecting Service Name like below (":" is replaced by "/") :
"jdbc:oracle:thin:@" + hostname + ":" + port + "/" + dbname, userName, userpwd)

**Comment by sty945** [comment]
Very helpful !!! Thank you so much!!!

**Comment by luoyuxia** [comment]
@dingyang0519 Thanks very much, would you like to open a pr for it? We'll really appreciate that.

**Comment by 290352095** [comment]
关于这个问题，大家可以移步https://github.com/ververica/flink-cdc-connectors/issues/632#issuecomment-984258805，我根据这个建议解决了用servicename连接RAC集群的问题

**Comment by leonardBang** [comment]
Fixed in https://github.com/ververica/flink-cdc-connectors/issues/1244
