### ISSUE TITLE
OracleTableSourceFactoryTest 报错 配置文件中的image找不到

### ISSUE THREAD

**Issue by yummyheng** [ververica/flink-cdc-connectors#711]
运行oracle test案例报错
com.github.dockerjava.api.exception.DockerClientException: Could not build image: The command '/bin/sh -c mkdir /u01/app/oracle/oradata/recovery_area &&     bash -x /assets/activate-archivelog.sh' returned a non-zero code: 127

![image](https://user-images.githubusercontent.com/3580351/145544676-bce845ee-9b39-48eb-afcb-3621695c28c6.png)
![image](https://user-images.githubusercontent.com/3580351/145545255-8353bee2-3002-4d59-b914-774e74ee2cbd.png)
![image](https://user-images.githubusercontent.com/3580351/145544899-ec5e98a4-59fa-420d-9d80-05deb97f0a55.png)
![image](https://user-images.githubusercontent.com/3580351/145545471-4fa1a3d2-77d7-478a-a9a6-4b33c3f782ea.png)

 - Flink version :  1.13.3
 - Flink CDC version: 2.1

**Additional Description**

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
