### ISSUE TITLE
使用incremental的方式读取全量数据的时候，snapshot读取完成之后，再读取binlog数据，binlog数据中会有之前snapshot中已经insert的数据

### ISSUE THREAD

**Issue by luxuebao** [ververica/flink-cdc-connectors#716]
使用incremental的方式读取全量数据的时候，snapshot读取完成之后，再读取binlog数据，binlog数据中会有之前snapshot中已经insert的数据，就是说使用incremental的方式全量读取mysql数据的时候，不能保证精确一次。
CREATE TABLE test1 (
id varchar(10),
value varchar(10)
primary key(id) not enforced)
with(
'connector' = 'mysql-cdc',
 'hostname' = 'XXXX',
 'port' = '4417',
 'username' = 'bigdata_r',
 'password' = 'XXXXX',
 'database-name' = 'test',
 'table-name' = 'test1',
 'scan.incremental.snapshot.enabled'='true',
 'scan.incremental.snapshot.chunk.size' = '10240',
 'scan.snapshot.fetch.size' = '1024',
 'scan.startup.mode'='initial'
);

select count(*),id from test1 group by id having count(*)>1;

以上的sql是我测试时的逻辑，测试结果可以参考下图
![image](https://user-images.githubusercontent.com/20124259/145801268-2ad9101e-a73c-41f2-9780-06d942da4c32.png)
有些id 被count之后会出现两次，说明数据重复插入了

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.

**Comment by JesseAtSZ** [comment]
请问这个问题最后解决了吗？我这里也遇到了类似的问题
