### ISSUE TITLE
[test][mongodb]SomeTimes mongodb test ("testConsumingAllEvents") runs timeout when checking pr.

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#721]
**Additional Description**
SomeTimes mongodb test ("testConsumingAllEvents") runs timeout when checking pr.

**Comment by leonardBang** [comment]
Thanks @GOODBOY008 for opening this ticket, cool!
https://dev.azure.com/ververica/flink-cdc-connectors/_build/results?buildId=804&view=logs&j=e0f7c6c4-6c56-5ca5-511d-b91cbc4c1a53&t=35f661f6-a91b-58bc-c86e-9c0883818913
