### ISSUE TITLE
flinkcdc2.1增量BINLOG不前进不变动问题

### ISSUE THREAD

**Issue by niunan2019** [ververica/flink-cdc-connectors#726]
**Describe the bug**

**Environment :**
 - Flink version :  1.13.1
 - Flink CDC version: 2.1
 - Database and version:  mysql5.7

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :
```
作业报错 The connector is trying to read binlog starting at GTIDs xxx and binlog file '"mysql-bin.008391","pos":"55779304", skipping 4 events plus 1 rows, but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed
```
**Additional Description**
目前我用flinkcdc过程中Binlog位置一直不前进，导致7天后过期报上面的异常，目前的Binlog位置时8391，是第一次启动全量加增量时的位置。源数据一直有变动修改。目前的BINLOG已经到了9000了。POS位置有在前进。不是道是慢还是怎么回事

**Comment by haormj** [comment]
the same problem in 2.1.1

**Comment by haormj** [comment]
you can set `scan.incremental.snapshot.enabled` = `false` to resolve it

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.

**Comment by ldwnt** [comment]
> Could you use English for better communication? feel free to reopen once updated the description.

FlinkCDC MySQL connector option "heartbeat.interval" is introduced in version 2.2. With version 2.1, can I use the Debezium config prop "heartbeat.interval.ms" to achieve the same goal of fetching latest binlog offset when there is no updates on table A while the db binlog offset keeps changing all the time?

**Comment by leonardBang** [comment]
> > Could you use English for better communication? feel free to reopen once updated the description.
> 
> FlinkCDC MySQL connector option "heartbeat.interval" is introduced in version 2.2. With version 2.1, can I use the Debezium config prop "heartbeat.interval.ms" to achieve the same goal of fetching latest binlog offset when there is no updates on table A while the db binlog offset keeps changing all the time?

No, the quickest way is bumping you flink cdc version to 2.2

**Comment by ldwnt** [comment]
> 

Thanks for clarification
