### ISSUE TITLE
mysql用增量模式到kafka，update一个字段的内容，输出到kafka的json没有before {"before":null,"after":{"id":5,"name":"shawn","age":90},"op":"c"}

### ISSUE THREAD

**Issue by wjshean** [ververica/flink-cdc-connectors#729]
tableEnv.executeSql("CREATE TABLE cdc_test (" +
                " id INT ," +
                " name STRING," +
                " age INT," +
                "primary key(id)  NOT ENFORCED"+
                ") WITH (" +
                " 'connector' = 'mysql-cdc'," +
                " 'hostname' = '10.10.5.11'," +
                " 'port' = '3306'," +
                " 'username' = 'tiangou'," +
                " 'password' = 'tiangou123'," +
                " 'database-name' = 'standford'," +
                " 'table-name' = 'cdc_test'," +
                " 'scan.startup.mode' = 'latest-offset'" +
                ")");

        tableEnv.executeSql("CREATE TABLE kafka_mysql_cdc (\n" +
                "  id INT,\n" +
                "  name STRING,\n" +
                "  age INT\n" +
                ") WITH (\n" +
                " 'connector' = 'kafka',\n" +
                " 'topic' = 'cdc_test',\n" +
                " 'properties.bootstrap.servers' = '10.10.5.104:9092',\n" +
                " 'scan.startup.mode' = 'latest-offset',\n" +
                " 'format' = 'debezium-json'\n" +
                ")");
        tableEnv.executeSql("INSERT INTO kafka_mysql_cdc SELECT id,name,age FROM cdc_test");

**Comment by paul8263** [comment]
Hi @wjshean ,
Could you get the data before change if you print the table cdc_test?

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
