### ISSUE TITLE
A failover happens when mysql source occur, Flink cdc job is always restart

### ISSUE THREAD

**Issue by camelus0211** [ververica/flink-cdc-connectors#743]
**Describe the bug**
A failover happens when mysql source occur, Flink cdc job is always restart. 

**Environment :**
 - Flink version :  1.13
 - Flink CDC version: 2.2
 - Database and version: mysql 5.7

**Additional Description**
<img width="1211" alt="wecom-temp-705b6903a5b894beb6e5ce7ce82a0ec7" src="https://user-images.githubusercontent.com/44798441/146723552-bcbfffea-ff84-497f-a1d7-2af0a0a8375c.png">

**Comment by ruanhang1993** [comment]
The PR has been merged. Close this issue.
