### ISSUE TITLE
任务异常循环重启时，未释放连接

### ISSUE THREAD

**Issue by ljc2008110** [ververica/flink-cdc-connectors#744]
**Describe the bug**
当数据库binlog设置保留较少时，任务读取binlog时发现数据库的对应position的binlog已被清除，在这种情况下会发生task不断失败重启，此时重启任务时未释放数据库连接，重新初始化数据库连接，导致最终数据库连接数不断上升的问题。

**Environment :**
 - Flink version :  1.13.0
 - Flink CDC version: 2.1.0
 - Database and version: mysql 5.7.26

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**

**Comment by 762871227Wang** [comment]
我们也遇到了连接数持续上升的情况.
环境 ：
Flink 版本：1.13.3
Flink CDC 版本：2.1.0
数据库及版本：mysql 8.0.18

**Comment by leonardBang** [comment]
@gwqlovelinux Could you use English for better communication? feel free to reopen once updated the description.
