### ISSUE TITLE
多个任务同时使用一个Source table server-id如何设置

### ISSUE THREAD

**Issue by yuxihongdan** [ververica/flink-cdc-connectors#75]
INSERT INTO flink_issue_report
SELECT
       cast(DATE_FORMAT(update_at, 'yyyy-MM-dd') as date) AS report_date,
       ticket_id,
       ticket_plan_no,
       cast(count( 1 ) as INT) AS bet_count,
       cast(count( CASE WHEN bet_status = 5 THEN 1 END ) as INT) AS prize_count,
       cast(sum( bet_money ) as DECIMAL(14, 4))AS bet_amount,
       cast(sum( win_amount ) as  DECIMAL(14, 4))AS prize_amount,
       merchant_id,
       merchant_account
FROM flink_order 
WHERE bet_status IN ( 2, 5 ) AND cancel_status = 0 AND tester = 0
GROUP BY DATE_FORMAT(update_at, 'yyyy-MM-dd'),merchant_id,merchant_account,ticket_id,ticket_plan_no;

这个是我多job任务  请问如何设置server-id？

**Comment by wwek** [comment]
11. 多个作业共用同一张 source table 时，没有修改 server id 导致读取出来的数据有丢失。

原因：MySQL binlog 数据同步的原理是，CDC source 会伪装成 MySQL 集群的一个 slave（使用指定的 server id 作为唯一 id），然后从 MySQL 拉取 binlog 数据。如果一个 MySQL 集群中有多个 slave 有同样的 id，就会导致拉取数据错乱的问题。
解决方法：默认会随机生成一个 server id，容易有碰撞的风险。所以建议使用动态参数（table hint）在 query 中覆盖 server id。如下所示：
SELECT *
FROM bill_info /*+ OPTIONS('server-id'='123456') */ ;


来自： Flink SQL CDC 上线！我们总结了 13 条生产实践经验   https://developer.aliyun.com/article/773642?spm=a2c6h.12873639.0.0.6c3b53e4mJ9gC3

**Comment by wuchong** [comment]
@wwek 的回答已经很清楚了。
