### ISSUE TITLE
oracle connector大数据量拉取 snapshot too old

### ISSUE THREAD

**Issue by JamesIsHuang** [ververica/flink-cdc-connectors#755]
![image](https://user-images.githubusercontent.com/12915720/147526105-7d35091b-521e-4916-a269-30911e0d5bb8.png)

**Comment by hellochueng** [comment]
同样遇到了
java.sql.SQLException: ORA-01555: snapshot too old: rollback segment number 25 with name "_SYSSMU25_61319981$" too small

**Comment by JamesIsHuang** [comment]
> 同样遇到了 java.sql.SQLException: ORA-01555: snapshot too old: rollback segment number 25 with name "_SYSSMU25_61319981$" too small

有解决吗？

**Comment by hellochueng** [comment]
用其他工具拉分批拉全量，flink cdc只拉增量，后面还会有logminer慢导致log被删问题。无盖

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
