### ISSUE TITLE
Could FlinkCDC be supported on  Alicloud Full Hosting platform？

### ISSUE THREAD

**Issue by vleyong** [ververica/flink-cdc-connectors#758]
Like the topic said. I used the Alicloud Full Hosting Flink platform ,but I don't know how to apply FlinkCDC on this platform,is it supported?
Thanks .

**Comment by leonardBang** [comment]
@vleyong I guess you mean the fully managed flink platform provides by AliCloud. AFAK, all Flink CDC connectors are supported by them. You can consult them for more details.

**Comment by gnuhpc** [comment]
More powerful features would be provided in the fully-managed Flink cloud service by Alibaba Cloud.

**Comment by vleyong** [comment]
Thanks
