### ISSUE TITLE
[Feature] Support oracle-cdc connector

### ISSUE THREAD

**Issue by ZChanghai** [ververica/flink-cdc-connectors#76]
Is there any plan to support oracle-cdc connector?

**Comment by sparsh2rahul** [comment]
Any update on this enhancement ?

**Comment by leonardBang** [comment]
see #76

**Comment by ili-zh** [comment]
If the Cloudera team expects contributions longer than now, I can support a simplified version.

**Comment by fsk119** [comment]
Some feedbacks from the dingtalk about the request of the Oracle CDC connector.

![1630585603666-9a7adf09-3f6e-49b0-8770-e0a17682e325](https://user-images.githubusercontent.com/33114724/132158740-ff9a98f9-e197-455f-a3d9-8ce5a6f04933.png)
![1630399736297-432ba9e8-140f-489f-b919-e2d0ac6903f9](https://user-images.githubusercontent.com/33114724/132158737-30cec219-8995-4c9c-8e74-560e3487e621.png)
![1630566408004-a7429fdb-a659-46a9-b14b-53dcf8af0123](https://user-images.githubusercontent.com/33114724/132158730-1b3e05c8-b40e-4917-b3bc-fd06218b8ce1.png)

**Comment by ili-zh** [comment]
> Some feedbacks from the dingtalk about the request of the Oracle CDC connector.
> 
> ![1630585603666-9a7adf09-3f6e-49b0-8770-e0a17682e325](https://user-images.githubusercontent.com/33114724/132158740-ff9a98f9-e197-455f-a3d9-8ce5a6f04933.png)
> ![1630399736297-432ba9e8-140f-489f-b919-e2d0ac6903f9](https://user-images.githubusercontent.com/33114724/132158737-30cec219-8995-4c9c-8e74-560e3487e621.png)
> ![1630566408004-a7429fdb-a659-46a9-b14b-53dcf8af0123](https://user-images.githubusercontent.com/33114724/132158730-1b3e05c8-b40e-4917-b3bc-fd06218b8ce1.png)

I need debezium-oracle to accept my PR support for SCHEMA_ONLY_RECOVERY snapshot mode so that it can support earliest-offset/specific-offset/timestamp mode

**Comment by leonardBang** [comment]
Implemented by #418
