### ISSUE TITLE
flink 1.14 sql client kafka source bug

### ISSUE THREAD

**Issue by A-little-bit-of-data** [ververica/flink-cdc-connectors#763]
**Describe the bug**
![lQLPDhsBYjf-FsbMvc0Cu7DE0QQ_7cUilAHS8LEcQKQA_699_189](https://user-images.githubusercontent.com/31812278/147796957-55d5fd5b-8acf-41cd-bf49-9e07b77b3021.png)

This is caused by the fact that flink 1.14 Kafka source forced auto.offset.reset to none when using group, which caused the use of client to not continue the last offset consumption.

**Environment :**
 - Flink version :  1.14
 - Flink CDC version: 
 - Database and version: 

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**

**Comment by ruanhang1993** [comment]
It is not a cdc source issue.
