### ISSUE TITLE
REQ：密码密文调用

### ISSUE THREAD

**Issue by littleforce163** [ververica/flink-cdc-connectors#764]
**Is your feature request related to a problem? Please describe.**
在写sql建表语句中，可以通过引用方式调用密码吗？
希望秘密不是明文的。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by littleforce163** [comment]
-- creates a mysql cdc table source
CREATE TABLE mysql_binlog (
 id INT NOT NULL,
 name STRING,
 description STRING,
 weight DECIMAL(10,3)
) WITH (
 'connector' = 'mysql-cdc',
 'hostname' = 'localhost',
 'port' = '3306',
 'username' = 'flinkuser',
 'password' = '**flinkpw**',
 'database-name' = 'inventory',
 'table-name' = 'products'
);

-- read snapshot and binlog data from mysql, and do some transformation, and show on the client
SELECT id, UPPER(name), description, weight FROM mysql_binlog;

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
