### ISSUE TITLE
flink读取kafka数据如何指定读取的节点

### ISSUE THREAD

**Issue by yuxihongdan** [ververica/flink-cdc-connectors#77]
您好，因为我们kafka的数据是通过canal 读取mysql的binlog来的，json 格式数据里面有一个data节点数据。我只想读取这个数据需要如何弄？
如下是我的kafka里的json数据。
{
	"data": [{
		"order_id": "1342086493337813064",
		"play_id": "180200101"
	}],
	"database": "mkcp",
	"es": 1608813496000,
	"id": 32270,
	"isDdl": false,
	"mysqlType": {
		"order_id": "bigint(20)",
		"ticket_plan_no": "varchar(32)"
	},
	"old": [{
		"bet_status": "1",
		"ticket_result": ""
	}],
	"pkNames": ["order_id"],
	"sql": "",
	"sqlType": {
		"order_id": -5,
		"play_id": 4
	},
	"table": "t_ticket_bet_order",
	"ts": 1608813496253,
	"type": "UPDATE"
}
如下是我的flink table 
CREATE TABLE flink_order(
  order_id BIGINT,
  play_id INT
)WITH (
    'connector' = 'kafka',  
    'topic' = 'mkcp_orders',  
    'scan.startup.mode' = 'earliest-offset',  
    'properties.bootstrap.servers' = 'XXXXX',
    'format' = 'json'
);

**Comment by ithjz** [comment]
你好你的问题解决了吗?报啥错了?

**Comment by wuchong** [comment]
用 canal-json 而不是 json： https://ci.apache.org/projects/flink/flink-docs-master/docs/connectors/table/formats/canal/

Btw，你问错地方了。这个仓库是用来支持 cdc connector 的。
