### ISSUE TITLE
flink-cdc binlog不消费

### ISSUE THREAD

**Issue by 1105220927** [ververica/flink-cdc-connectors#789]
**Describe the bug**

**Environment :**
 - Flink version :  1.13.3  standalone
 - Flink CDC version: 1.4.0
 - Database and version:  mysql 5.7.17

1. 任务运行过程中发生task manager FullGC( full gc时间较长，40+s ) ，进而导致任务失败重启，自动重启之后就不再继续消费binlog。
2. 重新通过checkpoint手动重启，仍然无法继续消费binlog
3. 手动不通过checkpoint重启，任务可以继续消费binlog

根据现象感觉似乎是因为tm失联之后，触发了什么bug，导致checkpoint也有问题。 哪位大佬可以帮看下这里的问题

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
