### ISSUE TITLE
sql client cannot write data into es

### ISSUE THREAD

**Issue by jeffreyWaaaaaaa** [ververica/flink-cdc-connectors#8]
SQL client 执行insert into Enriched_orders的时候报错

![image](https://user-images.githubusercontent.com/22926969/89969186-5a7c9b00-dc88-11ea-931c-fe18d61308db.png)
其中es-connector的jar包已导入到lib下并重启了
![image](https://user-images.githubusercontent.com/22926969/89969245-826bfe80-dc88-11ea-83b0-c1f06a320f23.png)

**Comment by wuchong** [comment]
SQL Client 重启了么？

**Comment by jeffreyWaaaaaaa** [comment]
> SQL Client 重启了么？

重启了

**Comment by wuchong** [comment]
再列一下 `flink/lib` 下的文件？

**Comment by jeffreyWaaaaaaa** [comment]
> 再列一下 `flink/lib` 下的文件？

![image](https://user-images.githubusercontent.com/22926969/89991073-e1943800-dcb5-11ea-9aba-a51117373c96.png)

**Comment by wuchong** [comment]
这个挺奇怪的。。 理论上不应该啊。我这边也没法复现你的问题。

**Comment by jeffreyWaaaaaaa** [comment]
> 这个挺奇怪的。。 理论上不应该啊。我这边也没法复现你的问题。

好的，谢谢大佬 👍 。我在重新弄个环境试下看看，也期待你下次的学习视频

**Comment by jeffreyWaaaaaaa** [comment]
问题已经解决，下载的jar没有下载完全导致的 😭 谢谢

**Comment by wuchong** [comment]
额，还能这样...
