### ISSUE TITLE
mysql/postgres任务每次执行，可以接着上次的binlog的位置读取吗？

### ISSUE THREAD

**Issue by zwangcheng** [ververica/flink-cdc-connectors#80]
本地执行案例，使用stream抽取mysql或者postgres的指定表，如果停止任务，重新运行，抽取的日志每次都是一样的，从头开始抽取；想请问一下可以接着上次任务运行结束抽取的位置，继续抽取日志吗？

**Comment by kimmazhenxin** [comment]
做完checkpoint后就从上次位置消费了

**Comment by a626411464** [comment]
> 本地执行案例，使用stream抽取mysql或者postgres的指定表，如果停止任务，重新运行，抽取的日志每次都是一样的，从头开始抽取；想请问一下可以接着上次任务运行结束抽取的位置，继续抽取日志吗？

您好，实现了吗，可否分享一下配置代码，谢谢~

**Comment by 812406210** [comment]
> 做完checkpoint后就从上次位置消费了

你好，怎么实现的呀？每次都是全表的进行处理

**Comment by wuchong** [comment]
重新运行相当于这个作业无状态重启，自然是会从头开始消费的。 你要从 savepoint 恢复作业，才能从之前的位置继续消费。

**Comment by naive1992** [comment]
只能用savepoint实现吗，如果任务意外失败，重新运行怎么办

**Comment by wuchong** [comment]
@naive1992 v1.3.0 提供了比较丰富的 start offset 参数，具体可以看下 wiki 文档。

**Comment by naive1992** [comment]
@wuchong 我想实现的是从上次消费位置接着消费，目前看来只能从binlog指定position读取
