### ISSUE TITLE
MongoDB 支持 Raw 类型

### ISSUE THREAD

**Issue by mofadeyunduo** [ververica/flink-cdc-connectors#802]
**Is your feature request related to a problem? Please describe.**
MongoDB 是一个不强类型的语言，有的时候一个字段可能有多个类型，这个时候定义成任何类型都会报错。比如字段 A 可以存 String 和 Document，这个时候按照 MongoDB CDC 手册上无法定义这个类型，目前我看 RAW 类型是不支持的。

**Describe the solution you'd like**
需要 RAW 类型，当做 JSON 保存字段。

**Describe alternatives you've considered**
String as JSON 通用存储某些字段。

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
