### ISSUE TITLE
全量增量同步切换时在某些并发场景下会导致数据重复和落后

### ISSUE THREAD

**Issue by xiaoyu19950911** [ververica/flink-cdc-connectors#814]
**Describe the bug**
数据在进行全量同步时，假设正在同步chunk_0[<1,v1>,<2,v2>,<3,v3>]，同步前记录low_watermark，同步后记录high_watermark，high_watermark记录完后立即update id=2的数据为<2,v2_after>，此时结果表会出现两条<2,v2>的数据，update id=3的数据为<3,v3_after>，此时结果表出现<3,v3_after>，只有重新update id=2的数据为<2,v2_after_after>后，结果表才会出现<2,v2_after>，id=2这条记录始终落后一条binlog数据

**Environment :**
 - Flink version :  1.13
 - Flink CDC version: 2.1
 - Database and version: mysql 5.7.31

**Additional Description**
如图，id=2，counter_type=2的数据出现了两次
![image](https://user-images.githubusercontent.com/31729765/150080168-8ba9aa73-b561-44ea-afe5-179e0be78b58.png)

**Comment by Capri0110** [comment]
source是多并行的吗
我测试了所有source parallelism > 1 ，从 latest-offset 启动的场景，直接进入增量阶段（下游kafka使用 semantic.EXACTLY_ONCE)，首次启动时正常的，但是如果因为某些 failure job restart之后，上游并行的subtask 就会去重复消费binlog，下发到 kafka broker 的消息会重复

**Comment by JesseAtSZ** [comment]
请问这个问题最后解决了吗？我这里也遇到了类似的问题

**Comment by leonardBang** [comment]
duplicated with #716
