### ISSUE TITLE
我使用1.13.5版本的standalone启动，加入clickhouse-jdbc之后，找不到jdbc驱动

### ISSUE THREAD

**Issue by weilingfeng98** [ververica/flink-cdc-connectors#823]
**Describe the bug**

**Environment :**
 - Flink version :  1.3.5
 - Flink CDC version: 2.1.0
 - Database and version: 5.7

**To Reproduce**
1. Thes test data :

> CREATE TABLE sys_user (
    `user_id` BIGINT,
    `nick_name` STRING,
    `user_name` STRING,
	`dept_id` BIGINT,
    PRIMARY KEY (`user_id`) NOT ENFORCED
) WITH (
   'connector' = 'mysql-cdc',
   'hostname' = 'x.x.x.x',
   'port' = '3306',
   'username' = 'root',
   'password' = '123456',
   'database-name' = 'erp',
   'table-name' = 'sys_user'
);

2. The test code :
3. The error :
`Flink SQL> select * from sys_user;
[ERROR] Could not execute SQL statement. Reason:
java.sql.SQLException: No suitable driver
`

**Additional Description**

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
