### ISSUE TITLE
能否支持数据同步相关的监控metrics

### ISSUE THREAD

**Issue by luguanxing** [ververica/flink-cdc-connectors#825]
背景：
同步cdc数据时，需要监控binlog落后情况，目前是手动解析获取数据里面的eventTs作监控指标，比较麻烦且对于目标表如果是非连续数据会隔一段时间才更新eventTs

需求：
1.能否提供直接对接promethues的metrics监控数据，不需要代码层面手动从数据中获取eventTs
2.能否提供相对于整个数据库的延迟（不仅只对于需要目标表的）监控，能更准确监控同步延迟的落后情况

**Comment by camelus0211** [comment]
![image](https://user-images.githubusercontent.com/44798441/152467995-7ce158fb-fd5a-4a5a-9438-bddfe82df193.png)
https://github.com/ververica/flink-cdc-connectors/blob/master/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/metrics/MySqlSourceReaderMetrics.java
cdc目前支持了订阅表fetchtime/eventtime等事件

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.

**Comment by zhangqiang1116** [comment]
> [luguanxing](/luguanxing)

在用mysql cdc数据同步时，web ui上没有显示binlog读取情况的metrics,无法感知binlog有无延迟；请问有解决方法吗
