### ISSUE TITLE
2.1.1 MysqlSource startup option 启动项

### ISSUE THREAD

**Issue by Capri0110** [ververica/flink-cdc-connectors#828]
看到 2.1.1 目前 startup options 只支持设置 initial / latest_offset，
在2.2 road map 里未看到相关规划
想问下 目前是否有规划支持其他 startupMode 语义？
 （这对于我们从某一个状态开始启动/重启 对mysql实例的实时同步抽数非常有帮助）

**Comment by rookiegao** [comment]
+1
