### ISSUE TITLE
实现DebeziumDeserializationSchema，针对性输出问题

### ISSUE THREAD

**Issue by 812406210** [ververica/flink-cdc-connectors#84]
实现deserializer(new DebeziumDeserializationSchema()，并解析binlog数据，针对性的输出想要的数据，发现无法在flink算子中获取数据，请问如何解决呢？望指点下

**Comment by wuchong** [comment]
你可以先用仓库提供的 `StringDebeziumDeserializationSchema` 然后把捕获到的数据打印出来看看是否有数据。
然后再实现自定义 deserializer.

**Comment by 812406210** [comment]
我自定义实现解析了，但是打印不出来&nbsp;

请问是什么问题吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jark Wu"<notifications@github.com&gt;; 
发送时间: 2021年2月24日(星期三) 下午3:03
收件人: "ververica/flink-cdc-connectors"<flink-cdc-connectors@noreply.github.com&gt;; 
抄送: "想你"<812406210@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ververica/flink-cdc-connectors] 实现DebeziumDeserializationSchema，针对性输出问题 (#84)





 
你可以先用仓库提供的 StringDebeziumDeserializationSchema 然后把捕获到的数据打印出来看看是否有数据。
 然后再实现自定义 deserializer.

**Comment by wuchong** [comment]
用 `StringDebeziumDeserializationSchema` 能打印出来吗？

**Comment by 812406210** [comment]
能够得，就是自己定义解析后就不能打印出来，我只在deserialize做了解析，getProducedType和String那个一样。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jark Wu"<notifications@github.com&gt;; 
发送时间: 2021年2月24日(星期三) 下午4:11
收件人: "ververica/flink-cdc-connectors"<flink-cdc-connectors@noreply.github.com&gt;; 
抄送: "想你"<812406210@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ververica/flink-cdc-connectors] 实现DebeziumDeserializationSchema，针对性输出问题 (#84)





 
用 StringDebeziumDeserializationSchema 能打印出来吗？

**Comment by wuchong** [comment]
那要看下你的自定义实现。
