### ISSUE TITLE
Flink CDC2.1.0版本部署在flink1.14版本里报找不到类org.apache.flink.shaded.guava18.com.google.common.util.concurrent.ThreadFactoryBuilder

### ISSUE THREAD

**Issue by wo8000** [ververica/flink-cdc-connectors#841]
**Describe the bug*
flink 部署集群模式，
java.lang.ClassNotFoundException: org.apache.flink.shaded.guava18.com.google.common.util.concurrent.ThreadFactoryBuilder

**Environment :**
 - Flink version :  1.14.2
 - Flink CDC version: 2.1.0
 - Database and version: mysql 5.8

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**
![image](https://user-images.githubusercontent.com/23306829/153163648-54df675a-5cd0-42d3-9aaf-d7ae89527dd3.png)

![image](https://user-images.githubusercontent.com/23306829/153163461-a424cd3c-d80b-4c91-85ee-94629faf0522.png)

![image](https://user-images.githubusercontent.com/23306829/153164275-ef9d69db-2230-436f-af9f-c9c4efbfa93b.png)

**Comment by qixurulin** [comment]
貌似现在只支持到1.13,下个版本才支持1.14

**Comment by GourdErwa** [comment]
2.2 才支持 1.14 版本，要不 flink 换 1.13，要不 编译一个 cdc-master

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.

**Comment by WaylandWong** [comment]
master branch flink-sql-connector-*.jar works well with flink 1.14 while flink-connector-*.jar does not.
---

@wo8000  master分支已支持flink 1.14，不过要使用flink-sql-connector-*.jar
