### ISSUE TITLE
为什么2.2不支持SQLServer2016以下版本?比如2014?

### ISSUE THREAD

**Issue by qixurulin** [ververica/flink-cdc-connectors#843]
不是所有人都在用这么高的版本啊

**Comment by EcoleKeine** [comment]
可能是coder没有测过吧
我试着改了版本限制，简单跑了下好像没有问题
https://github.com/ververica/flink-cdc-connectors/issues/88#issuecomment-1022820041

**Comment by GOODBOY008** [comment]
Hi@qixurulin @EcoleKeine ,Flink cdc connector use embedded debezium engine  as source, just follow db version which debezium offical supported(debezium have pass test).But It does not mean, debezium do not support db version they declare.You can see this discussion [link](https://gitter.im/debezium/user?at=5e72743792063209fed8887a).

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
