### ISSUE TITLE
Design Documentation

### ISSUE THREAD

**Issue by mohanr** [ververica/flink-cdc-connectors#844]
I was looking for a consolidated list of features and found this.

Thus, Flink SQL collection, computing, and ETL can be unified, which has the following advantages:

Small end-to-end latency
Exactly-once guarantee for read and compute
No data storage and lower storage costs
Stream reading of full and incremental data supported
Backtracking of Binlog collection site

The documentation for this is key when we compare and contrast this with Kafka Connect Worker Clusters and its CDC support.
Where can I locate the detailed explanation of the points mentioned above ?

**Comment by leonardBang** [comment]
Nice insight @mohanr ！ Currently our documentation focuses on technical details and does not list the pros and cons that users consider when choosing a project. I think we can open a new chapter to document the advantages of Flink CDC Connector and the advantages of combining Flink SQL.

**Comment by wuchong** [comment]
Good point! I think we need to highlight the advantages in the home page. Do you want to contribute the documentation?

**Comment by mohanr** [comment]
I am beginning to look at Flink. If I locate some benchmarks and test code I can try.
