### ISSUE TITLE
flinksql模式下怎么拿到mysql binlog里的operation和beforedata？

### ISSUE THREAD

**Issue by boenxu2** [ververica/flink-cdc-connectors#847]
flinksql模式下怎么拿到binlog里的operation和beforedata，operation如数据是insert，update还是delete；beforedata如operation是update时，输出数据既能显示更新后的数据，也会输出更新前的数据。

**Comment by guixin** [comment]
在 Table API 转 Stream API 模式下可以拿到 row 信息，知道当前数据是什么事件类型（delete, insert, update_before, update_after）。目前 Flink SQL 应该没有提供操作类型的 METADATA

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
