### ISSUE TITLE
能否指定全量同步不同表时,同步的先后顺序

### ISSUE THREAD

**Issue by mabiao17921** [ververica/flink-cdc-connectors#850]
cdc版本：2.11
使用：datastream
场景: 使用cdc监听两张mysql表,  表A 和 表B .   两张表的DateStream进行 connect 操作.
         正常业务逻辑是先消费A表,将主键信息存储在状态中,然后根据状态过滤B表的数据.

问题: 当CDC先全量同步A在全量同步B ,逻辑正常.  先全量同步B,在全量同步A,因为状态中缺少数据就会造成  业务上的 过滤异常

能否指定全量同步不同表的 先后顺序. 
( 我自测 MySqlSource.<String>builder().tableList("A,B")   中的顺序不影响 全量同步的顺序,而是根据字典顺序)

**Comment by fuyun2024** [comment]
建议你可以把 B 表变成主表， A 表变成广播流的方式，然后在广播流算子中做逻辑判断，如果 B 表的数据来到了，没有发现 A 中的状态，就把 B 表的数据存储到状态中，等发现 A 表的数据来后，再刷新历史状态中的数据。

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.
