### ISSUE TITLE
[doc] Add connection.pool.size and connect.max-retries option in mysql document

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#854]
We missed document when introduced mysql connection pool in https://github.com/ververica/flink-cdc-connectors/pull/534, we should add the introduced configuration options in document.

**Comment by eastfisher** [comment]
please assign to me

**Comment by leonardBang** [comment]
Thanks for taking this issue @eastfisher, assigned to you.

**Comment by eastfisher** [comment]
> Thanks for taking this issue @eastfisher, assigned to you.

Hi, I've submitted a PR #857 to fix this issue, please take a look. ^_^
