### ISSUE TITLE
Any ideas of supporting elaticsearch ?

### ISSUE THREAD

**Issue by spancer** [ververica/flink-cdc-connectors#86]
I'm wondering whether are we going to support Elasticsearch in the future?

**Comment by wuchong** [comment]
The `flink-cdc-connectors` is based on Debezium. Unfortunately, Debezium doesn't support Elasticsearch. I'm afraid we can't support Elasticsearch in the near future.

**Comment by spancer** [comment]
> The `flink-cdc-connectors` is based on Debezium. Unfortunately, Debezium doesn't support Elasticsearch. I'm afraid we can't support Elasticsearch in the near future.

Got it.  I'll close this issue.
