### ISSUE TITLE
[mysql] Too many splitInfo cause OOM of jobmanager

### ISSUE THREAD

**Issue by minchowang** [ververica/flink-cdc-connectors#865]
**Describe the bug**

in the issue https://issues.apache.org/jira/browse/FLINK-24855， have some problems when we sync big tables or full database 

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version:  2.1.1
 - Database and version: mysql-5.7

**To Reproduce**
1. Thes test data :  The data scale more than billion ，and produce more than one hundred thousand enumerator state
2. The test code :  The multiple tables sync by stream api 
3. The error :
Source Coordinator Thread already exists. There should never be more than one thread driving the actions of a Source Coordinator.

**Additional Description**

**Comment by mincwang** [comment]
Temporary optimization points:
1.  increase size of `scan.incremental.snapshot.chunk.size = 8096(default)` to 80960 or 809600

**Comment by miaogr86** [comment]
me too @leonardBang

**Comment by miaogr86** [comment]
不规则的主键情况下执行
SELECT MAX(`tid`) FROM (SELECT `tid` FROM `sod`.`sod_bill_info` WHERE `tid` >= 59935676 ORDER BY `tid` ASC LIMIT 242880) AS T
非常慢，checkpoint会失败，taskmanager读取数据中断

**Comment by leonardBang** [comment]
@mincwang I think we can clean up the splits information form JM state at some point e.g. the binlog reading has been start

**Comment by mincwang** [comment]
> @mincwang I think we can clean up the splits information form JM state at some point e.g. the binlog reading has been start

agree ， but this issue  happened during reading snapshot phase. So cleanup the splits info belong to improve in the binlog phase?

**Comment by mincwang** [comment]
However，in the reading snapshot phase increase `jm.process.size` Is also can solve this  issues,  in the reading binlog phase reduce `jm.process.size` to release these shouldn't have resource overhead

**Comment by mincwang** [comment]
but It needs me to ops  the rescale of resource, we have too many db-instance(800+)，This is hard work for me . 😭

**Comment by mincwang** [comment]
# Screenshots:
![image](https://user-images.githubusercontent.com/33626973/159217553-b25b8d8e-b945-4525-827a-4730cf8ad04e.png)

**Comment by zhjwpku** [comment]
If the split info is cleaned up in the snapshot phase, the logic before **pure** binlog read phase can be wrong ;(

**Comment by minchowang** [comment]
> If the split info is cleaned up in the snapshot phase, the logic before **pure** binlog read phase can be wrong ;(

https://github.com/ververica/flink-cdc-connectors/blob/196f9a4fca1dd83dc2c972da404784005dbabd45/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssigner.java#L201-L207

A lot thank @zhjwpku  alerts, i ignored the above code. Do you have time to help me solve this issue?  🙏

**Comment by zhjwpku** [comment]
> > If the split info is cleaned up in the snapshot phase, the logic before **pure** binlog read phase can be wrong ;(
> 
> https://github.com/ververica/flink-cdc-connectors/blob/196f9a4fca1dd83dc2c972da404784005dbabd45/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssigner.java#L201-L207
> 
> A lot thank @zhjwpku alerts, i ignored the above code. Do you have time to help me solve this issue? 🙏

@minchowang I can not came up with a good solution right now, will keep this in mind though ;)

**Comment by minchowang** [comment]
> > > If the split info is cleaned up in the snapshot phase, the logic before **pure** binlog read phase can be wrong ;(
> > 
> > 
> > https://github.com/ververica/flink-cdc-connectors/blob/196f9a4fca1dd83dc2c972da404784005dbabd45/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlHybridSplitAssigner.java#L201-L207
> > 
> > A lot thank @zhjwpku alerts, i ignored the above code. Do you have time to help me solve this issue? 🙏
> 
> @minchowang I can not came up with a good solution right now, will keep this in mind though ;)

Never mind, let's solution that later.

**Comment by leonardBang** [comment]
I've invested some inputs, now I come up with following ideas to reduce the memory usage.
![image](https://user-images.githubusercontent.com/5163645/175448565-3a04fca1-9d84-46b4-b001-70a675d24f15.png)
![image](https://user-images.githubusercontent.com/5163645/175448578-d30a2324-97b3-4451-b005-9972d9f18724.png)
