### ISSUE TITLE
MySQL CDC 元数据中op_type怎样获取呢

### ISSUE THREAD

**Issue by liulpStart** [ververica/flink-cdc-connectors#866]
**Describe the bug**
MySQL CDC 目前元数据只支持database_name、table_name、op_ts三个字段，想获取数据库的操作类型 op_type，例如 INSERT/DELETE 等

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version: 2.1.1
 - Database and version: mysql5.7

**To Reproduce**
1. Thes test data :
2. The test code :
tableEnv.executeSql("CREATE TABLE user_info2 (" +
                "  db_name STRING METADATA FROM 'database_name' VIRTUAL," +
                "  table_name STRING METADATA  FROM 'table_name' VIRTUAL," +
                "  operation_ts TIMESTAMP_LTZ(3) METADATA FROM 'op_ts' VIRTUAL," +
                "  op_type STRING METADATA FROM 'op_type' VIRTUAL," +
                "  id INT," +
                "  name STRING," +
                "  age INT," +
                " PRIMARY KEY (id) NOT ENFORCED\n" +
                ") WITH (" +
                "  'connector' = 'mysql-cdc'," +
                "  'hostname' = 'localhost'," +
                "  'port' = '3306'," +
                "  'username' = 'root'," +
                "  'password' = 'password'," +
                "  'database-name' = 'cdc_test'," +
                "  'table-name' = 'user_info2'" +
                ")");
3. The error : 
(Exception in thread "main" org.apache.flink.table.api.ValidationException: Invalid metadata key 'op_type' in column 'op_type' of table 'default_catalog.default_database.user_info2'. The DynamicTableSource class 'com.ververica.cdc.connectors.mysql.table.MySqlTableSource' supports the following metadata keys for reading:
database_name
op_ts
table_name)

**Additional Description**
![image](https://user-images.githubusercontent.com/67847357/154612413-c30183b3-7eb4-46dc-8feb-98aadb312ea5.png)

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.

**Comment by NoahSheep** [comment]
> 你能用英语更好地沟通吗？更新描述后，请随时重新打开。

I ran into the same problem, trying to get the operation type through METADATA. The above problem is: MySQL CDC currently supports only database_name, table_name, op_ts three fields of metadata, want to obtain the database operation type op_type, such as INSERT/DELETE
