### ISSUE TITLE
flinkCDC 是我觉得实现实时数仓最好途径

### ISSUE THREAD

**Issue by yaoboxu** [ververica/flink-cdc-connectors#87]
1、其实就是历史数据与实时数据有关联，多个表同时更新，就是多个表同时更新，就是flink-cdc整表更新的概念，只是以后怎么解决存储的问题，能否像MR一样走文件，又能想kafka一样顺序写磁盘，提高读取速度
2、对于市面上一直宣传实时数仓满天飞， 我们还处于 实时和离线分开的架构，需要实现所有数据实时关联的场景都采用MPP（tidb）内存数据库来实现。
3、flink 现在对接Kafka这种模式，怎么实现流批一体？？ 我一直有疑问，kafka的分区数据保留有限不能无限期保留下去，也不能让flinK的窗口无限期扩大，不知道你们大厂都会如何实现的，也希望大家给个思路，纯粹一个技术人员的疑惑，也看到了flink-CDC给出了道路，但是历史数据如何解决，还是有点疑问？

**Comment by snycc15** [comment]
我也存在这样的疑惑，CDC数据应该直接进入数据湖，kafka只能解决实时计算的场景，对于历史统计等需求解决不了。

**Comment by wuchong** [comment]
对接 kafka 的主要问题就是成本高，数据无法长期保留，对于某些维度数据还好，对于事件数据就不太友好了。 
所以目前的业界方向是 cdc 对接数据湖，iceberg 0.11 已经支持 cdc 数据入湖，也就是 mysql-cdc + iceberg 可以串通了。 iceberg 的优势是成本低，无限存储。缺点只能达到分钟级延迟，无法像 kafka 一样的毫秒级延迟。不过对于大多数实时分析已经够 用了。

**Comment by yaoboxu** [comment]
@wuchong  最新的社会包括flink12版本，我也看到了mysql-cdc+iceberg的思路。--- 关于 source和sink缺失都解决了， 那么关于这个思路中最关心的数据拉宽：ETL 过程，是不是还是和flink-cdc一样，在同步的过程中，进行数据的关联展开，历史数据的关联（稍微大一点的表）是否会导致flink机器内存溢出， ETL这一块，一直很有疑问，求赐教，不胜感激！

**Comment by wuchong** [comment]
如果是 双流 JOIN，那么数据会放在 state 里，state 一般线上使用 rocksdb ，是会落盘的，不会有内存 OOM 的问题。
如果是维表 JOIN，那么没有 state，也就更不会内存 OOM 了。

**Comment by melin** [comment]
> 对接 kafka 的主要问题就是成本高，数据无法长期保留，对于某些维度数据还好，对于事件数据就不太友好了。 所以目前的业界方向是 cdc 对接数据湖，iceberg 0.11 已经支持 cdc 数据入湖，也就是 mysql-cdc + iceberg 可以串通了。 iceberg 的优势是成本低，无限存储。缺点只能达到分钟级延迟，无法像 kafka 一样的毫秒级延迟。不过对于大多数实时分析已经够 用了。

如果是个位表且表结构不怎么变化需要同步，数据湖（iceberg/hudi）还能支持，但如果大量的数据表需要同步，就存在比较淡问题。例如遇到一个需求，地市药监局要同步数据到省药监局，每个地市600多张mysql表。
