### ISSUE TITLE
[e2e][postgresql]  The e2e test PostgresE2eITCase.testPostgresCDC failed in azure CI

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#875]
https://dev.azure.com/ververica/flink-cdc-connectors/_build/results?buildId=979&view=logs&j=ccedd2bf-e82a-54b8-b75f-7971f1fbbb9f&t=385827ba-1388-5c8f-6875-4ed5108d031f

**Comment by leonardBang** [comment]
https://dev.azure.com/ververica/flink-cdc-connectors/_build/results?buildId=1150&view=logs&j=ccedd2bf-e82a-54b8-b75f-7971f1fbbb9f&t=385827ba-1388-5c8f-6875-4ed5108d031f

**Comment by leonardBang** [comment]
The failed test appears again...
https://dev.azure.com/ververica/flink-cdc-connectors/_build/results?buildId=1234&view=logs&j=ccedd2bf-e82a-54b8-b75f-7971f1fbbb9f&t=385827ba-1388-5c8f-6875-4ed5108d031f

**Comment by ruanhang1993** [comment]
Fixed.
