### ISSUE TITLE
[Feature] Support Sqlserver  CDC Connector

### ISSUE THREAD

**Issue by zuoyebushiwo** [ververica/flink-cdc-connectors#88]
Can  implement sqlserver cdc ?

**Comment by leonardBang** [comment]
#549

**Comment by GOODBOY008** [comment]
I am working on it, anyone wants to work together to complete this feature?

**Comment by EcoleKeine** [comment]
Why sqlserver's version is limited to 14 and 15?
I try edited to support v13, no error.

`if (metaData.getDatabaseMajorVersion() != 14 && metaData.getDatabaseMajorVersion() != 15)`
[source code](https://github.com/ververica/flink-cdc-connectors/blob/5511904b622e6904c5b4f36a78f9ef982b527727/flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/SqlServerValidator.java#L72)

**Comment by ynzzxc** [comment]
是否考虑支持一下14以前的版本呢？
org.apache.flink.table.api.ValidationException: Currently Flink SqlServer CDC connector only supports SqlServer whose version is either 14 or 15, but actual is 13.

**Comment by cooltnt** [comment]
刚巧遇到有在用sqlserver2012的, 话说, 我下载的源码里, 为啥sqlserver cdc 的源码不存在 ?

**Comment by yeching1989** [comment]
Caused by: org.apache.flink.table.api.ValidationException: Currently Flink SqlServer CDC connector only supports SqlServer whose version is either 14 or 15, but actual is 13

**Comment by yeching1989** [comment]
我在Dinky上跑任务也是报这个错误：Caused by: org.apache.flink.table.api.ValidationException: Currently Flink SqlServer CDC connector only supports SqlServer whose version is either 14 or 15, but actual is 13，各位大神，怎么解决呢？

**Comment by GOODBOY008** [comment]
> 我在Dinky上跑任务也是报这个错误：Caused by: org.apache.flink.table.api.ValidationException: Currently Flink SqlServer CDC connector only supports SqlServer whose version is either 14 or 15, but actual is 13，各位大神，怎么解决呢？
@yeching1989 
sqlserver 2008 with test fail and need to adjust.
