### ISSUE TITLE
MySQL CDC 元数据中op_type使用SQL语句怎样获取呢

### ISSUE THREAD

**Issue by liulpStart** [ververica/flink-cdc-connectors#880]
**Is your feature request related to a problem? Please describe.**
MySQL CDC 目前元数据只支持database_name、table_name、op_ts三个字段，想获取数据库的操作类型 op_type，例如 INSERT/DELETE 等

**Describe the solution you'd like**
**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version: 2.1.1
 - Database and version: mysql5.7
**To Reproduce**
1. Thes test data :
2. The test code :
tableEnv.executeSql("CREATE TABLE user_info2 (" +
                "  db_name STRING METADATA FROM 'database_name' VIRTUAL," +
                "  table_name STRING METADATA  FROM 'table_name' VIRTUAL," +
                "  operation_ts TIMESTAMP_LTZ(3) METADATA FROM 'op_ts' VIRTUAL," +
                "  op_type STRING METADATA FROM 'op_type' VIRTUAL," +
                "  id INT," +
                "  name STRING," +
                "  age INT," +
                " PRIMARY KEY (id) NOT ENFORCED\n" +
                ") WITH (" +
                "  'connector' = 'mysql-cdc'," +
                "  'hostname' = 'localhost'," +
                "  'port' = '3306'," +
                "  'username' = 'root'," +
                "  'password' = 'password'," +
                "  'database-name' = 'cdc_test'," +
                "  'table-name' = 'user_info2'" +
                ")");
3. The error : 
(Exception in thread "main" org.apache.flink.table.api.ValidationException: Invalid metadata key 'op_type' in column 'op_type' of table 'default_catalog.default_database.user_info2'. The DynamicTableSource class 'com.ververica.cdc.connectors.mysql.table.MySqlTableSource' supports the following metadata keys for reading:
database_name
op_ts
table_name)

**Additional Description**
![image](https://user-images.githubusercontent.com/67847357/154612413-c30183b3-7eb4-46dc-8feb-98aadb312ea5.png)

**Describe alternatives you've considered**
Can the "op_type" field be put into the metadata of CDC in the later updated version

**Comment by rookiegao** [comment]
sql 方式目前不支持获取 op 类型

**Comment by liulpStart** [comment]
> sql 方式 当前不支持获取 op 类型
后续版本会增加这个功能嘛

**Comment by liulpStart** [comment]
> sql 方式 当前不支持获取 op 类型

后续版本会增加这个功能吗？

**Comment by liulpStart** [comment]
> sql 方式 当前不支持获取 op 类型

    后续更新的版本会增加这个功能吗？

**Comment by liulpStart** [comment]
> sql 方式目前不支持获取 op 类型

后续更新的版本会增加这个功能吗？

**Comment by liulpStart** [comment]
> sql 方式目前不支持获取 op 类型

  @rookiegao 大佬您好，后续更新的版本会增加这个功能吗？

**Comment by leonardBang** [comment]
Could you use English for better communication? feel free to reopen once updated the description.

**Comment by SandoHuang** [comment]
@liulpStart 可以使用debezium-json格式解决这个问题。
CREATE TABLE item_stat_binlog (
      `item_id` BIGINT,
     `item_count` BIGINT,
     PRIMARY KEY (item_id) NOT ENFORCED
) WITH (
 'connector' = 'mysql-cdc',
 'hostname' = '9.134.189.12',
 'port' = '3306',
 'username' = 'root',
 'password' = 'yang',
 'database-name' = 'flink_test',
 'table-name' = 'item_stat'
);

 CREATE TABLE item_stat_debezium_sink (
  `item_id` BIGINT,
  `item_count` BIGINT NOT NULL,
  PRIMARY KEY (item_id) NOT ENFORCED
) WITH (
  'connector' = 'kafka',
  'topic' = 'item_stat_debezium_sink',
  'properties.bootstrap.servers' = '9.134.189.12:9092',
  'value.format' = 'debezium-json'
);

insert into item_stat_debezium_sink
select item_id ,item_count  from item_stat_binlog   ;

**Comment by bravekong** [comment]
> @liulpStart 可以使用debezium-json格式解决这个问题。 CREATE TABLE item_stat_binlog ( `item_id` BIGINT, `item_count` BIGINT, PRIMARY KEY (item_id) NOT ENFORCED ) WITH ( 'connector' = 'mysql-cdc', 'hostname' = '', 'port' = '3306', 'username' = 'root', 'password' = '', 'database-name' = 'flink_test', 'table-name' = 'item_stat' );
> 
> CREATE TABLE item_stat_debezium_sink ( `item_id` BIGINT, `item_count` BIGINT NOT NULL, PRIMARY KEY (item_id) NOT ENFORCED ) WITH ( 'connector' = 'kafka', 'topic' = 'item_stat_debezium_sink', 'properties.bootstrap.servers' = '', 'value.format' = 'debezium-json' );
> 
> insert into item_stat_debezium_sink select item_id ,item_count from item_stat_binlog ;

What should we do next? Still reporting error Column 'op' not found in any table
