### ISSUE TITLE
[document] Flink CDC is Compatible with Flink 1.14,document should be updated.

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#882]
**Is your feature request related to a problem? Please describe.**
Flink CDC is Compatible with Flink 1.14,document should be updated.

**Comment by hsbajwa** [comment]
Hi, when 2.2.* will be available to use?

**Comment by GOODBOY008** [comment]
fixed in https://github.com/ververica/flink-cdc-connectors/commit/7fc9c9ded061712f2dcdc2a8ec6cfe2b3bd9637a.
