### ISSUE TITLE
如何通过ddl使创建kafka的topic使多分区的

### ISSUE THREAD

**Issue by chenxiaoliang0901** [ververica/flink-cdc-connectors#89]
最近在测试环境测试flink cdc的功能，使用mysql-cdc拉取的数据直接insert到kafka中，而创建的topic是只有一个partition的，请问如何设置才能实现insert到多分区

**Comment by wuchong** [comment]
创建一个多分区的 kafka topic 即可。不过因为 binlog 是有更新数据的，为了 key 内保序，一般建议搭配 upsert-kafka connector 使用。https://ci.apache.org/projects/flink/flink-docs-master/docs/connectors/table/upsert-kafka/

**Comment by wuchong** [comment]
创建一个多分区的 kafka topic 即可。不过因为 binlog 是有更新数据的，为了 key 内保序，一般建议搭配 upsert-kafka connector 使用。https://ci.apache.org/projects/flink/flink-docs-master/docs/connectors/table/upsert-kafka/
