### ISSUE TITLE
StreamPhysicalWindowAggregate doesn't support consuming update and delete changes

### ISSUE THREAD

**Issue by www2388258980** [ververica/flink-cdc-connectors#904]
**Is your feature request related to a problem? Please describe.**
table define：

**create table flink_medatc_cloud.t_window(
id int,
organization_id int,
took_at TIMESTAMP(3),
WATERMARK FOR took_at AS took_at - INTERVAL '5' SECOND,
primary key(id) NOT ENFORCED
)
with (
'connector' = 'postgres-cdc',
'hostname' = '',
'port' = '5432',
'username' = '',
'password' = '',
'database-name' = 'ibupro_cloud',
'schema-name' = 'public',
'table-name' = 't_window',
'decoding.plugin.name' = 'wal2json_streaming'
);**

sql-client command cli
action:
**select organization_id,window_start,window_end,count(1) as cnt
from TABLE(TUMBLE(TABLE t_window,descriptor(took_at),interval '1' days))
group by organization_id,window_start,window_end;**

error:
org.apache.flink.table.api.TableException: StreamPhysicalWindowAggregate doesn't support consuming update and delete changes which is produced by node TableSourceScan(table=[[emr_hive, default, t_window]], fields=[id, organization_id, took_at])

**Describe the solution you'd like**
how to solve  this problem?
Would you help me?

**Comment by leonardBang** [comment]
The reason is Flink SQL window operator doesn't support changelog input before Flink 1.15, and flink cdc connector can do nothing now.

**Comment by link3280** [comment]
@leonardBang I have a glance at the release note of Flink 1.15, and found no mention of changes of StreamPhysicalWindowAggregate, and neither do the git logs. Could you give me some pointers to track this effort? I'm longing for this feature. 😭

**Comment by leonardBang** [comment]
Looks like no contributors work for this issue @link3280 ...
