### ISSUE TITLE
希望mysql-cdc支持扩展的mysql ddl语法

### ISSUE THREAD

**Issue by Cleverdada** [ververica/flink-cdc-connectors#905]
**目前flink-cdc通过 "show create table"来获取mysql表结构, 解析时报ddl解析失败( 如"dbpartition by" 或 "auto_increment by group")**
![image](https://user-images.githubusercontent.com/11186845/156359482-dea1948b-bcce-41b8-83b1-8d3186d7ce9e.png)

**希望支持截图所示DDL:**
```
CREATE TABLE multi_db_single_tbl(
  id bigint not null auto_increment by group, 
  name varchar(30), 
  primary key(id)
) dbpartition by hash(id);
```
![image](https://user-images.githubusercontent.com/11186845/156359559-d29e0ad1-e90a-43e6-8b62-5b9d956dd0c3.png)

**或者可以通过information_schema来获取表结构**

**Comment by leonardBang** [comment]
would you like to take this ticket to suppport PoloarDBx DDL @Cleverdada ?

**Comment by Cleverdada** [comment]
> would you like to take this ticket to suppport PoloarDBx DDL @Cleverdada ?

Yes

**Comment by leonardBang** [comment]
Could you use English for better communication @Cleverdada ? feel free to reopen once updated the description.
