### ISSUE TITLE
[Document] How to use datastream API？

### ISSUE THREAD

**Issue by JesseAtSZ** [ververica/flink-cdc-connectors#906]
As for the use of Flink CDC data synchronization, the official website only introduces the use of Flink SQL. DataStream API only shows from Mysql to Console. I don't how to use of the DataStream Interface (for example, from Mysql to MySQL). Can you provide me with a demo?

**Comment by fuyun2024** [comment]
I suggest you go to see Flink JDBC sink

https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/connectors/datastream/jdbc/

**Comment by paul8263** [comment]
Hi @JesseAtSZ ,

You can take a look at the following example:

```scala
val env = StreamExecutionEnvironment.getExecutionEnvironment

val sourceFunction = MySQLSource.builder().hostname("xxx").port(3306)
      .databaseList("demo").username("username").password("yourpassword")
      .deserializer(new JsonDebeziumDeserializationSchema).build()

env.addSource(sourceFunction).print.setParallelism(1)

env.execute()

```

**Comment by JesseAtSZ** [comment]
Thanks @paul8263 ,
In fact, I'm confused about how to write into mysql, because I see many online examples by writing SQL and then executing JDBC, I wonder if there is a more elegant way.
