### ISSUE TITLE
Clean up the deleted table information when restarting the task

### ISSUE THREAD

**Issue by fuyun2024** [ververica/flink-cdc-connectors#913]
**Describe the bug**
I have a flink mysql cdc task, which is reading binlog data of A、B、C table. I stopped the task and changed the configuration to read-only access to table A. Restart the task, Now it is true that it only reads the data of table A, but the information of table B and C still exists in the code variable.

**Environment :**
 - Flink version :  flink 1.3.5
 - Flink CDC version: 2.2-SNAPSHOT
 - Database and version: mysql 5.7

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**

**Comment by fuyun2024** [comment]
@leonardBang Do we need this optimization? If so, please assign it to me .

**Comment by leonardBang** [comment]
I think we need this feature but not in 2.2 version, we need to consider newly added tables feature when implement this,  please also take a look @zhjwpku

**Comment by zhjwpku** [comment]
> I think we need this feature but not in 2.2 version, we need to consider newly added tables feature when implement this, please also take a look @zhjwpku

yeah, we definitely need this feature, will keep an eye on this 🧐

**Comment by zmzeng** [comment]
@leonardBang @fuyun2024 are we getting any progress?

**Comment by ruanhang1993** [comment]
Closed by #1134
