### ISSUE TITLE
[docs] The link of download flink is 404 now.

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#918]
The link of download flink is 404 now.Affect files `docs/content/快速上手/mysql-postgres-tutorial-zh.md`,`docs/content/quickstart/mysql-postgres-tutorial.md`.

**Comment by leonardBang** [comment]
would you like to fix the download link ? Current website only offer the latest bugfix version of flink i.e. It offers `1.13.6` instead of `1.13.4` or `1.13.5`. I can replace it with archive website like  https://archive.apache.org/dist/flink/flink-1.13.2/

**Comment by GOODBOY008** [comment]
@leonardBang Yes,I am willing to fix.Please assign to me.

**Comment by leonardBang** [comment]
Thanks @GOODBOY008 for picking this, assigned to you
