### ISSUE TITLE
Support ' heartbeat.interval​.ms' options to reduce WAL disk space consumption of PG 

### ISSUE THREAD

**Issue by docete** [ververica/flink-cdc-connectors#92]
https://debezium.io/documentation/reference/connectors/postgresql.html#postgresql-property-heartbeat-interval-ms

**Comment by eric3zhao** [comment]
hi @docete I have commit a PR for this https://github.com/ververica/flink-cdc-connectors/pull/107

**Comment by leonardBang** [comment]
fixed in 4127661
