### ISSUE TITLE
Metadata Documentation

### ISSUE THREAD

**Issue by sebasmagri** [ververica/flink-cdc-connectors#93]
Does this connector expose any metadata for the SQL API?

**Comment by wuchong** [comment]
Not yet. What metadata do you want to expose?

**Comment by Gavineil** [comment]
i want yo expose row kind in Flink SQL api, is there any way to do this? @wuchong

**Comment by leonardBang** [comment]
Implemented by 
#249 
#476 
#575

**Comment by sebasmagri** [comment]
Is there a chance to get this for PostgreSQL?
