### ISSUE TITLE
分库分表导致Flink-cdc流频繁full gc

### ISSUE THREAD

**Issue by gwqlovelinux** [ververica/flink-cdc-connectors#939]
## 背景：
公司交易中心分库分表，mysql数据库32schema，每个schema 32张表；等于一个逻辑表对应32*32=1024张物理表。目前通过flink-connector-mysql-cdc 2.1同步数据到kafka，发现只要job运行一周左右，就会频繁full gc。

## 分析：
1、通过jmap把内存dump下来分析发现，tableMapEventByTableId消耗了大量的内存。因为物理库有两个，所以这个流会同时读两个库的binlog，也就是下面为啥会存在两个一样的内存问题。
2、tableMapEventByTableId 是LRUCache一个实例，LRUCache扩展自LinkedHashMap，实现了清理的方法，理论上不应该操作1万个node

```
public EventDeserializer(
            EventHeaderDeserializer eventHeaderDeserializer,
            EventDataDeserializer defaultEventDataDeserializer
    ) {
        this.eventHeaderDeserializer = eventHeaderDeserializer;
        this.defaultEventDataDeserializer = defaultEventDataDeserializer;
        this.eventDataDeserializers = new IdentityHashMap<EventType, EventDataDeserializer>();
        this.tableMapEventByTableId = new LRUCache<>(100, 0.75f, 10000);
        registerDefaultEventDataDeserializers();
        afterEventDataDeserializerSet(null);
    }
```

```
public class LRUCache<K,V> extends LinkedHashMap<K,V> {
    private int maxSize;

    public LRUCache(int initialCapacity, float loadFactor, int maxSize) {
        super(initialCapacity, loadFactor, true);
        this.maxSize = maxSize;
    }

    @Override
    protected boolean removeEldestEntry(Map.Entry<K, V> eldest) {
        return size() > maxSize;
    }
}
```

补充一个文档，上面有mat分析的截图。
https://pyie1bcd1x.feishu.cn/docs/doccnpn6mZ6rU1vrmAClIOnc8ec#

**Comment by gwqlovelinux** [comment]
https://pyie1bcd1x.feishu.cn/docs/doccnpn6mZ6rU1vrmAClIOnc8ec#

**Comment by leonardBang** [comment]
@gwqlovelinux Could you use English for better communication? feel free to reopen once updated the description.

**Comment by leonardBang** [comment]
This issue has been fixed in debezium https://github.com/debezium/debezium/pull/3498, we can fix in flink cdc community in patch way.  CC @Jiabao-Sun
