### ISSUE TITLE
Source parallelism

### ISSUE THREAD

**Issue by SmirAlex** [ververica/flink-cdc-connectors#94]
As stated [here](https://github.com/ververica/flink-cdc-connectors/wiki/MySQL-CDC-Connector#exactly-once-processing) MySQLSource does not support parallelism > 1. Does parallel execution is not even possible? Or maybe it is not supported only at the current time and is planning in the future releases?

**Comment by SmirAlex** [comment]
I found out that Debezium does not support multiple connections with the same serverId (numeric ID of database client). So it seems that parallelism > 1 is not possible.

**Comment by leonardBang** [comment]
@SmirAlex Sorry that l just see your comment. The parallel execution is pretty diffcult if we want to keep the data order and  exactly-once-semantics. But now, Flink CDC 2.0 implemented the parallel source which offers parallel reading, lock-free and exactly-once-semantics, you can have a try, you can contact me if you meet any problem.
