### ISSUE TITLE
Flink-cdc full gc

### ISSUE THREAD

**Issue by gwqlovelinux** [ververica/flink-cdc-connectors#941]
## Background
The company's trading center has sub-databases and sub-tables, the mysql database has 32 schemas, and each schema has 32 tables; it is equivalent to a logical table corresponding to 32*32=1024 physical tables. Currently synchronizing data to kafka through flink-connector-mysql-cdc 2.1, it is found that as long as the job runs for about a week, full gc will be frequent.

## Analyze
1. Dump the memory through jmap and find that tableMapEventByTableId consumes a lot of memory. Because there are two physical libraries, this stream will read the binlogs of the two libraries at the same time, which is why there are two same memory problems below.
2. tableMapEventByTableId is an instance of LRUCache. LRUCache extends from LinkedHashMap and implements the cleaning method. In theory, it should not operate 10,000 nodes.

```
public EventDeserializer(
            EventHeaderDeserializer eventHeaderDeserializer,
            EventDataDeserializer defaultEventDataDeserializer
    ) {
        this.eventHeaderDeserializer = eventHeaderDeserializer;
        this.defaultEventDataDeserializer = defaultEventDataDeserializer;
        this.eventDataDeserializers = new IdentityHashMap<EventType, EventDataDeserializer>();
        this.tableMapEventByTableId = new LRUCache<>(100, 0.75f, 10000);
        registerDefaultEventDataDeserializers();
        afterEventDataDeserializerSet(null);
    }
```
```
public class LRUCache<K,V> extends LinkedHashMap<K,V> {
    private int maxSize;

    public LRUCache(int initialCapacity, float loadFactor, int maxSize) {
        super(initialCapacity, loadFactor, true);
        this.maxSize = maxSize;
    }

    @Override
    protected boolean removeEldestEntry(Map.Entry<K, V> eldest) {
        return size() > maxSize;
    }
}
```

Add a document with screenshots of mat analysis.
https://pyie1bcd1x.feishu.cn/docs/doccnpn6mZ6rU1vrmAClIOnc8ec#

**Comment by hunanjsd** [comment]
+1

**Comment by gwqlovelinux** [comment]
已解决，感谢蒋少东支持
https://pyie1bcd1x.feishu.cn/docs/doccnpn6mZ6rU1vrmAClIOnc8ec?appStyle=UI4&domain=www.feishu.cn&locale=zh-CN&refresh=1&sidebarOpen=1&tabName=space&theme=light&userId=6899042780148940804#
