### ISSUE TITLE
[docs] Flink CDC has supported many databases who supports MySQL protocol, we can list them to let user know

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#943]
https://ververica.github.io/flink-cdc-connectors/master/content/about.html#supported-connectors

**Comment by Cleverdada** [comment]
polardb
polardbx

**Comment by leonardBang** [comment]
@Cleverdada Would you like to take the task to help list the supported database in our document?

**Comment by Cleverdada** [comment]
> @Cleverdada Would you like to take the task to help list the supported database in our document?

sure, I'm goting to write a common document .
