### ISSUE TITLE
flink mysql  cdc 只读取全量数据 增量数据捕获不到

### ISSUE THREAD

**Issue by 15890776783** [ververica/flink-cdc-connectors#945]
![image](https://user-images.githubusercontent.com/43566263/158286947-6ec597ec-fe07-4560-92fa-4090d083699d.png)
flink cdc 版本位2.0.2 往上的版本都试过了,只会读取全量数据 增量数据捕获不到没有报任何异常,将初始化读取偏移量设置为最近是可以读取增量数据,但是全量数据就没了,将cdc 版本下降到 1.4.0的时候可以了
22/03/15 10:07:59 WARN DatabaseHistoryMetrics: Unable to register the MBean 'debezium.mysql:type=connector-metrics,context=schema-history,server=mysql_binlog_source': debezium.mysql:type=connector-metrics,context=schema-history,server=mysql_binlog_source

**Comment by zzzzzzzs** [comment]
如何解决的，我现在也遇到了这样的问题

**Comment by qq919856** [comment]
你好，我也遇到跟你一样的问题，能请问您最终是怎么解决的嘛

**Comment by 15890776783** [comment]
开启checkpoint试试










在 2022-04-24 10:38:22，"qq919856" ***@***.***> 写道：

你好，我也遇到跟你一样的问题，能请问您最终是怎么解决的嘛

**Comment by chen-yu342** [comment]
> 开启checkpoint试试 在 2022-04-24 10:38:22，"qq919856" ***@***.***> 写道： 你好，我也遇到跟你一样的问题，能请问您最终是怎么解决的嘛 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

开启cehcpoint也没有用
