### ISSUE TITLE
package org.apache.flink.shaded.guava version conflict in flink 1.14

### ISSUE THREAD

**Issue by WaylandWong** [ververica/flink-cdc-connectors#946]
**Describe the bug(Please use English)**
same with #841

flink-cdc-connectors (master branch which resolve #746 ) use flink-shaded-guava@18.0-13.0
https://github.com/ververica/flink-cdc-connectors/blob/473e36b9cd00b46a62f4bcd6fd5f6a2f8aeaab2c/pom.xml#L127-L132

however, flink 1.14 use flink-shaded-guava@30.1.1-jre-14.0 (actually flink use the latest version)

https://github.com/apache/flink/blob/5c3bca55682d7f10be0e2ab399d8a03d10d0f5fb/flink-streaming-java/pom.xml#L65-L68

```yaml
		<dependency>
			<groupId>org.apache.flink</groupId>
			<artifactId>flink-shaded-guava</artifactId>
		</dependency>
```

**Environment :**
 - Flink version :  1.14
 - Flink CDC version: master branch
 - Database and version: postgres 11.8

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**
`java.lang.ClassNotFoundException: org.apache.flink.shaded.guava18.com.google.common.util.concurrent.ThreadFactoryBuilder` error occured because of this confliction.

**Comment by WaylandWong** [comment]
Now I know that sql jar include all dependencies required and non-sql jar doese not.

So I decide to use sql jar at present.

**Comment by hb0** [comment]
_For future readers:_

Got the same exception using `com.ververica:flink-connector-mongodb-cdc`

I wasn't sure what the `sql` jar is, but `com.ververica:flink-sql-connector-mongodb-cdc` fixed it.

_(I'm not sure if this has any other consequences, though)_

**Comment by ramizgit** [comment]
> Now I know that sql jar include all dependencies required and non-sql jar doese not.
> 
> So I decide to use sql jar at present.

Can you please paste your maven dependency which fixed the issue?

**Comment by jiaowt762** [comment]
Can you please paste your maven dependency which fixed the issue? l meet you
