### ISSUE TITLE
默认slot_name为"debezium“不支持自定义设置，导致日常部署和本地开发时冲突”multiple connectors for the same database host“

### ISSUE THREAD

**Issue by tiyh** [ververica/flink-cdc-connectors#96]
PostgreSQLSource是否支持设置replication slot Name？
Stream方式使用，默认slot_name为"debezium“不支持自定义设置，导致日常部署和本地开发时冲突”multiple connectors for the same database host“

io.debezium.DebeziumException: Failed to start replication stream at LSN{xx/xxxxxxxx}; when setting up multiple connectors for the same database host, please make sure to use a distinct replication slot name for each.

**Comment by Sdu0** [comment]
使用 'debezium.slot.name' = 'xxx'

![image](https://user-images.githubusercontent.com/23182508/107012511-13eda080-67d4-11eb-85f5-cb19502b83ec.png)

**Comment by tiyh** [comment]
.debeziumProperties()
 'debezium.slot.name' = 'xxx'
