### ISSUE TITLE
We should make some improvements to the Flink CDC document

### ISSUE THREAD

**Issue by rookiegao** [ververica/flink-cdc-connectors#963]
These areas that need to be improved often confuse beginners.

-  The Flink CDC datastream API does not need to set the tablelist parameter when synchronizing the whole database.
-  Flink Oracle CDC wiki Q4: Oracle Sid and schema name should be distinguished by punctuation to avoid ambiguity.
-  After 2.1.0, the Flink MySQL CDC includes the MySQL driver package by default. We don't need to provide it ourselves.
-  The Flink CDC connector is a source connector rather than a sink connector. The project is only responsible for reading data from the source and does not support the sink function.
-  Specific instructions should be added to the Oracle CDC SQL table creation example on the official website.

For example, on the official website:

CREATE TABLE products (
     ID INT NOT NULL,
     NAME STRING,
     DESCRIPTION STRING,
     WEIGHT DECIMAL(10, 3),
     PRIMARY KEY(id) NOT ENFORCED
     ) WITH (
     'connector' = 'oracle-cdc',
     'hostname' = 'localhost',
     'port' = '1521',
     'username' = 'flinkuser',
     'password' = 'flinkpw',
     'database-name' = 'XE',
     'schema-name' = 'inventory', 
     'table-name' = 'products');

New description

CREATE TABLE products (
     ID INT NOT NULL,
     NAME STRING,
     DESCRIPTION STRING,
     WEIGHT DECIMAL(10, 3),
     PRIMARY KEY(id) NOT ENFORCED
     ) WITH (
     'connector' = 'oracle-cdc',
     'hostname' = 'localhost',
     'port' = '1521',
     'username' = 'flinkuser',
     'password' = 'flinkpw',
     'database-name' = 'XE',  -- XE is oracle SID
     'schema-name' = 'inventory', -- inventory is oracle user
     'table-name' = 'products');
     
- Other areas that need improvement are welcome to discuss.

**Comment by leonardBang** [comment]
Thanks for opening this issue, would you like to open a PR to improve the document ? @rookiegao

**Comment by rookiegao** [comment]
@leonardBang Yes, I'm willing to improve it. Do you have any other good suggestions？
